### ISSUE TITLE
Request: Energy value for Pzem004-T Pzemac

### ISSUE THREAD

**Issue by ASL07** [esphome/issues#1003]
**Affected component:**

https://esphome.io/components/sensor/pzemac.html
https://innovatorsguru.com/wp-content/uploads/2019/06/PZEM-004T-V3.0-Datasheet-User-Manual.pdf

**Description of problem:**

Hello,

I am not sure this is the proper way to request a feature. Please indicate  how it should be done otherwise.
The total energy value for this device is not available in esphome. It is stored in a couple of modbus registers. Please see doc above.
If we can read every other value, then we should be able to read the total energy one quite easily.
I can find some time to implement it if anyone is kind enough to give me some guidance regarding to what files need modified (apart from pzemac.h and pzemac.cpp)

Thanks

**Comment by rradar** [comment]
@ASL07 there is a special tracker for feature-requests and this one exists already here:

https://github.com/esphome/feature-requests/issues/457

Looks like the coding is also done and it maybe get's integrated in the next release.

This issue here can be therefor closed

**Comment by ASL07** [comment]
@rradar 
Thanks, this is great
Looking forward to the next release then
