### ISSUE TITLE
Base Sensor Configuration not comply with Template Sensor

### ISSUE THREAD

**Issue by Heiner1967** [esphome/issues#1017]
As per ESPHome the Base Sensor Configuration allws for example the setting of unit_of_measurement.

This unfortunate does not work for the template sensor.

**Comment by brandond** [comment]
Template sensor should extend the base sensor schema. Do you get an error when using it?

**Comment by brandond** [comment]
Ah I see, it extends them with the icon and unit specifically unset:
https://github.com/esphome/esphome/blob/dev/esphome/components/template/sensor/__init__.py#L10

**Comment by Heiner1967** [comment]
Hi sorry to ask, but what does this now mean. You identified and corrected the code with the link above? And how could i test if it works in my installation or when will it be part of an update? Just to understand how it runs?

However to answer your previous question, yes I get a Error if I try to add the core command
"unit_of_measurement: " to the template Sensor as not available option.

**Comment by glmnet** [comment]
Seems like @brandond just confirmed what you reported, now I don't understand why this is this way.

**Comment by Heiner1967** [comment]
I'm sorry, my fault tried to define the unit inside the lamda where I set the value. Which does not work. No doing it within the templatesensor definition all is good.
