### ISSUE TITLE
502 Bad Gateway for ESPHome web UI on docker HASS.io

### ISSUE THREAD

**Issue by rjalexa** [esphome/issues#1054]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**RPi4 Raspbian Buster Lite with Docker - HASS.io docker on it - ESPHome 1.14.3 from https://github.com/esphome/hassio repository**
**Fresh HASS.io install with only ESPHome, Mosquitto and Config File add-ons**

**ESP (ESP32/ESP8266, Board/Sonoff):**

Will want to use ESPHome to flash several ESP32-WROOM ESP-32S NodeMCU boards but problem prevents me to get to the device flash stage

**Affected component:**

**ESPHome WEBUI inside HASS.io**

**Description of problem:**

**The Launch Web UI command from either the Add-on page or the left sidebar produces an empty page with a blue spinning circle for some 10 seconds then a simple text error -> 502: Bad Gateway**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
config file for ESPHome reverted to default (epmty); also tried with ssl: false but problem did not change
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
Hass.io Add-on: ESPHome
 ESPHome Hass.io add-on for intelligently managing all your ESP8266/ESP32 devices.
-----------------------------------------------------------
 Add-on version: 1.14.3
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant version: 0.105.5
 Supervisor version: 201

and each time I try to launch the WebUI I see the following in the Supervisor->System log:

20-02-18 20:45:50 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62939 ssl:None [Operation timed out]

```

**Additional information and things you've tried:**

**Comment by KustHardball** [comment]
Hello! Same issue. Did you find a solution?

**Comment by rjalexa** [comment]
No Sir. This is making me CRAZY !!! Now the crazy thing is that the board does connect without any problems to another AP (a WiFi extender) I have at home. At the same time the main modem/router AP does not seem to have any blacklisting capabilities ... no clue so far.

**Comment by KustHardball** [comment]
I think problem with a docker ports settings. I have same situation when trying to connect remotely and on local mashine. Maybe we need to change this settings?
![Screenshot_1](https://user-images.githubusercontent.com/47186127/75383910-41f11200-58ee-11ea-8aac-52255b593bf1.png)

**Comment by KustHardball** [comment]
You can define port on Host field and ESPhome dashboard will be avaliable, but only on localhost.

**Comment by KustHardball** [comment]
If you define port in Host field, you can get access to ESPhome dashbord without Home Assistant.

**Comment by rjalexa** [comment]
Yes Sir. I tried with 6055 and then http://serverIP:6055 from a browser does work but still would love to get it working within HA.

**Comment by glmnet** [comment]
Seems a ingress home assistant issue. I assume you already tried a full system restart?

**Comment by rjalexa** [comment]
Hi Gimnet yes of course many system restarts, full HA reinstalls (wiping away all dockers and config files). PRoblem stays the same. I am armed with Portainer to debug but do not have the skills :( Wonder if anyone might start explaining what exactly happens when I click on the "Start UI" button.

**Comment by Sergksvs** [comment]
Hi rjalexa.  I have also error. You are resolve it?

**Comment by rjalexa** [comment]
Yes I have solved it :)
Do the following
Try to start the Web UI and wait for the 502 error and when you get it
Go to the supervisor and scroll down to the last lines of the system log
There you will find a red line of an error with a port number (eg 65432)
use the proper command to allow your operating system firewall to grant access to that port

This should fix the problem.
In my case I had "hardened" IPTables but the 172.x.y.z network wanted to access that port.
Hope this helps you. Let me know please.
