### ISSUE TITLE
AP Mode without Captive Portal

### ISSUE THREAD

**Issue by ministryofsillywalks** [esphome/issues#1058]
Home Assistant

Gosund Switch

AP Mode

I wanted to change wifi however i miss typed (yes im dumb) and the switch can't connect.
Now "luckily" I enabled AP mode thinking it would also automatically have the captive portal to change wifi...
It doesn't!
Now I have the switch giving out the AP and I can connect but once connected I can't do anything as there is no portal.
Is now the only way to access it via the commandline or do I have to open it up and connect wires again to reflash?

**Problem-relevant YAML-configuration entries:**
```yaml
  ap:
    ssid: "Gosund2 Fallback Hotspot"
    password: "WCRkAaj5Ufm7"

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by rradar** [comment]
Did you include `webserver:`. It's possible to upload your .bin there
