### ISSUE TITLE
Tuya Dimmer DM_WF_MDV4 RX0 TX0

### ISSUE THREAD

**Issue by nlambuca** [esphome/issues#1064]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 TUYA
**Affected component:**

TUYA DImmer

**Description of problem:**
My device is using RX0 and TX0. How to set those up in configuration file?
I knoiw I need to hold STM32 in RST condition to upload it, buit I want to know about using same pins to download and after (not in programming mode) to talk to dimmer.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by ssieb** [comment]
Your question is not clear.  The docs explain how to set the pins, what part don't you understand?
