### ISSUE TITLE
Travis rules overly strict for buggy linter

### ISSUE THREAD

**Issue by igg** [esphome/issues#1066]
- You can review the commit log for pull request esphome/esphome#985. This is not right.  The spacing recommended by the Cpp linter is not an improvement, and recommends under-indenting one-line comments in the else clause of the if statement.
If this is the intent, then the script should go ahead and implement the suggested whitespace requirements and push them up to the repo without further involvement.
Alternatively, you should relax the requirements for running the check scripts locally.  I'm not about to install PIO for the sole purpose of fixing buggy whitespace requirements from an over-restrictive linter.

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
> If this is the intent, then the script should go ahead and implement the suggested whitespace requirements and push them up to the repo without further involvement.

That would indeed be nice, but not really possible with our CI infrastructure.

> Alternatively, you should relax the requirements for running the check scripts locally. I'm not about to install PIO for the sole purpose of fixing buggy whitespace requirements from an over-restrictive linter.

Well how are you running ESPHome then? I'm assuming not on your computer via pip, but then you still have docker with the esphome/esphome-lint docker image.

The linter is there for a reason: Previously, there were lots of PRs where people's IDEs accidentally changed the whitespace on some lines (automatically removed trailing whitespace), and that made the git history unreadable.

Also, changes done in a PR should always be tested anyway, so installing some sort of development setup is required anyway.
