### ISSUE TITLE
EspHome on Ethernet connected hassio

### ISSUE THREAD

**Issue by Med-WAHIB** [esphome/issues#1084]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

I'm using a standard Hassio on Rpi 3, latest version.

**ESP (ESP32/ESP8266, Board/Sonoff):**

I use D1 mini

**Affected component:**

**Description of problem:**

When it is connected via wifi, devices are connected, when I use the ethernet interface devices don't connect. I used terminal to ping devices ips, the ping works.

**Problem-relevant YAML-configuration entries:**
```yaml
No errors here

```

**Logs (if applicable):**

```

No errors here

```

**Additional information and things you've tried:**

**Comment by glmnet** [comment]
I have my home assistant on rpi3bp and connected via ethernet, no problems, did you try using the ip address on home assistant side? (instead of node hostname) this will indicate a possible problem with mDNS
