### ISSUE TITLE
Documentation for PID Controller in next wasn't merged.

### ISSUE THREAD

**Issue by carlos-sarmiento** [esphome/issues#1172]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
N/A

**ESP (ESP32/ESP8266, Board/Sonoff):**
N/A

**Affected component:**

**Description of problem:**
Pull request esphome/esphome-docs#432 was never merged, even though the code for the component was merged esphome/esphome-docs#885. 

We should reopen and commit the PR so that the documentation is available on next.esphome.io 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by glmnet** [comment]
I just did it, can you review the docs are complete? Anything to add/remove?

I see you did some work related to PIDs

Thanks

**Comment by carlos-sarmiento** [comment]
Docs look good, but I still can't comment on the PR. Also there seems to be a conflict but I can't modify it either

**Comment by carlos-sarmiento** [comment]
@glmnet any update on this?

**Comment by carlos-sarmiento** [comment]
Is there any chance this documentation will be merged so it's at least available in next.esphome.io?

**Comment by glmnet** [comment]
Done, thanks @carlos-sarmiento for pushing
