### ISSUE TITLE
RF Bridge Component - transmit not working

### ISSUE THREAD

**Issue by JeeCeetje** [esphome/issues#1259]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HassOS 3.13
Home Assistant 0.110.0
ESPHome v1.15.0-dev

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff RF Bridge R2 V1.0, no hardware modifications

**Affected component:**

[RF Bridge Component](https://next.esphome.io/components/rf_bridge.html)

**Description of problem:**

Receiving RF codes works as they are correctly seen in the ESPHome logger.

However transmitting codes does not work:

- the receiving device does not act upon, 

- I don't receive any RF codes with another ESP8266 running OpenMQTTGateway,

- [other users reported the same behavior](https://community.home-assistant.io/t/sonoff-rf-bridge-with-esphome/112676/118)

I've been looking [into the code](https://github.com/esphome/esphome/blob/d1f4c2ab57e7fc4c982a091106c82fed0ec09822/esphome/components/rf_bridge/rf_bridge.cpp) and I think there is a bug in function
`void RFBridgeComponent::send_code(RFBridgeData data)`
which does not correctly transmit data to the efm8bb1 MCU. The write function writes a single byte I think, while the `sync`, `low` and `high` data is two bytes and the `code` is three bytes. Probably a flush is desired at the end as well.

When I replace the function with following code, the codes are actually transmitted (however my range is super low 3-4m line of sight but that is probably another issue). Receiving device acts upon code and OpenMQTTGateway also receives the code.
```
void RFBridgeComponent::send_code(RFBridgeData data) {
  ESP_LOGD(TAG, "Sending code: sync=0x%04X low=0x%04X high=0x%04X code=0x%06X", data.sync, data.low, data.high,
           data.code);
  this->write(RF_CODE_START);
  this->write(RF_CODE_RFOUT);
  this->write((data.sync >> 8) & 0xFF);
  this->write(data.sync & 0xFF);
  this->write((data.low >> 8) & 0xFF);
  this->write(data.low & 0xFF);
  this->write((data.high >> 8) & 0xFF);
  this->write(data.high & 0xFF);
  this->write((data.code >> 16) & 0xFF);
  this->write((data.code >> 8) & 0xFF);
  this->write(data.code & 0xFF);
  this->write(RF_CODE_STOP);
  this->flush();
}
```

And in the log, you can actually see that the efm8bb1 MCU actually acknowledges a correct action, which wasn’t the case before:
```
[18:26:06][D][rf_bridge:079]: Sending code: sync=0x125C low=0x0092 high=0x01E0 code=0xFFC554
[18:26:06][D][rf_bridge:024]: Action OK
```

**Problem-relevant YAML-configuration entries:**
[YAML as suggested in the documentation](https://next.esphome.io/components/rf_bridge.html#getting-started-with-home-assistant)

**Comment by zvldz** [comment]
I confirm it works.
Please fix it.
