### ISSUE TITLE
Unable to control entities using HTTP Web Server without access to WAN internet

### ISSUE THREAD

**Issue by JeffResc** [esphome/issues#1260]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**Affected component:**

HTTP Web Server

**Description of problem:**
Unable to set state of entity without access to WAN on browser device to download JS/CSS from external server (esphome.io). This becomes an issue when the ISP internet is down and you are unable to easily control your ESP. I ended up having to use the REST API to control my lights, but I expected it to be more seamless. I understand this may be due to size limitations, but the HTTP Web Server just becomes completely useless in the time that I would need it the most.

**Problem-relevant YAML-configuration entries:**
```yaml
N/A

```

**Logs (if applicable):**

```
N/A
```

**Additional information and things you've tried:**
N/A

**Comment by randybb** [comment]
Just switch to dev branch where you have more options https://next.esphome.io/components/web_server.html

**Comment by glmnet** [comment]
Ahh yes, you now have options to host locally the css / js files (e.g. local web server) or even include them inside the ESP itself. Thanks to the contributors!!

We really need a new version!
