### ISSUE TITLE
Request: Please put 'test disable no delay (#1026)' in the next release

### ISSUE THREAD

**Issue by S-Przybylski** [esphome/issues#1273]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

RB4 ARM Docker Version 0.112.0.dev20200605
ESPHOME 14.4 docker container ARMv7

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 D1 mini

**Affected component:**

https://esphome.io/components/api.html

**Description of problem:**
Dear @OttoWinter and @glmnet
today i have tested the new 14.4 ARM docker release. My problem described in 'Home Assistant disconnects after switching a switch group component: api (#794)' was not solved by the current release.

Then i have copied parts out of the current dev branch into the existing container (../components/api/* and ../script/api-protobuf/*), restarted the container and compiled the firmware again. After that, the problem has been disappeared!

I believe that it relies on @glmnet's update: 'test disable no delay (#1026)'
Thanks for your excellent work!

By the way: Is it possible to implement a ARMv7 DEV container too? Could you please share the dockerfile for ARM (perhaps in the project)?

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by glmnet** [comment]
Well thanks for the request. Of course this fix is going to the next release. However this minor version come in a rush because nothing was working. so Otto has to do it and I believe he is not aware this is a bug fix. 

We are working on a mechanism to provide releases quickly
