### ISSUE TITLE
D1_Mini & WS2811 issue

### ISSUE THREAD

**Issue by Octoross** [esphome/issues#1288]
Tried the following code on D1-Mini to control 12V WS2811 LED Strip through Home Assistant.  Tried pins D0, D1 and D5 so far.  Light is always on (regardless of light switch in HASS) and flickers a bit.  Tried the same thing on a NodeMCU and everything works as expected.  Is this a D1 Mini Limitation?

Thanks

esphome:
  name: led_cinema_maison
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  
  manual_ip:
    static_ip: 
    gateway: 
    subnet: 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led Cinema Maison"
    password: 

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret general_ota

ota:
  password: !secret general_ota

light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: D5
    num_leds: 150
    rgb_order: BRG
    name: "LED Cinema Maison"

**Comment by herostrat** [comment]
Can you give me an overview of the schematic?
I cannot think of a hardware limitation.

Typical problems wrt. WS2811 and other variants are:
 - Voltage level for data. Although 3V3 typically suffice 5V are nominal (recheck with datasheet), you can use a level shifter for this
 - Interference if datalines are near a power switching line/cable
 - pin multiplexing (meaning the dataline is used for other stuff too, e.g. serial)

**Comment by sermayoral** [comment]
@herostrat I have the same problem. LED always on.

My schematic is like this: https://external-preview.redd.it/zxOPnOPxrsTJbpL1mVCJIhdiIsZ_TKCmbhNi6FbShYE.jpg?auto=webp&s=acc6a45ca03d8c4f7d727f07511b5d4096af5f64

But without using the logic shift. I mean, the GPIO is directly connected to the D0 LED strip. Do you think the problem is I need the logic shift?

**Comment by Octoross** [comment]
I added one 6ohm resistor to the data pin and all is well now!

Sent from Nine<http://www.9folders.com/>
________________________________
De : Sergio Mayoral Martínez <notifications@github.com>
Envoyé : vendredi 24 juillet 2020 20:51
À : esphome/issues
Cc: Octoross; Author
Objet : Re: [esphome/issues] D1_Mini & WS2811 issue (#1288)


@herostrat<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fherostrat&data=02%7C01%7C%7C634bd71bc75c4f65a35508d83034ea5d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637312351105137592&sdata=JLiVLgFUmkrCdWTAsAkEzK87K2EaFrukiSfcu2voT%2Fk%3D&reserved=0> I have the same problem. LED always on.

My schematic is like this: https://external-preview.redd.it/zxOPnOPxrsTJbpL1mVCJIhdiIsZ_TKCmbhNi6FbShYE.jpg?auto=webp&s=acc6a45ca03d8c4f7d727f07511b5d4096af5f64<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fexternal-preview.redd.it%2FzxOPnOPxrsTJbpL1mVCJIhdiIsZ_TKCmbhNi6FbShYE.jpg%3Fauto%3Dwebp%26s%3Dacc6a45ca03d8c4f7d727f07511b5d4096af5f64&data=02%7C01%7C%7C634bd71bc75c4f65a35508d83034ea5d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637312351105147587&sdata=3zCndt25FrSscbxyzS6yt0LbE2KJLSmT3RJLFFsL1Is%3D&reserved=0>

But without using the logic shift. I mean, the GPIO is directly connected to the D0 LED strip. Do you think the problem is I need the logic shift?

**Comment by sermayoral** [comment]
@Octoross, so you have not used the logic shift and everything works well?

**Comment by Octoross** [comment]
works perfectly without the logic level shifter.

**Comment by sermayoral** [comment]
@Octoross i dont have a 6 Ohm resistor. I have put a 10R resistor between the data pin and the esp32 gpio, but it does not work.

**Comment by Octoross** [comment]
Hum... the length of the wires can also influence this.  do you have a potentiometer?  This is what i used to find the value i needed.

Sent from Nine<http://www.9folders.com/>
________________________________
De : Sergio Mayoral Martínez <notifications@github.com>
Envoyé : samedi 25 juillet 2020 09:58
À : esphome/issues
Cc: Octoross; Mention
Objet : Re: [esphome/issues] D1_Mini & WS2811 issue (#1288)


@Octoross<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOctoross&data=02%7C01%7C%7Cabdbda0a6873433a7ec608d830a2bf62%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637312822832020206&sdata=EgAcr0CeJlFSl9IYNOTRPkHfmmOJilfgNkaZuJDAKwQ%3D&reserved=0> i dont have a 6 Ohm resistor. I have put a 10R resistor between the data pin and the esp32 gpio, but it does not work.
