### ISSUE TITLE
Teckin SB50 Cookbook entry

### ISSUE THREAD

**Issue by phixion** [esphome/issues#1289]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**Affected component:**

https://esphome.io/cookbook/teckin_sb50.html

**Description of problem:**

This Device and many other tuya based are no longer tuya-convertible since they ship with new keys in their current firmware. It should be stated that only devices prior to FW versions 1.6.1 will work that way.

https://github.com/ct-Open-Source/tuya-convert/issues/483#issuecomment-577938924

**Problem-relevant YAML-configuration entries:**
```yaml
N/A

```

**Logs (if applicable):**

```
N/A

```

**Additional information and things you've tried:**

**Comment by rradar** [comment]
@phixion thank's for your input!

You can easily change the [mentioned cookbook entry](https://esphome.io/cookbook/teckin_sb50.html) by just clicking the "[Edit this page on GitHub](https://github.com/esphome/esphome-docs/blob/current/cookbook/teckin_sb50.rst)" :pencil2:  button at the bottom of the site:
![image](https://user-images.githubusercontent.com/34582688/86510772-b717ab00-bdea-11ea-8f8f-af62df124283.png)

This is actually true for the whole documentation found under www.esphome.io :tada:
