### ISSUE TITLE
Future Warning in Core Log

### ISSUE THREAD

**Issue by holdestmade** [esphome/issues#1290]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant 0.111

**ESP (ESP32/ESP8266, Board/Sonoff):**

Various

**Affected component:**

Various

**Description of problem:**

Getting a few of these in the Core log of HA with various 0x************.
All seems to be working OK though

/usr/local/lib/python3.7/site-packages/zeroconf/__init__.py:1541: FutureWarning: <netdisco.discoverables.esphome.Discoverable object at 0x7f13fb3ecf10> has no update_service method. Provide one (it can be empty if you don't care about the updates), it'll become mandatory.
  FutureWarning,

**Problem-relevant YAML-configuration entries:**
```yaml


```

**Logs (if applicable):**

```


```

**Additional information and things you've tried:**

**Comment by noli2000** [comment]
Same issue here
