### ISSUE TITLE
How to specifiy ota with the --upload-port command

### ISSUE THREAD

**Issue by jlo88** [esphome/issues#1293]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Not relevant?

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266

**Affected component:**
Uploading over the command line

**Description of problem:**
I'd like to automate my uploads with a script to do ota updates of all my nodes: 

```
f_list=$(ls *shelly*.yaml | xargs)
echo f_list
esphome $f_list run --no-logs
```
I'd like to avoid choosing the upload port manually for each device: 
```
Found multiple options, please choose one:
  [1] /dev/ttyACM0 (XDS110 (03.00.00.12) Embed with CMSIS-DAP)
  [2] /dev/ttyACM1 (XDS110 (03.00.00.12) Embed with CMSIS-DAP)
  [3] Over The Air (office_wall_switch.local)
```
How do I select ota default using the --upload-port command? I tried `--upload-port ota` etc but none of this works..

**Problem-relevant YAML-configuration entries:**
Not applicable

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by brandond** [comment]
OTA in all caps.
