### ISSUE TITLE
Cut n Paste error in component AS3935

### ISSUE THREAD

**Issue by fancygaphtrn** [esphome/issues#1305]
Run esphome on Windows 10 via command line

**Nodemcu:**

**Affected component:** AS3935

**Description of problem:**
in sensor.py, I believe there is a cut and paste error for the energy sensor.

It reads:
    if CONF_LIGHTNING_ENERGY in config:
        conf = config[CONF_LIGHTNING_ENERGY]
        lightning_energy_sensor = yield sensor.new_sensor(conf)
        cg.add(hub.set_distance_sensor(lightning_energy_sensor))

I believe the last line should be:
        cg.add(hub.set_energy_sensor(lightning_energy_sensor))

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
Fixed in https://github.com/esphome/esphome/pull/1210
