### ISSUE TITLE
 Displaying degree symbol on PCF8574 LCD Display Solution

### ISSUE THREAD

**Issue by jumblies** [esphome/issues#1321]
@cyberplant and @anybody84

I found your old thread from last year  Displaying ASCII characters on PCF8574 LCD Display #226  when I was recently trying to create a new weather display node and wanted to put this solution in the knowledge base.  

This is tested using a 2004 PCF8574 LCD display (around $4 from ali).  As OttoWinter had noted, the displays have their own library of characters.   Someone on a arduino forum had a nice loop to figure out which characters are which and other posts had narrowed down the choices for the hex code for the degree symbol.  

I was able to put it together with the following code.  There may be more elegant ways to do it, but this works and is as concise as I could get it.   

```
display:
  - platform: lcd_pcf8574
    dimensions: 20x4
    address: 0x3F
    lambda: |-
      const unsigned char deg_sign[] = {0xDF, 0};    // ----> initialize the char array with the symbol and null terminate it. 
      //Line 1 current time
      it.strftime(0,0, "%H:%M:%S ", id(sntp_time).now());
      
      //Line 2 condition string
      it.print(0,1,id(out_curr_cond).state.c_str());
      
      //Line 3 Outdoor conditions from API
      it.printf(0,2, "OUT %.0f%s %.0f%%",id(out_temp).state, deg_sign, id(out_hum).state); // -----> Plug the char string into an f-string

      //Line 4 Upstairs
      it.printf(0,3,"iFan %.0f%s %.0f%%", id(ifan_temp).state, deg_sign, id(ifan_hum).state);// -----> Plug the char string into an f-string

```

**Comment by holdestmade** [comment]
Thanks for this, I had to diplay on 2 lines but works great:

```
      it.printf(14, 0, "%.1f", id(temperature).state);
      it.printf(18, 0, "%sC", deg_sign);
```
