### ISSUE TITLE
USB to Serial not showing in the dropdown

### ISSUE THREAD

**Issue by xrado** [esphome/issues#1346]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP 01

**ESPHome version (latest production, beta, dev branch)**

ESPHome 1.14.5

**Affected component:**

**Description of problem:**
Hass detects usb to serial as /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0 and is not showing in a dropdown, therefore can't be selected. Used to show up in previous versions, a few months ago. Don't know if this is esphome or hassio issue.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by glmnet** [comment]
Did you try restarting everything with the thing plugged in?

**Comment by xrado** [comment]
Ok I've tried restarting with USB plugged in and now I also see /dev/ttyUSB0 under hass.io supervisor hardware, but esphome dropdown still not showing it.

![Screenshot 2020-07-13 07 53 34](https://user-images.githubusercontent.com/17779/87275244-fd9d9180-c4dd-11ea-8611-f5a98bb812e4.png)

CC2531 is the zigbee dongle and I also have SSD over USB connected
![IMG_20200713_075701](https://user-images.githubusercontent.com/17779/87275650-deebca80-c4de-11ea-977e-6278c6781b3d.jpg)

**Comment by OttoWinter** [comment]
We use PySerial internally for listing the serial ports.

If you have SSH/terminal access to the device, could you run

```bash
pip3 install pyserial
python3 -c "from serial.tools.list_ports import comports; print([x[0] for x in comports(include_links=True)])"
```

and post the output?

**Comment by xrado** [comment]
@OttoWinter here is the output

    ['/dev/ttyACM0','/dev/ttyAMA0']

if I run `ha hardware info`:

    ...
    serial:
    /dev/ttyAMA0
    /dev/ttyACM0
    /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001949D626-if00
    /dev/ttyUSB0

**Comment by OttoWinter** [comment]
Hmm since pyserial doesn't seem to list them we probably have to extend those methods ourselves.

**Comment by xrado** [comment]
@OttoWinter I've tested dev version ..works great
