### ISSUE TITLE
Wrong configuration value options for AS3935 

### ISSUE THREAD

**Issue by trylika** [esphome/issues#1366]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

doesn't matter
**ESP (ESP32/ESP8266, Board/Sonoff):**

doesn't matter
**ESPHome version (latest production, beta, dev branch)**

dev branch
**Affected component:**

AS3935  https://beta.esphome.io/components/sensor/as3935.html

**Description of problem:**
Wrong configuration value option for div_ratio, editor does allow entering only: 16, **22**, 64, 128
should be 16, **32**, 64, 128

**Problem-relevant YAML-configuration entries:**
```yaml
as3935_spi:
  div_ratio: 22
```

**Logs (if applicable):**

```
no log

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
Fixed in https://github.com/esphome/esphome/pull/1210
