### ISSUE TITLE
Merkury A21 Cookbook entry model MI-BW210-999W

### ISSUE THREAD

**Issue by nightshade00013** [esphome/issues#1369]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**
Tuya Based ESP8266 bulb

**ESPHome version (latest production, beta, dev branch)**

Latest ESPHome Version
**Affected component:**

**Description of problem:**
No real issue but I have been able to sucsessfully convert the Walmart (locally sold) Merkury A21 bulbs to ESPHome and have them work quite well.  https://github.com/nightshade00013/ESP-Home-Configs/blob/master/Merkury-A21.yaml is a link to the YAML file.  Not exactly sure how to edit or add things into the main site but wanted to allow others who may have seen or looked at the bulbs to have a quick configuration file.  

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
Ok yeah for that please edit the https://github.com/esphome/esphome-docs repo (see also the contributing guide on the webpage).

Not an issue, so will close.
