### ISSUE TITLE
Updates to Material Design Icons due to renaming introduced in 0.113.0

### ISSUE THREAD

**Issue by u17194907425** [esphome/issues#1374]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**ESPHome version (latest production, beta, dev branch)**

latest production

**Affected component:**

Multiple. E.g. this one https://esphome.io/components/sensor/mhz19.html

**Description of problem:**
There are MDI icons coming by default with different components in ESPHome. E.g. with the `mhz19` component the default icon is `mdi:periodic-table-co2`. Now in 0.113.0 there is a huge update to MDIs causing some of the names to become obsolete starting 0.115.0.

Please update accordingly.

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: mhz19

```

**Logs (if applicable):**

```
Icon mdi:periodic-table-co2 was renamed to mdi:molecule-co2, please change your config, it will be removed in version 0.115.

```

**Additional information and things you've tried:**

**Comment by rradar** [comment]
https://github.com/esphome/esphome/pull/1181 tries to address one icon (and not this on mentioned here)
