### ISSUE TITLE
requirements.txt is missing in Pypi SDIST source for esphome-1.15.0_beta1

### ISSUE THREAD

**Issue by onkelbeh** [esphome/issues#1378]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Gentoo Linux

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

esphome-1.15.0_beta1

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**

**Logs (if applicable):**

**Additional information and things you've tried:**

It is referenced on line 28 of setup.py

**Comment by OttoWinter** [comment]
I can't update the previous source distributions on PyPi, but 1.15.0b3 will be released with requirements.txt included.

Thanks for reporting this!

**Comment by onkelbeh** [comment]
Thanks for the fix.
