### ISSUE TITLE
Warning when passwords contain $ sign

### ISSUE THREAD

**Issue by lobradov** [esphome/issues#1413]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
hass.io integrated esphome (dev)

**ESP (ESP32/ESP8266, Board/Sonoff):**
esp8266, Sonoff and Dual

**ESPHome version (latest production, beta, dev branch)**
v1.16.0-dev

**Affected component:**
secrets.yaml
config/substitutions

**Description of problem:**
Secrets file seems to be interpreted for substitutions, throwing a warning if passwords include $ sign (with the password itself being shown on the screen).

Issue might be cosmetic, but could have a conflict if there would be a substitution matching remaining part of the password after $, eg: 
```yaml
password: test$mypassword
mypassword: something
```
would result in ```password: testsomething```

**Problem-relevant YAML-configuration entries:**

secrets.yaml:
```yaml
pass: te$tpass
```

test.yaml:
```yaml 
...
api:
  password: !secret 'api_password'
...
```

**Logs (if applicable):**

```
INFO Reading configuration /config/esphome/test.yaml...
WARNING Found 'te$tpass' (see api->password) which looks like a substitution, but 'tpass' was not declared
INFO Configuration is valid!
...
```

**Additional information and things you've tried:**
Quoted (single and double) do not help much.

```yaml
quoted_pass: "quotedte$tpass"
singlequote_pass: 'singlequotete$tpass'
```

**Comment by heschlie** [comment]
Is it possible to reopen this issue and address it? I don't really like having my wifi password spit into my console on every compile, it seems like a really easy thing to accidentally paste into an issue when requesting help. Also as noted above it could lead to subtle bugs if you are unaware this could happen.
