### ISSUE TITLE
ESP Home Dallas Temperature does not flashed 

### ISSUE THREAD

**Issue by ImmanuelT8** [esphome/issues#1461]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESp32 Dev

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

https://esphome.io/components/sensor/dallas.html?highlight=dallas

**Description of problem:**

After flashing the ESP they doesn't flashed ight, die yaml is korrekt, also the Sensors work with Arduino IDE

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
https://pastebin.com/iM5KyyUG
```

**Additional information and things you've tried:**

**Comment by randybb** [comment]
My heating controller uses 6 ds18b20 temp sensors without any problems, so could you please show us your configuration?

**Comment by ImmanuelT8** [comment]
> My heating controller uses 6 ds18b20 temp sensors without any problems, so could you please show us your configuration?

Hi,

first the serial print on arduino IDe, secend the programm in arduino, last the yaml .... i don't see an failure...

19:24:15.161 -> rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
19:24:15.161 -> configsip: 0, SPIWP:0xee
19:24:15.161 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
19:24:15.161 -> mode:DIO, clock div:1
19:24:15.161 -> load:0x3fff0018,len:4
19:24:15.161 -> load:0x3fff001c,len:1216
19:24:15.161 -> ho 0 tail 12 room 4
19:24:15.161 -> load:0x40078000,len:9720
19:24:15.161 -> ho 0 tail 12 room 4
19:24:15.161 -> load:0x40080400,len:6352
19:24:15.195 -> entry 0x400806b8
19:24:15.432 -> Locating devices...Found 3 devices.
19:24:15.432 -> Found device 0 with address: 281C5E7E121901B7
19:24:15.466 -> Found device 1 with address: 28F6B46E1219010E
19:24:15.500 -> Found device 2 with address: 28D1A26F12190152
19:24:15.636 -> Temperature for device: 0
19:24:15.636 -> Temp C: 35.50 Temp F: 95.90
19:24:15.670 -> Temperature for device: 1
19:24:15.670 -> Temp C: 28.50 Temp F: 83.30
19:24:15.738 -> Temperature for device: 2
19:24:15.738 -> Temp C: 33.50 Temp F: 92.30

----------
/*********
  Rui Santos
  Complete project details at https://RandomNerdTutorials.com  
*********/

#include <OneWire.h>
#include <DallasTemperature.h>

// Data wire is plugged TO GPIO 4
#define ONE_WIRE_BUS 4

// Setup a oneWire instance to communicate with any OneWire devices (not just Maxim/Dallas temperature ICs)
OneWire oneWire(ONE_WIRE_BUS);

// Pass our oneWire reference to Dallas Temperature. 
DallasTemperature sensors(&oneWire);

// Number of temperature devices found
int numberOfDevices;

// We'll use this variable to store a found device address
DeviceAddress tempDeviceAddress; 

void setup(){
  // start serial port
  Serial.begin(115200);
  
  // Start up the library
  sensors.begin();
  
  // Grab a count of devices on the wire
  numberOfDevices = sensors.getDeviceCount();
  
  // locate devices on the bus
  Serial.print("Locating devices...");
  Serial.print("Found ");
  Serial.print(numberOfDevices, DEC);
  Serial.println(" devices.");

  // Loop through each device, print out address
  for(int i=0;i<numberOfDevices; i++){
    // Search the wire for address
    if(sensors.getAddress(tempDeviceAddress, i)){
      Serial.print("Found device ");
      Serial.print(i, DEC);
      Serial.print(" with address: ");
      printAddress(tempDeviceAddress);
      Serial.println();
    } else {
      Serial.print("Found ghost device at ");
      Serial.print(i, DEC);
      Serial.print(" but could not detect address. Check power and cabling");
    }
  }
}

void loop(){ 
  sensors.requestTemperatures(); // Send the command to get temperatures
  
  // Loop through each device, print out temperature data
  for(int i=0;i<numberOfDevices; i++){
    // Search the wire for address
    if(sensors.getAddress(tempDeviceAddress, i)){
      // Output the device ID
      Serial.print("Temperature for device: ");
      Serial.println(i,DEC);
      // Print the data
      float tempC = sensors.getTempC(tempDeviceAddress);
      Serial.print("Temp C: ");
      Serial.print(tempC);
      Serial.print(" Temp F: ");
      Serial.println(DallasTemperature::toFahrenheit(tempC)); // Converts tempC to Fahrenheit
    }
  }
  delay(5000);
}

// function to print a device address
void printAddress(DeviceAddress deviceAddress) {
  for (uint8_t i = 0; i < 8; i++){
    if (deviceAddress[i] < 16) Serial.print("0");
      Serial.print(deviceAddress[i], HEX);
  }
}

----------------------esphome:
  name: temperature
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "WLAN1-000727"
  password: "swint145!"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temperature Fallback Hotspot"
    password: "vt7CJlRXZYMw"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:


dallas:
  - pin: GPIO4

sensor:
  - platform: dallas
    address: 0x281C5E7E121901B7
    name: "Temperature #1"
    
  - platform: dallas
    address: 0x28F6B46E1219010E
    name: "Temperature #2"
    
  - platform: dallas
    address: 0x28D1A26F12190152
    name: "Temperature #3"

Regards

**Comment by randybb** [comment]
Your dallas addresses are in wrong reversed format (arduino uses it), just replace it with this:
```yaml
sensor:
  - platform: dallas
    address: 0xB70119127E5E1C28
    name: "Temperature #1"
   
  - platform: dallas
    address: 0x0E0119126EB4F628
    name: "Temperature #2"
   
  - platform: dallas
    address: 0x520119126FA2D128
    name: "Temperature #3"
```

Next time, just connect a new sensor, look into log and just copy the right address to your config.

**Comment by ImmanuelT8** [comment]
> Your dallas addresses are in wrong reversed format (arduino uses it), just replace it with this:
> 
> ```yaml
> sensor:
>   - platform: dallas
>     address: 0xB70119127E5E1C28
>     name: "Temperature #1"
>    
>   - platform: dallas
>     address: 0x0E0119126EB4F628
>     name: "Temperature #2"
>    
>   - platform: dallas
>     address: 0x520119126FA2D128
>     name: "Temperature #3"
> ```
> 
> Next time, just connect a new sensor, look into log and just copy the right address to your config.

Thx but if i replace it i have still the same error:

========================= [SUCCESS] Took 37.27 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of schalter.local
INFO  -> 192.168.8.103
INFO Uploading /data/schalter/.pioenvs/schalter/firmware.bin (886160 bytes)
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from schalter.local using esphome API
WARNING Error resolving IP address of schalter.local. Is it connected to WiFi?
WARNING (If this error persists, please set a static IP address: https://esphome.io/components/wifi.html#manual-ips)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error resolving IP address: Error resolving address with mDNS: Did not respond. Maybe the device is offline., [Errno -5] No address associated with hostname). Re-Trying in 1 seconds
WARNING Error resolving IP address of schalter.local. Is it connected to WiFi?
WARNING (If this error persists, please set a static IP address: https://esphome.io/components/wifi.html#manual-ips)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error resolving IP address: Error resolving address with mDNS: Did not respond. Maybe the device is offline., [Errno -5] No address associated with hostname). Re-Trying in 1 seconds
INFO Connecting to schalter.local:6053 (192.168.8.103)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.8.103: [Errno 111] Connection refused). Re-Trying in 2 seconds
INFO Connecting to schalter.local:6053 (192.168.8.103)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.8.103: [Errno 111] Connection refused). Re-Trying in 3 seconds
INFO Connecting to schalter.local:6053 (192.168.8.103)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.8.103: [Errno 111] Connection refused). Re-Trying in 5 seconds
INFO Connecting to schalter.local:6053 (192.168.8.103)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.8.103: [Errno 111] Connection refused). Re-Trying in 7 seconds
INFO Connecting to schalter.local:6053 (192.168.8.103)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.8.103: [Errno 111] Connection refused). Re-Trying in 11 seconds
INFO Connecting to schalter.local:6053 (192.168.8.103)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.8.103: [Errno 111] Connection refused). Re-Trying in 17 seconds
INFO Connecting to schalter.local:6053 (192.168.8.103)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.8.103: [Errno 111] Connection refused). Re-Trying in 25 seconds
INFO Connecting to schalter.local:6053 (192.168.8.103)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.8.103: [Errno 111] Connection refused). Re-Trying in 30 seconds
INFO Connecting to schalter.local:6053 (192.168.8.103)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to 192.168.8.103: [Errno 111] Connection refused). Re-Trying in 30 seconds

**Comment by ImmanuelT8** [comment]
> Your dallas addresses are in wrong reversed format (arduino uses it), just replace it with this:
> 
> ```yaml
> sensor:
>   - platform: dallas
>     address: 0xB70119127E5E1C28
>     name: "Temperature #1"
>    
>   - platform: dallas
>     address: 0x0E0119126EB4F628
>     name: "Temperature #2"
>    
>   - platform: dallas
>     address: 0x520119126FA2D128
>     name: "Temperature #3"
> ```
> 
> Next time, just connect a new sensor, look into log and just copy the right address to your config.

Maybe the IP is the problem? The IP from my localhost is: 192.168.8.102 the log write: 

192.168.8.102
Is it normal, that the esp have a other IP then the localhost? Can i change the IP from the ESP?

**Comment by randybb** [comment]
You have flashed your ESP via UART and after that it will just connect to your WiFi, if your wifi username and password is right, and then all configuration, flashing and debugging (log file) will work remotely. That means it needs to have a different IP than your compute.
You have configured WIFI hotspot, you can try to check if it is not visible:
```yaml
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temperature Fallback Hotspot"
    password: "vt7CJlRXZYMw"
```

**Comment by ImmanuelT8** [comment]
Tahnk, if i delet the part also an error, i think i should set the IP
manually:

"WARNING (If this error persists, please set a static IP address:
https://esphome.io/components/wifi.html#manual-ips)
WARNING Initial connection failed. The ESP might not be connected to WiFi
yet (Error resolving IP address: Error resolving address with mDNS: Did not
respond. Maybe the device is offline., [Errno -5] No address associated
with hostname). Re-Trying in 1 seconds" I will  take a look how i can
handle this.

Am Fr., 11. Sept. 2020 um 21:34 Uhr schrieb Roman Priesol <
notifications@github.com>:

**Comment by ImmanuelT8** [comment]
If i set the IP manually i get:

========================= [SUCCESS] Took 10.82 seconds
=========================INFO Successfully compiled program.INFO
Connecting to 192.168.8.109ERROR Connecting to 192.168.8.109:3232
failed: [Errno 113] No route to host

I simulat hassio in virtual Box, maybe this is the problem? In Windows CMD
i had not Gataway in virtual box ethernet adapter etc?.. Did you have any
idea? THX

Regards

Am Fr., 11. Sept. 2020 um 21:40 Uhr schrieb Emanuel Schicktanz <
emanuel.schicktanz@gmail.com>:

**Comment by randybb** [comment]
hassio needs to be on the same network together with esphome nodes, mDNS must be allowed,... there is plenty of things that could go wrong and it would be better to reach guys on https://discord.gg/KhAMKrd or https://community.home-assistant.io/c/third-party/esphome - there will be people that can resolve you problem much quicker that here on our issue tracker.

These issues are not related to any bug. Well, the reverse one wire address should not bring it down, but the other problems are not.

**Comment by ssieb** [comment]
Turns out that he's using 1.14.4 which has an issue with ESP32 and dallas sensors.  Using 1.14.5, beta, or dev will fix this.
