### ISSUE TITLE
Captive portal not working on ios

### ISSUE THREAD

**Issue by adonno** [esphome/issues#1482]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

Wemos D1 mini (ESP8266)
**ESPHome version (latest production, beta, dev branch)**

ESPHome 1.15
**Affected component:**

https://esphome.io/components/captive_portal.html 

**Description of problem:**

When on iOS (i.e. iPhone) 
The available networks are not listed, 

When entering the network SSID and PW manually and saving nothing happens. 
After rebooting the esp, it will connect to the network

@magnusoverli experienced the same issue. 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by magnusoverli** [comment]
I experienced this issue, but I was on Mac/Safari. Also tested on Android.
