### ISSUE TITLE
No up-to-date i386 build

### ISSUE THREAD

**Issue by ehmke** [esphome/issues#1513]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

esphome 

**Description of problem:**
I can't update to an up-to-date version of esphome. hassio reports: "This update is no longer compatible with your system."

On Docker-Hub there is no i386 build available of the latest version either.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by jesserockz** [comment]
i386 images were removed due to them not working recently.
https://github.com/esphome/esphome-docker-base/issues/5

**Comment by napieraj** [comment]
closing this issue, the images have been removed, for more information and further discussion see #1386
