### ISSUE TITLE
Configuration colors not visible to include files

### ISSUE THREAD

**Issue by GHF** [esphome/issues#1515]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

macOS 10.15.7 using Homebrew pip3

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 (TTGO T-Display board)

**ESPHome version (latest production, beta, dev branch)**

1.15.2 (through pip)

**Affected component:**

https://esphome.io/guides/configuration-types.html#color

**Description of problem:**

All of the colors generated by the `color:` top-level configuration block are only visible within the main sketch's `setup()`, not globally accessible like with other configuration types that have IDs.

It would be nice if the code generator placed these colors at the namespace level instead inside of setup (or maybe they can be indirect pointer that get set by `setup()` like the other ID-able variables).

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  includes: # Only included into main sketch
    - display.h
...
color:
  - id: color_card_divider
    red: 0.1
    green: 0.1
    blue: 0.1
```
Part of configuration at https://github.com/GHF/iaq-node/blob/dev/iaq-node.yaml

**Logs (if applicable):**

If I actually try to write code in `display.h` that use the `color_card_divider` Color, then I get this:

```
In file included from src/main.cpp:98:
src/display.h: In function 'void {anonymous}::DrawPage(esphome::display::DisplayBuffer&, size_t)':
src/display.h:128:58: error: 'color_card_divider' was not declared in this scope
                        it.get_width() - kCardSpacing, id(color_card_divider));
                                                          ^~~~~~~~~~~~~~~~~~
*** [.pioenvs/esphome_iaq_0/src/main.cpp.o] Error 1
```

**Additional information and things you've tried:**

**Comment by jesserockz** [comment]
Yes, the header is included so that you can use variables and functions define inside it, but the other direction does not work.
If you want to use the color (or any other components), you will most likely need to pass it as one of the parameters to your defined function.
 
If you have many, you could create another function which sets pointers to them in the custom header file to be used elsewhere in the file.

**Comment by GHF** [comment]
> If you want to use the color (or any other components)

I opened this bug because _only_ colors seem to be inaccessible from the custom header files, while other components _are_ accessible. For example, I could use `id(<font>)` and `id(<sensor>)` just fine in https://github.com/GHF/iaq-node/blob/dev/display.h

FWIW, the workaround you provided is reasonable (and I ended up just putting colors in the header itself), but this particular behavior unique to Color seemed unintentional.

**Comment by jesserockz** [comment]
Ah ok, I was unaware that you could get other components via `id()` too, which does make this a bug then.
