### ISSUE TITLE
Possibility to have LOCK entity

### ISSUE THREAD

**Issue by Klagio** [esphome/issues#154]
I managed to have two switch: one goes ON for LOCK and another switch goes ON for UNLOCK,

but now in frontend I have two switches. I wish I had a single entity "lock"

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
feature request
