### ISSUE TITLE
Direct communication between esphome devices

### ISSUE THREAD

**Issue by fdb-git** [esphome/issues#1540]
Hi,

is there a way to communicate events directly between two or more esphome devices without the need of an Home Assistant? A simple example: a button press in device1 toggle a relay on device2 and device3.

DO NOT DELETE ANY TEXT from this template! Otherwise the issue may be closed without a comment.
-->

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by rradar** [comment]
Please be aware that this here is only a tracker for esphome issues. For question best use the chat or forum.

[wifi_now esphome component - communicate directly to other ESP device via ESP-Now #1290](https://github.com/esphome/esphome/pull/1290)
