### ISSUE TITLE
can not compile 

### ISSUE THREAD

**Issue by drk-geek** [esphome/issues#1549]
I am using home assistant core on RPI so intalled Eshphome via command line on same RPI, able to open dashboard, can add first node but when I tried to compile it there is nothing, even for 10hrs, nothing at all, Esphome 1.14.5, trying to add BME280 with D1 mini, any help ?
The screen remains black all the time

![esphome1](https://user-images.githubusercontent.com/63916817/95748285-33a40a80-0cb3-11eb-9a40-d8d518fc32d5.png)
![esphome2](https://user-images.githubusercontent.com/63916817/95748328-41599000-0cb3-11eb-9c02-e8e066ad05d3.png)

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by rradar** [comment]
Could you try again with the latest release 1.15.x
