### ISSUE TITLE
Can't set GPIO0 HIGH

### ISSUE THREAD

**Issue by sliwma** [esphome/issues#1554]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP01S / Wemos D1 Mini
**ESPHome version (latest production, beta, dev branch)**

1.15.2

**Affected component:**

https://esphome.io/components/switch/gpio.html

**Description of problem:**
GPIO0 does not give HIGH state - checked with ESP01S and Wemos D1 Mini.
Code is OK, as changing pin to GPIO2 both in config and wiring works.
Boards are OK, as it works properly with Tasmota.
Logs states that everything is OK.

**Problem-relevant YAML-configuration entries:**
```yaml
switch:
  - platform: gpio
    pin: GPIO0
    name: "Domofon"
```

**Logs (if applicable):**

```
[11:11:44][D][switch:021]: 'Domofon' Turning ON.
[11:11:44][D][switch:045]: 'Domofon': Sending state ON

```

**Additional information and things you've tried:**

Tried with Tasmota - works properly.

**Comment by lazlyhu** [comment]
@sliwma Could you try, is it working with a GPIO binary sensor with a pullup resistor (or with internal pullup)? I have issues with GPIO0 too from 1.15, worked fine before. Maybe connected to this.
