### ISSUE TITLE
This add-on is not available on your system. 

### ISSUE THREAD

**Issue by ribbles** [esphome/issues#1604]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**
Get error in Home Assistant Supervisor attempting to add ESPHome add-on. The error is `This add-on is not available on your system. ` I have a clean install rPi Zero W with the Home Assistant OS image installed and Home Assistant Core 0.117.4.

Of course, [rPi is arm6](https://raspberrypi.stackexchange.com/questions/83374/raspberry-pi-zero-w-is-armv6-or-armv7), while esphone only supports [arm7, x64 & aarm64](https://github.com/hassio-addons/repository/blob/master/esphome/config.json#L3).

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
20-11-06 23:23:15 ERROR (MainThread) [supervisor.addons] Add-on a0d7b954_esphome not supported on that platform

```

**Additional information and things you've tried:**

I see others have had the same issue: https://community.home-assistant.io/t/esphome-this-add-on-is-not-available-on-your-system/135195/4

**Comment by rradar** [comment]
> Of course, rPi is **arm6**, while esphone only supports **arm7, x64 & aarm64**.

You answered your issue already. No Hass-io addon for arm6 (rpi0/rpi1). As a alternative you could try your luck with a [pip3 install](https://esphome.io/guides/getting_started_command_line.html)
