### ISSUE TITLE
I2C support does not permit 16-bit register addresses?

### ISSUE THREAD

**Issue by cerebrate** [esphome/issues#1624]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io (HA version 0.117.6)

**ESP (ESP32/ESP8266, Board/Sonoff):**

Adafruit Feather HUZZAH 8266

**ESPHome version (latest production, beta, dev branch)**

1.15.3

**Affected component:**

Custom I2C component - specific query relates to [esphome::i2c::I2CDevice](https://esphome.io/api/classesphome_1_1i2c_1_1_i2_c_device.html) class.

**Description of problem:**

I'm trying to implement a custom component for the Adafruit STEMMA Soil Sensor ([documented here](https://learn.adafruit.com/adafruit-stemma-soil-sensor-i2c-capacitive-moisture-sensor)) which is based on the [Adafruit seesaw platform](https://learn.adafruit.com/adafruit-seesaw-atsamd09-breakout/). As you can see from the latter documentation, this platform uses two register bytes to read and write data - for example, reading a value using Wire can be written as:

```
    Wire.beginTransmission((uint8_t)this->i2c_addr);
    Wire.write((uint8_t)regHigh);
    Wire.write((uint8_t)regLow);
    Wire.endTransmission();

    delayMicroseconds(delay);

    Wire.requestFrom((uint8_t)this->i2c_addr, 1);
    value = Wire.read();
```

Unfortunately, as I read the source for I2CDevice, it appears that all the current read/write functions take only a single byte for register addresses. Am I correct in the understanding that they cannot be used to read/write such registers as is, and lower-level functions must be used?

(Also, if this is the case, would a PR to extend I2CDevice to handle devices using two-byte register addresses be welcome?)

**Problem-relevant YAML-configuration entries:**
```yaml
None.
```

**Logs (if applicable):**
```
None.
```

**Additional information and things you've tried:**

I have a kluged workaround at the moment which bypasses ESPHome's own I2C support and uses Wire directly to access the STEMMA, and I am contemplating a less klugey workaround using the raw_* (internal) methods of I2CDevice.

**Comment by jesserockz** [comment]
esphome/esphome#1268
