### ISSUE TITLE
esphome:  does not work, if set in a package and the http_request component is used.

### ISSUE THREAD

**Issue by Lovely-Maisonette** [esphome/issues#1680]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

my esphome.yaml package with two lines:
esphome:
  name: ${node_name}
  comment: ${model}

$model is expanded correctly in the UI
$node_name is expanded correctly and creates a host under that name expansion.

my http_request.yaml package file, with one line
http_request:

my devices compile without problem, until I try to include anywhere an http_request action.
validation then fails with:

  File "/usr/src/app/esphome/components/http_request/__init__.py", line 30, in validate_framework
    if CONF_ARDUINO_VERSION in CORE.raw_config[CONF_ESPHOME]:
KeyError: 'esphome'

it seems this code (CORE.raw_config?) does not read esphome: from a package, and abort for not finding this section
if I move the two lines to my main yaml file, validates without problem.

def validate_framework(config):
    if CORE.is_esp32:
        return config

    version = 'RECOMMENDED'
    if CONF_ARDUINO_VERSION in CORE.raw_config[CONF_ESPHOME]:
        version = CORE.raw_config[CONF_ESPHOME][CONF_ARDUINO_VERSION]

That makes sense, because this code is ONLY called once I use the http_request component, to verify I am having Framework > 2.5

**Comment by ashmckenzie** [comment]
Am seeing the same issue with `ESPHome v1.16.2`.
