### ISSUE TITLE
Light automation '- light.turn_on:' wont allow two (or more) 'transformers'

### ISSUE THREAD

**Issue by 3ative** [esphome/issues#1705]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**ESPHome version (latest production, beta, dev branch)**

Latest - v1.15.3

**Affected component:**

### **light.turn_on Action**
https://esphome.io/components/light/index.html?highlight=light%20turn_on#light-turn-on-action

**Description of problem:**
When using _'light.turn_on Action'_, an error occurs when 'effect' and 'transition_length' are used together - either on their own work as expected. The '**Configuration options:**' (_docs page_) suggests any combination is allowed. 

**Problem-relevant YAML-configuration entries:**
![Error](https://user-images.githubusercontent.com/51385971/102704178-deb2e080-426f-11eb-928b-2d6fdaf7845a.JPG)

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
When sending an API command from Node-Red, I.E. 'Call service Node' >Domain > Light > 'turn_on'** with Data 'effect).
For example:
```yaml
    data:
    {"effect":"flicker"}
```
The **default_transition_length:** of the light is respected - So it would be great if this was also the case for this "light.turn_on Action"

**Comment by 3ative** [comment]
Anyone ??
Bueller... Bueller...

**Comment by glmnet** [comment]
looks like you want a pulsating effect?

**Comment by 3ative** [comment]
> looks like you want a pulsating effect?

No, I would like to add 'Flicker' effect and another parameter - as mentioned above, ESPHome "light.turn_on:' only allows one.

**Comment by glmnet** [comment]
Yes seems like two different effects 

What you want to accomplish exactly?

Transition length is for fading from one brightness or color to another, no fading from or to effects is supported

**Comment by 3ative** [comment]
@glmnet 
Within ESPHome code there is a 'Default Transition Length' and if I command this light to come on, from outside - E.G. HA or Node-Red, both the 'Flicker' effect and default transition is honoured.
However, using the ESPHome automation, this _default transition_ is ignored - so, I tried to include it in the ESPHome automation... as you can see, it doesn't like it.
