### ISSUE TITLE
Create firmware .bin file without Hass.io

### ISSUE THREAD

**Issue by onlize** [esphome/issues#175]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant Virtual Environment
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

I do not have Hass.io because I use Home Assistant Virtual Environment. Your instructions show me how to create *.bin firmware file from Hass.io interface. Home Assistant Virtual Environment does not have that interface. How can I create firmware *.bin file without Hass.io?

Thank you.

**Comment by OttoWinter** [comment]
It's in the FAQ, second entry.
