### ISSUE TITLE
Failed OTA update does not allow for manual download of compiled binary (without HTML edits)

### ISSUE THREAD

**Issue by ab3lson** [esphome/issues#1775]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

All boards.
**ESPHome version (latest production, beta, dev branch)**

ESPHome latest.
**Affected component:**

**Description of problem:**
When OTA updates error out, you should be able to download the binary by clicking on the ... and then "Download Binary". However, the option is greyed out. This should be a simple fix, because if I go into the HTML and delete the "disabled" attribute, then I can download the binary just fine. This bug is rather annoying, because sometimes the code can take a while to compile and if the OTA update fails, a user would have to manually compile the code in a different menu, when it has already been compiled. I believe that if the code has successfully compiled, the "disabled" attribute should not be applied to the "Download Binary" option.

**Problem-relevant YAML-configuration entries:**

**Logs (if applicable):**

**Additional information and things you've tried:**
Deleting the "disabled" attribute in the HTML after an OTA update has failed allows you to download the compiled binary.

**Comment by cerebrate** [comment]
I also have this problem, since I run ESPHome in a container inside a VM, and all of that makes it rather awkward to do non-OTA-or-downloaded-binary updates - would very much appreciate a fix.

In the meantime, many thanks to @ab3lson for the workaround!
