### ISSUE TITLE
Color logs still broken maybe.

### ISSUE THREAD

**Issue by foxsam21** [esphome/issues#1778]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip installation of esphome in a venv
**ESP (ESP32/ESP8266, Board/Sonoff):**

any
**ESPHome version (latest production, beta, dev branch)**

1.17.0-dev

**Affected component:**

`logger` https://esphome.io/components/logger.html

**Description of problem:**
Color logs still missing even after fix.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

I saw https://github.com/esphome/esphome/pull/1385 and understand it to be fixed however my experience is that it is only fixed in dashboard not in cli. I tried asking in discord but I think there will be more work and exposure here.
Here is the cli:
![image](https://user-images.githubusercontent.com/11862524/105446244-bb4cce00-5c3f-11eb-8bd8-2c10fa23a19d.png)

and here is dashboard:
![image](https://user-images.githubusercontent.com/11862524/105446137-8771a880-5c3f-11eb-9f99-1d970e4100e5.png)

**Comment by gretel** [comment]
same for me.

**Comment by foxsam21** [comment]
Works good so far. Thanks for everything.
