### ISSUE TITLE
Total Daily Energy inaccurate for sensors that only produce a new value on change

### ISSUE THREAD

**Issue by frog32** [esphome/issues#1786]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):** ESP8266

ESP12F based circuit.

**ESPHome version (latest production, beta, dev branch)**

Latest

**Affected component:**

Total Daily Energy

**Description of problem:**
Total Daily Energy on new value multiplies this new measurement with the time spent since last value was received. This is equivalent to using the right side value to interpolate. For every sensor that only produces a value on change this can be significantly off as shown by my coffee machine that apparently uses double digit kWh each day. Attached are screen shots of a scenario where the calculated value is equivalent of flipping the heating and idle cycles of my coffee machine.
<img width="1378" alt="Screenshot 2021-01-24 at 21 20 22" src="https://user-images.githubusercontent.com/328966/105642658-4ec60f00-5e8b-11eb-8f78-e78d1433a04a.png">
<img width="1378" alt="Screenshot 2021-01-24 at 21 20 50" src="https://user-images.githubusercontent.com/328966/105642674-68ffed00-5e8b-11eb-8332-42472ec66830.png">

The power consumption is almost 1.2kWh in one hour which is the power consumption when the heating element is running.

The issue is on the following line https://github.com/esphome/esphome/blob/dev/esphome/components/total_daily_energy/total_daily_energy.cpp#L50 which is equivalent to right side approximation in integration sensor https://github.com/esphome/esphome/blob/dev/esphome/components/integration/integration_sensor.cpp#L62

**Problem-relevant YAML-configuration entries:**
```yaml
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by nuttytree** [comment]
I ran into this issue using a template sensor that simply publishes the wattage of the attached device when turned on and publishes 0 when turned off.  With the infrequent sensor updates this results in you get a total usage of the wattage of the device times the time it was off when it gets turned on and it never captures the usage when it was on.  This sensor is essentially a helper sensor that does the same thing as the integration sensor but sets some of the config values for you.  It really should have an option to specify the method (left, right, or trapezoid).
