### ISSUE TITLE
Nextion display component doesn't seem to work properly

### ISSUE THREAD

**Issue by thedexboy** [esphome/issues#18]
So I tried connecting a Nextion display to a Wemos D1 Pro board via a level shifter.
Funny thing is, ESPHome does send correct command over to Nextion and Nextion seems to reply back correctly. Nextion will also show the data that was sent to it.
Here is a very-verbose log:

> [VV][component:134]: Running interval 'update':0 with interval=5000 last_execution=36794 (now=41800)
[VV][uart:168]:     Wrote "uradatum.txt="It's alive!""
[VV][uart:157]:     Wrote 0b11111111 (0xFF)
[VV][uart:157]:     Wrote 0b11111111 (0xFF)
[VV][uart:157]:     Wrote 0b11111111 (0xFF)
[VV][uart:201]:     Read 0b00000001 (0x01)
[VV][uart:201]:     Read 0b11111111 (0xFF)
[VV][uart:201]:     Read 0b11111111 (0xFF)
[VV][uart:201]:     Read 0b11111111 (0xFF)
[W][display.nextion:111]: Sending command 'uradatum.txt="It's alive!"' failed because no ACK was received

On Nextion you have to set "[bkcmd=3](https://www.itead.cc/wiki/Nextion_Instruction_Set)" because if I leave it default, Nextion only returns a message if there is an error.

> bkcmd=0 (Return nothing)
bkcmd=1 (Only return on successful data)
bkcmd=2 (Only return on failed data)
bkcmd=3 (Always return） 

Thsre are the options.
If you leave it default (2 - only return failed data), I get the following:

> [VV][component:134]: Running interval 'update':0 with interval=5000 last_execution=464146 (now=469150)
[VV][uart:168]:     Wrote "uradatum.txt="It's alive!""
[VV][uart:157]:     Wrote 0b11111111 (0xFF)
[VV][uart:157]:     Wrote 0b11111111 (0xFF)
[VV][uart:157]:     Wrote 0b11111111 (0xFF)
[E][uart:213]: Reading from UART timed out at byte 0!
[W][display.nextion:039]: Nextion returned no ACK data!

That is expected as Nextion doesn't return any data. For the display, data was received successfully and it displays the data.

My config:
```yaml
uart:
  rx_pin: D7
  tx_pin: D4
  baud_rate: 9600

binary_sensor:
  - platform: nextion
    page_id: 0
    component_id: 13
    name: "Nextion test button"

display:
  - platform: nextion
     # set bkcmd=3 to Nextion to get back confirmation
    lambda: |-
      it.set_component_text("uradatum", "It's alive!");
```

In short, Nextion does reply with 0x01 0xff 0xff 0xff to state that it got correct data. ESPHome doesn't treat received data as ok and is sending out warnings.

One more thing, if I press a button on Nextion, error changes to:

> [VV][component:134]: Running interval 'update':0 with interval=5000 last_execution=38340 (now=43347)
[VV][uart:168]:     Wrote "uradatum.txt="It's alive!""
[VV][uart:157]:     Wrote 0b11111111 (0xFF)
[VV][uart:157]:     Wrote 0b11111111 (0xFF)
[VV][uart:157]:     Wrote 0b11111111 (0xFF)
[VV][uart:201]:     Read 0b01100101 (0x65)
[VV][uart:201]:     Read 0b00000000 (0x00)
[VV][uart:201]:     Read 0b00001101 (0x0D)
[VV][uart:201]:     Read 0b00000001 (0x01)
[W][display.nextion:044]: Nextion returned invalid ACK data!
[VV][uart:178]:     Read 0b11111111 (0xFF)
[VV][uart:178]:     Read 0b11111111 (0xFF)
[VV][uart:178]:     Read 0b11111111 (0xFF)

Touch event is logged as 0x65, button's ID is 13 (0x0D) on page 0 (0x00) and I pressed the button (0x01) in this case.
[https://www.itead.cc/wiki/Nextion_Instruction_Set#Format_of_Device_Return_Data](https://www.itead.cc/wiki/Nextion_Instruction_Set#Format_of_Device_Return_Data)

If you need some more testing please let me know, I'll be glad if I can be of any help :)

**Comment by OttoWinter** [comment]
Should be fixed in 1.12 and latest.
