### ISSUE TITLE
Logging of LED % value not correct

### ISSUE THREAD

**Issue by matthijsberg** [esphome/issues#1834]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio supervised with container running ESP-Home 1.6

**ESP (ESP32/ESP8266, Board/Sonoff):**

Lolin 3.1 ESP8266

**ESPHome version (latest production, beta, dev branch)**

v1.6

**Affected component:**

Logger I presume.

**Description of problem:**

The log shows, imho, the wrong % for the led lights. I based the led colors % on a calculated valued (see code), and I would expect the % in the logging to match that values I set. That is never the case. 

The actual color of the leds seems correct! This is especially a problem if you're remote debugging

In the logging you'll see `[D][main:299]: CO2 800 - 1500 loop.. Green: 0.620252, red: 0.129748, blue: 0.000000` as the calculated values that I use to set the led colors, but the logging shows `[D][light:287]:   Red=21%, Green=100%, Blue=0%`. I think this is not correct (I would expect 62%, 12%, 0% based on the values).

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: scd30
    i2c_id: bus_a
    address: 0x61
    co2:
      name: "scd30 CO2"
      id: scd30_co2
      accuracy_decimals: 1
      on_raw_value:
        then:
          lambda: !lambda |-
            auto call = id(color_leds_id).turn_on();
            static float red = 0.0;
            static float green = 0.0;
            static float blue = 0.0;             // x is sensor value input from ESP Home
            ESP_LOGD("main", "CO2 number is: %f", x);
            if (x < 800) {
              green = 0.75;
              red = 0.0;
              blue = 0.0;
              ESP_LOGD("main", "CO2 < 800 loop. Green: %f, red: %f, blue: %f", green, red, blue);
            } else if (x > 800 and x < 1500) { 
              red = ((x -800) / 700) * 0.75;
              green = (1 - ((x - 800) / 700)) * 0.75;
              blue = 0.0;
              ESP_LOGD("main", "CO2 800 - 1500 loop.. Green: %f, red: %f, blue: %f", green, red, blue);
            } else if (x > 1500 and x < 2000){ 
              red = ((x - 1500) / 500) * 0.75;
              green = 0.0;
              blue = (x / 500.0 - 3.0) * 0.75;
              ESP_LOGD("main", "CO2 1500 - 2000 loop. Green: %f, red: %f, blue: %f", green, red, blue);
            } else if (x > 2000 ){ 
              red = 0.75;
              green = 0.0;
              blue = 0.75;
              ESP_LOGD("main", "CO2 > 2000 loop. Green: %f, red: %f, blue: %f", green, red, blue);
            } 
            call.set_transition_length(1000); // in ms
            call.set_rgb(red, green, blue); // color, 1.0 is fully lit
            call.perform();
          # note that the logging in ESP Home debug console for RGB % is not correct, but the leds do give the right color.
    temperature:
      name: "scd30 Temperature"
      id: scd30_temperature
      accuracy_decimals: 1
    humidity:
      name: "scd30 Humidity"
      id: scd30_humidity
      accuracy_decimals: 1
    temperature_offset: 5.5
    update_interval: 10s

```

**Logs (if applicable):**

```
[D][scd30:153]: Got CO2=921.10ppm temperature=23.04°C humidity=31.67%
[D][main:289]: CO2 number is: 921.098572
[D][main:299]: CO2 800 - 1500 loop.. Green: 0.620252, red: 0.129748, blue: 0.000000
[D][light:265]: 'LED Light' Setting:
[D][light:287]:   Red=21%, Green=100%, Blue=0%
[D][light:304]:   Transition Length: 1.0s
[D][sensor:092]: 'scd30 CO2': Sending state 921.09857 ppm with 1 decimals of accuracy
[D][sensor:092]: 'scd30 Temperature': Sending state 23.04357 °C with 1 decimals of accuracy
[D][sensor:092]: 'scd30 Humidity': Sending state 31.67292 % with 1 decimals of accuracy

```

**Additional information and things you've tried:**

I tried the `light.control` and other light. commands too, they give the same result. 
I tried fastled_clockless in stead of neopixelbus
I played around with brightness values as I thought that might influence the output, but it appears not to.

**Comment by oxan** [comment]
> the logging shows [D][light:287]: Red=21%, Green=100%, Blue=0%. I think this is not correct (I would expect 62%, 12%, 0% based on the values).

No, this is correct. The red, green, blue values only control the color of the light, not its brightness. Only the value of the channels relative to each other matters, and ESPHome normalizes these values so that at least one channel is exactly 100%. See also the note in the documentation [here](https://esphome.io/components/light/index.html#light-turn-on-action).
