### ISSUE TITLE
Inaccessible WiFi causes immediate battery drain

### ISSUE THREAD

**Issue by jbrepogmailcom** [esphome/issues#1838]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**ESPHome version (latest production, beta, dev branch)**

latest
**Affected component:**

WiFi

**Description of problem:**
I use deep sleep, wake once per hour, connect to wifi, send mqtt and go back to deep sleep. If wifi is not available, then ESPHome causes the sensor either reset endlessly, or start captive portal and if wifi is not configured then restart again. This is not desirable behavior, because it causes the sensor never to go to deep sleep and try later. I would believe that correct behavior would be to try for a while, but then skip wifi configuration and go to deep sleep and try wifi at next wakeup.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by ssieb** [comment]
If you don't want the captive portal, then don't include it in the config.  What is your deep sleep configuration?  If you want it to go back to sleep regardless of sending data, then you could have an `on_boot:` with a delay and a forced sleep.
The only way I could see this being a bug is if your deep_sleep config sets a runtime, but doesn't go to sleep after that time if wifi doesn't connect.
