### ISSUE TITLE
ESP32 DHCP Hostname official Bugfix

### ISSUE THREAD

**Issue by Sn0ff** [esphome/issues#1855]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

hostname problem was ixed in version  ( ESP32 Arduino 1.0.5 RC7 ) 2 days ago

ESP32 Arduino 1.0.5 RC7
https://github.com/espressif/arduino-esp32/commit/ad4cf1461bea3fb1378402b572383813ea9c2a06

**Comment by glmnet** [comment]
This isn't reporting anything
