### ISSUE TITLE
ESPHome HA Addon 1.16.2 missing configuration section

### ISSUE THREAD

**Issue by pcartwright81** [esphome/issues#1862]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

1.16.2
**Affected component:**

 HA Addon

I hit reset on the configuration section, now it is missing.

![108600081-89bc4500-735a-11eb-9552-f16f74e7e678](https://user-images.githubusercontent.com/2352477/108600684-17e5fa80-735e-11eb-913c-321a4dca75f6.png)
![108600092-95a80700-735a-11eb-9a19-f7f681c0a395](https://user-images.githubusercontent.com/2352477/108600687-1e747200-735e-11eb-85a5-50f2fafe8c6e.png)

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Uninstalling and reinstalling addon.  
Finding configuration file.

**Comment by Protoncek** [comment]
@pcartwright81 : Hello!
Did you solve the problem? How? Because i have the same situation...

**Comment by pcartwright81** [comment]
Since this is a home assistant issue I opened it on the home assistant issue tracker.
It is a supervisor issue and will be fixed in the latest beta.
https://github.com/home-assistant/core/issues/46826

**Comment by Protoncek** [comment]
Ok, thanks a lot!
