### ISSUE TITLE
slow_pwm doesn't work as intended (it is always on)

### ISSUE THREAD

**Issue by qqgg231** [esphome/issues#1992]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HassOS

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 and ESP8266

**ESPHome version (latest production, beta, dev branch)**

1.16.2
**Affected component:**

https://esphome.io/components/output/slow_pwm.html

**Description of problem:**

https://community.home-assistant.io/t/how-to-use-slow-pwm-and-define-the-duty-cycle/287822

**Problem-relevant YAML-configuration entries:**
```yaml
in link above

```

**Logs (if applicable):**

```
-

```

**Additional information and things you've tried:**

**Comment by ssieb** [comment]
It looks like you found the answer.

**Comment by qqgg231** [comment]
@ssieb 
yes, but I think the way slow_pwm works is unintuitive

**Comment by ssieb** [comment]
In what way?  It works exactly the same as all the other pwm outputs.
