### ISSUE TITLE
Documentation: simple Xiaomi BLE bindkey extraction

### ISSUE THREAD

**Issue by PiotrMachowski** [esphome/issues#2014]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

n/a

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**ESPHome version (latest production, beta, dev branch)**

n/a

**Affected component:**

[xiaomi_ble](https://esphome.io/components/sensor/xiaomi_ble.html)

**Description of problem:**

It seems that there is an easy way to extract encryption keys for devices connected to Xiaomi cloud, can you confirm it and add to ESPHome documentation if it works for this case (I can't try it by myself, because I don't have BLE devices)?

[Xiaomi cloud tokens extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor)

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by kiwipaulrob** [comment]
Works for me and fabulous to have (windows). I see that author is working on adding the MAC addresses. Whoop. Should  definitely be added to documentation.
