### ISSUE TITLE
Board type error v overview listed

### ISSUE THREAD

**Issue by Magic-m-canon** [esphome/issues#2025]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.4.6
 Home Assistant Supervisor: 2021.04.3

**ESP (ESP32/ESP8266, Board/Sonoff):**

M5CAM module which corresponds to M5Stack Camera

**ESPHome version (latest production, beta, dev branch)**

Add-on version: 1.17.0

**Affected component:**

https://esphome.io/components/esp32_camera.html?highlight=esp32

**Description of problem:**
I can not find the corresponding BOARD TYPE for the M5Stack Camera listed in the attached guide - and when trying to match the list of accepted boards listed in error message do not have a brakline to allow for a total overview. So I am left with guessing.

**Problem-relevant YAML-configuration entries:**
esphome:
  name: myname
  platform: ESP32
  board: M5Stack <------ what is the board type for this? ref to attached link above
PASTE YAML FILE HERE

```

**Logs (if applicable):**
<!--
Please copy the debug log here. If possible, also connect to the ESP over USB and copy those logs into the backticks.
-->
```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**




<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE ISSUE WILL BE CLOSED AUTOMATICALLY. -->

**Comment by ssieb** [comment]
This isn't an esphome bug.  It's not really a bug at all.  The doc page for [ESP32](https://esphome.io/devices/esp32.html) points to the [platformio page](http://docs.platformio.org/en/latest/platforms/espressif32.html) that has a list of all the board definitions that are available.  Find your board or an equivalent one and use the given board name in your config.
