### ISSUE TITLE
On ESP8266, reading analog A0 during wifi transmission can provide bad result

### ISSUE THREAD

**Issue by jbrepogmailcom** [esphome/issues#2030]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**
I was getting some noisy readings from A0 pin. Then I found some articles that A0 should not be read during wifi transmission. There are also other precautions that need to be taken in account, chapter 4.9 of 0a-esp8266ex_datasheet_en.pdf.

Considering all this, I think there should be a mechanism to allow to read A0 before wifi is initialized. Is that possible?

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
> read A0 before wifi is initialized

then you'd only have a single reading per boot, so not very useful I think
