### ISSUE TITLE
esphome-docs: docker image out of date (Python outdated)

### ISSUE THREAD

**Issue by Grtschnk** [esphome/issues#2041]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Win10+Docker (esphome-docs)

**ESP (ESP32/ESP8266, Board/Sonoff):**

n/a

**ESPHome version (latest production, beta, dev branch)**

esphome-docs:current

**Affected component:**

Python version in docker image for esphome-docs (and possible other libraries/dependencies)
https://hub.docker.com/r/esphome/esphome-docs/
https://esphome.io/guides/contributing.html#contributing-to-esphome-docs

**Description of problem:**
Trying to build esphome-docs locally. Build inside Docker image fails. Python throwing syntax error due to F-strings. This feature was added with Python 3.6. The container seems to have Python 3.5

**Problem-relevant YAML-configuration entries:**
```yaml
n/a
```

**Logs (if applicable):**

```
PS C:\WINDOWS\system32> docker run --rm -v C:\esphomedocsnew\:/data/esphomedocs -p 18845:8000 -it esphome/esphome-docs
sphinx-build -M html . _build -j auto -n
Running Sphinx v1.8.4
loading translations [en]... done

Exception occurred:
  File "/usr/local/lib/python3.5/dist-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/data/esphomedocs/schema_doc.py", line 26
    logger.info(f"{SCHEMA_PATH} not found. Not documenting schema.")
                                                                  ^
SyntaxError: invalid syntax
```

**Additional information and things you've tried:**

I managed to build the documentation with sphinx directly. I also had to generate the "schema.json" (with script/build_jsonschema,py) first.

**Comment by martgras** [comment]
Just submitted a PR to fix the docker error. 
In the meantime you can use this Dockerfile https://github.com/esphome/esphome-docs/blob/67b1e1e7c510f78208e7ad43c47d6971a85640f1/Dockerfile  and then run 

````
docker build  -t esphome/esphome-docs .
docker run --rm -v "${PWD}/":/data/esphomedocs -p 8000:8000 -it esphome/esphome-docs
````
