### ISSUE TITLE
Add support for Lilygo TTGO K210 camera and touch display ESP32

### ISSUE THREAD

**Issue by Hellis81** [esphome/issues#2050]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 
**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**
It would be nice if this device was added.
Link to Lilygo Github: https://github.com/Xinyuan-LilyGO/LilyGo-K210-Script
The actual device: https://www.banggood.com/sv/LILYGO-TTGO-T-Watch-K210-ESP32-Chip-AI-Face-Recognition-Programming-Bluetooth-WiFi-Module-p-1691936.html

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by rradar** [comment]
this tracker is for issues only, please **open a feature request** here: https://github.com/esphome/feature-requests
