### ISSUE TITLE
"Warning! More than one package has been found by AsyncTCP-esphome" during compilation on 1.17.2

### ISSUE THREAD

**Issue by evgeni** [esphome/issues#2052]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Fedora 33, pip

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266, Shelly 2.5

**ESPHome version (latest production, beta, dev branch)**
1.17.2

**Affected component:**
N/A

**Description of problem:**
When compiling after the update (from 1.16.x), platformio emits a warning:

```
Library Manager: Warning! More than one package has been found by AsyncTCP-esphome requirements:
 - ottowinter/AsyncTCP-esphome @ 1.2.1
 - esphome/AsyncTCP-esphome @ 1.2.2
Library Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts
Library Manager: AsyncTCP-esphome @ 1.2.1 has been installed!
```

I'd expect it to pick up 1.2.2 instead?

**Problem-relevant YAML-configuration entries:**
```yaml
N/A

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
Fixed in https://github.com/esphome/esphome/pull/1762
