### ISSUE TITLE
PZEM-017/03 Energy Parameter 

### ISSUE THREAD

**Issue by speakerboar** [esphome/issues#2062]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio
**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff
**ESPHome version (latest production, beta, dev branch)**

1.17.2
**Affected component:**

pzemdc

**Description of problem:**
Pzem component missing energy Wh sensor.
The PZEM-017 and PZEM-003 measures DC volts , Power , Ampere and Energy but there is no support for Energy in esphome 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by rradar** [comment]
You could just use home assistant for that: https://www.home-assistant.io/integrations/utility_meter/

Also this is more a feature request than a "real" issue, feel free to **open a request here**: https://github.com/esphome/feature-requests
