### ISSUE TITLE
Error: Unknown board ID 'lolin32-lite'

### ISSUE THREAD

**Issue by cityboy19** [esphome/issues#2064]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

firmware upload to LOLIN32-lite
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 Lolin32 lite [https://www.aliexpress.com/item/33009178296.html](url)
**ESPHome version (latest production, beta, dev branch)**

1.18.0
**Affected component:**

**Description of problem:**
Error: Unknown board ID 'lolin32-lite'

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: szklarnia
  platform: ESP32
  board: lolin32-lite

```

**Logs (if applicable):**

```
[proelite@optiplex790 esp32]$ esphome szklarnia.yaml run
INFO Reading configuration szklarnia.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d szklarnia
Processing szklarnia (board: lolin32-lite; framework: arduino; platform: platformio/espressif32@3.0.0)
--------------------------------------------------------------------------------
Error: Unknown board ID 'lolin32-lite'

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
Correct, that board is not in ESPHome right now. But as stated in the setup wizard, you can use the generic option if your board is unavailable, and it will continue to work fine.
