### ISSUE TITLE
Support for buzzer

### ISSUE THREAD

**Issue by Melcos1970** [esphome/issues#207]
Support to play sound like in a arduino sketch like this on for a wemos buzzer shield.. 

https://github.com/wemos/D1_mini_Examples/blob/master/examples/04.Shields/Buzzer_Shield/Do_Re_Mi/Do_Re_Mi.ino

I have tryed to make the buzzer make sound with esphome ? 
I have tryed this but no sound, I can hear a littel click but no tone. 
Is it me or a bug or something else ?

output:
  - platform: esp8266_pwm
    pin: D5
    frequency: 1000 Hz
    id: buzzer_pwm_output

switch:
  - platform: output
    name: "Buzzer Output"
    output: 'buzzer_pwm_output'

**Comment by HFsi** [comment]
Use an active buzzer, it has the oscillator inside and you can control it with just a switch component
