### ISSUE TITLE
Invalid Configuration For Deta-Grid-Connect-Smart-Fan-Speed-Controller-with-Touch-Light-Switch #101

### ISSUE THREAD

**Issue by rowie1** [esphome/issues#2085]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant OS Raspberry Pi4 : core-2021.5.5

**ESP (ESP32/ESP8266, Board/Sonoff):**
 ESP8266 Deta-Grid-Connect-Smart-Fan-Speed-Controller-with-Touch-Light-Switch

**ESPHome version (latest production, beta, dev branch)**
 ESPHome version is the latest 1.18.0

**Affected component:**
 https://www.esphome-devices.com/devices/Deta-Grid-Connect-Smart-Fan-Speed-Controller-with-Touch-Light-Switch/

**Description of problem:**

I have a known working .yaml configuration file for this device, however when I copy and paste the known working file in to ESPHome in Homeassistant it is recognised as being invalid and I'm unable to compile and upload the .bin file to the fan/light controller.
I can upload the same config file to the device using the web server and the device functions as intended.
The issue ESPHome has with the config file is the fan speeds: LOW,MEDIUM & HIGH. Image attached showing the error returned from these values:

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/69198519/120269281-a9162700-c2e6-11eb-91f3-d63032b83896.png">

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by jkelly73** [comment]
I get this same error too.  Looking for some advice how to solve please.

Thx
Jon

**Comment by rowie1** [comment]
Hi Jon

ESPHome doesn’t recognise low, med & high anymore. Replace each of these entries with the equivalent percentage value (33,66,100) in your configuration then it will validate.

Hope this helps

Cheers 

Adrian

**Comment by jkelly73** [comment]
Thanks Adrian, changing the low, medium and high for 33, 66, & 100 worked like a charm!

My question now is how do you change the fan speed?  The fan ON/OFF and speed buttons doesn’t seem to behave as I would expect.  I can’t select High (100), or Medium (66), only LOW (33).  I suspect the problem lies in the timing return state routine associated with the fan_speed, here:
  - platform: template
    id: fan_speed
    type: float
    write_action:
      - then:
        - if:
            condition:
              lambda: return ((state > 0) && (state < .4));
            then:
  
As I am not a programmer and only a newbie at Homeassistant, I am in no way certain of my diagnostics!!

Any help would be greatly appreciated.

Thanks
Jon

**Comment by rowie1** [comment]
Have you controlled the fan in HA yet or just attempted to operate using the physical buttons on the controller?
I think from memory I had issues with the physical buttons until I activated the fan speeds in HA.  Following this they began working correctly on the controller.

FYI I use an ifan03 custom card in Lovelace for my fans, it works well.

Cheers 

Adrian

**Comment by jkelly73** [comment]
Well how strange! The buttons did not work as expected (as I mentioned above)... I have installed the ifan03 custom card - that works excellently and performs exactly as I expected / wanted and now the buttons work correctly also!?!?!?!

Just one small problem now, 2 of the 4 fan icons are missing from the lovelace card, although they are present in the 'static' folder????

<img width="505" alt="Screen Shot 2021-07-25 at 20 27 46" src="https://user-images.githubusercontent.com/85336126/126895974-b7879396-d266-49c5-9170-7069f76f5507.png">

Any thoughts?
Thanks
Jon

**Comment by jkelly73** [comment]
> Well how strange! The buttons did not work as expected (as I mentioned above)... I have installed the ifan03 custom card - that works excellently and performs exactly as I expected / wanted and now the buttons work correctly also!?!?!?!
> 
> Just one small problem now, 2 of the 4 fan icons are missing from the lovelace card, although they are present in the 'static' folder????
> 
> <img alt="Screen Shot 2021-07-25 at 20 27 46" width="505" src="https://user-images.githubusercontent.com/85336126/126895974-b7879396-d266-49c5-9170-7069f76f5507.png">
> 
> Any thoughts?
> Thanks
> Jon
> 
> Update...
> Ive looked in the ifan03-card.js file and I suspect there are inconsistencies between "low" and "slow.svg" and similarly with "high" and "fast.svg".

Fixed it...
I had to rename the two svg files from slow.svg to low.svg and fast.svg to high.svg and then remove the resource and re-add it.  Simply 'update'ing the resource had no affect.
<img width="497" alt="Screen Shot 2021-07-25 at 20 50 15" src="https://user-images.githubusercontent.com/85336126/126896494-bea5153f-da24-4702-9350-e3aa97507571.png">

**Comment by rowie1** [comment]
Yeah cool, I had to do something like that too, just couldn’t quite remember what I did. I also changed the speeds to low, med, high. I reckon I just opened the json file & edited all of  the normal & fast entries to be med & high.
