### ISSUE TITLE
Channels in off after reboots or updates

### ISSUE THREAD

**Issue by andker87** [esphome/issues#2087]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker
**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff 4ch
**ESPHome version (latest production, beta, dev branch)**

1.19.0
**Affected component:**

https://esphome.io/devices/sonoff_4ch.html

**Description of problem:**
Sonoff 4ch n°1, the fourth channel is assigned to the water valve (configured as a switch) and has no buttons connected, it is controlled only via Home Assistant.
I restarted the raspberry, the whole system restarted and HA and EspHome started up without any problems.
However, the water stops flowing, the valve is closed, but on Home Assistant the switch is ON. I had to turn the valve OFF and then ON again to get the water back.

Following this event I also checked the Sonoff 4ch No. 2, to which the gas valve is connected (the channel, set as a switch, is controlled only by Home Assistant and the Sonoff has no buttons connected). Also in this case the gas didn't come out, I had to put the entity in OFF and then in ON.

I don't understand why the raspberry restart has sent the esphome devices to OFF...

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
I don't know if it is related to this problem, but I noticed that every time I upload the firmware to the sonoff the same problem occurs, and I notice it because the gas valve, despite being in ON, does not allow the passage of gas, because it seems that after a short power failure (during the upload process I suppose) the valve goes into lockout, and therefore it is necessary to perform the manual reset.

**Comment by Fusseldieb** [comment]
Post your YAML and your log output. 

My valve, for example, works just fine inside HA.
