### ISSUE TITLE
Docs Table of Contents is not scrollable

### ISSUE THREAD

**Issue by Chupaka** [esphome/issues#2088]
**Affected component:**

Doc pages with many sections. For example: https://esphome.io/devices/sonoff.html

**Description of problem:**
Table of Contents in docs is not scrollable, so even having browser window maximized I can't reach out to the bottom items.

**Additional information and things you've tried:**
I can repeat it in Chrome and Safari browsers on my laptop.

On mobile device, ToC is rendered on the top of page, so it's not a problem there.

**Comment by Chupaka** [comment]
The activity (as the issue is still relevant)

**Comment by nepozs** [comment]
It is really important for all using low resolution displays - eg. for my laptop everything below Light Components is unavailable!
![Table of Contents_too_long_Screenshot 2021-11-29 at 18-42-49 ESPHome — ESPHome](https://user-images.githubusercontent.com/56661567/143917164-bb933a17-132b-4cdc-9b07-509bf1407e3a.png)

**Comment by slovdahl** [comment]
FWIW, also happening on Firefox on (on macOS).

**Comment by slovdahl** [comment]
This SO answer seems to have the solution: https://stackoverflow.com/a/57040610/1283519
