### ISSUE TITLE
midea_ac beeper function is not working

### ISSUE THREAD

**Issue by dszabolcs** [esphome/issues#2100]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Debian, Supervised Home Assistant

**ESP (ESP32/ESP8266, Board/Sonoff):**
esp8266

**ESPHome version (latest production, beta, dev branch)**
esphome 1.8.0

**Affected component:**
midea_ac

**Description of problem:**
The problem is regarding the beeper option under the configuration. The **beeper** was set true, and the expected result of this function that the A/C should give a sound feedback for any action, but it does not happen.

**Problem-relevant YAML-configuration entries:**
climate:
  - platform: midea_ac
    name: "midea climate"
    visual:
      min_temperature: 17 °C
      max_temperature: 30 °C
      temperature_step: 0.5 °C
    **beeper: true**
    swing_horizontal: true
    swing_both: true

**Logs (if applicable):**
-

**Additional information and things you've tried:**
-

**Comment by wouterbouvy** [comment]
I have the same on my AC unit, but I don't see this as an ESPHome issue. I think this depends on your AC unit if it supports the UART command for the beeper.
