### ISSUE TITLE
In a recent NodeMCU ESP8266 an ADC range is 0-3.3V

### ISSUE THREAD

**Issue by epiniguin** [esphome/issues#213]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCU ESP8266
**Affected component:**

https://esphome.io/components/sensor/adc.html

**Description of problem:**
In a recent NodeMCU ESP8266 an ADC range is 0-3.3V.
That's why an ADC sensor value is wrong - it should be multiplied by 3.3. 

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

**Comment by HFsi** [comment]
Could you provide more info? Brand, version, revision, etc

**Comment by brandond** [comment]
As far as I know, the esp8266 has always used 0.0 - 1.0 to represent 0v0 to 3v3. It's up to the user to scale that to whatever they're trying to measure.

**Comment by kimonm** [comment]
The ADC range is 0-1V at the chip. The range is 0-3.3V at the board pin. There is a voltage divider  comprised of 220k and 100k resistors between the board pin and chip pin.  See schematic on https://github.com/nodemcu/nodemcu-devkit

**Comment by HFsi** [comment]
This is very important, should be updated in the documentation, because Otto states in the NodeMCU board specs, that the measurement range is between 0-1 V

**Comment by epiniguin** [comment]
> 
> 
> The ADC range is 0-1V at the chip. The range is 0-3.3V at the board pin. There is a voltage divider comprised of 220k and 100k resistors between the board pin and chip pin. See schematic on https://github.com/nodemcu/nodemcu-devkit

Exactly!
And now ESPHome ADC sensor value is 3.3 times less.

**Comment by kimonm** [comment]
I submitted a PR for the documentation to clarify what voltage this component uses.

**Comment by HFsi** [comment]
Great info and great community!

**Comment by OttoWinter** [comment]
Documentation has been updated

**Comment by HFsi** [comment]
Thanks!
