### ISSUE TITLE
No way to download .bin file for previously flashed build using Firefox

### ISSUE THREAD

**Issue by tomlut** [esphome/issues#2136]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home Assistant OS (update your document template Hassio has not been a thing for 18 months).

**ESP (ESP32/ESP8266, Board/Sonoff):**

Any ESP board
**ESPHome version (latest production, beta, dev branch)**

1.19
**Affected component:**

Main Interface

**Description of problem:**
There is no way to compile and download a .bin file for a board that has previously been flashed. ESPHome goes straight to attempting to update OTA even though the device is not available. 

This appears to only be an issue on Firefox. Chrome does bring up the pop-up asking for flash method.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by tht** [comment]
I think there is a broader issue here… since the update to 1.19.0 it is also no longer possible to download the bin-file for a device never flashed before – or I can't find the link ;)

Older versions allowed to `compile` and download the binary afterwards. I used this to update existing Tasmota devices OTA but now there does not seem to be a way to download a binary.

btw… using Safari 14.1.1 on macOS but I don't think this matters.

**Comment by zvldz** [comment]
I was able to download successfully via firefox.

![esphome](https://user-images.githubusercontent.com/45265234/122388015-23e27180-cf78-11eb-878a-1886a4a3b43a.png)

**Comment by tomlut** [comment]
Was that the first time you ever attempted to flash that file?

**Comment by zvldz** [comment]
I copied the existing yaml file with the new name and renamed the device in it. And was able to compile and download twice.

**Comment by tomlut** [comment]
I just created a brand new file and attempted to install it. I see the pop-up for the briefest moment, then it disappears and an OTA install is attempted.

**Comment by zvldz** [comment]
I am using esphome v1.20.0-dev.
Maybe for this reason it works fine for me.

**Comment by tomlut** [comment]
I just blow away my entire browsing history, cookies, everything.

Now it works as expected.

Yet another example on not being able to flush the browser cache.
