### ISSUE TITLE
Update 1.19 crash connect to wi-fi with power_save_mode=none

### ISSUE THREAD

**Issue by Aliskin-Papa** [esphome/issues#2146]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Docker Supervised

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32S

**ESPHome version (latest production, beta, dev branch)**
1.19

**Affected component:**

**Description of problem:**
After update to 1.19 next section make esp32 in ble_tracker mode not connected to wi-fi:
wifi:
  power_save_mode: none

    

**Problem-relevant YAML-configuration entries:**
```yaml
wifi:
power_save_mode: none

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by Enzokot** [comment]
same here

**Comment by Malachi80** [comment]
Can confirm the issue (M5Stick-C and M5Atom-lite).

**Comment by baskapteijn** [comment]
This seems to be the same issue as I reported yesterday morning: https://github.com/esphome/issues/issues/2141

`power_save_mode` and `ble_tracker` seems to cause problems when used together.

**Comment by OttoWinter** [comment]
Merging issue into https://github.com/esphome/issues/issues/2141 as that has more discussions
