### ISSUE TITLE
changelog link not working in Home Assistant Supervisor (minor bug)

### ISSUE THREAD

**Issue by marcelkous** [esphome/issues#2150]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

Version | core-2021.6.3
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.9
Operating System Family | Linux
Operating System Version | 5.10.42
CPU Architecture | x86_64
Timezone | Europe/Amsterdam

**ESP (ESP32/ESP8266, Board/Sonoff):**

N/A

**ESPHome version (latest production, beta, dev branch)**

1.18.0

**Affected component:**

Add-on info page under Supervisor section

**Description of problem:**
The link to the changelog is not working. 
I always get a pop-up with header: Changelog
With the following message: "No changelog found for add-on 15ef4d2f_esphome!"

It would be great to have this fixed.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

![2021-06-17 20_07_05-Supervisor - Home Assistant - Brave](https://user-images.githubusercontent.com/61436181/122452015-12658d80-cfa9-11eb-8250-2e3b306942e9.png)

**Comment by jesserockz** [comment]
I have "fixed" this by adding a link to the changelog on the website
