### ISSUE TITLE
Thermostat doesn't start with a single temperature.

### ISSUE THREAD

**Issue by ssieb** [esphome/issues#2233]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

N/A

**ESP (ESP32/ESP8266, Board/Sonoff):**

N/A

**ESPHome version (latest production, beta, dev branch)**

1.19

**Affected component:**

Thermostat

**Description of problem:**
If you create a thermostat component with only one temperature, it will always be in the OFF action unless you switch the mode remotely.  This is because setup sets the mode to HEATCOOL (formerly AUTO) and that's not a valid condition in the compute action function, so the action nevers gets changed from OFF.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

A workaround is to set the mode to HEAT or COOL (depending on which temperature is configured) in on_boot.

**Comment by ptr727** [comment]
I ran into the the same issue, added a new thermostat, wondered why it was not working, as in turn the fan on when too hot.
I added the device to HA and noticed it was off, I clicked the cold button, and it started working as expected.

I tried adding state under the device config, but it is not a valid YML config.
I found a [Reddit post](https://www.reddit.com/r/homeassistant/comments/j622me/esphome_thermostat/g9l8imh/) where the Same problem was being discussed, advising to use `on_boot` to set the desired state.
I added the state change to `on_boot`, and it seems to work.

But, this is not deterministic, especially when HA gets involved, I think:
- The device default state should be a device config parameter, e.g. `mode: HEAT_COOL`
- It needs to be clearly documented how HA connected devices will restore state, e.g. if the YML default is Off, and the device was set to Cool in HA, and device powers up and reconnects to HA, I'd still expect HA to override the default.
- The state in HA seems inconsistent, when the device was just added, the text said Off, when I clicked cold the state went to Cool, and when it was satisfied it went to Idle. Click the Off button, state is Off, click the Cool button, state is still Off, and stays Off until cool is called for, the Cool, when satisfied is goes to Idle. It should be Off when Off, or Cool/Idle when On.
