### ISSUE TITLE
Manual IP not being used (DHCP IP remains active)

### ISSUE THREAD

**Issue by AleXSR700** [esphome/issues#2286]
### The problem

Hello everyone,
I am trying to assign my ESP32 manual IPs but it seems that the IP is not being used by the boards.

ESPHome tries to connect to the new IP but fails. If I remove the manual IP, ESPHome immediately finds and connects to the ESP32 via the old, DHCP assigned IP.

I rebooted the ESP32s. I rebooted my wifi APs and router. No success.

Is this a known bug or is there some additional information I can supply?

Thank you
Alex

### What is version of ESPHome has the issue?

1.20.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

ESP32-WROOM-32D DevKitC v4

### Component causing the issue

wifi

**Comment by oxan** [comment]
Did you reflash the ESP after changing the IP? You've to use the `use_address` option to workaround ESPHome trying to connect to the new IP: https://esphome.io/components/wifi.html#configuration-variables
