### ISSUE TITLE
LED status light of nodemcu esp8266

### ISSUE THREAD

**Issue by jack9603301** [esphome/issues#2313]
### The problem

It seems that the LED status light of nodemcu esp8266 should be D4 instead of D0, whether it is the unofficial `nodemcu v3` board I purchased from the merchant or the picture you provided.

![图片](https://user-images.githubusercontent.com/9047180/129042577-2c19b43a-15f6-4161-80ea-70762ae91cfa.png)

According to the settings in the picture, I can successfully drive the LED using D4 reverse mode. Although my board may not be the official board, I have reason to think that this is a document error.

![图片](https://user-images.githubusercontent.com/9047180/129042976-373bf5dd-5fe5-4776-bf5f-6bc073250593.png)

### Which version of ESPHome has the issue?

This is a document error, not a fault

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

This is a document error, not a fault

### What platform are you using?

ESP8266

**Comment by oxan** [comment]
NodeMCU boards used to have two leds, one on the ESP-12 module (connected to D4 / GPIO2) and one next to the UART chip (connected to D0 / GPIO16, active low). Fake boards save money by omitting that last LED.

I think the documentation is correct: it says that D0 is connected to the LED next to the UART chip.

**Comment by jack9603301** [comment]
I think the description of D4 LED should be added. In addition, I think the repo of nodemcu is a few years ago. I have reason to detail that the official does not release new development boards. Most development boards on the market are basically derived from the official open source design.
