### ISSUE TITLE
Not a bug, but misspeling

### ISSUE THREAD

**Issue by karolzlot** [esphome/issues#2326]
### The problem

![9o9vFub9Z2](https://user-images.githubusercontent.com/11590960/129739028-d6f2acae-5340-4901-85f0-3c121e67ae0d.png)

### Which version of ESPHome has the issue?

-

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP32

### Board

-

### Component causing the issue

-

### Example YAML snippet

```yaml
-
```

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

-

**Comment by oxan** [comment]
@jesserockz Seems the typo fix introduced another typo :rofl:

**Comment by jesserockz** [comment]
Haha, thanks. Will get this sorted
