### ISSUE TITLE
CCS811 sensor documentation

### ISSUE THREAD

**Issue by tudimoncom** [esphome/issues#2331]
### The problem

Such a popular CSS811 sensor from Aliexpress (as in the picture) is not detected when scanning the i2c bus.

![d3b998](https://user-images.githubusercontent.com/81709216/130045671-08c2bd5e-56d8-4c5d-b5d7-ef0ac015ade4.jpg)

For the i2c scanner to detect it, the nWAKE pin must be grounded.

It is necessary to add this to the documentation:

https://github.com/esphome/esphome-docs/blob/current/components/sensor/ccs811.rst

### Which version of ESPHome has the issue?

2021.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8.6

### What platform are you using?

ESP8266

### Board

wemos d1 mini

### Component causing the issue

CCS811

**Comment by oxan** [comment]
Feel free to submit a PR against the file you linked :)
