### ISSUE TITLE
pull request in C code

### ISSUE THREAD

**Issue by engrfaiz** [esphome/issues#2349]
### The problem

I am writing a custom C code and YAML for my home assistant project using ESPHome.  I have successfully pushed values to the sensor. but in my project, i need to pull those values in the c code for other ESP32. for which i am unable to find the code. 
Can i get some documentation which support C++ code in ESPHome and Home Assistan.
Also i need C code to send logs so that i may print pulled values on the logs.
Thank You

### Which version of ESPHome has the issue?

2021.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8.0

### What platform are you using?

ESP32

### Board

ESP32 DEV Board

### Component causing the issue

Custome C Code

**Comment by DAVe3283** [comment]
Have you looked at the excellent [ESPHome documentation](https://esphome.io/)? Namely, the [Custom Sensor Component](https://esphome.io/components/sensor/custom.html) might be of interest to you. It answers most of your questions, including logging.

You can also just look through the source code for ESPHome and see how all the sensors are implemented. I was able to write a custom C++ climate entry after looking through the linked documentation and reading through the source code.
