### ISSUE TITLE
Logs and other WebUI functionality broken without https

### ISSUE THREAD

**Issue by omegacore** [esphome/issues#2354]
### The problem

Webui seems broken when using http to connect.

Connected with http to ha, opened webui, clicked on Logs button to view logs of an active esp, and nothing happens.

Opened another browser window, reconnected to ha with https, and Logs button works.

Seems a warning or a note in the logs might help some people if this was an intentional change.

### Which version of ESPHome has the issue?

2021.8.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

Firefox 90.0.2

### Component causing the issue

logger

**Comment by OttoWinter** [comment]
Try pressing ctrl+shift+r while in the dashboard view to clear any caches

**Comment by omegacore** [comment]
Tried today and issue is gone...
