### ISSUE TITLE
SDM Meter energy sensor did not listed in home assistant Energy config panel.

### ISSUE THREAD

**Issue by hawkefly** [esphome/issues#2373]
### The problem

SDM Meter import and export active energy sensor did not listed in home assistant Energy config panel.

This is the picture of  consumed energy(kWh) 

<img width="428" alt="Screen Shot 2021-08-30 at 10 58 58 PM" src="https://user-images.githubusercontent.com/12472105/131360532-afc6018b-26f6-449d-a38d-33dc33ae4ec2.png">

But DSMR component works fine with home assistant energy config. 

I think , to be listed in consumed energy(kWh) , the sensor's unit should be kWh, and device type should be energy , and last_reset_type should not be null .  

this is the diff

https://github.com/esphome/esphome/blob/f923ba87c0c55e219e55993e13596b2a60724d37/esphome/components/sdm_meter/sensor.py#L108

https://github.com/esphome/esphome/blob/f923ba87c0c55e219e55993e13596b2a60724d37/esphome/components/dsmr/sensor.py#L42

### Which version of ESPHome has the issue?

ESPHome  dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8.8

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

sdm_meter

**Comment by hawkefly** [comment]
@jesserockz

**Comment by jesserockz** [comment]
All of the requirements for SDM to appear are met by SDM. Not sure why you would not see the entities

![Screenshot_20210901-195646.png](https://user-images.githubusercontent.com/3060199/131634532-5c1d4152-2cd4-45dc-8f55-7262ad9ec3af.png)
