### ISSUE TITLE
snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of ESPHome

### ISSUE THREAD

**Issue by paarak** [esphome/issues#2380]
### The problem

Fresh install Home Assistant OS 6.2, core-2021.8.8, supervisor-2021.08.1.

appears in supervisor log

## snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of ESPHome

[supervisor log.txt](https://github.com/esphome/issues/files/7096294/supervisor.log.txt)

**Comment by jesserockz** [comment]
This is fixed already but stable and beta will only update when they are next released

https://github.com/esphome/hassio/pull/40

**Comment by OttoWinter** [comment]
In stable now
