### ISSUE TITLE
How to update Development version of ESPHome add-on in Home Assistant 

### ISSUE THREAD

**Issue by WIsbrecht** [esphome/issues#2398]
### The problem

I've been using the ESPHome (dev) add-on in Home Assistant for some time now.
It used to be, that when I stopped and restarted the add-on in Home Assistant, the add-on automatically downloaded the newest version from GitHub. It reported this in the add-on log.
For some time now the add-on starts way quicker than before but doesn't update to the latest version from GitHub.
The only way I found to update the ESPHome (dev) add-on in Home Assistant is to uninstall and re-install the add-on.

Have there been any changes regarding this? If so, how do I update the add-on without reinstalling it?

### Which version of ESPHome has the issue?

v2021.9.0-dev 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.9.4

### What platform are you using?

ESP8266

### Component causing the issue

ESPHome (dev) add-on in Home Assistant

**Comment by jesserockz** [comment]
Yes, because of the removal of esphome_version. You now have to rebuild it then restart it.

**Comment by WIsbrecht** [comment]
Do you mean the "REBUILD" button on the right?
![image](https://user-images.githubusercontent.com/939173/132507258-bc939885-5de6-4d74-a976-d7796f1fd73c.png)
