### ISSUE TITLE
switching gpio after mqtt message has been sent.

### ISSUE THREAD

**Issue by hirani89** [esphome/issues#2412]
### The problem

i want to change the state of a gpio pin from low to high when all sensor information has been sent over mqtt. this gpio will notify a watchdog timer and that will shutdown power to all components.

### Which version of ESPHome has the issue?

1.20.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8.8

### What platform are you using?

ESP32

### Board

ESP32­WROOM­32UE

### Component causing the issue

mqtt

**Comment by oxan** [comment]
Hi! This isn't the correct place to ask questions about how to use ESPHome. Please use the [HA community forums](https://community.home-assistant.io/c/esphome/36), [GitHub discussions](https://github.com/esphome/esphome/discussions) or [ESPHome discord](https://discord.gg/KhAMKrd) instead.
