### ISSUE TITLE
esp32_ble_tracker failing with ESP32 + Arduino framework

### ISSUE THREAD

**Issue by rbaron** [esphome/issues#2473]
### The problem

The component `esp32_ble_tracker` seems to be failing for me when I use the default Arduino platform on my ESP32.
I have tried the following two configurations on two different Lolin32 boards:

# Configuration 1 - Failing (branch `dev` @ aec02afc)
```yaml
esphome:
  name: ble_test
  platform: ESP32
  board: lolin32

esp32_ble_tracker:

sensor:
  - platform: ble_rssi
    mac_address: "f0:ca:f0:ca:00:08"
    name: "b-parasite RSSI"

logger:
```

We see the error: `esp_bt_controller_init failed: ESP_ERR_INVALID_STATE` in the logs:
```
INFO Successfully uploaded program.
INFO Starting log output from /dev/cu.usbserial-143310 with baud rate 115200
[22:32:57][I][logger:216]: Log initialized
[22:32:57][I][app:029]: Running through setup()...
[22:32:57][E][esp32_ble_tracker:141]: esp_bt_controller_init failed: ESP_ERR_INVALID_STATE
[22:32:57][E][component:103]: Component esp32_ble_tracker was marked as failed.
[22:32:57][I][app:060]: setup() finished successfully!
[22:32:57][I][app:099]: ESPHome version 2021.10.0-dev compiled on Sep 24 2021, 22:32:06
```

# Configuration 2 - Working (branch `dev` @ aec02afc)
If I use the new `esp-idf` platform introduced in [PR 2303](https://github.com/esphome/esphome/pull/2303), things seem to work:
```yaml
esphome:
  name: ble_test

esp32:
  board: lolin32
  framework:
    type: esp-idf

esp32_ble_tracker:

sensor:
  - platform: ble_rssi
    mac_address: "f0:ca:f0:ca:00:08"
    name: "b-parasite RSSI"

logger:
```

Logs:
```
INFO Successfully uploaded program.
INFO Starting log output from /dev/cu.usbserial-143310 with baud rate 115200
[22:40:33][D][esp32_ble_tracker:205]: Starting scan...
[22:40:33][I][app:060]: setup() finished successfully!
[22:40:33][I][app:099]: ESPHome version 2021.10.0-dev compiled on Sep 24 2021, 22:37:13
...
[22:40:33][D][sensor:121]: 'b-parasite RSSI': Sending state -68.00000 dB with 0 decimals of accuracy
```

Please let me know if I can provide more info. Thanks!

### Which version of ESPHome has the issue?

dev (aec02afc)

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

Lolin32

### Component causing the issue

es32_ble_tracker

**Comment by nikito7** [comment]
Same here

**Comment by jhansche** [comment]
Seeing the same behavior while trying to test https://github.com/esphome/esphome/pull/2452 after rebasing on latest dev:
1. `dev` branch with default platform (arduino): `esp_bt_controller_init failed: ESP_ERR_INVALID_STATE`
2. `dev` branch with idf platform and my (new) component disabled: esp32_ble_tracker appears to work again
3. `dev` branch with idf platform any my (new) component enabled: dozens of linking errors, unable to test
4. `2021.9.2` with default arduino platform and my component enabled: all works
