### ISSUE TITLE
Navigation on docs site doesn't scroll

### ISSUE THREAD

**Issue by deosrc** [esphome/issues#2477]
### The problem

The navigation on the docs site (https://esphome.io/) doesn't scroll. This means that, on smaller browser windows, some navigation items are inaccessible.

Browser: Firefox 92.0
OS: Pop!_OS

Steps to reproduce:
1. Go to https://esphome.io/
2. Resize the browser so that the site is in desktop mode (width greater than about 870 pixels) and the bottom of the navigation bar is not visible.
3. Try to click the "Source Code" link at the bottom of the navigation

Screenshot of the page when scrolled down below. Scrolling on the nav bar scrolls the page instead.

![image](https://user-images.githubusercontent.com/50599779/134778859-d4f8693d-ae43-440f-90fe-94cdc42113af.png)

### Which version of ESPHome has the issue?

N/A

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

N/A

### Component causing the issue

N/A

### Example YAML snippet

```yaml
N/A
```

### Anything in the logs that might be useful for us?

```txt
N/A
```

**Comment by bookcasey** [comment]
This is more of an issue with the alabaster sphinx theme. Check out this (four-year-old, still open) PR that fixes it: https://github.com/bitprophet/alabaster/pull/114

Long story short we could patch it for the ESPHome docs by adding something like: 
```
div.sphinxsidebar {
    max-height: 100%;
    overflow-y: auto;
}
```
to `esphome-docs/_static/custom.css`
