### ISSUE TITLE
Help with custom SPI component

### ISSUE THREAD

**Issue by bigstation17** [esphome/issues#248]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

PIP

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**Affected component:**

Custom SPI Component / Digital potentiometer like MCP41100

**Description of problem:**
Hello,
I want to integrate a digital pot (Ex. MCP4xxxx) to esphome but i dont know how :(
I want to use with light component if it possible.
Can someone to help me with that?
Thank you in advance.

**Problem-relevant YAML-configuration entries:**
```yaml

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
Example code:

#include <SPI.h>
byte address = 0x11;
int CS= 10;
int i=0;

void setup()
{
  pinMode (CS, OUTPUT);
  SPI.begin();
  // adjust high and low resistance of potentiometer
  // adjust Highest Resistance .
   digitalPotWrite(0x00);
   delay(1000);
 
   //adjust  wiper in the  Mid point
   digitalPotWrite(0x80);
   delay(1000);

   // adjust Lowest Resistance
   digitalPotWrite(0xFF);
   delay(1000);
}

void loop()
{
    for (i = 0; i <= 255; i++)
    {
      digitalPotWrite(i);
      delay(10);
    }
    delay(500);
    for (i = 255; i >= 0; i--)
    {
      digitalPotWrite(i);
      delay(10);
    }
}

int digitalPotWrite(int value)
{
  digitalWrite(CS, LOW);
  SPI.transfer(address);
  SPI.transfer(value);
  digitalWrite(CS, HIGH);
}

**Comment by OttoWinter** [comment]
This is an issue/bug tracker, not a place for general questions (see forums for that).

Anyway, see the custom components guide first please. You'll want to use a custom output component.
