### ISSUE TITLE
Inkbird IBS-TH1 Temperature is 655.35 Degrees to High When the Temperature is Below Freezing

### ISSUE THREAD

**Issue by nuttytree** [esphome/issues#2531]
### The problem

The temperature field for these devices is a 2 byte unsigned integer so when the temperature drops below 0 (in Celsius) the value rolls back around to 65,535 (divided by 100.0f = 655.35) and then drops from there.

### Which version of ESPHome has the issue?

2021.9.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.10.1

### What platform are you using?

ESP32

### Board

wemos_d1_mini32

### Component causing the issue

inkbird_ibsth1_mini

**Comment by fkirill** [comment]
Hey guys, see the PR here https://github.com/esphome/esphome/pull/2470
