### ISSUE TITLE
RGBWW Bulb is using RGB and CW/WW channels to reproduce color temperature instead of using only CW/WW.

### ISSUE THREAD

**Issue by Seba-VT** [esphome/issues#2539]
### The problem

I flashed a bulb ([https://kaufha.com/blf10/](url)) with ESPHome using the RGBWW platform. The bulb works and is showing up on HA.

The issue is when I try to set the bulb to any temperature from an automation or node-red, it uses a mix of the RGB and the CW/WW LEDs to achieve the requested temperature instead of using only the CW/WW channels (see the video below).

https://user-images.githubusercontent.com/67033534/136714248-6a42b5d4-9722-4e3d-8075-194ad2557f6e.mp4

This causes an inaccurate color temperature produced by the bulb and an overheat of the hardware.

Now if I set the `color_interlock` to `true`, the color picker now shows the CT and COLOR mode (as shown in the next image). When the bulb is on CT or COLOR and transitions from one to another mode, the bulb gradually turns off and then turns on in the corresponding mode instead of smoothly transitioning between them.

![image](https://user-images.githubusercontent.com/67033534/136714391-3a3bdb8f-c1c6-4787-b199-7143786d4f87.png)

The desired transition behavior is a smooth transition from, let's say, Orange light to Warm White. (I'm trying to make a wake up routine).

### Which version of ESPHome has the issue?

2021.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.2

### What platform are you using?

ESP8266

### Component causing the issue

light:RGBWW

**Comment by bkaufx** [comment]
ESPHome is pretty hard coded to have to go through the "off" state when transitioning between different color modes.  I'm working on an update for that bulb with a forked ESPHome code base that will transition smoothly between RGB and CT without going through off.  Once it's done I'll try to contribute it back to ESPHome if the devs are amenable.  It may just be that no one has decided to tackle it yet since it's kind of a big change to the way lights work in ESPHome.

**Comment by Seba-VT** [comment]
@bkaufx 

> ESPHome is pretty hard coded to have to go through the "off" state when transitioning between different color modes. I'm working on an update for that bulb with a forked ESPHome code base that will transition smoothly between RGB and CT without going through off. Once it's done I'll try to contribute it back to ESPHome if the devs are amenable. It may just be that no one has decided to tackle it yet since it's kind of a big change to the way lights work in ESPHome.

That would be awesome! beside your website, where can I follow the progress of your work?

and Thank you for the contributions you have made to the community.

**Comment by bkaufx** [comment]
Probably youtube since that is the only place I have really posted updates so far.  I'm going to try to do a blog on my website with RSS so that would be easier, and probably Twitter but I just haven't gotten around to it yet.

**Comment by bdr99** [comment]
> I don't really like having four brightness sliders like in the video above so that is why I am partial to using separate RGB and CT color modes.

I agree. I use `color_interlock` not because my lights don't support RGB and white simultaneously, but rather because I prefer the separate RGB and color temperature controls over the color brightness, warm white brightness, and cold white brightness sliders.

**Comment by Seba-VT** [comment]
I also have WiZ bulbs and they control the RGB and CT just right, and they even transition smoothly between them. The only backdraw of those bulbs is the fact that you can't set a transition time.
