### ISSUE TITLE
Unable to set SM2135 current

### ISSUE THREAD

**Issue by stevenjev** [esphome/issues#2546]
### The problem

Currently using some RGBW bulbs with the SM2135 chip. Using the RGB LEDs produces an expected brightness, however using the W LED I've noticed that the brightness is too dim (when compared with the stock bulbs). 

Looking through the `sm2135.cpp` [file](https://github.com/esphome/esphome/blob/501f88ca8645ef0e7ca3e537e2e69688636e6e90/esphome/components/sm2135/sm2135.cpp) I can see the ability to modify the output current, but no way to configure that in my .yaml file. 

Testing the bulb with Tasmota (which I believe uses a very similar source code for the sm2135 control), I can change increase the default current output to a level which matches the stock brightness so I am confident that this is not a hardware issue. 

### Which version of ESPHome has the issue?

2021.9.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Component causing the issue

sm2135

### Example YAML snippet

    output:
      - platform: sm2135
        id: output_red
        channel: 2
      - platform: sm2135
        id: output_green
        channel: 0
      - platform: sm2135
        id: output_blue
        channel: 1
      - platform: sm2135
        id: output_cold_white
        channel: 3
        max_power: 1
      - platform: sm2135
        id: output_warm_white
        channel: 4
        max_power: 1

    light:
      - platform: rgbww
        name: ${friendly_name}
        id: office_lamp
        red: output_red
        green: output_green
        blue: output_blue
        cold_white: output_cold_white
        warm_white: output_warm_white
        cold_white_color_temperature: 5000 K
        warm_white_color_temperature: 2000 K
        color_interlock: true
        constant_brightness: false

**Comment by BoukeHaarsma23** [comment]
You could always use [external_components](https://esphome.io/components/external_components.html) to edit the file to increase the current. I'm a bit torn whether or not we should expose this through yaml.

**Comment by oxan** [comment]
> You could always use [external_components](https://esphome.io/components/external_components.html) or use a custom component locally and edit the file to increase the current. I'm a bit torn whether or not we should expose this through yaml.

I think it's fine to expose in YAML, there's plenty of other "dangerous" settings also exposed. However, we should at least change the default to use the same current for white as RGB, the current behaviour doesn't make much sense imo (and you can always get it back by using `max_power`).

**Comment by BoukeHaarsma23** [comment]
I disagree with increasing the white current. Since typically there are more white led's in these bulbs, increasing the current there could easily overwhelm the power supply. The current setting was chosen since it most resembled the factory default firmware on my lights. 

Either we make it all configurable or not at all would be my 2 cents.

So I would lean towards making it all configurable then. Since that seems like the preferred option of most. I hope to find some time in the near future for this.

**Comment by stevenjev** [comment]
The configuration option is not yet available and this issue should not be closed. I'll leave it to the code owner to provide any further updates on this.

**Comment by BoukeHaarsma23** [comment]
Please see https://github.com/esphome/esphome/pull/3311
