### ISSUE TITLE
New mdns component is not documented

### ISSUE THREAD

**Issue by sermayoral** [esphome/issues#2571]
### The problem

In this new version, the `enable_mdns` option under the wifi section has been removed, but it appears in the documentation yet: https://esphome.io/components/wifi.html#configuration-variables

Also I can't find anything about the new `mdns` component in the documentation. Maybe you forgot to merge the documentation, when you merged the functionality

### Which version of ESPHome has the issue?

2021.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.5

### What platform are you using?

ESP32

### Board

esp-wrover-kit

**Comment by OttoWinter** [comment]
https://github.com/esphome/esphome-docs/commit/b94082da298fdec800aeaa0e7f4e400d1ebcecad
