### ISSUE TITLE
Error: Could not find the package with 'platformio/toolchain-xtensa32 @ ~2.80400.0' requirements for your system 'linux_aarch64'

### ISSUE THREAD

**Issue by cracrama** [esphome/issues#2607]
### The problem

Hiya
After update to 2021.10.0 (and later) I'm getting below  error. I understand that error is related to certain libraries not available for given CPU architecture (RaspPi)? 

### Which version of ESPHome has the issue?

2021.10.0 (and later)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Component causing the issue

toolchain-xtensa32

### Example YAML snippet

```yaml
INFO Reading configuration /config/esphome/bedside-lamp.yaml...
INFO Updating https://github.com/mmakaay/esphome-xiaomi_bslamp2@dev
INFO Generating C++ source...
INFO Compiling app...
Processing bedside-lamp (board: esp32doit-devkit-v1; framework: espidf; platform: espressif32 @ 3.3.2)
Tool Manager: Installing platformio/toolchain-xtensa32 @ ~2.80400.0
Error: Could not find the package with 'platformio/toolchain-xtensa32 @ ~2.80400.0' requirements for your system 'linux_aarch64'
```

### Anything in the logs that might be useful for us?

```txt
Error: Could not find the package with 'platformio/toolchain-xtensa32 @ ~2.80400.0' requirements for your system 'linux_aarch64'
```

**Comment by Bascht74** [comment]
Hi @OttoWinter Is there a reference to the external issue (e.g. a Github issue where the problem is addressed) or to a know workaround? Thx for a hint as I am facing the same problem.

**Comment by Bascht74** [comment]
Hi @mmakaay  Is there a reference to the external issue (e.g. a Github issue where the problem is addressed) or does someone need to open a issue at the platformio repositories? 
Thx for a hint as I am facing the same problem and I haven't find any references...

**Comment by jwillikers** [comment]
It looks like perhaps they are still working on support for `aarch64` in esp-idf. See issue espressif/esp-idf#6432.

I've found the most straightforward workaround is to use my `x86_64` box to run second instance of ESPHome specifically for building and flashing ESP32-S2 devices. I have to copy the config back to my other ESPHome home instance running on my ROCKPro64 and that instance doesn't always detect my ESP32-S2 device, but it connects to Home Assistant no problem. You'll always want to note that you'll be limited on the features available.

**Comment by cracrama** [comment]
This was my solution: i have just switched installation to x86 and now everything compiles great. 
That is true - certain libraries are missing for arm support and all what is what users can do is to wait. 
Many thanks for expanation and support - I will close this topic.

**Comment by Bascht74** [comment]
@jwillikers thx for the link. I subscribed…
