### ISSUE TITLE
dashboard not showing used config.yaml per esp-node

### ISSUE THREAD

**Issue by pstimpel** [esphome/issues#2609]
### The problem

On each of the cards shown, I would expect the name of the yaml file to appear. However, only the first card is showing it.
![m3L5EB9bt2](https://user-images.githubusercontent.com/22441395/138552921-3ced4dd3-15b8-4825-9cb9-39aba8b15b1b.png)

### Which version of ESPHome has the issue?

2021.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP32

### Board

different esp32 devboards

### Component causing the issue

dont know

**Comment by markusg1234** [comment]
Hi, I believe the file name now only displays if it differs to the node name. This was changed in the dashboard recently.

The reason that Kuechensensor is displaying is that it has a capital K.

Regards,

Markus

**Comment by pstimpel** [comment]
ah, thanks @markusg1234 

Was walking though some history, but must have missed that one. I guess the some goes for that "Online" marker, which does not appear anymore. 

Cheerio

**Comment by pstimpel** [comment]
ok, mentioned in 20211015.0

**Comment by pstimpel** [comment]
Please see this, @markusg1234 

https://github.com/esphome/dashboard/pull/100

Seems to be wanted behavior, same release as the one that was hiding the yaml filename when equal to sensorname. 

BR, 
Peter
