### ISSUE TITLE
icon is an invalid option for light.monochromatic

### ISSUE THREAD

**Issue by ZsBT** [esphome/issues#2658]
### The problem

However the component documentation (https://esphome.io/components/light/) mentions, icon is is not accepted for a light component:

```
Failed config

light.monochromatic: [source termoswitch.yaml:41]
  platform: monochromatic
  
  [icon] is an invalid option for [light.monochromatic]. Please check the indentation.
  icon: mdi:car-parking-lights [source termoswitch.yaml:42]
```

### Which version of ESPHome has the issue?

2021.10.0-dev (Oct 29 2021, 10:57:18)

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.11.0b0

### What platform are you using?

ESP8266

### Board

wifi b6

### Component causing the issue

light

### Example YAML snippet

```yaml
light:
  - platform: monochromatic
    icon: mdi:car-parking-lights
    id: ${N}_gombfeny
    name: ${N} gombfény
    output: ${N}_pwm
    effects:
      - pulse:
```

### Anything in the logs that might be useful for us?

```txt
+ docker run --rm --name esphome-termoswitch.yaml -v /home/zsombor/prog/homeassistant/esphome-firmware:/config -it esphome/esphome:dev run --device 192.168.1.81 termoswitch.yaml
INFO Reading configuration termoswitch.yaml...
INFO Detected timezone 'CET' with UTC offset 1 and daylight saving time from 27 March 02:00:00 to 30 October 03:00:00
Failed config

light.monochromatic: [source termoswitch.yaml:41]
  platform: monochromatic
  
  [icon] is an invalid option for [light.monochromatic]. Please check the indentation.
  icon: mdi:car-parking-lights [source termoswitch.yaml:42]
  id: termosw_szoba2_gombfeny
  name: termosw_szoba2 gombfény
  output: termosw_szoba2_pwm
  effects: 
    - pulse: {}
+ exit 1
```

**Comment by paulmonigatti** [comment]
Hi, I'm unable to reproduce the issue with either the latest dev build (2021.11.0-dev), nor the release build (2021.10.3). Both of these versions work as expected.

Support for light icons was added in the 2021.10 release, so it's possible that the build you're running is from prior to this addition. Are you able to update and try again?

**Comment by ZsBT** [comment]
Thanks for the update.
Indeed, I was using an early 2021.10 dev version using docker environment where it doesn't seem to be supported yet.
I apologize for taking your time.
