### ISSUE TITLE
Hostname length limit of 31 characters should be warning, not error

### ISSUE THREAD

**Issue by poldim** [esphome/issues#2661]
### The problem

This was recently made into an `error` preventing you from compiling your code.  I have a dozen devices that were already created, uploaded, and running fine with longer names.  This should be a `warning` rather than an `error` so those devices can continue to run/be updated. 

IMO, this is the same thing as the underscore in the hostname.  All my devices have underscores and run with no issues.  _It would nice if there's a way to suppress these warnings as they don't apply._

![image](https://user-images.githubusercontent.com/16869713/139467509-b586c260-a8e0-4973-a752-ede543730dd9.png)

![image](https://user-images.githubusercontent.com/16869713/139470163-4c2a7441-b7eb-40a5-938e-959141566077.png)

### Which version of ESPHome has the issue?

2021.11.0-dev

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP8266

### Board

Various

### Example YAML snippet

```yaml
esphome:
  name: ${device_name}
```

**Comment by OttoWinter** [comment]
Ah I was under the impression that long hostnames made the device fail completely (as in wifi wouldn't work at all). But perhaps it's just DHCP that's broken then?

I mean it's a bit different than the underscore thing IMO because for a long time that was the only way to represent multiword ESP names, and so a lot of people used it that way. Here I think a lot less users are impacted so it should be more ok.

But yeah feel free to change it to a warning like the underscore one.

**Comment by oxan** [comment]
> Ah I was under the impression that long hostnames made the device fail completely (as in wifi wouldn't work at all). But perhaps it's just DHCP that's broken then?

See esphome/esphome#2647, current ESP-IDF actually outright rejects long hostnames.

**Comment by frittes** [comment]
I have also four such devices with device_name > 31 characters. Is it possible to reflash them with "new" names without dismounting, opening and serial flash?

**Comment by oxan** [comment]
> I have also four such devices with device_name > 31 characters. Is it possible to reflash them with "new" names without dismounting, opening and serial flash?

Yes, see [this](https://esphome.io/components/esphome.html#changing-esphome-node-name).

**Comment by poldim** [comment]
@frittes for me it was easier to compile the new flash and upload via webserver

**Comment by poldim** [comment]
closing due to comments in https://github.com/esphome/esphome/pull/2647
