### ISSUE TITLE
ESP32 BLE Arduino used not matching the library from arduino esp32 core

### ISSUE THREAD

**Issue by nanosonde** [esphome/issues#2666]
### The problem

When trying to compile a project which makes use of the Arduino BLE library, a wrong version is used when platformio installs the library. 
It seems that an old version from [here](https://platformio.org/lib/show/1841/ESP32%20BLE%20Arduino) is used.

This issue popped up recently, after [this PR](https://github.com/esphome/esphome/pull/2435
) disabled the library scanner.
Although it somehow worked with the old version. This behaviour is not correct.

The Arduino core already provides and maintains the [ESP32 BLE Arduino](https://github.com/espressif/arduino-esp32/tree/master/libraries/BLE) lib. So this should be used.

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.7

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

ESP32 BLE Arduino

### Example YAML snippet

```yaml
esphome:
  name: blekeyboard-eg
  platform: ESP32
  board: esp32dev
  includes:
    - esp32_ble_keyboard.h
  libraries:
    - "ESP32 BLE Arduino"
    - "t-vk/ESP32 BLE Keyboard"
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/blekeyboard-eg.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing blekeyboard-eg (board: esp32dev; framework: arduino; platform: espressif32 @ 3.3.2)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
Dependency Graph
|-- <AsyncTCP-esphome> 1.2.2
|-- <ESP32 BLE Arduino> 1.0.1
|-- <ESP32 BLE Keyboard> 0.3.1
|-- <WiFi> 1.0
|-- <FS> 1.0
|-- <Update> 1.0
|-- <ESPAsyncWebServer-esphome> 2.0.0
|   |-- <AsyncTCP-esphome> 1.2.2
|-- <DNSServer> 1.1.0
|-- <AsyncMqttClient-esphome> 0.8.6
|   |-- <AsyncTCP-esphome> 1.2.2
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESPmDNS> 1.0
```

### Additional information

Seems to be related to https://github.com/esphome/esphome/pull/2435

**Comment by OttoWinter** [comment]
> When trying to compile a project which makes use of the Arduino BLE library, a wrong version is used when platformio installs the library.

How do you see that a wrong version is used? If I just add `ESP32 BLE Arduino` to `libraries` it uses the core one.

Note that ESPHome has the arduino framework pinned to version 1.0.6 because platformio doesn't support v2.0.0 yet through the latest platform release. And there the lib version is set to 1.0.1: https://github.com/espressif/arduino-esp32/blob/1.0.6/libraries/BLE/library.properties
