### ISSUE TITLE
Fix incorrect GPIO for M5Stack Camera Pixel Data Bit 0.

### ISSUE THREAD

**Issue by markusg1234** [esphome/issues#2703]
### The problem

Fix for incorrect GPIO for M5Stack Camera Pixel Data Bit 0.

### Which version of ESPHome has the issue?

V2021.12.0-dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.3

### What platform are you using?

ESP32

### Component causing the issue

esphome-docs

### Additional information

https://github.com/markusg1234/esphome-docs/commit/a9ff86936317a15e46408106a4fb25a88ff737be

**Comment by oxan** [comment]
Please open a PR in the [esphome-docs repository](https://github.com/esphome/esphome-docs) with your proposed change.

**Comment by markusg1234** [comment]
Thankyou, will try again. My first pr.

**Comment by markusg1234** [comment]
Further investigation, this camera in the docs is the non PSRAM. I will put a PR in for the PSRAM camera.
