### ISSUE TITLE
Fix typo in BH1750 text in ESPHome 2021.11.0 blog post

### ISSUE THREAD

**Issue by cbhiii** [esphome/issues#2720]
### The problem

There is a typo in the blog post the description for the BH1750 sensor.

The text references **BH17850**. Do not look up BH17850 in Google. It will lead you to inappropriate websites I've found. That's why I feel this should be corrected. Thank you.

### Which version of ESPHome has the issue?

2021.11.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP8266

### Board

n/a

**Comment by oxan** [comment]
Thanks.
