### ISSUE TITLE
Entity category: SYSTEM is not yet supported

### ISSUE THREAD

**Issue by stefanroelofs** [esphome/issues#2729]
### The problem

All documentation regarding entity_category refers to this page:
https://developers.home-assistant.io/docs/core/entity/#generic-properties
On this page 'system' is listed as an option (as well as diagnostic and config).

Validation of the yaml gives the following result:
```
Unknown value 'system', valid options are '', 'config', 'diagnostic'.
  entity_category: system [source /config/esphome/shared/device_powerplug.yaml:143]
```
Can we add the value 'system'  to the EntityCategory enumeration?

Thanks.

### Which version of ESPHome has the issue?

2021.11.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.4

### What platform are you using?

ESP8266

**Comment by oxan** [comment]
Yeah, this is the issue with linking to HA docs, it isn't correct if HA gets updated before we do...

**Comment by frenck** [comment]
`system` should not be used, it is for internal use inside Home Assistant. They are not meant for interaction with the user (and not provided by a user either).

**Comment by makuser** [comment]
> `system` should not be used, it is for internal use inside Home Assistant. They are not meant for interaction with the user (and not provided by a user either).

So which `entity_category` should be used for a relay switch, which only purpose is to be used in the `generic_thermostat` HASS component and which must not be exposed to the user in the auto-generated dashboard? IMHO it is `system` and not `diagnostic` or `config`.
