### ISSUE TITLE
Excessive zeroconf logging

### ISSUE THREAD

**Issue by xtimmy86x** [esphome/issues#2760]
### The problem

After the last update, i see in the LOG of the addon and in the LOG of any ESP configured, this line repeated endlessly
{'DNS compression type 67 is unknown at 12': (<class 'zeroconf._exceptions.IncomingDecodeError'>,
                                              IncomingDecodeError('DNS compression type 67 is unknown at 12'),
                                              <traceback object at 0xb5ed8508>)}

### Which version of ESPHome has the issue?

2021.11.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.5

### What platform are you using?

ESP8266

### Board

nodemcu

### Anything in the logs that might be useful for us?

```txt
this error repeated endlessly
{'DNS compression type 67 is unknown at 12': (<class 'zeroconf._exceptions.IncomingDecodeError'>,
                                              IncomingDecodeError('DNS compression type 67 is unknown at 12'),
                                              <traceback object at 0xb5ed8508>)}
```

**Comment by oxan** [comment]
I think this is caused by a zeroconf update in 2021.11? @jesserockz any idea?

**Comment by ovanpeve** [comment]
Same kind of endless log with 8266/NodeMCU on 2021.11.5:
{'Corrupt packet received while decoding name': (<class 'zeroconf._exceptions.IncomingDecodeError'>,
                                                 IncomingDecodeError('Corrupt packet received while decoding name'),
                                                 <traceback object at 0x7fa87dba00>)}

**Comment by rlust** [comment]
Any update here?
I just updated to 2021.12.1 and issue still happens.

**Comment by sorted01** [comment]
For me it started once I've activated deep sleep in the yaml. Any ideas?

**Comment by Ziggy815** [comment]
Same error still occurs on 2022.1.3 !

**Comment by LuckyTriple7** [comment]
just updated to 2022.03.0
It's the first time the error occurs to me ...

**Comment by rlust** [comment]
Just came back with the current release of ESPHome!

**Comment by 53845714nF** [comment]
I have the problem as well.

**Comment by bdraco** [comment]
The incoming packet parser in zeroconf was re-written since this issue was created.  If its still happening, please open a new issue with logging for `zeroconf` set to debug so we can get a copy of the packet that causes the issue.
