### ISSUE TITLE
Shutdown "switch" is not supported by the new button component

### ISSUE THREAD

**Issue by lanrat** [esphome/issues#2805]
### The problem

With the release of ESPHome `2021.12.0` the new [Button Component](https://esphome.io/components/button/index.html) was added, which can now be used for things like the [Restart Button](https://esphome.io/components/button/restart.html), however it does not yet work with the [Shutdown Switch](https://esphome.io/components/switch/shutdown.html).

Can a Shutdown Button component be added?

Since shutting down, like restarting, does not track an on/off state, it would make sense to make a Shutdown Button component as well.

### Which version of ESPHome has the issue?

2021.12.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2021.12.0

### What platform are you using?

ESP32

### Board

NA

### Component causing the issue

Shutdown Switch

**Comment by lanrat** [comment]
It would likely also be worthwhile to make the [Safe Mode Switch](https://esphome.io/components/switch/safe_mode.html) a button as well.

**Comment by oxan** [comment]
Yes, I think it makes sense to convert these switches to buttons. Pull Requests welcome ;)

**Comment by jesserockz** [comment]
Yes I plan to do them, but this should be a feature request, not an issue.

**Comment by jsuanet** [comment]
@oxan Hi, I'm working on a PR for this, is this no longer needed?

**Comment by oxan** [comment]
@jsuanet No, still welcome, I closed it because it's not an issue but a feature request.
