### ISSUE TITLE
DSMR no readings / uptime & wifi signal work

### ISSUE THREAD

**Issue by jeroomdm** [esphome/issues#2814]
### The problem

After updating to 2021.12 i get no gas & electricity readings whatsoever. I do get the uptime, wifi sensor and others.

`[D][sensor:113]: 'SlimmeLezer Wi-Fi Signal': Sending state -26.00000 dBm with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Uptime': Sending state 358.59698 s with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Wi-Fi Signal': Sending state -26.00000 dBm with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Uptime': Sending state 418.60400 s with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Wi-Fi Signal': Sending state -26.00000 dBm with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Uptime': Sending state 478.59698 s with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Wi-Fi Signal': Sending state -27.00000 dBm with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Uptime': Sending state 538.59698 s with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Wi-Fi Signal': Sending state -27.00000 dBm with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Uptime': Sending state 598.59802 s with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Wi-Fi Signal': Sending state -28.00000 dBm with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Uptime': Sending state 658.59698 s with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Wi-Fi Signal': Sending state -28.00000 dBm with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Uptime': Sending state 718.60498 s with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Wi-Fi Signal': Sending state -26.00000 dBm with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Uptime': Sending state 778.60303 s with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Wi-Fi Signal': Sending state -27.00000 dBm with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Uptime': Sending state 838.60101 s with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Wi-Fi Signal': Sending state -26.00000 dBm with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Uptime': Sending state 898.60400 s with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Wi-Fi Signal': Sending state -27.00000 dBm with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Uptime': Sending state 958.59802 s with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Wi-Fi Signal': Sending state -28.00000 dBm with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Uptime': Sending state 1018.60303 s with 0 decimals of accuracy
[D][sensor:113]: 'SlimmeLezer Wi-Fi Signal': Sending state -28.00000 dBm with 0 decimals of accuracy
[D][api:098]: Accepted xxx.xxx.xxx.xxx
[D][api.connection:771]: ESPHome Logs 2021.12.0 (xxx.xxx.xxx.xxx): Connected successfully
[I][app:102]: ESPHome version 2021.12.0 compiled on Dec 13 2021, 07:49:36
[I][app:104]: Project zuidwijk.slimmelezer version 1.0
[C][wifi:488]: WiFi:
[C][wifi:350]:   Local MAC: xx:xx:xx:xx:xx
[C][wifi:351]:   SSID: [5m'XXXXXXXXXXXXXXX'[6m
[C][wifi:352]:   IP Address: xxx.xxx.xxx.xxx
[C][wifi:354]:   BSSID: [5mxx:xx:xx:xx:xx[6m
[C][wifi:355]:   Hostname: 'slimmelezer'
[C][wifi:357]:   Signal strength: -27 dB [0;32m▂▄▆█[0m
[C][wifi:361]:   Channel: xx
[C][wifi:362]:   Subnet: xxx.xxx.xxx.xxx
[C][wifi:363]:   Gateway: xxx.xxx.xxx.xxx
[C][wifi:364]:   DNS1: xxx.xxx.xxx.xxx
[C][wifi:365]:   DNS2: xxx.xxx.xxx.xxx
[C][logger:233]: Logger:
[C][logger:234]:   Level: DEBUG
[C][logger:235]:   Log Baud Rate: 0
[C][logger:236]:   Hardware UART: UART0
[C][uart.arduino_esp8266:100]: UART Bus:
[C][uart.arduino_esp8266:102]:   RX Pin: GPIO13
[C][uart.arduino_esp8266:104]:   RX Buffer Size: 1500
[C][uart.arduino_esp8266:106]:   Baud Rate: 115200 baud
[C][uart.arduino_esp8266:107]:   Data Bits: 8
[C][uart.arduino_esp8266:108]:   Parity: NONE
[C][uart.arduino_esp8266:109]:   Stop bits: 1
[C][uart.arduino_esp8266:111]:   Using hardware serial interface.
[C][uptime.sensor:031]: Uptime Sensor 'SlimmeLezer Uptime'
[C][uptime.sensor:031]:   State Class: 'total_increasing'
[C][uptime.sensor:031]:   Unit of Measurement: 's'
[C][uptime.sensor:031]:   Accuracy Decimals: 0
[C][uptime.sensor:031]:   Icon: 'mdi:timer-outline'
[C][dsmr:178]: DSMR:
[C][dsmr:181]:   energy_delivered_tariff1 'Energy Consumed Tariff 1'
[C][dsmr:181]:     State Class: 'measurement'
[C][captive_portal:144]: Captive Portal:
[C][api:134]: API Server:
[C][mdns:084]: mDNS:`

This is my config:
`---
substitutions:
  device_name: slimmelezer
  device_description: "DIY P1 module to read your smart meter"
     
esphome:
  name: ${device_name}
  comment: "${device_description}"
  platform: ESP8266
  esp8266_restore_from_flash: true
  board: d1_mini
  name_add_mac_suffix: false
  project:
    name: zuidwijk.slimmelezer
    version: "1.0"
  on_boot:
    then:
      - if:
          condition:
            lambda: return id(has_key);
          then:
            - lambda: |-
                std::string key(id(stored_decryption_key), 32);
                id(dsmr_instance).set_decryption_key(key);
          else:
            - logger.log:
                level: info
                format: "Not using decryption key. If you need to set a key use Home Assistant service 'ESPHome:  ${device_name}_set_dsmr_key'"
 
external_components:
  - source:
      type: git
      url: https://github.com/mmakaay/esphome
      ref: fix-dsmr-read-chunk-size
    components: [ "dsmr" ]
    refresh: 60s
     
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
 
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    ap_timeout: 15s
 
captive_portal:
 
# Enable logging
logger:
  baud_rate: 0
 
# Enable Home Assistant API
api:
  services:
    service: set_dsmr_key
    variables:
      private_key: string
    then:
      - logger.log:
          format: Setting private key %s. Set to empty string to disable
          args: [private_key.c_str()]
      - globals.set:
          id: has_key
          value: !lambda "return private_key.length() == 32;"
      - lambda: |-
          if (private_key.length() == 32)
            private_key.copy(id(stored_decryption_key), 32);
          id(dsmr_instance).set_decryption_key(private_key);
 
ota:
 
web_server:
  port: 80
 
uart:
  baud_rate: 115200
  rx_pin: D7
  rx_buffer_size: 1500
 
globals:
  - id: has_key
    type: bool
    restore_value: yes
    initial_value: "false"
  - id: stored_decryption_key
    type: char[32]
    restore_value: yes
 
dsmr:
  id: dsmr_instance
sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: "Energy Consumed Tariff 1"
      state_class: total_increasing
    energy_delivered_tariff2:
      name: "Energy Consumed Tariff 2"
      state_class: total_increasing
    energy_returned_tariff1:
      name: "Energy Produced Tariff 1"
      state_class: total_increasing
    energy_returned_tariff2:
      name: "Energy Produced Tariff 2"
      state_class: total_increasing
    power_delivered:
      name: "Power Consumed"
      accuracy_decimals: 3
    power_returned:
      name: "Power Produced"
      accuracy_decimals: 3
    electricity_failures:
      name: "Electricity Failures"
      icon: mdi:alert
    electricity_long_failures:
      name: "Long Electricity Failures"
      icon: mdi:alert
    voltage_l1:
      name: "Voltage Phase 1"
    current_l1:
      name: "Current Phase 1"
    power_delivered_l1:
      name: "Power Consumed Phase 1"
      accuracy_decimals: 3
    power_returned_l1:
      name: "Power Produced Phase 1"
      accuracy_decimals: 3
    gas_delivered_be:
      name: "Gas Consumed"
      state_class: total_increasing
  - platform: uptime
    name: "SlimmeLezer Uptime"
  - platform: wifi_signal
    name: "SlimmeLezer Wi-Fi Signal"
    update_interval: 60s
 
text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version_be:
      name: "DSMR Version"
  - platform: wifi_info
    ip_address:
      name: "SlimmeLezer IP Address"
    ssid:
      name: "SlimmeLezer Wi-Fi SSID"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true`

### Which version of ESPHome has the issue?

2021.12

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12

### What platform are you using?

ESP32

### Board

slimmelezer

### Component causing the issue

dsmr

**Comment by mmakaay** [comment]
First a tip: if you paste logs / configs in here, then place them
\`\`\`
within three backticks like this
for readability
\`\`\`

Second, I see that you are still using an external component for the dsmr code.
All changes have been incorporated into the main code tree of ESPHome. Changes from the external component that you use, but some other changes as well.
Please remove the external component from your code and make use of ESPHome 2021.12.0 for the latest and greatest DSMR code available.
