### ISSUE TITLE
Secrets.yaml is not available within packages in subfolders

### ISSUE THREAD

**Issue by wildblue** [esphome/issues#2819]
### The problem

As described here:
https://esphome.io/guides/configuration-types.html

I created a local package common/wifi.yaml and my code looks like:
wifi:
  ssid:          !secret wifi_ssid
  password:      !secret wifi_password
  
I get the following errot when compiling:
Error reading file /config/esphome/common/secrets.yaml: [Errno 2] No such file or directory: '/config/esphome/common/secrets.yaml'

### Which version of ESPHome has the issue?

2021.12.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021-12

### What platform are you using?

ESP32

### Board

Esp32dev

**Comment by jesserockz** [comment]
You need to have a `secrets.yaml` file also in any sub-folder.

You can make it like this:
```yaml
<<: !include ../secrets.yaml
```

**Comment by Sholofly** [comment]
@jesserockz That doesn't work. Validating in esphome doesn't work in that case:
```ERROR Error while reading config: Invalid YAML syntax:

Error reading file /config/esphome/./common/../secrets.yaml: [Errno 2] No such file or directory: '/config/esphome/./common/../secrets.yaml'```

**Comment by jesserockz** [comment]
Do you have a `secrets.yaml` file in your main esphome config folder though?

**Comment by Sholofly** [comment]
I thought i had, but it turned out i didn't. It works. Thanks!

**Comment by Sholofly** [comment]
Does someone see whats going wrong here? Config validation works fine in Esphome but doesn't in the action.
https://github.com/Sholofly/home-assistant-config/runs/4696172208?check_suite_focus=true

**Comment by wildblue** [comment]
I have a main sectets file and also figured the include thing out by myself weeks ago.
my point is:
It does not work as expected. And i iam a software engeneer myself, rarely post any "not working" tickets when it is obvious or documented. When i use a redirection to my one and only sectets.yaml, i don't want to take care of creating another file which redirects my obvious command somewhere else. What happens when this file gets modified by someone else? On a filesystem where the rw access is restricted to only admins can see the sectets?

Just fix that and don't argue why not fixing this could also work. If the next person having this issue finds your comment on githib...
