### ISSUE TITLE
Configuration type "Time" can't be used as described in doc's in Binary Sensor filter "delayed_off".

### ISSUE THREAD

**Issue by wimbu** [esphome/issues#291]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Not relevant.

**ESP (ESP32/ESP8266, Board/Sonoff):**

platform: ESP8266
board: d1_mini

**Affected component:**

Binary sensor

**Description of problem:**
One of the filters supported by Binary Sensor is "delayed_off" filter.
According to the documentation:
[https://esphome.io/components/binary_sensor/index.html#binary-sensor-filters](url)
> delayed_off: When a signal OFF is received, wait for the specified time period until publishing an OFF state....
Configuration item example:
>       - delayed_off: 100ms

My assumption is, that "delayed_off" can be configured in the same way as any configuration item of type "Time" as described on the page:
[https://esphome.io/guides/configuration-types.html#time](url)

At the present moment, only following ("simple") configuration compiles without errors.
    filters:
      - delayed_off: 5s
Following configuration throws compilation error:
    filters:
      - delayed_off:
        seconds: 5

Error:
Failed config

binary_sensor.template: [source lx_move.yaml:78]
  platform: template
  lambda: return id(pir_01).state;
  id: pir_01_helper
  filters:  [source lx_move.yaml:82]
    - [source lx_move.yaml:82]

      Expected string for time period with unit.
      delayed_off:

      [seconds] is an invalid option for [0].
      seconds: 5

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
# OK
    filters:
      - delayed_off: 5s

# Compilation error
    filters:
      - delayed_off:
        seconds: 5

```

**Traceback (if applicable):**

```
Failed config

binary_sensor.template: [source lx_move.yaml:78]
  platform: template
  lambda: return id(pir_01).state;
  id: pir_01_helper
  filters:  [source lx_move.yaml:82]
    - [source lx_move.yaml:82]

      Expected string for time period with unit.
      delayed_off:

      [seconds] is an invalid option for [0].
      seconds: 5
```

**Additional information and things you've tried:**
The core of my problem is that I would like to calculate the value for "delayed_off" by using lambda but it seems that lambda can't be used for assigning value for single line configuration entry like:
      - delayed_off: 5s

**Comment by OttoWinter** [comment]
> At the present moment, only following ("simple") configuration compiles without errors.

The `seconds` entry needs to be indented by two spaces. It is the *value* of the delayed_off key.

> The core of my problem is that I would like to calculate the value for "delayed_off" by using lambda

`delayed_off` value cannot be templated. The delayed off filter expects a constant value for the delay time - otherwise some bad edge cases like what happens when the templated value decreases suddenly while waiting for a past event can happen. Also then the value would need to be evaluated in every loop() cycle which would be quite slow.
