### ISSUE TITLE
Web Server ui js fails

### ISSUE THREAD

**Issue by junalmeida** [esphome/issues#2965]
### The problem

I just built a fresh version of the esphome firmware for a device, and the webserver page js fails to render toggle states.

### Which version of ESPHome has the issue?

2022.1.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.10

### What platform are you using?

ESP32

### Board

ESP-CAM (AiThinker)

### Component causing the issue

web server

### Example YAML snippet

```yaml
web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
```

### Anything in the logs that might be useful for us?

```txt
Uncaught TypeError: Cannot read properties of null (reading 'children')
    at EventSource.<anonymous> (webserver-v1.min.js:formatted:11:34)
(anonymous) @ webserver-v1.min.js:formatted:11
```

### Additional information

![image](https://user-images.githubusercontent.com/991675/150380425-dc8b1c29-8d88-4280-b94b-06a66995d60e.png)

All states are empty. Toggle button works though

**Comment by enurist** [comment]
Same here: Lilygo TTGO T-Camera and Lilygo TTGO T-Camera Mini. ESP32s without camera are not affected.
