### ISSUE TITLE
In HA, ESPHome trying to connect to old nonexistent device

### ISSUE THREAD

**Issue by Tropaion** [esphome/issues#2994]
### The problem

I'm using ESPHome in Home Assistant and it is always trying to connect to the same IP adress:
```
Logger: aioesphomeapi.reconnect_logic
Source: /usr/local/lib/python3.9/site-packages/aioesphomeapi/reconnect_logic.py:126
First occurred: 15:01:06 (1 occurrences)
Last logged: 15:01:06

Can't connect to ESPHome API for 192.168.44.37 @ 192.168.44.37: Timeout while connecting to ('192.168.44.37', 6053)
```
I'm not sure but I think it is an old testdevice which I completely delete aready.
I also tried reinstalling ESPHome and deleting all it's files in /config/esp-home/* but it still tries to connect to it.

### Which version of ESPHome has the issue?

v2022.1.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.10

### What platform are you using?

ESP8266

**Comment by randybb** [comment]
The ESPHome directory has nothing to do with ESPHome Integration in HA. If HA is trying to connect to your device, it means you have an active integration with this device - open HA page, then Configuration -> Devices & Services and find this device in ESPHome integration.
