### ISSUE TITLE
MQTT Host name, IP Address and Traefik

### ISSUE THREAD

**Issue by pnt-thiago** [esphome/issues#3004]
### The problem

Hi,
I'm trying to get some advice with the following issue:
When I setup a MQTT broker behind Traefik, it expects that the client connects using the hostname "mqtt1.my-domain.com" because I have also set another broker at "mqtt2.my-domain.com" both of them resolving to the same IP address (because they are at the same machine).
Pointing the esphome MQTT client to the hostname works like it should until something causes the MQTT server to go offline, if this happens them the MQTT client in esphome tries to resolve the hostname to its IP address and keeps trying to connect with that IP. As the MQTT server is behind Traefik, it will not forward that connection to the correct server and eventually the esphome device will reboot after 15 min and when it does it will connect to the broker because now it will try to use the hostname again...
Is there a way to set esphome to try hostname them, if it fails, IP address them, if it fails, hostname, and so on? And not: hostname them, if it fails, IP address until reboot...
Thanks,

### Which version of ESPHome has the issue?

2022.1.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Anything in the logs that might be useful for us?

```txt
[I][mqtt:175]: Connecting to MQTT...
[D][mqtt:116]: Resolving MQTT broker IP address...
[D][mqtt:149]: Resolved broker IP address to xxx.xxx.xxx.xxx
[I][mqtt:175]: Connecting to MQTT...
[I][mqtt:175]: Connecting to MQTT...
[I][mqtt:175]: Connecting to MQTT...
[I][mqtt:175]: Connecting to MQTT...
[E][mqtt:295]: Can't connect to MQTT... Restarting...
```

**Comment by OttoWinter** [comment]
No, there is not. And this problem should really be solved on the DNS level (as in other applications too).
