### ISSUE TITLE
Hass.io missing docker tag esphome-hassio-amd64:1.12.2

### ISSUE THREAD

**Issue by k1ng440** [esphome/issues#304]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**
19-05-09 07:07:01 INFO (SyncWorker_11) [hassio.docker.interface] Pull image esphome/esphome-hassio-amd64 tag 1.12.2.
19-05-09 07:07:19 ERROR (SyncWorker_11) [hassio.docker.interface] Can't install esphome/esphome-hassio-amd64:1.12.2 -> 404 Client Error: Not Found ("no such image: esphome/esphome-hassio-amd64:1.12.2: No such image: esphome/esphome-hassio-amd64:1.12.2").

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
The tag does exist: https://hub.docker.com/r/esphome/esphome-hassio-amd64/tags

This is an error in Hass.io (or docker) - I've heard it happen before but don't know how it's solved. Please try restarting the system and upgrading the Hass.io supervisor to the latest version.

Closing this as this is an issue in Hass.io - not with ESPHome - bug should be reported in Hass.io bug tracker.
