### ISSUE TITLE
ESPHome 2022.2.3. launching - FATAL ERROR

### ISSUE THREAD

**Issue by Krzysztonek** [esphome/issues#3069]
### The problem

Please see the below screen:

![image](https://user-images.githubusercontent.com/87784133/154862374-61ea833a-6fb8-446d-89b9-dd6103b9ff20.png)

A fatal error occurs:
`/var/run/s6/etc/cont-init.d/10-requirements.sh: line 10: bashio::fatal: command not found`
when trying to start this add-on. Please advise.

### Which version of ESPHome has the issue?

2022.2.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.2.9

### What platform are you using?

ESP8266

**Comment by jesserockz** [comment]
Thanks, this is a bug in the shell script.
BTW, the error message you were supposed to see was

> SSL is enabled, but no certfile was specified
