### ISSUE TITLE
 All devices seen as offline

### ISSUE THREAD

**Issue by marcinwrobel** [esphome/issues#3104]
### The problem

The ESPHome panel shows all devices as offline. Fixed IP devices connected to the router. Devices show logs. Home Assistant reads all data from devices.
![image](https://user-images.githubusercontent.com/7246779/156202774-bb377047-df8d-4b67-b637-0b537987c6b1.png)
![image](https://user-images.githubusercontent.com/7246779/156202865-5ce5eb7d-eb21-4c0f-ab49-d240635e986c.png)

### Which version of ESPHome has the issue?

2022.2.5 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2022.2.9

### What platform are you using?

ESP8266

### Board

All ESP platforms, ESP32 and ESP8266

### Example YAML snippet

```yaml
esphome:
  name: kociol-co
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.10.8.7
    gateway: 10.10.8.1
    subnet: 255.255.255.0


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kotlownia Fallback Hotspot"
    password: "4RqxDtdxAMvq"
```

### Anything in the logs that might be useful for us?

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ESPHome
 ESPHome add-on for intelligently managing all your ESP8266/ESP32 devices
-----------------------------------------------------------
 Add-on version: 2022.2.5
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.2.9
 Home Assistant Supervisor: 2022.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-nginx.sh: executing... 
[cont-init.d] 20-nginx.sh: exited 0.
[cont-init.d] 30-dirs.sh: executing... 
[cont-init.d] 30-dirs.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:04:33] INFO: Waiting for dashboard to come up...
[17:04:34] INFO: Starting ESPHome dashboard...
2022-03-01 17:04:34,707 INFO Starting dashboard web server on unix socket /var/run/esphome.sock and configuration dir /config/esphome...
[17:04:35] INFO: Starting NGINX...
2022-03-01 17:06:17,006 INFO 304 GET / (0.0.0.0) 13.30ms
2022-03-01 17:06:17,054 INFO 200 GET /static/fonts/material-icons/material-icons.css?hash=ead4c276 (0.0.0.0) 13.64ms
2022-03-01 17:06:17,059 INFO 200 GET /static/css/vendor/materialize/materialize.min.css?hash=ec1df3ba (0.0.0.0) 3.25ms
2022-03-01 17:06:17,079 INFO 200 GET /static/js/vendor/jquery/jquery.min.js?hash=12108007 (0.0.0.0) 2.42ms
2022-03-01 17:06:17,084 INFO 200 GET /static/js/vendor/jquery-ui/jquery-ui.min.js?hash=cab3392d (0.0.0.0) 3.70ms
2022-03-01 17:06:17,092 INFO 200 GET /static/js/vendor/jquery-validate/jquery.validate.min.js?hash=aad785d4 (0.0.0.0) 1.49ms
2022-03-01 17:06:17,096 INFO 200 GET /static/css/esphome-2.css?hash=b79b4733 (0.0.0.0) 2.15ms
2022-03-01 17:06:17,097 INFO 200 GET /static/fonts/material-icons/MaterialIcons-Regular.woff2?hash=570eb838 (0.0.0.0) 2.80ms
2022-03-01 17:06:17,165 INFO 200 GET /static/js/vendor/materialize/materialize.min.js?hash=4be20daf (0.0.0.0) 4.01ms
2022-03-01 17:06:17,193 INFO 200 GET /static/js/vendor/ace/ace.js?hash=65322f49 (0.0.0.0) 13.08ms
2022-03-01 17:06:17,195 INFO 200 GET /static/js/esphome/index-f6fdac20.js (0.0.0.0) 8.08ms
2022-03-01 17:06:17,694 INFO 200 GET /static/js/vendor/ace/mode-yaml.js (0.0.0.0) 2.26ms
2022-03-01 17:06:17,698 INFO 200 GET /static/js/vendor/ace/theme-dreamweaver.js (0.0.0.0) 2.44ms
2022-03-01 17:06:17,719 INFO 304 GET /devices (0.0.0.0) 4.76ms
2022-03-01 17:06:17,763 INFO 200 GET /static/fonts/material-icons/MaterialIcons-Regular.woff2 (0.0.0.0) 1.77ms
2022-03-01 17:06:17,803 INFO 101 GET /ace (0.0.0.0) 1.12ms
2022-03-01 17:06:17,935 INFO Running command 'esphome --dashboard -q vscode --ace /config/esphome'
```

**Comment by OttoWinter** [comment]
Have you tried to use the `status_use_ping` option? https://github.com/esphome/home-assistant-addon/blob/main/esphome/DOCS.md#option-status_use_ping

If your network doesn't accept mDNS traffic (or blocks it in some way), you need to use that option.

**Comment by chatziko** [comment]
I have the same issue. I use HA supervised 2022.3.3 with esphome addon 2022.2.6.
I do use `status_use_ping` (devices are in a different subnet), and I can manually ping all devices (also from within the esphome container). 

Something interesting: I have a single esp32 device, and this one does appear online. All the others are esp8266, and they show offline. Coincidentally (?) the esp32 device also appears first in the ping response (see below).

Example `/api/hassio_ingress/.../ping` response:
```
{
   "misc-audioengine-livingroom.yaml":true,
   "led-controller-kidsroom1.yaml":false,
   "led-controller-balcony.yaml":false,
   "led-controller-kitchen-island.yaml":false,
   "switch-balcony-cabinet.yaml":false,
   "misc-doorbell-entrance.yaml":false,
   "led-controller-kidsroom2.yaml":false,
   "led-controller-kitchen-counter.yaml":false,
   "led-controller-living-desk.yaml":false,
   "switch-bedroom-balcony.yaml":false,
   "switch-bathroom-door.yaml":false,
   "switch-entrance-corridor1.yaml":false,
   "switch-bedroom-bed.yaml":false,
   "switch-bedroom-door.yaml":false,
   "switch-entrance-door.yaml":false,
   "switch-kidsroom-balcony.yaml":false,
   "switch-entrance-corridor2.yaml":false,
   "switch-kidsroom-bed.yaml":false,
   "switch-kidsroom-door.yaml":false,
   "switch-kitchen-balcony2.yaml":false,
   "switch-kitchen-balcony1.yaml":false,
   "switch-living-balcony2.yaml":false,
   "switch-living-balcony1.yaml":false,
   "switch-kitchen-counter.yaml":false,
   "switch-living-desk.yaml":false,
   "switch-wc-door.yaml":false
}
```

**Comment by chatziko** [comment]
Update: in any of the devices that appear as offline, I do the following:
- Select "..." / Clean build files
- Select "..." / Compile" / Wirelessly, the compilation window opens, wait a couple of seconds, then select Stop (before it has the time to really compile anything)
Then after a few seconds the device appears online.

**Comment by marcinwrobel** [comment]
Not work. Still offline.

**Comment by sheminasalam** [comment]
any solutions? I am facing the same issue

**Comment by pashdown** [comment]
This problem is hit or miss for me.  Some of my devices have it, some do not. MDNS works and I've removed dashes and underscores from the problematic devices to no avail.

**Comment by Julusian** [comment]
Why was this closed?

I am still having this issue. mdns of other devices works fine, including shelly devices before they were flashed with esphome.
I also recently tried with an esp32 which had a wired ethernet port and it also does not work. (switches and wifi are all unifi)

Additionally, I have checked with wireshark and could not see any mdns traffic from esphome devices after the initial one at boot

**Comment by denisfrench** [comment]
Hi @marcinwrobel;

Did you manage to fix this, if so, how? If not, are you able to re-open the issue?

Thanks, Denis.

**Comment by kevinblo** [comment]
I have this problem too.

**Comment by sheminasalam** [comment]
If you are using esphome addon.

1. go to addon configurations
2. enable Show unused optional configuration options
3. enable status_use_ping
4. save and restart

This should solve offline issue.

**Comment by Rocky131** [comment]
> If you are using esphome addon.
> 
> 1. go to addon configurations
> 2. enable Show unused optional configuration options
> 3. enable status_use_ping
> 4. save and restart
> 
> This should solve offline issue.
That's fix it

> If you are using esphome addon.
> 
> 1. go to addon configurations
> 2. enable Show unused optional configuration options
> 3. enable status_use_ping
> 4. save and restart
> 
> This should solve offline issue.

Good solution! Thank you!

**Comment by bledzer** [comment]
> environment:
>       - ESPHOME_DASHBOARD_USE_PING=true

Thanks. This solved my issue of devices being online after community based addon -> repo migration

**Comment by bledzer** [comment]
> If you are using esphome addon.
> 
> 1. go to addon configurations
> 2. enable Show unused optional configuration options
> 3. enable status_use_ping
> 4. save and restart
> 
> This should solve offline issue.

Thanks. This solved my issue of devices being online after community based addon -> repo migration

**Comment by olegrasskazovpro** [comment]
> If you are using esphome addon.
> 
> 1. go to addon configurations
> 2. enable Show unused optional configuration options
> 3. enable status_use_ping
> 4. save and restart
> 
> This should solve offline issue.

Doesnt work for me

**Comment by ilgio** [comment]
> > If you are using esphome addon.
> > 
> > 1. go to addon configurations
> > 2. enable Show unused optional configuration options
> > 3. enable status_use_ping
> > 4. save and restart
> > 
> > This should solve offline issue.
> 
> Doesnt work for me

same problem
:(

**Comment by pieterdevriesch** [comment]
also. I used to be able to see the online status, then it stopped working at some point. Status_use_ping is already set to true, all esp's are in my local DNS server and can be pinged. (in my case the wireless update also just works, so clearly ESPhome can find them, just won't show them as online which is inconvenient)

**Comment by emrahgultekin** [comment]
> If you are using esphome addon.
> 
>     1. go to addon configurations
> 
>     2. enable Show unused optional configuration options
> 
>     3. enable status_use_ping
> 
>     4. save and restart
> 
> 
> This should solve offline issue.



Thanks man. This is solved my probem.

**Comment by pieterdevriesch** [comment]
> also. I used to be able to see the online status, then it stopped working at some point. Status_use_ping is already set to true, all esp's are in my local DNS server and can be pinged. (in my case the wireless update also just works, so clearly ESPhome can find them, just won't show them as online which is inconvenient)

And after the latest home assistant update it's working again. This time I got some warnings about mDNS and stuff from the supervisor, after fixing all the warnings it was working again. So looks like the problem was with the underlying (supervised) OS.
