### ISSUE TITLE
Contributing documentation outdated

### ISSUE THREAD

**Issue by jld3103** [esphome/issues#311]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

Contributing documentation
https://esphome.io/guides/contributing.html

**Description of problem:**
The documentation says you have to download the esphome-core, but this is not needed anymore.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
Yes and that is being worked on (see https://github.com/esphome/feature-requests/issues/222)

You can already see some of the updated docs here: https://next.esphome.io/ - but it's still under active development.

Closing to track this in https://github.com/esphome/feature-requests/issues/222
