### ISSUE TITLE
OTA Logs crash decoding bad utf8 and does not recover

### ISSUE THREAD

**Issue by glmnet** [esphome/issues#313]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Windows, VSCode, command line `esphome ...yaml run --upload-port OTA`
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266

**Affected component:**

Logger OTA only.

**Description of problem:**
Logger crash trying to decode, in this case char `0xff` but I guess it failed with other weird characters too, this is happening because I'm debugging a serial communication with the SIM800L and sometimes a little garbage comes from the wire.

I believe the issue is clear in the stack, also another issue arises as it cannot reconnect again but, if I kill the logger `Ctrl+C` then do `esphome ... logs` it quickly reconnects (and doesn't fails anymore as I guess no bad character on the wire is comming)

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Traceback (if applicable):**

```
[23:47:53][D][api:572]: Client 'Home Assistant 0.92.2 (10.0.1.206)' connected successfully!
[23:47:58][V][sim800l:041]: S: AT - 1
Exception in thread Thread-4:
Traceback (most recent call last):
  File "c:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\git\esphome\esphome\api\client.py", line 396, in run
    self._run_once()
  File "c:\git\esphome\esphome\api\client.py", line 385, in _run_once
    msg.ParseFromString(raw_msg)
  File "c:\python27\lib\site-packages\google\protobuf\message.py", line 187, in ParseFromString
    return self.MergeFromString(serialized)
  File "c:\python27\lib\site-packages\google\protobuf\internal\python_message.py", line 1145, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "c:\python27\lib\site-packages\google\protobuf\internal\python_message.py", line 1210, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "c:\python27\lib\site-packages\google\protobuf\internal\decoder.py", line 592, in DecodeField
    field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])
  File "c:\python27\lib\site-packages\google\protobuf\internal\decoder.py", line 548, in _ConvertToUnicode
    value = local_unicode(byte_str, 'utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 28: 'utf8' codec can't decode byte 0xff in position 28: invalid start byte in field: SubscribeLogsResponse.message

?[33mWARNING Disconnected from API.?[0m
?[32mINFO Connecting to eh_planta_alta.local:6053 (10.0.1.9)?[0m
?[33mWARNING Couldn't connect to API (Timeout while waiting for message response!). Trying to reconnect in 1 seconds?[0m
?[33mWARNING Disconnected from API.?[0m
?[32mINFO Connecting to eh_planta_alta.local:6053 (10.0.1.9)?[0m
?[33mWARNING Couldn't connect to API (Timeout while waiting for message response!). Trying to reconnect in 2 seconds?[0m
?[33mWARNING Disconnected from API.?[0m
?[32mINFO Connecting to eh_planta_alta.local:6053 (10.0.1.9)?[0m
?[33mWARNING Couldn't connect to API (Timeout while waiting for message response!). Trying to reconnect in 4 seconds?[0m
?[33mWARNING Disconnected from API.?[0m
```

**Additional information and things you've tried:**

I tried nothing, I don't know if catching the exception thrown by google's protobuf will be ok and then continue happy, it would be great if this character where filtered / replaced / marked, etc.

**Comment by OttoWinter** [comment]
> Logger crash trying to decode, in this case char 0xff but I guess it failed with other weird characters too, this is happening because I'm debugging a serial communication with the SIM800L and sometimes a little garbage comes from the wire.

The behavior is correct - protobuf strings are UTF-8 encoded strings so non-UTF8 is not allowed.

The problem is the code that is printing the message - it should escape the data.
