### ISSUE TITLE
Problem to convert uptime sensor to date format....

### ISSUE THREAD

**Issue by theniz** [esphome/issues#316]
Thanks for reporting a bug for this project. READ THIS FIRST:

- Provide as many details as possible. Simply saying "X gives bug" or "X gives error" is not enough!
- Paste logs, configuration sample and code into the backticks (```).
- Read through the template carefully and fill out all missing details.
- Please also search for similar issues in this issue tracker first and read through the ESPHome FAQ.

DO NOT DELETE ANY TEXT from this template! Otherwise the issue may be closed without a comment.
--> 
Hello, everybody...
As we know, uptime sensor's output is seconds only now.
I would like to convert it to date format like "1d 12h 24m" which could be easily read.
I have tried several times with my knowledge based upon homeassistant, I could not do  at all.
I realized that the grammer is different with homeassistant.
my script is here;

```yaml
sensor:
  - platform: uptime
    name: "d1mini Online"
    id: d1mini_up_time
    filters:
      - lambda: !lambda |-
          int ontime = x;
          int minutes = ontime / 60;
          int hours = ontime / 3600;
          int days = ontime / 86400;
          if (ontime < 60) {
            ontime
          } else { 
            if (days > 0) {
              days 
            }
            if (hours > 0) {
              if (days > 0) {
                ' '
              }
              hours
            }
            if (minutes > 0) {
              if ((days > 0) or (hours > 0)) {
                ' '
              }
              minutes
            }
          }
    update_interval: 60s
```

With above script, I got error.
What should I do? I know my script is wrong, but I can't how to correct this.
Please give me some hints where I should go to. Or you can edit it for me.
Thanks in advnace.

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
You're using the HA jinja2 syntax here - this is C++ and doing something like you want is more complicated.

You need to use a text_sensor (not a sensor filter, that's only for converting numbers, not text). And you need to use an std::string object to concatenate the fields one after another. But that's not really the place for this issue tracker.
