### ISSUE TITLE
WiFi SSID and Password in Secrets

### ISSUE THREAD

**Issue by albarlow** [esphome/issues#3227]
### The problem

A few versions back, [a feature was introduced](https://esphome.io/changelog/2021.12.0.html#the-dashboard-and-secrets) that the WiFi password would automatically be stored in secrets.yaml in the ESPHome folder.  It was [already a feature](https://esphome.io/guides/faq.html#how-do-i-use-my-home-assistant-secrets-yaml) that you could !include other files in the the secrets.yaml (e.g. the main Home Assistant secrets.yaml file.  I opted to do that so that I am only storing the WiFi settings in one location.

The problem is that the check for existing wifi credentials seems to happen without reference to any !include files.  This means that every time I add a new device, I have to type something in the box, then find the secrets.yaml file and delete the credentials.

I know this is relatively trivial, but it stumped me for some time when it first happened so may cause confusion for others and would just smooth out the experience.

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3.8

### What platform are you using?

ESP8266

**Comment by Protoncek** [comment]
I have a virtual device, set up just for this case, it's called "start-config". Inside there are all "universal" lines, like includes for wifi data, all "common stuff" ( i have a blinking led in all my devices to show status of wifi/HA connction) etc.
Then i just add a new device, type anything in, next...next... done. Then i open this newly created device and i just copy-paste all from my start-config. All it's needed then is give this new device a new name and you're ready to write commands part.
