### ISSUE TITLE
Typo in honeywellabp.rst documentation

### ISSUE THREAD

**Issue by ovitters** [esphome/issues#3229]
### The problem

I noticed a typo in https://github.com/esphome/esphome-docs/blob/current/components/sensor/honeywellabp.rst / https://www.esphome.io/components/sensor/honeywellabp.html:

> min_pressure (Required, int or float): _**Minumim**_ pressure for the pressure sensor, default unit psi.

This should read:

> Minimum

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.4.5

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

honeywellabp

### Anything in the logs that might be useful for us?

```txt
It's in the documentation. I don't use this component, I noticed this while reading the esphome changelog.
```

**Comment by sumirati** [comment]
Created PR to fix https://github.com/esphome/esphome-docs/pull/2043
