### ISSUE TITLE
DSMR Checksum mismatch

### ISSUE THREAD

**Issue by RyberNL** [esphome/issues#3249]
### The problem

I am getting a Checksum mismatch when trying to read data from my DSMR5 compatible smart meter.

### Which version of ESPHome has the issue?

2022.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.4.7

### What platform are you using?

ESP8266

### Board

D1 Mini / Slimmelezer Plus

### Component causing the issue

DSMR

### Example YAML snippet

```yaml
Using latest, slimmelezer.yaml, YAML from Marcel Zuidwijks Github
```

### Anything in the logs that might be useful for us?

```txt
[18:31:17][E][dsmr:265]: !CB64
 ^
Checksum mismatch
[18:31:18][E][dsmr:265]: !888C
 ^
Checksum mismatch
[18:31:20][E][dsmr:265]: !A226
 ^
Checksum mismatch
[18:31:21][E][dsmr:265]: !3B7C
 ^
Checksum mismatch
[18:31:22][E][dsmr:265]: !E78A
 ^
Checksum mismatch
[18:31:23][E][dsmr:265]: !6D82
 ^
Checksum mismatch
[18:31:24][E][dsmr:265]: !B0D5
 ^
Checksum mismatch
[18:31:25][W][dsmr:092]: Timeout while reading data for telegram
[18:31:26][E][dsmr:265]: !47B3
 ^
Checksum mismatch

...

[18:33:45][E][dsmr:265]: 0-3:24.2.1(220427183003S)(01127nͼ7*mf\xce\xc3\xe1!FEE9
                                          ^
Checksum mismatch
[18:33:46][E][dsmr:265]: !3EAA
  ^
Checksum mismatch
[18:33:47][E][dsmr:265]: !0B69
 ^
Checksum mismatch
[18:33:48][E][dsmr:265]: !B9B1
 ^
Checksum mismatch
[18:33:49][E][dsmr:265]: !7553
 ^
Checksum mismatch
[18:33:50][E][dsmr:265]: !Au44
 ^
Incomplete or malformed checksum
```

**Comment by mmakaay** [comment]
There is definitely some disturbance in the force.

The message "Timeout while reading data for telegram" shouldn't happen. That means that the DSMR component was expecting some data from the meter, but never saw it.

Another curious thing is the line `[18:33:50][E][dsmr:265]: !Au44`, stating that `Au44` is the checksum for the data telegram. However, this is a hex encoded number, and `u` is not a valid hex character. That tells us that the data is not clean for some reason.

Can you enable UART debugging, to get some more logging to inspect what actual data is being received? You can do this by modifying the `uart:` definition in your config to:

```yaml
uart:
  baud_rate: 115200
  rx_pin: D7
  rx_buffer_size: 1700
  debug:
    direction: RX
    after:
      delimiter: "\r\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);
```
