### ISSUE TITLE
SCD4x ambient_pressure_compensation_source is undocumented / doc addition was never merged

### ISSUE THREAD

**Issue by Wumpf** [esphome/issues#3268]
### The problem

The scd4x sensor platform has an undocumented config option `ambient_pressure_compensation_source` which was introduced in  https://github.com/esphome/esphome/pull/2493.
There was also a PR for documenting it https://github.com/esphome/esphome-docs/pull/1526, even detailing the feature with an example. However, it looks like it got abandoned and then forgotten until eventually auto-close kicked in. That PR looks good as is to me and should go in :)

### Which version of ESPHome has the issue?

Docs

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

n/a

### What platform are you using?

ESP32

**Comment by martgras** [comment]
Thanks - the changes is merged now
