### ISSUE TITLE
BH1750 fails with update interval < 1s

### ISSUE THREAD

**Issue by Stewie3112** [esphome/issues#3362]
### The problem

As per title, bh1750 sensor (and maybe other components using time) just doesn't work without any warning in the logs when update_interval is set below 1s. I actually need faster response time and was using  200ms with the previous releases successfully.

### Which version of ESPHome has the issue?

2022.5.1

### What type of installation are you using?

pip

### What platform are you using?

ESP32

**Comment by EugeneKorneev** [comment]
affected for me too v2022.6.3
i try change update_interval from 1s to 0.5s and get n/a

**Comment by Garfield-Z** [comment]
ESPHome 2023.2.4 still suffers this issue, the minimal working interval I tried so far is 800ms, when reduced further to 600ms, stopped working thereafter.
