### ISSUE TITLE
SX1509 forces use of internal pull-down if pin is not configured as a pull-up

### ISSUE THREAD

**Issue by PeteAndersen** [esphome/issues#3365]
### The problem

The SX1509 chip has both internal pull-down and pull-up resistors. The [pin schema](https://github.com/esphome/esphome/blob/c0fc5b48aec6c99e9e95bb74f050c54f54a9fe68/esphome/components/sx1509/__init__.py#L70-L96) only exposes the `PULL_UP` option, and the implementation in [sx1509.cpp](https://github.com/esphome/esphome/blob/c0fc5b48aec6c99e9e95bb74f050c54f54a9fe68/esphome/components/sx1509/sx1509.cpp#L79) will force on the pull-down if `PULL_UP` option is false. We should be able to enable pull-up or -down independently. 

### Which version of ESPHome has the issue?

2022.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

N/A

### Component causing the issue

SX1509

**Comment by ssieb** [comment]
Please test the PR to make sure it works properly as I don't have this device myself.
