### ISSUE TITLE
delayed_on not working as it should

### ISSUE THREAD

**Issue by PM04290** [esphome/issues#3367]
### The problem

Hello

as it is written in the documentation, with a duration of 100ms, it is necessary to wait 100ms of stable signal for the event to be triggered, indeed with this duration it seems that it works.
for a special need, I wanted the user to press a button for at least 3 seconds to trigger an event (on_press) so I configured delayed_on: 3000ms
I expected the on_press event to be activated after 3 seconds, except as long as you hold down the button nothing happens and when you release the button the on_press event is activated at after 3 seconds.
I think there is a problem :)

### Which version of ESPHome has the issue?

2022.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2022.6.5

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

button with pullup configuration

**Comment by bkaufx** [comment]
I just tried a delayed_on of 3000ms and it worked fine for me.  You really need to post your yaml.

**Comment by jesserockz** [comment]
I think your binary sensor pin needs to be inverted =)

**Comment by PM04290** [comment]
here is my yaml configuration
```
binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode:
        input: true
        pullup: true
    name: "Mode manuel"
    id: btnmanu
    internal: true
    filters:
      - delayed_on: 3000ms
    on_press:
      then:
        - logger.log: "=====> bouton"
        - lambda: |-
            auto call = id(climateemma1).make_call();
            if (id(climateemma1).mode == climate::CLIMATE_MODE_OFF) {
              call.set_mode("HEAT");
            } else {
              call.set_mode("OFF");
            }
            call.perform();

```
when i press button, all time is pressed nothing happened and when i release it, 3 second later the on_press event is called

**Comment by jesserockz** [comment]
Try adding `inverted: true` as below

```yaml
    pin:
      number: D5
      inverted: true
      mode:
        ...
```

**Comment by jesserockz** [comment]
Basically when you have a pullup, the binary_sensor is **off** when you are pushing it, and on when you are not, so the delayed_on starts when you release.

**Comment by PM04290** [comment]
I have inverted, so it's **off** wheen released, no ?

**Comment by PM04290** [comment]
if i keep pressed the buton, why **on_press** not called after 3000ms (debounce time) even if the button is pressed.
the fact of having to release the button to have the **on_press** action corresponds rather to the on_click action

**Comment by jesserockz** [comment]
@nagyrobi `on_click` is not right as OP wants the action to be performed while holding for at least 3s, not after its released after 3s.


>I have inverted, so it's off wheen released, no ?

Not according to your config pasted above my message...
https://github.com/esphome/issues/issues/3367#issuecomment-1155981426

**Comment by nagyrobi** [comment]
_on press_ then. Triggers on rising edge

**Comment by PM04290** [comment]
@bkaufx i understand what you mean about level detecting (0-3v3-0),
i have seen then line on digital read
`return bool(digitalRead(pin_)) != inverted_`
and i don't can explain why my configuration not run, i think filter is not managed correctly after pin reading for on_press event, but i don't find the code for this.

**Comment by bkaufx** [comment]
Here is what you need to add (commented ADD THIS LINE below):

```
binary_sensor:
  - platform: gpio
    pin:
      number: D5
      inverted: true  ################ ADD THIS LINE
      mode:
        input: true
        pullup: true
    name: "Mode manuel"
    id: btnmanu
    internal: true
    filters:
      - delayed_on: 3000ms
    on_press:
      then:
        - logger.log: "=====> bouton"
        - lambda: |-
            auto call = id(climateemma1).make_call();
            if (id(climateemma1).mode == climate::CLIMATE_MODE_OFF) {
              call.set_mode("HEAT");
            } else {
              call.set_mode("OFF");
            }
            call.perform();
```

**Comment by PM04290** [comment]
I'm sorry, I confused inverted and internal, problem when reading the same code 50 times
sorry, and thanks
