### ISSUE TITLE
am43 connect only to one device

### ISSUE THREAD

**Issue by wypalacz** [esphome/issues#3404]
### The problem

Hello,

I found issue with custom compontent AM43 Cover with esp32_ble_tracker.

Only one (first) device can be connected with esphome. 
Next devices reports:

[I][ble_client:085]: Attempting BLE connection to XX:XX:XX:XX:XX:XX
[W][ble_client:118]: connect to XX:XX:XX:XX:XX:XX failed, status=133

and never connect, only report this:
[W][am43:098]: [XX:XX:XX:XX:XX:XX] Cannot poll, not connected

How to fix this?

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.7

### What platform are you using?

ESP32

### Board

nodemcu

**Comment by Emilef22** [comment]
Same issue, do you solve this?
