### ISSUE TITLE
Stepper component docs: typo

### ISSUE THREAD

**Issue by definitio** [esphome/issues#343]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**
https://esphome.io/components/stepper/index.html#stepper-set-target-action

There is a typo under warning:
`- stepper:set_target:`
Should be:
`- stepper.set_target:`

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
Fixed in https://github.com/esphome/esphome-docs/pull/254
