### ISSUE TITLE
PIP Solar

### ISSUE THREAD

**Issue by quintinsleeking** [esphome/issues#3451]
### The problem

Hi 

I managed to build a rs232 to ttl device and setup esphome PIP solar.

I however get the worng values on the solar voltage, solar current,  etc.

Some value are 100% like load and voltage on ouput and battery percentage.

Please could you assist, how to fix the panel voltages, wattages etc?

Kind Regards
Quintin 

### Which version of ESPHome has the issue?

 2022.6.2 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.7.5

### What platform are you using?

ESP8266

### Board

witty cloud esp8266

### Component causing the issue

PIP Solar

**Comment by SeByDocKy** [comment]
There are some varations of the data structure depending which model you own. I advice to have a look the github of syssi, where you can find different variation implementations
