### ISSUE TITLE
daly BMS address via RS485

### ISSUE THREAD

**Issue by Kurs270** [esphome/issues#3452]
### The problem

Hello, 
I tried to interface EspHome with daly BMS via RS485 and ran into 2 problems:

Problem 1:
the address of 0x80 is hard-coded into daly_bms.cpp, but my bms (8s, 250A) did not answer. I needed to change the address to 0x40, than it worked. I am not sure if this is specific to rs485 or newer bms generally need this. The program for PC used 0x40 and did not even try 0x80, not even when no bms was connected and hence the requests were unsuccessfull.

This should be made configurable.

Problem 2:
Same as in #3086. Things were worse with RS485 of course, as 485 is strictly half duplex.
I did a quick fix myself, then later discovered that this was already fixed (#3385, April) but the fix did not yet make it into the master, which is a pity.

Could somebody please merge that pull request?
Regards
Thomas

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.7.5

### What platform are you using?

ESP32

### Component causing the issue

daly bms

**Comment by ssieb** [comment]
I assume you're referring to https://github.com/esphome/esphome/pull/3388.  It's not ready to be merged, there are still issues that need to be addressed.
