### ISSUE TITLE
customize text_sensor problem

### ISSUE THREAD

**Issue by liwei19920307** [esphome/issues#3460]
### The problem

I customized a text sensor, but it didn't update in time when calling publish_state(), but waited 60 seconds after calling

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

esp_c3_13u

### Component causing the issue

text_sensor

### Example YAML snippet

```yaml
TextSensor *status_sensor = new TextSensor();
status_sensor->publish_state("MOVE");
```

**Comment by ssieb** [comment]
That's not yaml.  You need to provide more information than that.
