### ISSUE TITLE
`pulse_meter` deduplicates values

### ISSUE THREAD

**Issue by Dennis4b** [esphome/issues#3473]
### The problem

The `pulse_meter` component uses deduplication to choose when to publish a new value:

```
if (this->pulse_width_dedupe_.next(pulse_width_ms)) {
```

but this creates unfortunate side effects where it's perfectly reasonable for two consecutive pulse intervals to be both valid yet occasionally identical.

Example motivation, details, and a patch, are in: https://github.com/klaasnicolaas/home-assistant-glow/issues/135#issuecomment-1199905076

Consider that the `pulse_meter` component already decides perfectly fine when a proper pulse has occured (when it updates `this->pulse_width_us_`) and could use the same logic to decide to publish.

It's a small change (example patch in the linked comment), if it can be picked up by a maintainer. I can of course add a PR, but would like to then ask for a heads-up if the patch looks like something that would be acceptable.

### Which version of ESPHome has the issue?

2022.6.2

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

D1 Mini

### Component causing the issue

pulse_meter

**Comment by ssieb** [comment]
There is no bug here, de-duplication is correct.  You're using the on_value for something it's not intended for.  The value hasn't changed, so there's no reason to publish it again.  It's also not losing anything in the total.  You could use the on_value of that if you want to get the pulses.
