### ISSUE TITLE
ESP32 camera - possible jpeg_quality is too low

### ISSUE THREAD

**Issue by maciekczwa** [esphome/issues#3570]
### The problem

The esphome validates the jpeg_quality in range 10-63.
In esp camera documentation the valid jpeg_quality is range 0-63
I have module TTGO T-Journal without PSRAM.

I modified the source of esphome to extend the range of values and run the camera successfully with jpeg_quality 6.
On lower values there is not enough RAM to fit bigger jpeg.

On jpeg_quality 6 - the quality is much better the JPEGs are around 40KB compared to 27 KB on jpeg_quality 10, resolution 800x600.

What is the reason to limit maximal quality to 10?

### Which version of ESPHome has the issue?

2022.9.0-dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.9.1

### What platform are you using?

ESP32

### Board

TTGO T-Journal

### Component causing the issue

esp32_camera

**Comment by sisco0** [comment]
@maciekczwa , could you kindly check if the code works as expected for the changes proposed in https://github.com/esphome/esphome/pull/3872?
