### ISSUE TITLE
Device unable to connect to api - home assistant reports 2 different devices

### ISSUE THREAD

**Issue by workingmanrob** [esphome/issues#3578]
### The problem

I have had this happen a few times recently and it is just bizarre.

For example today my workbench remote stopped working.  It was connected to wifi but not the api.  Checked home assistant frontend and workbench remote reported 2 devices.

![workbench-remote](https://user-images.githubusercontent.com/24377919/190001832-161c6404-fae6-44d5-b693-5aa9b105e666.png)

When I click on 2 devices I get a list - one is obviously not my workbench remote.

![devices-list](https://user-images.githubusercontent.com/24377919/190001991-6044206d-ecee-420f-8423-c19f33a71333.png)

This is an esp32 board and an esp32 camera but I am pretty sure I have had this with esp8266 devices as well.

### Which version of ESPHome has the issue?

2022.8.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2022.9.2

### What platform are you using?

ESP32

### Board

esp32doit-devkit-v1

### Component causing the issue

api

### Anything in the logs that might be useful for us?

```txt
There was a message about api not connecting but I have removed, updated and added the device back to home assistant.
```

**Comment by ssieb** [comment]
You need to remove both of those devices from the integration list to fix this.

**Comment by workingmanrob** [comment]
Ya thanks - I did that already - I have done it several times now actually cause I had to do it every time it happened.

The reason I reported it was the hope of having it fixed so it doesn't happen again. :beers:

**Comment by ssieb** [comment]
It shouldn't be happening unless you're either changing the name of a device or somehow two devices have the same IP address at different times.

**Comment by workingmanrob** [comment]
One is an esp32 camera in my living room the other is an esp32 board with a touchscreen attached to it so they have never switched places.

I use static DHCP mappings for all my IoT goodies so they should never come up with the same IP.

I do agree that it should not be happening.
