### ISSUE TITLE
Confusing Deep Sleep docs

### ISSUE THREAD

**Issue by jjok** [esphome/issues#359]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Any

**ESP (ESP32/ESP8266, Board/Sonoff):**

Any

**Affected component:**

https://esphome.io/components/deep_sleep.html

**Description of problem:**

This paragraph doesn't really make sense.

 >  To use deep_sleep first specify how long the node should be active, i.e. how long it should check sensor values and report them, using the run_duration options. If you use both in your configuration, any time either one of them is finished, the node will go into deep sleep mode.

Both what?

**Problem-relevant YAML-configuration entries:**
```yaml
N/A
```

**Traceback (if applicable):**

```
N/A
```

**Additional information and things you've tried:**

Read it a load of times to see if I could understand it. I couldn't.

**Comment by OttoWinter** [comment]
Ah yes, there previously were two options for that
