### ISSUE TITLE
Help! could IP101GRI ethernet chips support？

### ISSUE THREAD

**Issue by 645340633** [esphome/issues#3595]
### The problem

![gl-s10](https://user-images.githubusercontent.com/80463778/191089050-7fa7dd0e-3126-4859-8097-17339e66f1c5.png)
the new Ethernet chip of the board is IP101GRI that is not supported by esphome currently . I need Bluetooth proxy component through LAN eth. please      help me.

### Which version of ESPHome has the issue?

2022.8.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

**Comment by jesserockz** [comment]
Support for this is already merged, pending release tomorrow. esphome/esphome#3751
