### ISSUE TITLE
Default tab length is 4 instead of 2

### ISSUE THREAD

**Issue by Protoncek** [esphome/issues#3601]
### The problem

As title says: default tab length is now 4 and thus many times unusable. Can it be reverted back to 2 ?

### Which version of ESPHome has the issue?

2022.9.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.9

### What platform are you using?

ESP8266

**Comment by ssieb** [comment]
I assume you're referring to the dashboard editor.  That's an issue for https://github.com/esphome/dashboard/issues

**Comment by Protoncek** [comment]
It concerns new "monaco" editor. But, it's pretty odd that no-one noticed that yet..??? Since yaml is notoriously picky regarding indentations this is pretty big bug, don't you think?

**Comment by ssieb** [comment]
Normally people don't use tabs, you should be using spaces.  But this is still the wrong repo to be filing the issue in.  The editor is part of the dashboard.  This one is for the esphome device code.

**Comment by 3ative** [comment]
@ssieb If that's the case, why then does the editor add a Tab (and not two 'Spaces') when you add a new line?

**Comment by 3ative** [comment]
Not here, it adds 2 x 'Space' when I hit Return

**Comment by 3ative** [comment]
it is done in https://github.com/esphome/dashboard/pull/305.
