### ISSUE TITLE
Logging operating time - stored on powercycle

### ISSUE THREAD

**Issue by Bach-Danielsson** [esphome/issues#3616]
### The problem

I´m looking for the possibility to log the operating time from a machine. 
When a GPIO trigged the timer starts when GPIO low the timer stops. 

Timer value should be written to memory and be read when ESP reboots.

### Which version of ESPHome has the issue?

-

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

**Comment by ssieb** [comment]
This is not an issue.  It's either a feature request or a support request.  You can ask on the discord server for how you could do it.
