### ISSUE TITLE
sensor platform homeassistant - binary sensor no way to determine unavailable

### ISSUE THREAD

**Issue by warthog9** [esphome/issues#3630]
### The problem

The binary sensor component seems to only be a binary state sensor vs. a tri-state sensor (ignoring the obvious 'binary' in it's name).  The documentation is a little vague but seemed to imply that the valid responses were 0, 1, and {} if it didn't make it all the way through the filters.

My specific case involves home assistant platform sensors that unavailable, and/or the device hasn't fully connected yet and I want to ensure that they are reporting as problematic.  However the filter chain seems to translate 'unavailable' inherently to 0.

[01:25:08][W][homeassistant.binary_sensor:017]: Can't convert 'unavailable' to binary state!

Which leads to two possible requests:
- allow the filter to translate unavailable to nan / {} and return that instead of 0 or 1 as the error condition
- add an additional function that can be called to check for binary sensor availability more explicitly

### Which version of ESPHome has the issue?

2022.10.0-dev (Oct 1 2022, 01:24:20)

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

not a home assistant issue per-se

### What platform are you using?

ESP32

### Board

inkplate 10

### Anything in the logs that might be useful for us?

```txt
[01:25:08][W][homeassistant.binary_sensor:017]: Can't convert 'unavailable' to binary state!
```

**Comment by ssieb** [comment]
In a lambda, you can use `id(my_binary_sensor).has_state()`.  It returns a boolean value.
