### ISSUE TITLE
TH20 Elite(THR320D) - DS18B20- Dallas Temperature Sensor

### ISSUE THREAD

**Issue by cybertza** [esphome/issues#3657]
### The problem

No Sensor detected
Works on Tasmota and native

### Which version of ESPHome has the issue?

2022.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.0

### What platform are you using?

ESP32

### Board

TH20 - Elete with Display

### Component causing the issue

dallas

### Example YAML snippet

```yaml
- platform: dallas
    index: 0
    id: temp1
    name: "Geyser Temperature"
  - platform: dallas
    index: 1
    id: temp2
    name: "Geyser Temperature2"
```

### Anything in the logs that might be useful for us?

```txt
[22:43:37][C][dallas.sensor:075]: DallasComponent:
[22:43:37][C][dallas.sensor:076]:   Pin: GPIO25
[22:43:37][C][dallas.sensor:077]:   Update Interval: 60.0s
[22:43:37][W][dallas.sensor:080]:   Found no sensors!
```

### Additional information

Works on tasmota, 
<img width="213" alt="image" src="https://user-images.githubusercontent.com/20600538/194416850-6a3081a0-5de9-47a4-905e-b5b9e532a2c5.png">

(https://user-images.githubusercontent.com/20600538/194415072-dd57ca6a-9917-4dea-8c5c-d369fc4231c1.jpg)
<img width="737" alt="image" src="https://user-images.githubusercontent.com/20600538/194415153-22a1a9b8-8fdc-4f57-ae45-7dc1ef30cd11.png">
<img width="321" alt="image" src="https://user-images.githubusercontent.com/20600538/194415227-79bd85df-aaf3-46c4-bd36-23320cc10ee5.png">

https://github.com/arendst/Tasmota/issues/14338
https://github.com/pstolarz/OneWireNg

**Comment by cybertza** [comment]
Any Details, has anyone got this working?

**Comment by randybb** [comment]
There is no issue with ```dallas``` component. This is from my heating controller:
```
[10:36:01][C][dallas.sensor:075]: DallasComponent:
[10:36:01][C][dallas.sensor:076]:   Pin: GPIO32
[10:36:01][C][dallas.sensor:077]:   Update Interval: 60.0s
[10:36:01][D][dallas.sensor:082]:   Found sensors:
[10:36:01][D][dallas.sensor:084]:     0x1701143e35c5aa28
[10:36:01][D][dallas.sensor:084]:     0x7301143f7f57aa28
[10:36:01][D][dallas.sensor:084]:     0xf701143e397faa28
[10:36:01][D][dallas.sensor:084]:     0x5a041750b2c8ff28
[10:36:01][D][dallas.sensor:084]:     0xdb041750eae2ff28
[10:36:01][D][dallas.sensor:084]:     0xb2041750cf1aff28
[10:36:01][D][dallas.sensor:084]:     0x960417517301ff28
```
I don't have the same device as you have, I have only sonoff ts10 where it uses GPIO04 for jack connector and it works fine too.

As it is sonoff, tasmota must using some hacks to get it working...

**Comment by randybb** [comment]
And here we go :) just found it https://templates.blakadder.com/sonoff_THR320D.html

You have to pull GPIO27 high first.
```yaml
switch:
  - platform: gpio
    pin: GPIO27
    id: dallas_power
    restore_mode: ALWAYS_ON
```

**Comment by cybertza** [comment]
resolved with the solution by @randybb 
Thanks Guys

**Comment by DuncanCT** [comment]
Hi @cybertza did this work for you? If so please can you post your full config. I've tried but not working for me.

**Comment by cybertza** [comment]
Yea, so the config is as above, just add the 2 together.

switch:
  - platform: gpio
    pin: GPIO27
    id: dallas_power
    restore_mode: ALWAYS_ON

- platform: dallas
    index: 0
    id: temp1
    name: "Geyser Temperature"

or you can use the address. 
They have a pin connected to pin 27 that provides the power
