### ISSUE TITLE
ESP32 Safe Mode Boot became unavailable

### ISSUE THREAD

**Issue by tomi19921702** [esphome/issues#3663]
### The problem

Every few minutes Safe Mode Boot became unavailable and don't get data of Bluetooth Devices.

### Which version of ESPHome has the issue?

2022.9.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10

### What platform are you using?

ESP32

**Comment by tomi19921702** [comment]
![Screenshot_20221011-031516](https://user-images.githubusercontent.com/114293432/194969973-a2b40393-56ff-4190-9002-02f306ad6ffe.png)

![Screenshot_20221011-034630](https://user-images.githubusercontent.com/114293432/194969983-538c495a-caf0-43ab-bc1a-218d690928bb.png)
Attached a couple screenshots of the esphome logs when its helping

**Comment by nagyrobi** [comment]
Add to your config, and flash again:

```
debug:

sensor:
- platform: template
  name: Free HEAP
  lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
  icon: "mdi:memory"
  entity_category: diagnostic
  state_class: measurement
  unit_of_measurement: "b"
  update_interval: 60s
- platform: uptime
  name: Uptime
- platform: debug
  free:
    name: Free MEM
```
Wait for some time and look at the graphs.

**Comment by tomi19921702** [comment]
![Uploading Screenshot_20221014-092258.png…]()
