### ISSUE TITLE
olimex-bluetooth-proxy connection issues

### ISSUE THREAD

**Issue by marc-gist** [esphome/issues#3688]
I get CONSTANT disconnect, connect on the proxy.  Network is fine, and happens to various HA instances I have tested it on.

![image](https://user-images.githubusercontent.com/4084427/194879772-e15faa11-ab3c-4a42-9b45-f94022819f4f.png)

Nothing in the logs except:
```
WARNING GPIO12 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
```

Logs also contantly disconnect and reconnect.
```
INFO 10.20.1.31: Error while reading incoming messages: Error while reading data: [Errno 104] Connection reset by peer
INFO 10.20.1.31: Ping Failed: Error while reading data: [Errno 104] Connection reset by peer
INFO Disconnected from ESPHome API for 10.20.1.31
```

Both static and dynamic ips tend to do this :(

**Comment by nagyrobi** [comment]
A memory leak has been identified causing this. A potential fix is available in the current beta release, please try that.
