### ISSUE TITLE
Error: Please upgrade to the PlatformIO Core 6

### ISSUE THREAD

**Issue by alexkoel1958** [esphome/issues#3700]
### The problem

I'm trying to intialize a ESP-01. When I try write to the device I get the error: "Error: Please upgrade to the PlatformIO Core 6". I already has a ESP32 running without any problems. I got the message via USB in my laptop, and also via USB in the RPI4.

All software (HASSIO and ESPHome) is up to date.

Please help.

### Which version of ESPHome has the issue?

2022.2.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.4

### What platform are you using?

ESP8266

### Board

ESP-01

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/tempsensor-1.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing tempsensor-1 (board: esp01_1m; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
Platform Manager: Installing platformio/espressif8266 @ 3.2.0
Error: Please upgrade to the PlatformIO Core 6
```

**Comment by ssieb** [comment]
Your esphome version is very old.

**Comment by alexkoel1958** [comment]
I removed it, and reinstall. Everything works now. Why didn't it ask to update?

**Comment by jc-141** [comment]
> I removed it, and reinstall. Everything works now. Why didn't it ask to update?

what exactly did you remove? I'm having this issue too.

**Comment by ssieb** [comment]
You need to remove the add-on and get the current version.

**Comment by echoztrip** [comment]
I had a similar problem. Thankfully uninstalling and reinstalling the addon doesn't remove any data. I had historically restored from backup to new HA installation, so I wonder if that broke it somehow.

**Comment by kontiainen** [comment]
Maybe a newbie question, but how do you remove ESPHome add-on nowadays? 
On HA UI there are no "three dots" menu on right low corner, like on the other integrations.
<img width="577" alt="how-to-remove-esphome-from-ha" src="https://user-images.githubusercontent.com/10351861/197963017-20733a71-69b4-484e-8163-564211ee969f.png">

**Comment by emcniece** [comment]
I too encountered this, on Mac. Deleting the `.esphome` directory was not sufficient, nor was `pip uninstall esphome && pip install esphome --upgrade` - I had to delete and recreate the Python virtualenv.

**Comment by anszom** [comment]
All the responses discuss upgrading. Why is this considered acceptable? 

I've installed esphome about a year ago, built a project and forgot about it. Today I wanted to make a small change in the configuration, and surprise! I can't actually make a rebuild because I need to upgrade some components. **I have zero reasons to upgrade anything, I don't need any new bugs, if it works, why fix it?**

**Comment by ssieb** [comment]
This is not an esphome issue, we have no control over that.  It's from platformio.

**Comment by mwright-git** [comment]
> 

Okay please forgive this inexperienced user here!  I have this issue and I am getting the error whenever I try to update an existing node or add a new one.

I'm extremely worried about just deleting the add on and then reinstalling it as it would be very painful if I lost the configuration for the nodes (especially one that is remote and uses mqtt to communicate)

Do I just need to literally uninstall the add on and then reinstall it? Restart in-between. Will my node configuration come back or should I save the .yaml files?

Any help appreciated!

Thanks

**Comment by michaelsidenius** [comment]
Had to do:
```
pip install -U platformio
pip install -U esphome
```
for it to work

**Comment by dwertz1** [comment]
I removed the ESPHome and re-added.  All good and didn't lose anything.

**Comment by mwright-git** [comment]
Did the uninstall/install and everything seems to be still there and working after updating. 

Thanks everybody!

**Comment by danielbrunt57** [comment]
I too did the re&re from 2022.3.x to 2022.11.3 and have finished updating 9 of my 10 devices with no issues.  
EmporiaVue is still not supported...
```
Tool Manager: Installing platformio/toolchain-esp32ulp @ ~1.22851.0
INFO Installing platformio/toolchain-esp32ulp @ ~1.22851.0
Error: Could not find the package with 'platformio/toolchain-esp32ulp @ ~1.22851.0' requirements for your system 'linux_aarch64'
```

**Comment by orange-artworks** [comment]
Same problem for me today using esphome:latest via docker on command line of Rasp. Pi 4.  Same fix as per these commands.
```
rm -R .esphome
docker pull esphome/esphome:2022.11.3
docker run  --privileged --rm -v "${PWD}":/config -it esphome/esphome:2022.11.3 run test.yaml

```
