### ISSUE TITLE
has_built_in_endstop variable not working in time_based cover platform

### ISSUE THREAD

**Issue by JHeijting** [esphome/issues#3731]
### The problem

I have a garage door that can be opened, closed and stopped by putting a short pulse on one single input. I have flashed a Sonoff Basic with ESPhome using Home Assistant in order to open, close and stop my garage door. Because opening, closing and stopping the door all is done by the same command I wish to use the 'has_built_in_endstop' in order to make sure that the door is not accidentaly opened when pushing the stop button while the door is closed.

As per documentation the 'has_builtïn_endstop' does exactly this when set to True. However this does not work. While having this variable set to True, the stop button will still result in the stop_action being performed during a close or open action.

### Which version of ESPHome has the issue?

2022.10.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.5

### What platform are you using?

ESP8266

### Board

sonoff basic

### Component causing the issue

Time Based Cover

### Example YAML snippet

```yaml
switch:
  - platform: gpio
    pin: GPIO12
    id: relay
    on_turn_on:
      - delay: 100ms
      - switch.turn_off: relay

cover:
   - platform: time_based
     name: "Garagedeur"
     
     open_action:
      - switch.turn_on: relay
     open_duration: 20s

     close_action:
      - switch.turn_on: relay
     close_duration: 20s

     stop_action:
      - switch.turn_on: relay

     assumed_state: False
     has_built_in_endstop: True
```

### Anything in the logs that might be useful for us?

```txt
Here you see (the end part) of the garage door fully opening. The door goes to IDLE. After this I pressed the Stop button in Home Assistant. You can see in the logging that after this the relay still gets turned on.

[14:54:17][D][cover:173]:   Position: 86%
[14:54:17][D][cover:186]:   Current Operation: OPENING
[14:54:18][D][cover:170]: 'Garagedeur' - Publishing:
[14:54:18][D][cover:173]:   Position: 91%
[14:54:18][D][cover:186]:   Current Operation: OPENING
[14:54:19][D][cover:170]: 'Garagedeur' - Publishing:
[14:54:19][D][cover:173]:   Position: 96%
[14:54:19][D][cover:186]:   Current Operation: OPENING
[14:54:20][D][cover:170]: 'Garagedeur' - Publishing:
[14:54:20][D][cover:173]:   Position: 100%
[14:54:20][D][cover:186]:   Current Operation: IDLE
[14:54:23][D][cover:076]: 'Garagedeur' - Setting
[14:54:23][D][cover:080]:   Command: STOP
[14:54:23][D][switch:013]: 'relay' Turning ON.
[14:54:23][D][switch:037]: 'relay': Sending state ON
[14:54:23][D][cover:170]: 'Garagedeur' - Publishing:
[14:54:23][D][cover:173]:   Position: 100%
[14:54:23][D][cover:186]:   Current Operation: IDLE
[14:54:24][D][switch:017]: 'relay' Turning OFF.
[14:54:24][D][switch:037]: 'relay': Sending state OFF
```

**Comment by ianchi** [comment]
Hi @JHeijting 

That is not the use of `has_built_in_endstop`. It is stating that the *stop* action is done by the hardware itself when it is fully open/closed and that the component shouldn't issue a *stop* command at the end of the open/close time.

The kind of cover that you describe is quite tricky to model as a `cover` as you cannot issue independent open/close/stop commands to the hardware.
It definitely cannot be modeled by a simple `time_based` cover.

I had a similar problem as yours. With the help of some sensor to know in which direction the cover was moving and a new component `feedback cover` I was able to properly do it.

But if you don't have some feedback sensor, I think it is better to just use a Button. It just models what you have:
+ no known state
+ a single way to cycle thru the open/stop/close actions

**Comment by JHeijting** [comment]
Hi @ianchi,

Thank you for clarifying this. Now it makes perfect sense.

I indeed ended up as 'just use a button'. The original remote also has a button, so now it works just like that. In the end it is important to see the gate visually in my use case. Although there is a built in fail safe when it encounters an object (or dog or kid for that matter) this is not something to be trusted in my opinion.

I'll close the ticket so that anyone having the same misconception can find your answer :)
