### ISSUE TITLE
Total daily energy sensor resetting at wrong time despite correct time zone

### ISSUE THREAD

**Issue by frazzyfin** [esphome/issues#3736]
### The problem

The total daily energy sensor in home assistant for my energy monitor running ESPHome is resetting at 1am instead of midnight. My timezone is currently BST (UTC+1).

I have tried using the sntp time component and the homeassistant time component. I think the correct time zone is selected because when I look at the logs in ESPHome each log line shows the real current time.

ESPHome is running in a docker container and I have the timezone passed into the container (- /etc/localtime:/etc/localtime:ro).

### Which version of ESPHome has the issue?

v2022.10.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.10.4

### What platform are you using?

ESP32

### Board

Emporia Vue 2

### Component causing the issue

emporiavue2

### Additional information

See log time and windows clock are the same:

![image](https://user-images.githubusercontent.com/828721/198354787-789b14cf-4f18-43b2-9626-f3315af68432.png)

Home assistant sensor resetting at 1am: 

![image](https://user-images.githubusercontent.com/828721/198355019-34335d94-6ddf-4393-b3c1-402e000335a3.png)

**Comment by ssieb** [comment]
The log timestamps are from the receiving side.  They don't show what time the ESP has.  Add the timezone to the ESP config.

**Comment by frazzyfin** [comment]
Thanks that worked. Though I wonder why the timezone was being picked up correctly through the container or homeassistant.
