### ISSUE TITLE
Installation successful on ESP8922 but then offline and empty log

### ISSUE THREAD

**Issue by enzodesena** [esphome/issues#3754]
### The problem

Hi everyone. I am trying to install ESPHome and connect to a AZDelivery NodeMCU V2 WiFi Amica ESP8266. Here is the log. It looks like the installation goes well, but then the log is just empty (both when connecting through my Mac and on the RPI) and it does not connect to the card. I tried: (a) using a different USB cable; (b) connecting from my Mac or from the RPI running the ESPHome dashboard; (c) using 2 different wifi networks;  (d) using esp01_1m and nodemcuv2 board settings; (e) added "baud_rate: 9600" and "level: VERY_VERBOSE" to "logger:" in the yaml file; (f) communicating through the Arduino IDE, but failed to connect in any meaningful way. This is my first ESPHome board; any chance it is just broken?

[logs_buzzer_upload-4.txt](https://github.com/esphome/issues/files/9921640/logs_buzzer_upload-4.txt)

### Which version of ESPHome has the issue?

 2022.10.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

AZDelivery NodeMCU V2 WiFi Amica ESP8266

**Comment by ssieb** [comment]
GitHub issues are not for support requests.  I think you posted this on Discord earlier, but didn't respond to questions after.  Continue there.
