### ISSUE TITLE
Homeassistant is getting unresponsive when updating esp8266 

### ISSUE THREAD

**Issue by liakjim** [esphome/issues#3755]
### The problem

What title says. Only when updating esp8266's. Esp32's are updating just fine. I have to remove power to my raspberry in order to have my system run again. 

### Which version of ESPHome has the issue?

2022.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

 2022.10.5

### What platform are you using?

ESP8266

### Board

d1 mini

**Comment by ssieb** [comment]
Assuming you are using a pi3, use dev esphome with https://next.esphome.io/components/esphome.html#:~:text=compile_process_limit

**Comment by liakjim** [comment]
> Assuming you are using a pi3, use dev esphome with https://next.esphome.io/components/esphome.html#:~:text=compile_process_limit

I am using raspberry pi4 2GB.

**Comment by ssieb** [comment]
Ok, same thing, too little memory.  Use 1.

**Comment by liakjim** [comment]
> Ok, same thing, too little memory. Use 1.

Just to confirm. 
I need to add compile_process_limit=1 inside each 8266's yaml?

**Comment by liakjim** [comment]
Ok, i can confirm that ```compile_process_limit: 1``` did the trick. I had to install dev esphome add-on in order to accept this setting.
