### ISSUE TITLE
esp32-generic.yaml does not exist in repository.

### ISSUE THREAD

**Issue by ahaverty** [esphome/issues#3759]
### The problem

Trying to setup an esp32 as a bluetooth proxy, I get:

```
INFO Reading configuration /config/esphome/esp32-bluetooth-proxy-c85bb0.yaml...
Failed config

packages: [source /config/esphome/esp32-bluetooth-proxy-c85bb0.yaml:4]
  
  esp32-generic.yaml does not exist in repository.
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main [source /config/esphome/esp32-bluetooth-proxy-c85bb0.yaml:4]
```

### Which version of ESPHome has the issue?

2022.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.5

### What platform are you using?

ESP32

### Board

AZ-Delivery ESP32 NodeMCU

**Comment by nielsnl68** [comment]
Could it be you are using the old ESPHome Dashboard version? 
When you try to install a new add-on you should see 3 version of ESPHome. ESPHome, ESPHome (beta) and ESPHome (dev).
