### ISSUE TITLE
Get esphome-Dashboard located in docker to work with apache2 reverseproxy

### ISSUE THREAD

**Issue by platofan23** [esphome/issues#3805]
### The problem

When accessing the dashboard over the apache reverseproxy and https the logs and some functions don't work.

The browser-console says this with 400 Bad Request:
Uncaught TypeError: this.parentNode is null
wss://xxx:8083/esphome/logs
Firefox kann keine Verbindung zu dem Server unter wss://xxx:8083/esphome/ace aufbauen.
SyntaxError: import declarations may only appear at top level of a module

My apache2 reverseproxy mod looks like following:

SSLEngine on
ProxyRequests off
SSLProxyEngine on
SSLProxyVerify off
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off
ProxyPreserveHost on
<Location "/esphome">
                RequestHeader unset Origin
                ProxyPass http://xxx:6052
                ProxyPassReverse https://xxx:6052
                RewriteCond %{HTTP:Upgrade} websocket [NC]
                RewriteCond %{HTTP:Connection} upgrade [NC]
                RewriteRule ^/esphome/(.*) "wss://xxx:6052/$1" [P,L]
        </Location>

### Which version of ESPHome has the issue?

 v2022.10.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

**Comment by Gp2mv3** [comment]
I have the same error (`Uncaught TypeError: this.parentNode is null`) and no logs appear in the window when trying to connect wirelessly.
But I don't see those network errors.

I'm also on Firefox, and Chrome has the same issue.

**Comment by MaxWinterstein** [comment]
I guess this is related to https://github.com/esphome/issues/issues/3696
