### ISSUE TITLE
cant install 2022.11.1

### ISSUE THREAD

**Issue by hmax42** [esphome/issues#3812]
### The problem

I have a freshly installed kali debian macbook pro (mid 2012) with Python 3.10.8
i check out the respective tag from github
then
>pip install --user .
>...
>fastapi 0.85.0 requires starlette==0.20.4, but you have starlette 0.21.0 which is incompatible.

then i try
>pip install --user . -I starlette==0.20.4
>ERROR: Cannot install esphome and starlette==0.20.4 because these package versions have conflicting dependencies.
>
>The conflict is caused by:
>    The user requested starlette==0.20.4
>    platformio 6.1.5 depends on starlette==0.21.*

### Which version of ESPHome has the issue?

2022.11.1

### What type of installation are you using?

pip

### What platform are you using?

ESP32

**Comment by ssieb** [comment]
Run `script/setup` instead.

**Comment by hmax42** [comment]
thank you
