### ISSUE TITLE
Missing slider for monochromatic lights

### ISSUE THREAD

**Issue by cociweb** [esphome/issues#3821]
### The problem

This ticket is for administration and/or notification. 
The original problem and the resolution are linked:
Issue: https://github.com/esphome/esphome-webserver/issues/15
PR: https://github.com/esphome/esphome-webserver/pull/19

### Which version of ESPHome has the issue?

-

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP8266

### Board

-

### Component causing the issue

web_server + light.monochromatic

### Example YAML snippet

```yaml
-
```

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

Could anyone review and approve the small PR?

**Comment by jesserockz** [comment]
You dont need to create new issues when there already is one, and already a PR even. Its just creating noise.
