### ISSUE TITLE
Bluetooth Proxy compile fail: no toolchain 32 in HA Blue

### ISSUE THREAD

**Issue by timshadel** [esphome/issues#3889]
### The problem

I’m trying to update my bluetooth-proxy, but I get a compile failure right off:

```
INFO Reading configuration /config/esphome/esp32-bluetooth-proxy-fbf01c.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp32-bluetooth-proxy-fbf01c (board: esp32dev; framework: espidf; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
Tool Manager: Installing platformio/toolchain-esp32ulp @ ~1.22851.0
INFO Installing platformio/toolchain-esp32ulp @ ~1.22851.0
Error: Could not find the package with 'platformio/toolchain-esp32ulp @ ~1.22851.0' requirements for your system 'linux_aarch64'
```

### Which version of ESPHome has the issue?

2022.11.5 (Running as HA Add-on)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2022.12.1;   Supervisor 2022.11.2;   Operating System 9.3;   Frontend 20221208.0 - latest

### What platform are you using?

ESP8266

### Board

esp32dev

### Component causing the issue

bluetooth-proxy

### Example YAML snippet

```yaml
INFO Reading configuration /config/esphome/esp32-bluetooth-proxy-fbf01c.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp32-bluetooth-proxy-fbf01c (board: esp32dev; framework: espidf; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
Tool Manager: Installing platformio/toolchain-esp32ulp @ ~1.22851.0
INFO Installing platformio/toolchain-esp32ulp @ ~1.22851.0
Error: Could not find the package with 'platformio/toolchain-esp32ulp @ ~1.22851.0' requirements for your system 'linux_aarch64'
```

### Anything in the logs that might be useful for us?

```txt
Pasted above in the issue body
```

### Additional information

HA is running on [Home Assistant Blue](https://www.home-assistant.io/blue/) hardware.

**Comment by timshadel** [comment]
Looks like the Platform above is listed wrong. Should be ESP32, not ESP8266.

**Comment by vern59** [comment]
I am having a problem recompiling my bluetooth proxy on both of my esp32 boards.  no change in my yaml I now get 
Reading CMake configuration...
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The ASM compiler identification is unknown
-- Found assembler: /data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-gcc
-- Check for working C compiler: /data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-gcc
-- Check for working C compiler: /data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-gcc -- broken
-- Configuring incomplete, errors occurred!
See also "/data/esp32-bluetooth-proxy-6d66a0/.pioenvs/esp32-bluetooth-proxy-6d66a0/CMakeFiles/CMakeOutput.log".
See also "/data/esp32-bluetooth-proxy-6d66a0/.pioenvs/esp32-bluetooth-proxy-6d66a0/CMakeFiles/CMakeError.log".

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /data/cache/platformio/packages/tool-cmake/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /data/esp32-bluetooth-proxy-6d66a0/.pioenvs/esp32-bluetooth-proxy-6d66a0/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/data/cache/platformio/packages/tool-ninja/ninja cmTC_c04d8 && [1/2] Building C object CMakeFiles/cmTC_c04d8.dir/testCCompiler.c.obj
    FAILED: CMakeFiles/cmTC_c04d8.dir/testCCompiler.c.obj 
    /data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-gcc   -mlongcalls -Wno-frame-address -o CMakeFiles/cmTC_c04d8.dir/testCCompiler.c.obj   -c testCCompiler.c
    /bin/sh: 1: /data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-gcc: not found
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:311 (__project)
  CMakeLists.txt:3 (project)

**Comment by timshadel** [comment]
ESPHome 2022.12.0 fixed it. Thank you!

**Comment by MihaT2021** [comment]
I have also the same issue with EspHome version 2023.3.0 
[logs_esp32-bluetooth-proxy-f46cfd_run.txt](https://github.com/esphome/issues/files/10995057/logs_esp32-bluetooth-proxy-f46cfd_run.txt)

yaml:

substitutions:
  name: esp32-bluetooth-proxy-f46cfd
  friendly_name: Bluetooth Proxy f46cfd
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: fcIP0YGEQd/I3dQezMsEWNHZEaZpGgOGtpoFjtd15Ok=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
