### ISSUE TITLE
UUID displayed incorrectly in BLE Tracker logs

### ISSUE THREAD

**Issue by deunlee** [esphome/issues#3903]
### The problem

I found an issue with the UUID is reversed in the [ESP32 BLE Tracker](https://esphome.io/components/esp32_ble_tracker.html) log.

If someone sees the BLE Tracker's log to use BLE related components on ESP32, the UUID is displayed incorrectly, and it may be confusing like me to configure BLE related components.

If you set the UUID to `00112233-4455-6677-8899-AABBCCDDEEFF` as shown in the picture below, it will be displayed as `FFEEDDCC-BBAA-9988-7766-554433221100` in the log. (log level at VERY_VERBOSE)
(Tested on Beacon Simulator app and Home Assistant Android app.)

![beacon](https://user-images.githubusercontent.com/54697735/207493122-1101894b-784d-4c4b-9c60-6dc16af0f2a8.jpg)

```
[11:42:03][VV][esp32_ble_tracker:615]:     iBeacon data:
[11:42:03][VV][esp32_ble_tracker:616]:       UUID: FFEEDDCC-BBAA-9988-7766-554433221100
[11:42:03][VV][esp32_ble_tracker:617]:       Major: 10
[11:42:03][VV][esp32_ble_tracker:618]:       Minor: 20
[11:42:03][VV][esp32_ble_tracker:619]:       TXPower: -65
```

I found the [ESPBTUUID::to_string()](https://github.com/esphome/esphome/blob/0c24d951ff07bccd982443733ecce0675e93833d/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp#L604) function wrong in the source. It should start at 0. After looking through the commits, it seems that [1177 PR](https://github.com/esphome/esphome/pull/1177) is the problem. Here the starting value has changed.

It seems that it should be changed from `for (int8_t i = 15; i >= 0; i--)` to `for (uint8_t i = 0; i < 16; i++)`.

`ble_rssi` and `ble_presence` are unaffected because they use [ESPBTUUID::get_uuid()](https://github.com/esphome/esphome/blob/0c24d951ff07bccd982443733ecce0675e93833d/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp#L592). Also, `ble_scanner` doesn't use UUIDs, so it's irrelevant.

Please let me know if I can write a PR. Thanks for reading.

### Which version of ESPHome has the issue?

2022.11.5

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

**Comment by ssieb** [comment]
The author of that change agrees that it's wrong, so go for it.
