### ISSUE TITLE
Dallas temp sensor not found 

### ISSUE THREAD

**Issue by Skottelbraai** [esphome/issues#4029]
### The problem

After last update Dallas temp sensor is not found anny more by ESPHome.

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.2

### What platform are you using?

ESP32

### Board

Nodemcu

### Component causing the issue

Dallas DS18b20

**Comment by dd32** [comment]
See #3909

**Comment by Skottelbraai** [comment]
Thanks,
I found the solution here
