### ISSUE TITLE
Dallas DS18B20 parasitic power mode

### ISSUE THREAD

**Issue by tiimsvk** [esphome/issues#4081]
### The problem

Does the dallas ds18b20 parasitic power mode work with esphome?  I would need a two-wire connection to the sensor.

![Diagram-of-DS18B20-parasitic-power-supply](https://user-images.githubusercontent.com/52893640/214804288-3ac0fcfd-2b4d-4c21-8c4b-b1d109490aa5.png)

### Which version of ESPHome has the issue?

2022.12.7

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.01

### What platform are you using?

ESP32

### Board

esp32 s

### Component causing the issue

dallas ds20b18

**Comment by ssieb** [comment]
Github issues are not the place to ask questions.  Ask on the discord server or one of the forums.
