### ISSUE TITLE
Error reading file basic.bin: 'utf-8' codec can't decode byte 0xe9 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by raoulteeuwenPE** [esphome/issues#4128]
### The problem

I have created a ESPhome bin file on a Rpi4 with the ESPhome dashboard in Home Assistant (HA), and saved the resulting bin file to my Windows11 machine. I am attempting to ota upload it via the ESPhome CLI (the target device is a Sonoff Basic without webserver interface; it's online, but i don't have the files anymore that i once flashed to it, so also no connection via the HA ESPhome dashboard, and i hope i can flash the device without having to uninstall it and hook it up to my PC with wires and all).

When i use the ESPhome CLI with command "esphome -v config basic.bin" i get:

INFO Reading configuration basic.bin...
ERROR Error while reading config: Invalid YAML syntax: Error reading file basic.bin: 'utf-8' codec can't decode byte 0xe9 in position 0: invalid continuation byte

I have done some Google-ing, but didn't find a solution yet.

### Which version of ESPHome has the issue?

2022.12.8

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

sonoff basic

**Comment by ssieb** [comment]
The `esphome` command is expecting a yaml file.  You need to use esptool to flash a binary.  Or since you already have esphome installed locally, just use it to compile and upload there instead of transferring things around.  You could also use the web installer with the binary file.
