### ISSUE TITLE
Light inside HA seems limited on number of colours avalable

### ISSUE THREAD

**Issue by markcarline** [esphome/issues#413]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

PIP
**ESP (ESP32/ESP8266, Board/Sonoff):**

AI light and ws2812b LED strip
**Affected component:**

Light component

**Description of problem:**

From within the yaml file we are able to use the number 1 to 100 to determine the brightness of RGB colours. When a light is created via auto Discovery in home assistant the colour picker seems to be limited.

See this discussion over on the home assistant forums
https://community.home-assistant.io/t/better-colour-picker-for-led-strip-esphome-device/120310/8

I wonder if when the light is created it should be created using full colour?

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
Seems to affect all of light components however defined
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
This is a HA limitation - not ESPHome. Please ask the HA developers about it in the feature request section of the community forums.

Quite some versions ago, HA had a different color picker with continuous values, but that was removed for the new color picker. ESPHome does offer the ability to have very fine-grained controls of light colors, it's just the HA frontend that's limiting
