### ISSUE TITLE
mdns appears to "time-out" over time.

### ISSUE THREAD

**Issue by the-maldridge** [esphome/issues#4148]
### The problem

When a device is restarted it shows up as on-line, but after roughly 4 minutes the device is considered "offline" even though I can still access and control the devices, and can still use them via home assistant.

As such, this issue is specifically to the esphome dashboard's definition of "online" or "offline".

### Which version of ESPHome has the issue?

2022.11, 2022.12.8

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

sonoff basic, gosund wp6, gosund wp5

### Component causing the issue

mdns

### Additional information

I have minor suspicions that this is a network level mDNS issue, however I can from inside the esphome container invoke avahi queries and see the devices show up across the avahi-reflector on my network, so it does appear to work.

If there is a better approach I should be using here instead of mDNS where the esphome dashboard and its managed devices are not on the same layer 2 network but are instead on 2 different routed networks, feel free to point me in a different direction and close this issue.

**Comment by bdraco** [comment]
fixed via https://github.com/esphome/esphome/pull/5681
