### ISSUE TITLE
Wiegand tag scanned: invalid parity (and tag not scanned into HA)

### ISSUE THREAD

**Issue by Quarco** [esphome/issues#4220]
### The problem

Installed Wiegand tag reader (FSTech 13,56 MHz).

Problems are: 

- when a tag is scanned HA reports an "Invalid Parity
- it seems the on_tag statement is not executed 

![image](https://user-images.githubusercontent.com/41013449/220187599-20b40a66-a708-4700-ae19-82fcf38a3b46.png)

Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend-versie: 20230202.0 - latest

### Which version of ESPHome has the issue?

2023.2.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.5

### What platform are you using?

ESP32

### Board

esp32-dev + external antenna

### Component causing the issue

Wiegand keypad / tag scanner

### Additional information

Tried with 26 and 34 bit setting in keypad

**Comment by ssieb** [comment]
Yes, this is a known issue.  Somehow I broke the parity checking just before it was merged.  I thought it was tested, but apparently not.  I will fix it soon.

**Comment by ssieb** [comment]
Try adding this to your yaml and see if that fixes it:
```yaml
external_components:
  - source: github://ssieb/esphome@wiegand
    components: [ wiegand ]
    refresh: 1min
```

**Comment by Quarco** [comment]
Yes, that seems to remove the parity-error!

(MARCO = for my debugging / yaml)
![image](https://user-images.githubusercontent.com/41013449/220544091-200ad5e8-5622-4c6b-ba2c-01630446db9f.png)

![image](https://user-images.githubusercontent.com/41013449/220544170-20f7ba20-3270-4f70-be8e-faf6e3349a45.png)

(Seems to be a delay from about 1 sec)

**Comment by marcolinux46** [comment]
> Yes, that seems to remove the parity-error!
> 
> (MARCO = for my debugging / yaml) ![image](https://user-images.githubusercontent.com/41013449/220544091-200ad5e8-5622-4c6b-ba2c-01630446db9f.png)
> 
> ![image](https://user-images.githubusercontent.com/41013449/220544170-20f7ba20-3270-4f70-be8e-faf6e3349a45.png)
> 
> (Seems to be a delay (after scan-tag) of about 1 sec)

@Quarco do You remember the procedure to convert the reader in wiegand 26/34 mode? 
Today i opened an issue case for Unknown bit problem with the reader.

**Comment by Quarco** [comment]
The fontsize of the manual was so tiny, I had to take photo's of it :-)
If you need more, let me know!

![photo_2023-04-28_17-05-10](https://user-images.githubusercontent.com/41013449/235184006-6f7d2811-277b-4b0a-a4c0-bd4a2d6e702d.jpg)

**Comment by marcolinux46** [comment]
@Quarco thank you for your quick reply,

your information paper is same as mine.

So if i undestood:
1 - power-off the reader , short-circuit RESET and power-on until consequential bip.
2 - Power-off again and connect D0 or D1 to ground and power-on
3 - Wait until the green light starts to blink and during blink disconnect D0 or D1 and ground immediately.
4 - Click any button only one time (what do they mean for "click once to complete the conversion"? )

This is the right procedure?

Thank you for your support

**Comment by Quarco** [comment]
I did follow the procedure and it wasn't that hard after all. Had it changed the first time I tried it.
Tried both modes trying to fix my problem in february. Immediately the debug / log in HA showed 26 / 34 .

Just give it a try, i'm sure you'll get it :-)

**Comment by marcolinux46** [comment]
> I did follow the procedure and it wasn't that hard after all. Had it changed the first time I tried it. Tried both modes trying to fix my problem in february. Immediately the debug / log in HA showed 26 / 34 .
> 
> Just give it a try, i'm sure you'll get it :-)

Thank you for your reply.
"Immediately the debug / log in HA showed 26 / 34" --> During the boot procedure?

Only one question....after reset i have to reboot the reader?

Thank you

**Comment by Quarco** [comment]
Reboot can't do any harm :-)
After the procedure the log in HA should show 34 or 26 in the logs.

**Comment by marcolinux46** [comment]
> Reboot can't do any harm :-) After the procedure the log in HA should show 34 or 26 in the logs.

Procedure done again.....Now everything is working.
I connected also the ESP GND (thanks to @ssieb) that was missed yesterday.

@Quarco Thank you for your support

**Comment by laxfiend77** [comment]
I'm having the invalid parity issue currently with one of my esphome setups. Admittedly this is my first go round with these. I've tried pasting what you said into my yaml....assuming it's supposed to go into the esp home yaml for that reader and not my homeassistant config yaml or somewhere else.

**Comment by ssieb** [comment]
@laxfiend77 this was fixed a long time ago.  Do you have the latest esphome version?

**Comment by zipposi** [comment]
I'm having the same issue. Don't know exactly since when, but a few versions eatrlier was functioning

```
[07:51:03][D][wiegand:073]: received 26-bit tag: 10663461
[07:51:03][W][wiegand:075]: invalid parity
```

**Comment by ssieb** [comment]
What esphome version do you have?  Does the number match the tag?  Try swapping the data lines.
