### ISSUE TITLE
100% CPU when updating device firmware

### ISSUE THREAD

**Issue by D3-Bug** [esphome/issues#4228]
### The problem

When updating devices (using Homa Assistant) the CPU risses to 100%

Don't know if this is related:
Before finding this out, I had started multiple updates at the same time and my HA Blue crashed.

![image](https://user-images.githubusercontent.com/23278191/220696448-b1fc67a7-3ec8-45a0-a3b1-32b9b829ea9b.png)

### Which version of ESPHome has the issue?

2023.2.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.5

### What platform are you using?

ESP8266

### Board

various sonoff and shellys

**Comment by ssieb** [comment]
It has to compile the firmware, so yes, it's going to use 100% CPU.  And if you try to do multiple at once, you'll probably run out of RAM as well.
