### ISSUE TITLE
internal_temperature sensor on ESP32-S3

### ISSUE THREAD

**Issue by yousaf465** [esphome/issues#4271]
### The problem

Internal temperature was recently merged in ESp-dev branch. I tried using it via external component on ESP32-S3 esp32-s3-devkitc-1 v1.3. 
According to official documentation, it does support internal temperature sensor, but it doesn't seems to be working. 
https://docs.espressif.com/projects/esp-idf/en/v5.0.1/esp32/hw-reference/chip-series-comparison.html 

I get these values for the sensor 
```
11:32:02 | [D] | [internal_temperature:048] | Ignoring invalid temperature (success=0, value=139.0)
```
![image](https://user-images.githubusercontent.com/83491212/222648967-e28b7d82-8a8a-467e-aac6-c3184cb64aed.png)

### Which version of ESPHome has the issue?

2023.3-dev

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2023.3.1

### What platform are you using?

ESP32

### Board

ESP32-S3 esp32-s3-devkitc-1 v1.3

### Component causing the issue

internal_temperature

### Example YAML snippet

```yaml
external_components:
  - source: github://pr#4330
    components: [internal_temperature]
    refresh: always

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
```

### Anything in the logs that might be useful for us?

```txt
11:32:02 | [D] | [internal_temperature:048] | Ignoring invalid temperature (success=0, value=139.0)
11:35:02	[D]	[internal_temperature:048]	
Ignoring invalid temperature (success=0, value=139.9)
11:38:02	[D]	[internal_temperature:048]	
Ignoring invalid temperature (success=0, value=139.4)
```

### Additional information

![image](https://user-images.githubusercontent.com/83491212/222649384-907e676a-76b6-40e0-9ce2-cbfd31a4d00c.png)
![image](https://user-images.githubusercontent.com/83491212/222649438-067d85dc-664a-4f0c-9865-463ef5c87bb8.png)

**Comment by yousaf465** [comment]
![image](https://user-images.githubusercontent.com/83491212/222653443-1778ff4f-9b64-4ac1-944c-d4246973b027.png)

so temperature reported shouldn't be reported as invalid bcz it is round 57 if raw value is 139

**Comment by nopbop** [comment]
Hi

Same issue on my side for ESP32-S3

I get something like this in the log :
[00:09:05][D][internal_temperature:048]: Ignoring invalid temperature (success=0, value=92.1)

And temperature sensor in Hassio is marked as "NaN"

Any help on that point ?

Thx

**Comment by 2400bps** [comment]
[18:24:01][D][internal_temperature:048]: Ignoring invalid temperature (success=0, value=102.5)

**Comment by Fabian-Schmidt** [comment]
Hi,
This is known and fixed bug in ESP-IDF 4.4.3 within method `parse_temp_sensor_raw_value` (see https://github.com/espressif/esp-idf/issues/11343).

ESP Home is using [Arduino ESP32 2.0.5](https://github.com/espressif/arduino-esp32/releases/tag/2.0.5) (ESP-IDF 4.4.2) as recommended version which contains this bug. Set version to `latest` to get version `2.0.7` based on 4.4.4 which fixes the bug.

```yaml
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: latest
```

**Comment by yousaf465** [comment]
> 

let me try it.

**Comment by evlo** [comment]
For some reason I get this error when using 2023.7 .
```
  framework:
    type: arduino
    version: latest
```

**Comment by Fabian-Schmidt** [comment]
Hi @evlo,
Which error do you get?
To use a newer version of the Framework to be able to use the internal temperature sensor in your ESP32 S3?

And when you set the `version` it does not fix the issue?

**Comment by evlo** [comment]
I do not remember the error exactly, but it does contain link to this issue.

It does fix the issue, it was supposed to be note for others that this happens too, or me in the future, that it is indeed the fix.

**Comment by BarryReid** [comment]
I have tried setting the specific version and I too am still just getting invalid temp warnings.

![image](https://github.com/esphome/issues/assets/2881645/4b662f53-207e-4967-8b40-c5c759ad8372)

**Comment by moskovskiy82** [comment]
Same issue on 2023.11 ESP32 dev board

[D][internal_temperature:052]: Ignoring invalid temperature (success=0, value=53.3)
As i'm getting the same values as @BarryReid it seems the temp is not being read at all

**Comment by Fabian-Schmidt** [comment]
@moskovskiy82 What kind of dev board do you have? An ESP32 or an ESP32-S3? 
The ESP32 does not have an internal temperature sensor. See first post in this thread with list of ESP devices and also docs Note about it <https://esphome.io/components/sensor/internal_temperature>.
