### ISSUE TITLE
Web API uses `name` instead of `id`

### ISSUE THREAD

**Issue by mfbehrens99** [esphome/issues#4281]
### The problem

```yaml
switch:
  - platform: template
    id: switch_id
    name: Switch Name
    optimistic: true
```

It seems like the web API is using an entity's name as ID for the web API instead of `id`

This works:

`curl -X POST "http://esp.local/switch/switch_name/toggle"`

This does not work:

`curl -X POST "http://esp.local/switch/switch_id/toggle"`

In the [docs](https://next.esphome.io/web-api/index.html?highlight=api#rest-api), it is stated that the ID should be used to target an entity

### Which version of ESPHome has the issue?

2023.2.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

d1_mini_lite

### Component causing the issue

web api

### Anything in the logs that might be useful for us?

```txt
I think it is way better to use the ID instead of the name since "the" name is usually modified (whitespaces replaced with underscores) and it makes much more sense to target entities by their ID than their friendly name
```

### Additional information

Hope this is not a duplicate, but couldn't find any

**Comment by ssieb** [comment]
The `id:` is not usable as it is very internal.  Please read that section of the docs again as it does not say what you think it does.  The REST api "id" is based on the `name:`.
