### ISSUE TITLE
NSPanel tasmota to esphome fails OTA

### ISSUE THREAD

**Issue by rfaelens** [esphome/issues#4289]
### The problem

On an NSPanel EU version, I first flashed tasmota using the tasmota web installer.
I then downloaded a Legacy image of esphome, and flashed through the tasmota web interface.
Esphome booted succesfully.

**However, a subsequent esphome OTA update failed with Connection reset by peer at 1%.** The device logs stated "OTA update starting, 0.1%" and then also aborts with Connection reset by peer.
I had to flash esphome through _serial_ first, before OTA worked on subsequent attempts.

Probably flashing esphome through the tasmota web interface does not allow changing the partition table?
In my view, there are two issues here:
- Missing error reported by esphome to indicate the problem
- Tasmota not correctly flashing esphome through OTA (e.g. missing partition table)?

Feel free to close this issue if it should be reported at Tasmota instead.

### Which version of ESPHome has the issue?

2023.2.4

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

Sonoff NSPanel

### Anything in the logs that might be useful for us?

Logs from esphome logger:
```
[22:18:13][D][ota:147]: Starting OTA Update from ::FFFF:192.168.10.2...
[22:18:13][D][ota:316]: OTA in progress: 0.1%
WARNING 192.168.10.118: Connection error occurred: [Errno 104] Connection reset by peer
```

Logs from esphome upload:
```
INFO Reading configuration nspanel-black.yaml...
INFO Connecting to 192.168.10.118
INFO Uploading .esphome/build/nspanel-black/.pioenvs/nspanel-black/firmware.bin (856576 bytes)
Uploading: [=                                                           ] 1%

ERROR Error sending data: [Errno 104] Connection reset by peer
```

**Comment by hapklaar** [comment]
> I had to flash esphome through _serial_ first, before OTA worked on subsequent attempts.

I had the same issue, thanks for also supplying the solution.

**Comment by fabiobrolo** [comment]
Have you found any workaround to fix this issue?

**Comment by rfaelens** [comment]
Yes! The issue was in wifi sleep settings. Disabling those allowed the nspanel to work well

**Comment by morpheus-pl** [comment]
> Yes! The issue was in wifi sleep settings. Disabling those allowed the nspanel to work well

Where exactly do You change that ?
