### ISSUE TITLE
Flashing QIACHIP Wifi Wireless 433Mhz RF with esp8266-s3 (Sonoff RF clone)

### ISSUE THREAD

**Issue by rradar** [esphome/issues#430]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

QIACHIP Wifi Wireless 433Mhz RF with esp8266-s3 
![image](https://user-images.githubusercontent.com/34582688/59191931-d22cd280-8b78-11e9-87f8-849182d58ebb.png)

**Description of problem:**

I'm having hard time flashing this sonoff rf clone which has a little but important (I think) diffrence to the 'original'. The button on the device is connected directly to the 433 rf module to pair remotes (the sonoff rf instead connects it to the esp if I'm right). Therefor I have the hope to flash this device with esphome and still being able to controll it parallel with the rf module which is integrated in the device.

Problem is that I'm not able flash this esp8266-s3 thing despite having even the data sheet (https://fccid.io/2AKBPESP8266-S3/User-Manual/User-Manual-3594791).

![image](https://user-images.githubusercontent.com/34582688/59193512-e1624f00-8b7d-11e9-8fe7-bb53f6ba6231.png)
![image](https://user-images.githubusercontent.com/34582688/59193571-0e166680-8b7e-11e9-9820-028c6e83b406.png)

I tried with the usual Voltage, GND, RX, TX and pull GPIO 0 to ground to get in flash mode. Problem is that serial connection to the device always fails. Weird is also that I don't get the led (I think I see one right under the metal cap) on the esp8266-s3 to light up. It makes me wonder a little bit... usually this is always a great indicator that the board has power and from the type of blinking it's normally even possible to see if it booted successfully in the flash mode. I'm confused. :confused: :grey_question:  

![image](https://user-images.githubusercontent.com/34582688/59193740-98f76100-8b7e-11e9-987a-e558cbd752fa.png)
![image](https://user-images.githubusercontent.com/34582688/59193749-a4e32300-8b7e-11e9-9483-75d4488ef63e.png)

**Comment by OttoWinter** [comment]
Can't help much here - I don't know the chip and generally don't know much about non-NodeMCU ESP chips.

This is a bug tracker, and not for these general question. Please use the HA community forums for this.
