### ISSUE TITLE
Scaling for Tuya number component

### ISSUE THREAD

**Issue by prigorus** [esphome/issues#4309]
### The problem

The device sends values that are scaled by 10. I want to write these values to a number (to display in the frontend and change) and then send them back using the same number. The number component doesn't allow scaling like the sensor component.

### Which version of ESPHome has the issue?

2023.2.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Component causing the issue

Tuya number

### Additional information

There is the option to write the number to a global variable and display it as a sensor template, but this creates two entities of the same number. If the number component would have a scaling option, it would make the code much cleaner and easier to use.
This, in my opinion is a very common feature for others that are using Tuya MCU or something similar where values are multiplied to only use integers instead of float.

**Comment by InvncibiltyCloak** [comment]
I think I have fixed this issue in my feature branch. I used the Number's step to define the scaling between Tuya's integer values and ESPHome floats. Makes the most sense to me.
