### ISSUE TITLE
LD2410 on esp32 - all sensors are unknown

### ISSUE THREAD

**Issue by cburghardt** [esphome/issues#4317]
### The problem

I have connected the LD2410 to an esp32-pico-kit-v4
Unfortunately all of the sensors show up as unknown in HA.
I have tried various combinations of RX/TX pins on the board (18/23, 9/10, 16/17) but the behaviour is always identical.
Current version is GPIO9 for TX, GPIO10 for RX

### Which version of ESPHome has the issue?

2023.3.0 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.5

### What platform are you using?

ESP32-IDF

### Board

 Espressif ESP32 ESP32-PICO-KIT V4.1SiP Development Board

### Component causing the issue

ld2410

### Example YAML snippet

```yaml
esphome:
  name: "esp32-presence-office"
  name_add_mac_suffix: False
  friendly_name: Presence Office

esp32:
  board: esp32dev
  framework:
    type: esp-idf

api:

logger:
  #baud_rate: 0  
  logs:
    sensor: INFO 
    binary_sensor: INFO

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  id: uart1
  tx_pin: GPIO9
  rx_pin: GPIO10
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  timeout: 150s
  max_move_distance : 6m
  max_still_distance: 0.75m
  g0_move_threshold: 10
  g0_still_threshold: 20
  g1_move_threshold: 10
  g1_still_threshold: 20
  g2_move_threshold: 20
  g2_still_threshold: 21
  g3_move_threshold: 30
  g3_still_threshold: 31
  g4_move_threshold: 40
  g4_still_threshold: 41
  g5_move_threshold: 50
  g5_still_threshold: 51
  g6_move_threshold: 60
  g6_still_threshold: 61
  g7_move_threshold: 70
  g7_still_threshold: 71
  g8_move_threshold: 80
  g8_still_threshold: 81  

sensor:
  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
```

### Anything in the logs that might be useful for us?

```txt
[15:56:08][C][logger:293]: Logger:
[15:56:08][C][logger:294]:   Level: DEBUG
[15:56:08][C][logger:295]:   Log Baud Rate: 115200
[15:56:08][C][logger:296]:   Hardware UART: UART0
[15:56:08][C][logger:298]:   Level for 'sensor': INFO
[15:56:08][C][logger:298]:   Level for 'binary_sensor': INFO
[15:56:08][C][uart.idf:116]: UART Bus:
[15:56:08][C][uart.idf:117]:   Number: 1
[15:56:08][C][uart.idf:118]:   TX Pin: GPIO9
[15:56:08][C][uart.idf:119]:   RX Pin: GPIO10
[15:56:08][C][uart.idf:121]:   RX Buffer Size: 256
[15:56:08][C][uart.idf:123]:   Baud Rate: 256000 baud
[15:56:08][C][uart.idf:124]:   Data Bits: 8
[15:56:08][C][uart.idf:125]:   Parity: NONE
[15:56:08][C][uart.idf:126]:   Stop bits: 1
[15:56:08][C][ld2410:012]: LD2410:
[15:56:08][C][ld2410:014]:   HasTargetSensor 'Presence'
[15:56:08][C][ld2410:014]:     Device Class: 'occupancy'
[15:56:08][C][ld2410:015]:   MovingSensor 'Moving Target'
[15:56:08][C][ld2410:015]:     Device Class: 'motion'
[15:56:08][C][ld2410:016]:   StillSensor 'Still Target'
[15:56:08][C][ld2410:016]:     Device Class: 'occupancy'
[15:56:08][C][ld2410:019]:   Moving Distance 'Moving Distance'
[15:56:08][C][ld2410:019]:     Device Class: 'distance'
[15:56:08][C][ld2410:019]:     State Class: ''
[15:56:08][C][ld2410:019]:     Unit of Measurement: 'cm'
[15:56:08][C][ld2410:019]:     Accuracy Decimals: 0
[15:56:08][C][ld2410:020]:   Still Distance 'Still Distance'
[15:56:08][C][ld2410:020]:     Device Class: 'distance'
[15:56:08][C][ld2410:020]:     State Class: ''
[15:56:08][C][ld2410:020]:     Unit of Measurement: 'cm'
[15:56:08][C][ld2410:020]:     Accuracy Decimals: 0
[15:56:08][C][ld2410:021]:   Moving Energy 'Move Energy'
[15:56:08][C][ld2410:021]:     Device Class: 'energy'
[15:56:08][C][ld2410:021]:     State Class: ''
[15:56:08][C][ld2410:021]:     Unit of Measurement: '%'
[15:56:08][C][ld2410:021]:     Accuracy Decimals: 0
[15:56:08][C][ld2410:022]:   Still Energy 'Still Energy'
[15:56:08][C][ld2410:022]:     Device Class: 'energy'
[15:56:08][C][ld2410:022]:     State Class: ''
[15:56:08][C][ld2410:022]:     Unit of Measurement: '%'
[15:56:08][C][ld2410:022]:     Accuracy Decimals: 0
[15:56:08][C][ld2410:023]:   Detection Distance 'Detection Distance'
[15:56:08][C][ld2410:023]:     Device Class: 'distance'
[15:56:08][C][ld2410:023]:     State Class: ''
[15:56:08][C][ld2410:023]:     Unit of Measurement: 'cm'
[15:56:08][C][ld2410:023]:     Accuracy Decimals: 0
[15:56:08][C][ld2410:029]:   Firmware Version : 0.0.0000
```

**Comment by WhereDoesTheCodeGo** [comment]
This just randomly popped up for me yesterday on an existing install of an emporia vue2 that had been humming along happily for over a month. No changes happened yesterday but I might have not noticed when the "failure" occurred because it initially presented with only a single circuit not reporting data until I rebooted both my HA and the vue2 at which point everything stopped reporting. I never touch the vue2 so I am suspecting something in HA changed?

Here is a diag dump from the HA integration:

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.3.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/New_York",
    "os_name": "Linux",
    "os_version": "5.15.90",
    "supervisor": "2023.03.1",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.30.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "esphome",
    "name": "ESPHome",
    "after_dependencies": [
      "zeroconf",
      "tag"
    ],
    "codeowners": [
      "@OttoWinter",
      "@jesserockz"
    ],
    "config_flow": true,
    "dependencies": [
      "bluetooth"
    ],
    "dhcp": [
      {
        "registered_devices": true
      }
    ],
    "documentation": "https://www.home-assistant.io/integrations/esphome",
    "integration_type": "device",
    "iot_class": "local_push",
    "loggers": [
      "aioesphomeapi",
      "noiseprotocol"
    ],
    "requirements": [
      "aioesphomeapi==13.5.1",
      "esphome-dashboard-api==1.2.3"
    ],
    "zeroconf": [
      "_esphomelib._tcp.local."
    ],
    "is_built_in": true
  },
  "data": {
    "config": {
      "entry_id": "d913cdca97794a0d81b56b2054fe27ea",
      "version": 1,
      "domain": "esphome",
      "title": "emporiavue2",
      "data": {
        "host": "10.10.10.11",
        "port": 6053,
        "password": "**REDACTED**",
        "noise_psk": "",
        "device_name": "emporiavue2"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "zeroconf",
      "unique_id": "30:83:98:72:b6:ac",
      "disabled_by": null
    },
    "storage_data": {
      "device_info": {
        "uses_password": true,
        "name": "emporiavue2",
        "friendly_name": "",
        "mac_address": "**REDACTED**",
        "compilation_time": "Feb 18 2023, 16:01:18",
        "model": "esp32dev",
        "manufacturer": "Espressif",
        "has_deep_sleep": false,
        "esphome_version": "2023.2.2",
        "project_name": "",
        "project_version": "",
        "webserver_port": 0,
        "bluetooth_proxy_version": 0
      },
      "services": [],
      "api_version": {
        "major": 1,
        "minor": 7
      },
      "sensor": [
        {
          "object_id": "phase_a_voltage",
          "key": 2863619077,
          "name": "Phase A Voltage",
          "unique_id": "emporiavue2sensorphase_a_voltage",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "voltage",
          "unit_of_measurement": "V",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "phase_a_frequency",
          "key": 3389884893,
          "name": "Phase A Frequency",
          "unique_id": "emporiavue2sensorphase_a_frequency",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "frequency",
          "unit_of_measurement": "Hz",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "phase_b_voltage",
          "key": 2255573242,
          "name": "Phase B Voltage",
          "unique_id": "emporiavue2sensorphase_b_voltage",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "voltage",
          "unit_of_measurement": "V",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "phase_b_phase_angle",
          "key": 133889,
          "name": "Phase B Phase Angle",
          "unique_id": "emporiavue2sensorphase_b_phase_angle",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "",
          "unit_of_measurement": "\u00b0",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "phase_a_power",
          "key": 2071124304,
          "name": "Phase A Power",
          "unique_id": "emporiavue2sensorphase_a_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "phase_b_power",
          "key": 1881871067,
          "name": "Phase B Power",
          "unique_id": "emporiavue2sensorphase_b_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_1_power",
          "key": 1100406468,
          "name": "Circuit 1 Power",
          "unique_id": "emporiavue2sensorcircuit_1_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_2_power",
          "key": 1216885375,
          "name": "Circuit 2 Power",
          "unique_id": "emporiavue2sensorcircuit_2_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_3_power",
          "key": 3104999002,
          "name": "Circuit 3 Power",
          "unique_id": "emporiavue2sensorcircuit_3_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_4_power",
          "key": 340601669,
          "name": "Circuit 4 Power",
          "unique_id": "emporiavue2sensorcircuit_4_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_5_power",
          "key": 3630121144,
          "name": "Circuit 5 Power",
          "unique_id": "emporiavue2sensorcircuit_5_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_6_power",
          "key": 1400347427,
          "name": "Circuit 6 Power",
          "unique_id": "emporiavue2sensorcircuit_6_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_7_power",
          "key": 2328110478,
          "name": "Circuit 7 Power",
          "unique_id": "emporiavue2sensorcircuit_7_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_8_power",
          "key": 3136095353,
          "name": "Circuit 8 Power",
          "unique_id": "emporiavue2sensorcircuit_8_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_9_power",
          "key": 3865253420,
          "name": "Circuit 9 Power",
          "unique_id": "emporiavue2sensorcircuit_9_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_10_power",
          "key": 3414231560,
          "name": "Circuit 10 Power",
          "unique_id": "emporiavue2sensorcircuit_10_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_11_power",
          "key": 2165129365,
          "name": "Circuit 11 Power",
          "unique_id": "emporiavue2sensorcircuit_11_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_12_power",
          "key": 2295066526,
          "name": "Circuit 12 Power",
          "unique_id": "emporiavue2sensorcircuit_12_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_13_power",
          "key": 196093747,
          "name": "Circuit 13 Power",
          "unique_id": "emporiavue2sensorcircuit_13_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_14_power",
          "key": 2512085076,
          "name": "Circuit 14 Power",
          "unique_id": "emporiavue2sensorcircuit_14_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_15_power",
          "key": 3518635073,
          "name": "Circuit 15 Power",
          "unique_id": "emporiavue2sensorcircuit_15_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_16_power",
          "key": 189809322,
          "name": "Circuit 16 Power",
          "unique_id": "emporiavue2sensorcircuit_16_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "last_reset_type": 0
        },
        {
          "object_id": "total_power",
          "key": 3900173051,
          "name": "Total Power",
          "unique_id": "emporiavue2sensortotal_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 0,
          "last_reset_type": 0
        },
        {
          "object_id": "total_daily_energy",
          "key": 294834382,
          "name": "Total Daily Energy",
          "unique_id": "emporiavue2sensortotal_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_1_daily_energy",
          "key": 1798665735,
          "name": "Circuit 1 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_1_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_2_daily_energy",
          "key": 2196232122,
          "name": "Circuit 2 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_2_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_3_daily_energy",
          "key": 509996093,
          "name": "Circuit 3 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_3_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_4_daily_energy",
          "key": 2228899472,
          "name": "Circuit 4 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_4_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_5_daily_energy",
          "key": 3664514387,
          "name": "Circuit 5 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_5_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_6_daily_energy",
          "key": 129398902,
          "name": "Circuit 6 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_6_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_7_daily_energy",
          "key": 2192744297,
          "name": "Circuit 7 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_7_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_8_daily_energy",
          "key": 3327223212,
          "name": "Circuit 8 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_8_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_9_daily_energy",
          "key": 1571449711,
          "name": "Circuit 9 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_9_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_10_daily_energy",
          "key": 1927343779,
          "name": "Circuit 10 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_10_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_11_daily_energy",
          "key": 2207641824,
          "name": "Circuit 11 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_11_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_12_daily_energy",
          "key": 2773708921,
          "name": "Circuit 12 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_12_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_13_daily_energy",
          "key": 3372005446,
          "name": "Circuit 13 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_13_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_14_daily_energy",
          "key": 1472838295,
          "name": "Circuit 14 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_14_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_15_daily_energy",
          "key": 2377255156,
          "name": "Circuit 15 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_15_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        },
        {
          "object_id": "circuit_16_daily_energy",
          "key": 2566306509,
          "name": "Circuit 16 Daily Energy",
          "unique_id": "emporiavue2sensorcircuit_16_daily_energy",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "Wh",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 2,
          "last_reset_type": 0
        }
      ],
      "text_sensor": []
    }
  }
}

**Comment by cburghardt** [comment]
OK, I got it working by swapping RX and TX pins. Apparently they need to be swapped between the esp32 and the ld2410. Now it works.
