### ISSUE TITLE
Number Box on Web Interface

### ISSUE THREAD

**Issue by Samu84** [esphome/issues#4335]
### The problem

On the official Site of EspHome  https://esphome.io/components/web_server.html on the sceenshot i can see possibility to add/modify numbers in the boxes, i am using number component already, but i see only the line, as i wrote in the request, it would be nice also a text box.

How i do it? at least with numbers

### Which version of ESPHome has the issue?

2023.3.1

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

**Comment by ssieb** [comment]
https://esphome.io/components/number/index.html
`mode: box`
