### ISSUE TITLE
Phantom device at Home Assistant

### ISSUE THREAD

**Issue by fabiorcosta** [esphome/issues#4336]
### The problem

I re-flashed (3 times) an ESPHOME with another configuration, names, etc. But when I add to HA usign the add on, it shows the former name,config etc. I have even deleted the integration and add again, but it never gets the new data. Any guess?

### Which version of ESPHome has the issue?

2023.3.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.3

### What platform are you using?

ESP8266

### Board

ESP8266EX 482019 UBOOPPMX76

**Comment by ssieb** [comment]
Github issues are not for support requests.  Ask on the discord server (best option) or one of the forums.
