### ISSUE TITLE
Error changing ESP upload baud rate: No serial data received.

### ISSUE THREAD

**Issue by hussain1sheikh** [esphome/issues#4351]
### The problem

please resolve it it is my tthird time to waste my money

### Which version of ESPHome has the issue?

14

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

14

### What platform are you using?

ESP8266

### Board

wemos d1 mini

### Component causing the issue

Error changing ESP upload baud rate: No serial data received.

**Comment by ssieb** [comment]
This is not an esphome issue and you didn't provide the requested information.  Come ask for help on the discord server.
