### ISSUE TITLE
[name] is an invalid option for [output.modbus_controller]

### ISSUE THREAD

**Issue by 645340633** [esphome/issues#4397]
### The problem

[name] is an invalid option for [output.modbus_controller]

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.2

### What platform are you using?

ESP32

**Comment by 645340633** [comment]
[name] is an invalid option for [output.modbus_controller]. Please check the indentation.

**Comment by 645340633** [comment]
![1681019458436](https://user-images.githubusercontent.com/80463778/230756786-9b9e3601-df6e-4709-afbc-b4d748106680.png)

**Comment by ssieb** [comment]
That's a bug in the docs, probably copy and paste.  `output`s don't have names.
