### ISSUE TITLE
ESPHome device compiled with dashboard_import not available for adoption

### ISSUE THREAD

**Issue by dfrap** [esphome/issues#4410]
### The problem

https://esphome.io/guides/creators.html says that added configuration options to ESPHome to make it easier to create, configure, install and distribute devices running ESPHome.  No limitations are documented for ESPHome installation type.  

This device does tell the ESPHome dashboard how to add it using the dashboard import feature. Based on multiple tests, it appears that ESPHome running on Docker does not use the dashboard import feature. New devices are not available to be adopted by ESPHome even though mDNS finds device. 

### Which version of ESPHome has the issue?

2023.3.2 

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.4.2

### What platform are you using?

ESP32

### Board

Konnected Pro

### Example YAML snippet

```yaml
Used separate ESPHome Docker instance to compile alarm-panel-pro-esp32.yaml from 
https://github.com/konnected-io/konnected-esphome which contains:
dashboard_import:
  package_import_url: github://konnected-io/konnected-esphome/alarm-panel-pro-esp32.yaml@master
  import_full_config: true

Edit file to uncomment Ethernet includes:
ethernet_type: LAN8720 # Alarm Panel Pro up to 1.7
ethernet: github://konnected-io/konnected-esphome/packages/ethernet.yaml@master
```

### Anything in the logs that might be useful for us?

```txt
Compile program to bin file modern format for manual download. 
Processing alarm-panel-pro (board: wesp32; framework: arduino; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/alarm-panel-pro/src/main.cpp.o
Linking .pioenvs/alarm-panel-pro/firmware.elf
RAM:   [=         ]  10.8% (used 35236 bytes from 327680 bytes)
Flash: [====      ]  36.2% (used 663805 bytes from 1835008 bytes)
Building .pioenvs/alarm-panel-pro/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
esp32_create_combined_bin([".pioenvs/alarm-panel-pro/firmware.bin"], [".pioenvs/alarm-panel-pro/firmware.elf"])
Wrote 0xb2640 bytes to file /config/.esphome/build/alarm-panel-pro/.pioenvs/alarm-panel-pro/firmware-factory.bin, ready to flash to offset 0x0

Flashed to ESP32 with https://web.esphome.io/

Logs
ets Jun  8 2016 00:22:57
rst:0x1 (POWERON_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[I][logger:258]: Log initialized
[C][ota:469]: There have been 0 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[C][ethernet:028]: Setting up Ethernet...
[D][esp32.preferences:113]: Saving 4 preferences to flash...
[D][esp32.preferences:142]: Saving 4 preferences to flash: 0 cached, 4 written, 0 failed
```

### Additional information

mDNS queries find device:
dns-sd -Q alarm-panel-pro.local
Timestamp     A/R Flags if Name                             T   C Rdata
14:32:36.809  Add     2 18 alarm-panel-pro.local.           1   1 192.168.1.61
dns-sd -L "alarm-panel-pro" _http._tcp
Lookup alarm-panel-pro._http._tcp.local
14:32:59.206  alarm-panel-pro._http._tcp.local. can be reached at alarm-panel-pro.local.:80 (interface 18)
dns-sd -B _http._tcp
Browsing for _http._tcp
Timestamp     A/R Flags if Domain                    Service Type              Instance Name
14:33:21.300  Add     3 18 local.                    _http._tcp.               shelly1-771F3F
14:33:21.300  Add     3 18 local.                    _http._tcp.               Brother HL-L5100DN series
14:33:21.304  Add     2 18 local.                    _http._tcp.               alarm-panel-pro

Device connected to POE Ethernet port
Found by Home Assistant
![image](https://user-images.githubusercontent.com/25964907/231855068-c74504f4-9949-4aa0-b28f-cd9537ce7898.png)

Not found by ESPHome
![image](https://user-images.githubusercontent.com/25964907/231855200-1227fd42-476d-4e10-b80c-d4d4136efc6a.png)

Home Assistant page for device
![image](https://user-images.githubusercontent.com/25964907/231855359-f2e3742f-2a51-4139-9b12-e6c502748984.png)

ESPHome page for device
![image](https://user-images.githubusercontent.com/25964907/231855502-34b14602-8d12-4d7b-a4cd-8c415526da74.png)

**Comment by ssieb** [comment]
Are you sure that your esphome docker can see mdns?  That's a common problem with that setup.

**Comment by ssieb** [comment]
I don't see how you're so sure about that.  There are no other requirements, I have no idea what you're saying.

**Comment by dfrap** [comment]
In https://github.com/esphome/issues/issues/3905 ssieb states status_use_ping disables mdns use which is how detection works. I agree with the op of 3905 that I don't understand why the documentation encourages the use of status_use_ping. As soon as I destroyed the current Docker instance of ESPHome and recreated it with out the ping, the ESPHome instance was detected and the ADOPT option is available. 
![image](https://user-images.githubusercontent.com/25964907/231927641-e8643331-0323-4d90-ab8c-113b94f10962.png)

**Comment by ssieb** [comment]
Where do you see the docs encouraging ping?  It's offered as an option if mdns isn't working or if you have separate subnets.

**Comment by dfrap** [comment]
The misinformation about ESPHOME_DASHBOARD_USE_PING and mDNS are throughout https://esphome.io/guides/faq.html 

By default ESPHome uses mDNS to show online/offline state in the dashboard view. So for that feature to work you need to enable host networking mode.  **Response: Somewhat correct, but there are more requirements.** 

Alternatively, you can make esphome use ICMP pings to check the status of the device with the Home Assistant add-on "status_use_ping": true, option or with Docker -e ESPHOME_DASHBOARD_USE_PING=true.  **Response: Very misleading since using  ESPHOME_DASHBOARD_USE_PING disables mDNS which is not documented.**  

Online status detection in ESPHome’s dashboard by default uses mDNS, so disabling mDNS will cause the ESPHome dashboard to show the status of the nodes created without mDNS support to be always offline. Currently, this does not affect any functionality, however if you want to see the online/offline status you could configure ESPHome to ping each node instead.  **Response: Incorrect information because features such as adopt require mDNS.** 

The FAQ also links to https://esphome.io/components/mdns.html which further muddles how mDNS might be disabled by showing a configuration entry without explaining this is not the only way that mDNS could be disabled: 
It is recommended to leave mDNS enabled.
# Example configuration entry
mdns:
  disabled: false

**Comment by ssieb** [comment]
That FAQ entry was written long before adopting was a thing.  Also, adopting is not commonly used.  But feel free to submit a PR to make the docs better if you want.
