### ISSUE TITLE
sen21231: Over-reporting state? Or getting even more state?

### ISSUE THREAD

**Issue by kdorff** [esphome/issues#4476]
### The problem

I believe I find that the sen21231 component will only observe a face present if the sensor's light is on at the moment the component checks, which I believe is based on the `update_interval`. The default `update_interval` seems way too long (60s) for this (for my desires).

In order to get the best benefit for the sen21231 sensor / component, I found I needed to increase the `update_interval` (I used 0.1s) but make the component `internal`. And then only publish actual state changes using a `template` `binary_sensor`.
```
binary_sensor:
  - name: "Office Person Sensor"
    id: office_person_sensor
    platform: template
    device_class: motion

sensor:
  - platform: sen21231
    id: office_person_sensor_raw
    update_interval: 0.1s
    internal: true
    filters:
      - lambda: !lambda |-
          if (x >= 1) {
            // Person detected
            if (id(office_person_sensor).state == true) {
              // Person already detected
              return {};
            }
            // Person was JUST detected
            id(office_person_sensor).publish_state(true);
            ESP_LOGI("office_person_sensor_raw", "Person just detected");
            return {};
          }
          else {
            // No person detected
            if (id(office_person_sensor).state == false) {
              // No person is the current state - no change.
              return {};
            }
            // Person was JUST not detected
            id(office_person_sensor).publish_state(false);
            ESP_LOGI("office_person_sensor_raw", "Person no longer detected");
            return {};
          }
```
The biggest difference here is that while I'm checking every 0.1s, it will only update my `template` `binary_sensor` when there is ACUTALLY a change instead of updating state to HA every 0.1s.

One idea: I wonder if the core component could report changes in state ONLY OF there is actually a change in state (which is what my workaround provides).

An alternative idea, maybe better: The sensor also provides additional for recognized faces (left, right, top, bottom, confidence, recognition confidence, recognition id, looking at). I wonder if those could be made available in the `filter` for those who want to see that data, not unlike the additional data provided from `xpt2046`  where I can get the objects `.x` and `.y` values in a touch event? I say this is an alternative request, because these likely change change continuously.

Thoughts?

### Which version of ESPHome has the issue?

2023.4.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.6

### What platform are you using?

ESP8266

### Board

ESP8266 D1 Mini

### Component causing the issue

sen21231

### Example YAML snippet

```yaml
sensor:
  - platform: sen21231
    id: office_person_sensor_raw
```

**Comment by SeByDocKy** [comment]
Hi,

If you are interested, I modified the current SEN21231 integration to output many other features and also controls the internal register: https://github.com/SeByDocKy/myESPhome/tree/main/components


If you can understand french, please check my demo video: https://www.youtube.com/watch?v=vprfoG-lY6g

**Comment by kdorff** [comment]
I'd been getting a lot of green flickering on the Person Sensor when using this code (both false positives and false negatives). I converted my code to use the sensor directly (not using this component) and I feel like I get a lot fewer false positives and false negatives. But I will keep testing.

**Comment by SeByDocKy** [comment]
For me it's working perfectly. FYI, the first sen21231 sensor I recelved got a badly tuned lens.. impacting drastically negatively performances

![sen21231_faulty](https://user-images.githubusercontent.com/6464595/236034613-4f53ce8e-d28f-4e98-aae7-1eb8cf7e5fff.jpg)

**Comment by kdorff** [comment]
@SeByDocKy my cameras look like the right one. I have a big TV on the desk that is right behind my primary work desk. I'm wondering if the false positives and "2 face recognitions" might be it seeing odd things in the reflection on the TV? Especially in a pretty dark room, it seems to hallucinate faces.
