### ISSUE TITLE
[Question] Different component constructor based on config

### ISSUE THREAD

**Issue by sharkydog** [esphome/issues#4484]
### The problem

Hello,
I am trying to turn this [FRAM_I2C](https://github.com/RobTillaart/FRAM_I2C) library for arduino into esphome component.
So far I've managed "plug" the I2C bus as initialized by esphome and it works for both Arduino and ESP-IDF frameworks.

The library defines several classes to handle devices with different addressing.
So, my modified code would be like this:
```c++
// the main class
class FRAM : public Component, public i2c::I2CDevice {
  public:
    FRAM();
  // more stuff here ...
}

// more classes like this
class FRAM9 : public FRAM {
  // some overrides
}
```

Then, `__init__.py`:
```python
import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.components import i2c
from esphome.const import CONF_ID, CONF_TYPE

DEPENDENCIES = ["i2c"]
MULTI_CONF = True

fram_ns = cg.esphome_ns.namespace("fram")
FRAMComponent = fram_ns.class_("FRAM", cg.Component, i2c.I2CDevice)
FRAM9Component = fram_ns.class_("FRAM9", FRAMComponent)

FRAM_TYPES = {
	"FRAM": FRAMComponent,
	"FRAM9": FRAM9Component
}

CONFIG_SCHEMA = (
    cv.Schema(
        {
            cv.GenerateID(): cv.declare_id(FRAMComponent),
            cv.Optional(CONF_TYPE, default="FRAM"): cv.one_of(
                *FRAM_TYPES, upper=True, space="_"
            )
        }
    )
    .extend(cv.COMPONENT_SCHEMA)
    .extend(i2c.i2c_device_schema(0x50))
)

async def to_code(config):
    var = cg.new_Pvariable(config[CONF_ID])
    await cg.register_component(var, config)
    await i2c.register_i2c_device(var, config)
```

will put in `main.cpp`:
```c++
fram::FRAM *fram_1;
fram_1 = new fram::FRAM();
// set i2c bus, etc
```

Is there any way to make the code generator put this:
```c++
fram::FRAM9 *fram_1;
fram_1 = new fram::FRAM9();
```
based on this config:
```yaml
fram:
  - id: fram_1
    type: FRAM9
```
And then this config would allow different chips to be used at the same time:
```yaml
fram:
  - id: fram_1
    type: FRAM9
    address: 0x50 # default
  - id: fram_2
    type: FRAM # default
    address: 0x51
```

### Which version of ESPHome has the issue?

2023.4.3

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

**Comment by ssieb** [comment]
github issues are not for support requests.  Asking on the discord server would be best or one of the forums.
Yes, you can do this, but if you need help, create a thread in the general support channel or a thread in the devs channel would be good for this one too.
