### ISSUE TITLE
Connection status messages in the ESPHome dashboard do not display correctly

### ISSUE THREAD

**Issue by Murianwind** [esphome/issues#4487]
### The problem

The ESP device is connected, working fine, and I can even see the logs, but the dashboard display OFFLINE.

![image](https://user-images.githubusercontent.com/6447460/236102683-e7fb7ac5-5349-4e59-97e9-c955e33b93b7.png)

### Which version of ESPHome has the issue?

2023.4.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.0

### What platform are you using?

ESP32

### Board

nodemcu

### Additional information

The connected ESP is 8266 and the ESP marked as offline is ESP32.

**Comment by sippeeey** [comment]
same here. 
have ESPHome 2023.5.5

when i reboot the esphome addon on homeassistant one of my two esps shows online, after a few secound it turn to offline but when i open the logs, both shows connection?...why?
