### ISSUE TITLE
Firmware not available anymore in Home Asisstant

### ISSUE THREAD

**Issue by mstuij** [esphome/issues#4496]
### The problem

I can't using the firmware update entity of ESPHome anymore. This is since a few versions ago (I don't know exactly from which version) not working anymore.

![image](https://user-images.githubusercontent.com/75884924/236639119-0c2c8e86-92dc-4117-a101-3ce290d5f56f.png)

Also after rebooting my system, the update entities are not available.

### Which version of ESPHome has the issue?

2023.4.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.2

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.helpers.entity_component
Source: helpers/entity_component.py:50
First occurred: 18:50:57 (15 occurrences)
Last logged: 18:51:06

Forced update failed. Entity update.meterkast_controller_firmware not found.
Forced update failed. Entity update.zijraam_woonk_buiten_controller_firmware not found.
Forced update failed. Entity update.kantoor_buiten_controller_firmware not found.
Forced update failed. Entity update.voorkant_buiten_controller_firmware not found.
Forced update failed. Entity update.achterkant_buiten_controller_firmware not found.
```

**Comment by randybb** [comment]
As is mentioned in https://github.com/esphome/issues/issues/4419, it is HA issue - https://github.com/home-assistant/core/issues/88155
