### ISSUE TITLE
ESPhome configuration

### ISSUE THREAD

**Issue by LYL14** [esphome/issues#4549]
### The problem

After using HA, I want to configure bin file and yaml file in other ways. Is there any other way?

### Which version of ESPHome has the issue?

2023

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

**Comment by ssieb** [comment]
github issues are not for support requests.  Come ask on the discord server or one of the forums.

**Comment by LYL14** [comment]
Can ESPhome configure ESPnow and ESPmesh functions?
