### ISSUE TITLE
ADC-Pin ESP32-s2-saola-S1 support GPIO32-39 or any other?

### ISSUE THREAD

**Issue by selfmade01** [esphome/issues#4558]
### The problem

Helllo,
use the ESP32-S2-Saola-1 and at the datasheet i get ADC-Ports only at pins GPIO3-17 and GPIO18-21
At the esphome ADC docu i read esphome support ==> ESP32: GPIO32 through GPIO39 can be used.

do i have to watch out for something?
best regards
Achim

### Which version of ESPHome has the issue?

2023.5.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.3

### What platform are you using?

ESP32

### Board

ESP32-S2-Saola-1R

### Component causing the issue

ACS712 / CD74HC4067

**Comment by ssieb** [comment]
That's ESP32, not ESP32S2.
