### ISSUE TITLE
ESPHome Climate Fujitsu AC: Quiet-Mode 

### ISSUE THREAD

**Issue by ulliohura** [esphome/issues#4575]
### The problem

Hello all,

im trying to set my Fujitsu AC into the fanmode "quiet" but i dont get it work with ESPHome climate.
Also it is not listed in HomeAssistant:

![grafik](https://github.com/esphome/issues/assets/121728420/1751651c-c364-4c8b-9548-ea69e29f9fd3)

Perhaps you can help me. Thanks

### Which version of ESPHome has the issue?

2023.5.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

 2023.5.4 

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

**Comment by TaruDesigns** [comment]
I have this same issue so I decided to check the [source code](https://github.com/esphome/esphome/blob/dev/esphome/components/fujitsu_general/fujitsu_general.cpp). The info for quiet mode is there: `const uint8_t FUJITSU_GENERAL_FAN_SILENT = 0x04;` but it's not actually used in the switch:

```cpp
switch (this->fan_mode.value()) {
    case climate::CLIMATE_FAN_HIGH:
      SET_NIBBLE(remote_state, FUJITSU_GENERAL_FAN_NIBBLE, FUJITSU_GENERAL_FAN_HIGH);
      break;
    case climate::CLIMATE_FAN_MEDIUM:
      SET_NIBBLE(remote_state, FUJITSU_GENERAL_FAN_NIBBLE, FUJITSU_GENERAL_FAN_MEDIUM);
      break;
    case climate::CLIMATE_FAN_LOW:
      SET_NIBBLE(remote_state, FUJITSU_GENERAL_FAN_NIBBLE, FUJITSU_GENERAL_FAN_LOW);
      break;
    case climate::CLIMATE_FAN_AUTO:
    default:
      SET_NIBBLE(remote_state, FUJITSU_GENERAL_FAN_NIBBLE, FUJITSU_GENERAL_FAN_AUTO);
      break;
      // TODO Quiet / Silent
  }

```
