### ISSUE TITLE
Web server does not show AC modes anymore

### ISSUE THREAD

**Issue by WorlockM** [esphome/issues#4602]
### The problem

Since yesterday I can't see any controls for my AC's. Serveral users reported this. I only see state "24" and not the controls like Cooling/Heating etc. I did not update the ESPHome version but all stopped working at the same time.

I have no problems with Home Assistant.

### Which version of ESPHome has the issue?

All versions

### What type of installation are you using?

Docker Container

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

**Comment by Tarik2142** [comment]
same

**Comment by Tarik2142** [comment]
problem with this script
![image](https://github.com/esphome/issues/assets/31830530/c6d7361f-c45b-49a2-97df-dfb61cf28fdc)

**Comment by jamexcb** [comment]
I have the same issue too.

**Comment by CamielFolmer** [comment]
Same issue here

**Comment by wilfredktlr** [comment]
This is the same problem as I described in my issue (https://github.com/esphome/issues/issues/4606). The cause of the bug can be found under the `Additional information` section.
