### ISSUE TITLE
Column "Actions" not showing with button control

### ISSUE THREAD

**Issue by wilfredktlr** [esphome/issues#4606]
### The problem

When the only control you have is a button the `Actions` column does not show in the webserver GUI.

![ESP Home button problem](https://github.com/esphome/issues/assets/1142879/71fbf3c4-0e30-4819-8398-dee79501e3c2)

### Which version of ESPHome has the issue?

2023.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.6.2

### What platform are you using?

ESP8266

### Board

Wemos D1 mini v4

### Component causing the issue

https://oi.esphome.io/v2/www.js

### Additional information

The problem is caused by [this change](https://github.com/esphome/esphome-webserver/pull/29/commits/af61e52ff31d32d1d21a8d258eb495e09bf1c80d#diff-27af2b81eb9dfc2444092b9a50036bf8b127d3a57f3913bbc1f741f95b0d3955R61) because `this.control(entity)` does not return an array.

**Comment by wilfredktlr** [comment]
FYI. this problem is caused by this commit (https://github.com/esphome/esphome-webserver/pull/29/commits/af61e52ff31d32d1d21a8d258eb495e09bf1c80d).

**Comment by screek-workshop** [comment]
same problem here. 
i wonder why not make www.js to local inside esp32?

**Comment by nijsni** [comment]
I have the same problems. Before version 2023.6.0 I was able to use the buttons in actions and now I can't see actions anymore.

**Comment by nijsni** [comment]
My configuration 
  platform: ESP8266
  board: d1_mini

button:
  - platform: template
    name: "hybridepomp + 0,001"
    on_press:
      then:
        lambda: id(totalhybridepompusage) += 0.001;

 Home Assistant 2023.6.3 Supervisor 2023.06.2 Operating System 10.3 Frontend-versie: 20230608.0 - latest

**Comment by nijsni** [comment]
Sorry, Trip5.It's not working for me. I'm not that skilled in this area. I need to save a file somewhere on my raspberry but where do I get it from.
 INFO ESPHome 2023.6.2
INFO Reading configuration /config/esphome/watermeter.yaml...
INFO Detected timezone 'Europe/Amsterdam'
Failed config

web_server: [source /config/esphome/watermeter.yaml:38]
  port: 80
  ota: True
  include_internal: True
  
  Could not find file '/config/esphome/www/v2_www.js'. Please make sure it exists (full path: /config/esphome/www/v2_www.js).
  js_include: www/v2_www.js
  js_url: ''
  Can you help me further.

**Comment by trip5** [comment]
Yeah you need to download that file (view as raw), save it somewhere, rename it as 'v2_www.js' then copy it over to the appropriate folder on your Pi.  Login to your Pi using WinSCP or similar.  Find your esphome folder.  For you looks like /config/esphome.  Make a folder called 'www' and then copy the file there.

**Comment by nijsni** [comment]
Thanks, it works.
