### ISSUE TITLE
Pillow version > 9 not accepted

### ISSUE THREAD

**Issue by sysrun** [esphome/issues#4651]
### The problem

Tried to use a Font and installed pillow version 10.0.0

At compile esphome will fail with error  "Please update your pillow installation to at least 4.0.x. "

Problem ist this check in "components/font/__init__.py""
`if PIL.__version__[0] < "4":`

The version is 10.0.0

As only the first character is tested, the version is detected as 1

### Which version of ESPHome has the issue?

2023.6.3

### What type of installation are you using?

pip

### What platform are you using?

ESP32

**Comment by jklap** [comment]
Suggested solution:

components/font/__init__.py:
```
from packaging import version
```

Line 73:
```
    if version.parse(PIL.__version__) < version.parse("4.0.0"):
```
