### ISSUE TITLE
Sonoff Basic R2 unresponsive after upgrade

### ISSUE THREAD

**Issue by sheminasalam** [esphome/issues#4654]
### The problem

I tried to upgrade tof my sonoff basic R2 with the latest esphome version using ota today. The logs showed that the upload was complete but then device didn’t come online. The device looked fine but it didnt connect to wifi and the led was not turning on also. I thought it would have been an issue with update so I tried to flashing the firmware using my PC. But it seems my PC is also not able to connect to the device. I tried using esp flasher, tasmotizer and all but nothing worked. What could be the issue?

This happened a few months back also with another sonoff basic R2. Both these devices were working fine till the upgrade. I have now stopped upgrading my devices because of fear of them being stale like these two.

I hope some one can help me figure out whats happening.

### Which version of ESPHome has the issue?

2023.6.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.6.3

### What platform are you using?

ESP8266

### Board

SONOFF BASIC R2

**Comment by ssieb** [comment]
There wasn't any point in creating this issue.  As I told you on discord, software can't stop the serial access, so you need to figure that out.  Follow up on discord.
