### ISSUE TITLE
Contradiction in Logger Documentation

### ISSUE THREAD

**Issue by markus2330** [esphome/issues#4668]
### The problem

https://esphome.io/components/logger.html says both:

1. `By default, all logs with a severity higher than DEBUG will be shown`
2. `Any log message with a lower severity will not be shown. Defaults to DEBUG.`

which is contradicting: 1. would exclude logs of DEBUG, 2. would include them.

**Comment by RoboMagus** [comment]
I dont interpret this as contradicting, but `DEBUG` does indeed seem to be excluded from both ranges.
` > Debug` and ` < Debug`, for which one of them should be inclusive.
