### ISSUE TITLE
Error in documentation: Automations and Template -> global variables

### ISSUE THREAD

**Issue by hiperiondev** [esphome/issues#4692]
### The problem

in the example say:
           ESP_LOGD(TAG, "%s: %d", id(my_global_string), id(my_global_int));

but doesn't work.

must be:
        ESP_LOGD(TAG, "%s: %d", id(my_global_string).c_str(), id(my_global_int));

### Which version of ESPHome has the issue?

documentation

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

**Comment by nielsnl68** [comment]
Good that you spotted this issue.
Just a suggestion, did you know you can edit the page yourself and create a PR for that change.

**Comment by hiperiondev** [comment]
> Good that you spotted this issue. Just a suggestion, did you know you can edit the page yourself and create a PR for that change.

Yes. As soon as I have a little time, I will definitely do it.

**Comment by KevynWithaY** [comment]
Created a pull request for this with a correction. Hopefully I did that correctly.
https://github.com/esphome/esphome-docs/pull/3076

**Comment by hiperiondev** [comment]
Corrected
