### ISSUE TITLE
Pillow version check breaks on version >= 10

### ISSUE THREAD

**Issue by zueski** [esphome/issues#4708]
### The problem

Unable to run esphome when using fonts if Pillow >= 10 is installed

### Which version of ESPHome has the issue?

2023.6.5

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

Any

### Component causing the issue

font

### Anything in the logs that might be useful for us?

```txt
in `esphome/components/font/__init__.py`, in function `validate_pillow_installed`, it is only checking the first digit, which is now '1' for version 10.  It should check the whole __version__ value.
```

### Additional information

I updated to use this as my function locally to bypass the issue:

```python
def validate_pillow_installed(value):
    try:
        import PIL
    except ImportError as err:
        raise cv.Invalid(
            "Please install the pillow python package to use this feature. "
            "(pip install pillow)"
        ) from err

    if int(re.sub(r'^([0-9]+).*', "\\1", PIL.__version__)) < 4:
        raise cv.Invalid(
            "Please update your pillow installation to at least 4.0.x. "
            "(pip install -U pillow)"
        )

    return value
```

**Comment by ssieb** [comment]
Fixed by https://github.com/esphome/esphome/pull/5090 and https://github.com/esphome/esphome/pull/5094
