### ISSUE TITLE
2023.7.0 broke inheritance of animation

### ISSUE THREAD

**Issue by lubeda** [esphome/issues#4726]
### The problem

In my custom [component](https://github.com/lubeda/EspHoMaTriXv2) I use animation as base class for a derived class like shown:

```
class EHMTX_Icon : public animation::Animation
{
   public:
    EHMTX_Icon(const uint8_t *data_start, int width, int height, uint32_t animation_frame_count, esphome::image::ImageType type, std::string icon_name, bool revers, uint16_t frame_duration);
};
}
```
Before the update I did not need to define an animation component in my YAML to compile. Now it only works with a defined image and a defined animation component (see also https://github.com/esphome/issues/issues/4719). Which is at least some unnecessary overhead

### Which version of ESPHome has the issue?

2023.7.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

latest

### What platform are you using?

ESP8266

### Board

all boards

### Component causing the issue

https://github.com/lubeda/EspHoMaTriXv2

### Additional information

It started here https://github.com/esphome/esphome/pull/4967

**Comment by nielsnl68** [comment]
we are aware of this. please add an small `image` to your YAML file for now
duplicate of #4720
