### ISSUE TITLE
BMP180 - 'on_value_range:' not working

### ISSUE THREAD

**Issue by Coldness00** [esphome/issues#4733]
### The problem

Hello Dears,

I'm making my own Air quality sensor for my home and to do so I'm using an esp8266 d1_mini with 2 sensors:
scd4x for Temperature, humidity and CO2 and a BMP180 for atmospherique pressure.
From those sensors, I do 2 things
1. I check the value on HomeAssistant, everything is working perfecly on that side
2. I use 4 led strips WS2812 for each data as a gauge

With the sensor scd4x, it's working perfectly however, for the sensor BMP180 the light do not turn on (on pressure and temperaure)

To perform this:
1: use neopixelbus 
2: below sensor I do as such (just an exctract)
```
  - platform: bmp085
    i2c_id: bus_a
    address: 0x77
    temperature:
      name: "Temperature bmp"
    pressure:
      name: "Inside Pressure"
      id: bme_pressure
      accuracy_decimals: 0
      on_value_range:
      - below: 1010
        then:
          - light.addressable_set:
              id: Strip_Press
              range_from: 0
              range_to: 1
              red: 0%
              green: 0%
              blue: 0%
          - delay : 100ms
          - light.addressable_set:
              id: Strip_Press
              range_from: 0
              range_to: 0
              red: 0%
              green: 50%
              blue: 25%
```

The Strip_Press is working fine as I tested with the same esp on the humidty value with the same code principle
To trouble shoot I declared the strip in HASS and I can control it from there without issue.

Thank you in advance for you help

### Which version of ESPHome has the issue?

2023.7.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2023.7.3

### What platform are you using?

ESP8266

### Board

d1 wimi

### Component causing the issue

i2c/bmp180

### Anything in the logs that might be useful for us?

```txt
[13:11:53][D][bmp085.sensor:079]: Got Temperature=23.7 °C
[13:11:53][D][sensor:093]: 'Temperature bmp': Sending state 23.72064 °C with 1 decimals of accuracy
[13:11:53][D][bmp085.sensor:125]: Got Pressure=972.2 hPa
[13:11:53][D][sensor:093]: 'Inside Pressure': Sending state 972.22662 hPa with 0 decimals of accuracy
[13:11:54][D][scd4x:269]: ambient pressure compensation skipped - no change required
[13:11:54][D][sensor:093]: 'CO2': Sending state 607.00000 ppm with 0 decimals of accuracy
[13:11:54][D][sensor:093]: 'Temperature': Sending state 24.88945 °C with 1 decimals of accuracy
[13:11:54][D][sensor:093]: 'Humidity': Sending state 35.13489 % with 1 decimals of accuracy
```

**Comment by ssieb** [comment]
`on_value_range:` only triggers when the value moves from outside the range to inside it.  You should probably use `on_value:` and test the ranges yourself.
