### ISSUE TITLE
Fix bug in esphome/ESPAsyncWebServer

### ISSUE THREAD

**Issue by asjdf** [esphome/issues#4798]
### The problem

I am sorry that I made a mistake in esphome/ESPAsyncWebServer [#10](https://github.com/esphome/ESPAsyncWebServer/pull/10/files#diff-09cab7c8017f6e1b622bbeccebb83bbbd7191e272f10f4330b4f4a4137d875f8L105) last year.

There seems to be a [PR](https://github.com/esphome/ESPAsyncWebServer/pull/17) fix for that mistake, and it looks good to me.

Thanks the maintainer of this project and I'm looking forward to having someone to review this PR.

### Which version of ESPHome has the issue?

dependency

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

**Comment by ssieb** [comment]
It's fixed now.
