### ISSUE TITLE
ESPhome zeroconf error

### ISSUE THREAD

**Issue by Wuppie007** [esphome/issues#481]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.3
timezone | Europe/Amsterdam
version | 0.94.4
virtualenv | false

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8966 and Sonoff

**Affected component:**

https://www.home-assistant.io/docs/mqtt/discovery/

**Description of problem:**
After fixing issues References: [#24187](https://github.com/home-assistant/home-assistant/issues/24187) and [#24578](https://github.com/home-assistant/home-assistant/issues/24578). The error changed, but still there is something wrong. Now a multiple of links are displayed on the integrations page ESPHome, but when it push "configure" a wait screen appear but nothing happend.

If added a traceback, what is available.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
Mon Jun 24 2019 21:23:54 GMT+0200 (Midden-Europese zomertijd)
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 71, in async_init
    return await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 123, in _async_handle_step
    result = await getattr(flow, method)(user_input)  # type: Dict
  File "/usr/src/homeassistant/homeassistant/components/esphome/config_flow.py", line 105, in async_step_zeroconf
    if flow['context']['name'] == node_name:
KeyError: 'name'

```

**Additional information and things you've tried:**
Restart the esphome hassio addon

![image](https://user-images.githubusercontent.com/23653628/60046730-58442f80-96c8-11e9-931f-f44a30bbc007.png)

**Comment by OttoWinter** [comment]
Yep, known. Try with the latest HA beta version - that has it fixed. But as the next HA release will come out very soon, there's not going to be a patch release for this small issue.

**Comment by OttoWinter** [comment]
Fixed in recent HA versions
