### ISSUE TITLE
Device access with api to private ip of home assistant instead external duckdns hostname

### ISSUE THREAD

**Issue by Revenge242** [esphome/issues#4843]
### The problem

given that where I live the line often drops therefore the external ip is unreachable and therefore all devices continue to restart and are almost always offline. It would be useful to implement the possibility of using homeassistant's private ip instead of the external one (like xxx.yyy.duckdns.org) so they would always work. I haven't found any way to do it in your guides.
if i change the time to check the server (disabling rebot when to connection are lost for x minutes) when is blocked i need to restart manually so this is not a good idea 

Thank in advance
Best Regards
Fausto from italy

### Which version of ESPHome has the issue?

2023.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.8.4 and earlier

### What platform are you using?

ESP8266

### Board

esp-01s

### Component causing the issue

reboot until the internet line come back

### Example YAML snippet

```yaml
I have home assistant 192.168.1.195 but the api check  is being done using xxxx.yyy.duckdns.org end when fiber go down this host is unreachable. the solution will be done adding the possibility of use 192.168.1.195 alway functional in lan.
```

**Comment by ssieb** [comment]
The device does not connect to HA.  It's the other way around, so the DNS name of HA is irrelevant.

**Comment by Revenge242** [comment]
When EspHome flash the devices ( esp01) write into it ip address or name that is used to comunicate with esphome server (add-on in home assistant) through api  . Now this address or name is the cause of problem, where is specified that is the external address of home assistant and is possible to force 192.168.1.195 as my  internal address?

**Comment by ssieb** [comment]
As I said, it doesn't work that way.  The ESP doesn't have a name or IP address for HA.

**Comment by Revenge242** [comment]
Ok thanks but which is the trigger that fire reboot action after x minutes when the connection is lost? And how can it decide that the connection is lost when ONLY internet connection is down and the router work correctly in lan and dhcp?
I think very Much but I don’t know the interaction from esp end esphome

**Comment by ssieb** [comment]
The device knows when HA is connected to it.  I don't know how the internet connection is involved here, but you need to figure out how HA is connecting to the device.  If you need more help with this, then come ask on the esphome discord server.  It's not an esphome issue, so this isn't the right place.
