### ISSUE TITLE
Can't install firmware for libretiny on Raspberry 

### ISSUE THREAD

**Issue by hunhejj** [esphome/issues#4859]
### The problem

I created a configuration for libretiny and tried to compile it on a 64bit Raspberry. I got the following error:

> UnknownPackageError: Could not find the package with 'libretiny @ 1.3.0' requirements for your system 'linux_aarch64'

### Which version of ESPHome has the issue?

2023.9.0-dev20230906

### What type of installation are you using?

Docker

**Comment by hunhejj** [comment]
@kuba2k2

**Comment by kuba2k2** [comment]
Publishing to PlatformIO has been delayed for an unknown reason. Please use this for now:
```yaml
bk72xx:
  framework:
    version: dev
```

**Comment by hunhejj** [comment]
Sorry to hear that. Well I will stick to the `dev` version then. As a reference for others here‘s the related thread: https://community.platformio.org/t/libretiny-platform-version-publish-delay
