### ISSUE TITLE
sending BLE advertisement from esp32

### ISSUE THREAD

**Issue by geniusled** [esphome/issues#4867]
### The problem

Hello, i am trying to control some devices that work using BLE advertisements under manufacture specific data.
there is no pairing required. the devices to not transmit anything, they only receive ble advertisements to change its state.

i cant seem to find a way to use a esp32 with esphome to do this. everything within esphome and ble is centered around receiving.

example of what i am looking for:
- upon button press, transmit ble advertisement of manufacture specific packet type, with payload X (expect no response)
- upon button press, transmit ble advertisement of manufacture specific packet type, with payload y (expect no response)

does this exist within esphome?

### Which version of ESPHome has the issue?

2023.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.8.1

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

ble

**Comment by Papadoma** [comment]
I have the same need. The suggested solution [here ](https://community.home-assistant.io/t/example-on-setting-up-esp32-as-ble-server/400230/3)does not work anymore with the latest esphome version Can we please get an answer and not have the bot automatically close it? Thanks
