### ISSUE TITLE
SHT3x now enables heater by default

### ISSUE THREAD

**Issue by jkl1337** [esphome/issues#4886]
### The problem

PR #5161 seems to enable the sensor heater by default despite its title: `cv.Optional(CONF_HEATER_ENABLED, default=True): cv.boolean`, and later `if (!this->write_command(heater_enabled_ ? SHT3XD_COMMAND_HEATER_ENABLE : SHT3XD_COMMAND_HEATER_DISABLE)) {`

### Which version of ESPHome has the issue?

2023.10.0-dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Component causing the issue

sht3xd

### Additional information

This can be worked around by setting `heater_enabled: false`, but I don't see the need for a breaking change.

However there in general there is no way to make a piece of code that changes a setting where previously no forced setting code existed non-breaking to someone. However I think the heater off is the reasonable setting for the majority of users.

**Comment by jasonlaguidice** [comment]
I just updated to 2023.9 and with no other changes the temperature sensor in my AirGradient box using the same sensor reads 15 *F higher. This may be the cause for me too and I will test.

**Comment by jasonlaguidice** [comment]
Returning back reporting the same thing - manually setting `heater_enabled: false` corrects the problem and normal sensor operation is restored.

**Comment by alexruffell** [comment]
No wonder all my sensors were off!
