### ISSUE TITLE
After (trying) to update to 0.95, all my ESPhome devices do not integrate in HASSIO, missing 1 required positional argument: 'esphome_core_version'

### ISSUE THREAD

**Issue by Klagio** [esphome/issues#490]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
The issue template has not been filled out. Closing...
