### ISSUE TITLE
Dashboard no longer displays "Update Available"

### ISSUE THREAD

**Issue by 3ative** [esphome/issues#4912]
### The problem

Post ESPHome 2023.9.0 (Add-on) Dashboard no longer displays blue "Update Available" on devices. 

Yet, HA Settings Icon displays number of devices with updates though.

I.E.
![image](https://github.com/esphome/issues/assets/51385971/b083b25e-1bce-4093-826b-1543180d9a4d)

### Which version of ESPHome has the issue?

2023.9.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.9.3

### What platform are you using?

ESP8266

### Board

N/A

### Component causing the issue

N/A

### Anything in the logs that might be useful for us?

```txt
None
```

**Comment by 3ative** [comment]
Forgot to add:
Tried HA Restart and Supervisor (VM) Reboot

**Comment by robgough1970** [comment]
same here - looking at device log - shows version 2023.9.0 although devices have not been updated

**Comment by 3ative** [comment]
Additional... If it helps:
![image](https://github.com/esphome/issues/assets/51385971/0ec58812-001a-4668-9af7-213ae07ecfb6)

**Comment by DieMetRik** [comment]
Try to install again.

**Comment by KrX3D** [comment]
i got the same problem. i noticed that the /config/esphome/.esphome folder is missing

when i hit install on i.e. one of my esp32 this folder is not generated anymore

im not sure  if this was always the folder or if it changed:

Building **.pioenvs**/flexispot-e7/firmware.bin

**Comment by DieMetRik** [comment]
Folder move to add-on/data folder

**Comment by 3ative** [comment]
> Try to install again.

Tried that too... Made no difference

**Comment by 3ative** [comment]
> > Folder move to addon/data folder
> 
> via windows smb this folder is empty, also when i look at it with studio code server

Yes, it was listed as one of the "Breaking Changes" - It's a real pain to debug cpp files now.

**Comment by jesserockz** [comment]
Unfortunately I cannot automatically fix this for people that have already upgraded to 2023.9.0, but I will try to put out 2023.9.1 today that will migrate the json files used for the card information so people that skip 2023.9.0 wont have this issue.

**Comment by ssieb** [comment]
> It's a real pain to debug cpp files now.

The only cpp file that you don't already have is the generated `main.cpp`.  But really, if you're debugging you should be running esphome locally.  It's much easier.

**Comment by andreas-bulling** [comment]
> Unfortunately I cannot automatically fix this for people that have already upgraded to 2023.9.0, but I will try to put out 2023.9.1 today that will migrate the json files used for the card information so people that skip 2023.9.0 wont have this issue.

Would be good to at least have instructions for how to fix this for these people (I am one of them and I have 45+ ESPHome devices running)

**Comment by jesserockz** [comment]
If you have a recent HA core backup, you could pull the json files from there and put them into the right place. This could be back into the `/config/esphome/.esphome` folder which should then be moved into the `/data` folder when upgrading to 2023.9.1 later

**Comment by andreas-bulling** [comment]
And how do I copy the files from the backup to the hassio directory - samba?

**Comment by ssieb** [comment]
Yes, or any of the other file manager addons.

**Comment by 3ative** [comment]
Thanks @jesserockz, that's great. 🙏
Luckily I copied my .esphome folder before I upgraded. 😎

**Comment by andreas-bulling** [comment]
that's not great, this is a desaster. I also don't get why it doesn't create the files in /data apparently - or does it, i.e. I can just upgrade all devices and don't have to  upload the json files manually one by one?

**Comment by jesserockz** [comment]
@andreas-bulling yes you can just install/upgrade them and the json files will be regenerated again one-by-one

**Comment by jesserockz** [comment]
@andreas-bulling If you have 2023.9.0 already, it wont be looking at the .esphome directory, it will only look in the /data directory for the files

**Comment by KrX3D** [comment]
/addon 
/data

do not contain any .esphome folder...

![image](https://github.com/esphome/issues/assets/18599852/2f407a9a-1762-4ca5-ade2-4a9a939a1266)

**Comment by jesserockz** [comment]
`/data` is individual per each addon (the ssh addon has its own `/data` folder). 
You can only see the contents either from the host OS, or by exec into the esphome addon container.

**Comment by 3ative** [comment]
For those with back-ups (prior to 2023.9.0), wait for this update, copy back your JSONs and start the add-on.

https://github.com/esphome/esphome/pull/5441#issuecomment-1738537547

**Comment by andreas-bulling** [comment]
FYI - I had upgraded to 2023.9.0 already without saving the JSONs. `.esphome` was gone and no available updates were indicated in the web interface then as many others have reported.

I upgraded to 2023.9.1 this morning without copying over the JSONs manually before and now the update status is still shown correctly again.

**Comment by 3ative** [comment]
> FYI - I had upgraded to 2023.9.0 already without saving the JSONs. `.esphome` was gone and no available updates were indicated in the web interface then as many others have reported.
> 
> I upgraded to 2023.9.1 this morning without copying over the JSONs manually before and now the update status is still shown correctly again.

I noticed that too... I thought I comment, just in case.

**Comment by KrX3D** [comment]
> For those with back-ups (prior to 2023.9.0), wait for this update, copy back your JSONs and start the add-on.
> 
> [esphome/esphome#5441 (comment)](https://github.com/esphome/esphome/pull/5441#issuecomment-1738537547)

- update esphome
- stop esphome addon
- copy back .esphome folder from backup
- start esphome addon

that worked for me, now i see the UPDATE button again

**Comment by JackTalisker** [comment]
I upgraded my esphome (docker container) from 2023.8.3 to 2023.9.2 and my .esphome config directory seems to be unharmed in its old position "/home/pi/esphome:/config"
Starting the container I do not see the update button.
What can I do?
Thank you
