### ISSUE TITLE
ESPHome 2023.9.0 broke SPI (with st7789v display)

### ISSUE THREAD

**Issue by RC-Thoughts** [esphome/issues#4914]
### The problem

Have been happy user of ESP32-board with st7789v display, no issues. Now did an update to 2023.9.0 (from previous, I think it was 2023.8.3) and suddenly the display stays blank. I can see a few flickers on backlight but that's it.

I would think this is an SPI issue since using "interface: software" I can get the attached display to work, albeit really slow.:
[W][component:204]: Component st7789v.display took a long time for an operation (1.85 s).

Before update it was more functional with:
[W][component:204]: Component st7789v.display took a long time for an operation (0.27 s).

### Which version of ESPHome has the issue?

2023.9.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.9.3

### What platform are you using?

ESP32

### Board

az-delivery-devkit-v4

### Component causing the issue

SPI st7789v

### Example YAML snippet

```yaml
esp32:
  board: esp32dev # Also tried az-delivery-devkit-v4 same result
  framework:
    type: arduino
--
--
# Display
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  interface: software # This is only option that works, hardware, spi, spi1, spi2 do not

display:
  - platform: st7789v
    model: Custom
    height: 240
    width: 240
    offset_height: 0
    offset_width: 0
    rotation: 90
    eightbitcolor : yes
    #update_interval: 20ms
    backlight_pin: GPIO16
    cs_pin: GPIO25
    dc_pin: GPIO26
    reset_pin: GPIO27
    lambda: .....
```

**Comment by RC-Thoughts** [comment]
Just as a test, tried esp-idf to rule out framework, no difference. Hardware SPI seems to be broken.

**Comment by RC-Thoughts** [comment]
Just tested 2023.9.1, still broken.

**Comment by ssieb** [comment]
Can you get serial logs?

**Comment by DrBando** [comment]
I believe I have a related problem: my TTGO-T1 ESP32 board with integrated ST7789V TFT LCD is working, however, I can't change the backlight brightness anymore. It stays at 100% and is not changable. Other components with other display types do work, even the brightness properties.

**Comment by RC-Thoughts** [comment]
> Can you get serial logs?

This is from OTA and restart after that:
`[D][ota:151]: Starting OTA Update from 123.123.123.6...68.1.6): Connection closed
[V][ota:182]: OTA features is 0x01to ESPHome Logs 2023.9.1 (123.123.123.6)
[V][ota:202]: Auth: Nonce is 6b04820963b9c22a5ca83990f3b2b1e7e for an operation (0.27 s).
[V][ota:222]: Auth: CNonce is a611c697eff041ca9ee914d71767355es.
[V][ota:229]: Auth: Result is 381883e0e6b4ebdd009e0d3e9a70940e
[V][ota:237]: Auth: Response is 381883e0e6b4ebdd009e0d3e9a70940ecess=0, value=53.3)
[V][ota:265]: OTA size is 1012128 bytes
[239401][D][Updater.cpp:133] begin(): OTA Partition: app0
[V][ota:282]: Update: Binary MD5 is cf83af65e38629292d7defd60ad6a1b7
[D][ota:320]: OTA in progress: 0.1%
[D][ota:320]: OTA in progress: 11.7%
[D][ota:320]: OTA in progress: 23.5%
[D][ota:320]: OTA in progress: 33.5%
[D][ota:320]: OTA in progress: 45.8%
[D][ota:320]: OTA in progress: 58.7%
[D][ota:320]: OTA in progress: 71.6%
[D][ota:320]: OTA in progress: 84.6%
[D][ota:320]: OTA in progress: 98.7%
[I][ota:353]: OTA update finished!
[I][app:134]: Rebooting safely...
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[V][esp32.preferences:126]: sync: key: 233825507, len: 4
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[248624][V][WiFiGeneric.cpp:360] _arduino_event_cb(): STA Disconnected: SSID: SSIDname, BSSID: 00:00:00:00:00:00, Reason: 8
[248626][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 5 - STA_DISCONNECTED
[248628][V][WiFiGeneric.cpp:341] _arduino_event_cb(): STA Stopped
[248633][W][WiFiGeneric.cpp:950] _eventCallback(): Reason: 8 - ASSOC_LEAVE
[W][wifi_esp32:465]: Event: Disconnected ssid='SSIDname' bssid=00:00:00:00:00:00 reason='Association Leave'
[248666][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 3 - STA_STOP
[V][wifi_esp32:440]: Event: WiFi STAets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
[     6][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
[I][logger:268]: Log initialized
[C][ota:473]: There have been 0 suspected unsuccessful boot attempts.
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[V][esp32.preferences:126]: sync: key: 233825507, len: 4
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[V][app:030]: Sorting components by setup priority...
[D][spi:039]: Setting up SPI bus...
[C][st7789v:011]: Setting up SPI ST7789V...
[D][spi_device:354]: mode 0, data_rate 20000kHz
[C][wifi:038]: Setting up WiFi...
[C][wifi:051]: Starting WiFi...
[C][wifi:052]:   Local MAC: 00:00:00:00:00:00
[V][esp32.preferences:059]: nvs_get_blob('3570421264'): ESP_ERR_NVS_NOT_FOUND - the key might not be set yet
[V][wifi_esp32:039]: Enabling STA.
[   657][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 0 - WIFI_READY
[V][wifi_esp32:424]: Event: WiFi ready
[   752][V][WiFiGeneric.cpp:338] _arduino_event_cb(): STA Started
[   753][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 2 - STA_START
[V][wifi_esp32:435]: Event: WiFi STA start
[V][internal_temperature:029]: Raw temperature value: 204
[V][sensor:043]: 'Internal Temp': Received new state 95.555557
[D][sensor:094]: 'Internal Temp': Sending state 95.55556 °C with 1 decimals of accuracy
[W][component:204]: Component st7789v.display took a long time for an operation (0.27 s).
[W][component:205]: Components should block for at most 20-30ms.
[V][esp-idf:000]: E (3436) wifi:
[V][esp-idf:000]: AP has neither DSSS parameter nor HT Information, drop it
[V][esp-idf:000]:

[V][esp-idf:000]: E (3578) wifi:
[V][esp-idf:000]: AP has neither DSSS parameter nor HT Information, drop it
[V][esp-idf:000]:

[V][esp-idf:000]: E (3589) wifi:
[V][esp-idf:000]: AP has neither DSSS parameter nor HT Information, drop it
[V][esp-idf:000]:

[W][component:204]: Component st7789v.display took a long time for an operation (0.26 s).
[W][component:205]: Components should block for at most 20-30ms.
[  6878][V][WiFiGeneric.cpp:381] _arduino_event_cb(): SCAN Done: ID: 128, Status: 0, Results: 10
[  6878][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 1 - SCAN_DONE
[V][wifi_esp32:429]: Event: WiFi Scan Done status=0 number=10 scan_id=128
[D][wifi:443]: Found networks:
[I][wifi:487]: - 'SSIDname' (00:00:00:00:00:00) ?_?¦
[D][wifi:488]:     Channel: 1
[D][wifi:489]:     RSSI: -44 dB
[D][wifi:492]: - 'Fiddleriddlediddle' (3C:84:6A:94:D8:72) ?_?¦
[D][wifi:492]: - '' (42:84:6A:94:D8:72) ?_?¦
[D][wifi:492]: - 'Living Room TV.v,' (FA:8F:CA:99:CC:2C) ?_?¦
[D][wifi:492]: - 'TP-Link_C794' (AC:84:C6:18:C7:94) ?_?¦
[D][wifi:492]: - 'PPP' (2C:FD:A1:2D:A4:C8) ?_?¦
[D][wifi:492]: - 'Fiddleriddlediddle' (3C:84:6A:95:19:32) ?_?¦
[D][wifi:492]: - 'Lettiniittymä' (FC:34:97:70:CD:C0) ?_?¦
[D][wifi:492]: - '' (42:84:6A:95:19:32) ?_?¦
[D][wifi:492]: - '#Telia-D614E3' (22:B0:01:D6:24:E3) ?_?¦
[I][wifi:277]: WiFi Connecting to 'SSIDname'...
[V][wifi:279]: Connection Params:
[V][wifi:280]:   SSID: 'SSIDname'
[V][wifi:283]:   BSSID: 00:00:00:00:00:00
[V][wifi:303]:   Password: 'password'
[V][wifi:308]:   Channel: 1
[V][wifi:315]:   Manual IP: Static IP=123.123.123.60 Gateway=123.123.123.1 Subnet=255.255.255.0 DNS1=0.0.0.0 DNS2=0.0.0.0
[V][wifi:319]:   Hidden: NO
[  8918][V][WiFiGeneric.cpp:353] _arduino_event_cb(): STA Connected: SSID: SSIDname, BSSID: 00:00:00:00:00:00, Channel: 1, Auth: WPA2_PSK
[  8920][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 4 - STA_CONNECTED
[  8923][V][WiFiGeneric.cpp:367] _arduino_event_cb(): STA Got New IP:123.123.123.60
[V][wifi_esp32:449]: Event: Connected ssid='SSIDname' bssid=00:00:00:00:00:00 channel=1, authmode=WPA2 PSK
[  8955][D][WiFiGeneric.cpp:929] _eventCallback(): Arduino Event: 7 - STA_GOT_IP
[  8956][D][WiFiGeneric.cpp:991] _eventCallback(): STA IP: 123.123.123.60, MASK: 255.255.255.0, GW: 123.123.123.1
[V][wifi_esp32:503]: Event: Got IP static_ip=123.123.123.60 gateway=123.123.123.1
[C][ota:097]: Over-The-Air Updates:
[C][ota:098]:   Address: 123.123.123.60:3232
[C][ota:101]:   Using Password.
[C][api:025]: Setting up Home Assistant API server...
[I][app:062]: setup() finished successfully!
[I][app:102]: ESPHome version 2023.9.1 compiled on Sep 28 2023, 20:11:11
[C][wifi:546]: WiFi:
[C][wifi:382]:   Local MAC: 00:00:00:00:00:00
[C][wifi:383]:   SSID: 'SSIDname'
[C][wifi:384]:   IP Address: 123.123.123.60
[C][wifi:386]:   BSSID: 00:00:00:00:00:00
[C][wifi:387]:   Hostname: 'media-display'
[C][wifi:389]:   Signal strength: -43 dB ?_?¦
[V][wifi:391]:   Priority: 0.0
[C][wifi:393]:   Channel: 1
[C][wifi:394]:   Subnet: 255.255.255.0
[C][wifi:395]:   Gateway: 123.123.123.1
[C][wifi:396]:   DNS1: 0.0.0.0
[C][wifi:397]:   DNS2: 0.0.0.0
[C][logger:357]: Logger:
[C][logger:358]:   Level: VERBOSE
[C][logger:359]:   Log Baud Rate: 115200
[C][logger:361]:   Hardware UART: UART0
[C][spi:067]: SPI bus:
[C][spi:068]:   CLK Pin: GPIO18
[C][spi:069]:   SDI Pin:
[C][spi:070]:   SDO Pin: GPIO23
[C][spi:072]:   Using HW SPI: SPI
[C][internal_temperature:059]: Internal Temperature Sensor 'Internal Temp'
[C][internal_temperature:059]:   Device Class: 'temperature'
[C][internal_temperature:059]:   State Class: 'measurement'
[C][internal_temperature:059]:   Unit of Measurement: '°C'
[C][internal_temperature:059]:   Accuracy Decimals: 1
[C][st7789v:124]: SPI ST7789V
[C][st7789v:124]:   Rotations: 90 °
[C][st7789v:124]:   Dimensions: 240px x 240px
[C][st7789v:125]:   Model: CUSTOM
[C][st7789v:126]:   Height: 240
[C][st7789v:127]:   Width: 240
[C][st7789v:128]:   Height Offset: 0
[C][st7789v:129]:   Width Offset: 0
[C][st7789v:130]:   8-bit color mode: YES
[C][st7789v:131]:   CS Pin: GPIO25
[C][st7789v:132]:   DC Pin: GPIO26
[C][st7789v:133]:   Reset Pin: GPIO27
[C][st7789v:134]:   B/L Pin: GPIO16
[C][st7789v:135]:   Update Interval: 5.0s
[C][mdns:115]: mDNS:
[C][mdns:116]:   Hostname: media-display
[V][mdns:117]:   Services:
[V][mdns:119]:   - _esphomelib, _tcp, 6053
[V][mdns:121]:     TXT: version = 2023.9.1
[V][mdns:121]:     TXT: mac = 782184a008e0
[V][mdns:121]:     TXT: platform = ESP32
[V][mdns:121]:     TXT: board = esp32dev
[V][mdns:121]:     TXT: network = wifi
[V][mdns:121]:     TXT: api_encryption = Noise_NNpsk0_25519_ChaChaPoly_SHA256
[C][ota:097]: Over-The-Air Updates:
[C][ota:098]:   Address: 123.123.123.60:3232
[C][ota:101]:   Using Password.
[C][api:138]: API Server:
[C][api:139]:   Address: 123.123.123.60:6053
[C][api:141]:   Using noise encryption: YES
[W][component:204]: Component st7789v.display took a long time for an operation (0.27 s).
[W][component:205]: Components should block for at most 20-30ms.
[C][homeassistant.sensor:030]: Homeassistant Sensor 'volume'
[C][homeassistant.sensor:030]:   State Class: ''
[C][homeassistant.sensor:030]:   Unit of Measurement: ''
[C][homeassistant.sensor:030]:   Accuracy Decimals: 1
[V][homeassistant.sensor:030]:   Force Update: YES
[C][homeassistant.sensor:031]:   Entity ID: 'media_player.marantz_sr7015_2'
[C][homeassistant.sensor:033]:   Attribute: 'volume_level'
[C][homeassistant.sensor:030]: Homeassistant Sensor 'lights'
[C][homeassistant.sensor:030]:   State Class: ''
[C][homeassistant.sensor:030]:   Unit of Measurement: ''
[C][homeassistant.sensor:030]:   Accuracy Decimals: 1
[V][homeassistant.sensor:030]:   Force Update: YES
[C][homeassistant.sensor:031]:   Entity ID: 'light.cd_led'
[C][homeassistant.sensor:033]:   Attribute: 'brightness'
[C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'power'
[C][homeassistant.text_sensor:024]:   Entity ID: 'media_player.living_room'
[C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'sound'
[C][homeassistant.text_sensor:024]:   Entity ID: 'media_player.living_room'
[C][homeassistant.text_sensor:026]:   Attribute: 'sound_mode'
[C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'mute'
[C][homeassistant.text_sensor:024]:   Entity ID: 'media_player.marantz_sr7015_2'
[C][homeassistant.text_sensor:026]:   Attribute: 'is_volume_muted'
[C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'source'
[C][homeassistant.text_sensor:024]:   Entity ID: 'media_player.living_room'
[C][homeassistant.text_sensor:026]:   Attribute: 'source'
[C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'heos'
[C][homeassistant.text_sensor:024]:   Entity ID: 'media_player.marantz_sr7015_2'
[C][homeassistant.text_sensor:026]:   Attribute: 'source'
[D][api:102]: Accepted 123.123.123.6
[W][component:204]: Component api took a long time for an operation (0.05 s).
[W][component:205]: Components should block for at most 20-30ms.
[V][api.connection:1013]: Hello from client: 'Home Assistant 2023.9.3 (123.123.123.6)' | API Version 1.9
[D][api.connection:1031]: Home Assistant 2023.9.3 (123.123.123.6): Connected successfully
[D][homeassistant.sensor:022]: 'media_player.marantz_sr7015_2::volume_level': Got attribute state 0.42
[V][sensor:043]: 'volume': Received new state 0.420000
[D][sensor:094]: 'volume': Sending state 0.42000  with 1 decimals of accuracy
[D][homeassistant.sensor:022]: 'light.cd_led::brightness': Got attribute state 255.00
[V][sensor:043]: 'lights': Received new state 255.000000
[D][sensor:094]: 'lights': Sending state 255.00000  with 1 decimals of accuracy
[D][homeassistant.text_sensor:017]: 'media_player.living_room': Got state 'on'
[V][text_sensor:013]: 'power': Received new state on
[D][text_sensor:064]: 'power': Sending state 'on'
[D][homeassistant.text_sensor:015]: 'media_player.living_room::sound_mode': Got attribute state 'DOLBY DIGITAL'
[V][text_sensor:013]: 'sound': Received new state DOLBY DIGITAL
[D][text_sensor:064]: 'sound': Sending state 'DOLBY DIGITAL'
[D][homeassistant.text_sensor:015]: 'media_player.marantz_sr7015_2::is_volume_muted': Got attribute state 'off'
[V][text_sensor:013]: 'mute': Received new state off
[D][text_sensor:064]: 'mute': Sending state 'off'
[D][homeassistant.text_sensor:015]: 'media_player.living_room::source': Got attribute state 'Digibox'
[V][text_sensor:013]: 'source': Received new state Digibox
[D][text_sensor:064]: 'source': Sending state 'Digibox'
[D][homeassistant.text_sensor:015]: 'media_player.marantz_sr7015_2::source': Got attribute state 'Ysäri'
[V][text_sensor:013]: 'heos': Received new state Ysäri
[D][text_sensor:064]: 'heos': Sending state 'Ysäri'
[W][component:204]: Component st7789v.display took a long time for an operation (0.27 s).
[W][component:205]: Components should block for at most 20-30ms.
[D][api:102]: Accepted 123.123.123.6
[V][api.connection:1013]: Hello from client: 'ESPHome Logs 2023.9.1 (123.123.123.6)' | API Version 1.9
[D][api.connection:1031]: ESPHome Logs 2023.9.1 (123.123.123.6): Connected successfully
[I][app:102]: ESPHome version 2023.9.1 compiled on Sep 28 2023, 20:11:11
[C][wifi:546]: WiFi:
[C][wifi:382]:   Local MAC: 00:00:00:00:00:00
[C][wifi:383]:   SSID: 'SSIDname'
[C][wifi:384]:   IP Address: 123.123.123.60
[C][wifi:386]:   BSSID: 00:00:00:00:00:00
[C][wifi:387]:   Hostname: 'media-display'
[C][wifi:389]:   Signal strength: -43 dB ?_?¦
[V][wifi:391]:   Priority: 0.0
[C][wifi:393]:   Channel: 1
[C][wifi:394]:   Subnet: 255.255.255.0
[C][wifi:395]:   Gateway: 123.123.123.1
[C][wifi:396]:   DNS1: 0.0.0.0
[C][wifi:397]:   DNS2: 0.0.0.0
[C][logger:357]: Logger:
[C][logger:358]:   Level: VERBOSE
[C][logger:359]:   Log Baud Rate: 115200
[C][logger:361]:   Hardware UART: UART0
[C][spi:067]: SPI bus:
[C][spi:068]:   CLK Pin: GPIO18
[C][spi:069]:   SDI Pin:
[C][spi:070]:   SDO Pin: GPIO23
[C][spi:072]:   Using HW SPI: SPI
[C][internal_temperature:059]: Internal Temperature Sensor 'Internal Temp'
[C][internal_temperature:059]:   Device Class: 'temperature'
[C][internal_temperature:059]:   State Class: 'measurement'
[C][internal_temperature:059]:   Unit of Measurement: '°C'
[C][internal_temperature:059]:   Accuracy Decimals: 1
[C][st7789v:124]: SPI ST7789V
[C][st7789v:124]:   Rotations: 90 °
[C][st7789v:124]:   Dimensions: 240px x 240px
[C][st7789v:125]:   Model: CUSTOM
[C][st7789v:126]:   Height: 240
[C][st7789v:127]:   Width: 240
[C][st7789v:128]:   Height Offset: 0
[C][st7789v:129]:   Width Offset: 0
[C][st7789v:130]:   8-bit color mode: YES
[C][st7789v:131]:   CS Pin: GPIO25
[C][st7789v:132]:   DC Pin: GPIO26
[C][st7789v:133]:   Reset Pin: GPIO27
[C][st7789v:134]:   B/L Pin: GPIO16
[C][st7789v:135]:   Update Interval: 5.0s
[C][mdns:115]: mDNS:
[C][mdns:116]:   Hostname: media-display
[V][mdns:117]:   Services:
[V][mdns:119]:   - _esphomelib, _tcp, 6053
[V][mdns:121]:     TXT: version = 2023.9.1
[V][mdns:121]:     TXT: mac = 782184a008e0
[V][mdns:121]:     TXT: platform = ESP32
[V][mdns:121]:     TXT: board = esp32dev
[V][mdns:121]:     TXT: network = wifi
[V][mdns:121]:     TXT: api_encryption = Noise_NNpsk0_25519_ChaChaPoly_SHA256
[C][ota:097]: Over-The-Air Updates:
[C][ota:098]:   Address: 123.123.123.60:3232
[C][ota:101]:   Using Password.
[C][api:138]: API Server:
[C][api:139]:   Address: 123.123.123.60:6053
[C][api:141]:   Using noise encryption: YES
[C][homeassistant.sensor:030]: Homeassistant Sensor 'volume'
[C][homeassistant.sensor:030]:   State Class: ''
[C][homeassistant.sensor:030]:   Unit of Measurement: ''
[C][homeassistant.sensor:030]:   Accuracy Decimals: 1
[V][homeassistant.sensor:030]:   Force Update: YES
[C][homeassistant.sensor:031]:   Entity ID: 'media_player.marantz_sr7015_2'
[C][homeassistant.sensor:033]:   Attribute: 'volume_level'
[C][homeassistant.sensor:030]: Homeassistant Sensor 'lights'
[C][homeassistant.sensor:030]:   State Class: ''
[C][homeassistant.sensor:030]:   Unit of Measurement: ''
[C][homeassistant.sensor:030]:   Accuracy Decimals: 1
[V][homeassistant.sensor:030]:   Force Update: YES
[C][homeassistant.sensor:031]:   Entity ID: 'light.cd_led'
[C][homeassistant.sensor:033]:   Attribute: 'brightness'
[C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'power'
[C][homeassistant.text_sensor:024]:   Entity ID: 'media_player.living_room'
[C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'sound'
[C][homeassistant.text_sensor:024]:   Entity ID: 'media_player.living_room'
[C][homeassistant.text_sensor:026]:   Attribute: 'sound_mode'
[C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'mute'
[C][homeassistant.text_sensor:024]:   Entity ID: 'media_player.marantz_sr7015_2'
[C][homeassistant.text_sensor:026]:   Attribute: 'is_volume_muted'
[C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'source'
[C][homeassistant.text_sensor:024]:   Entity ID: 'media_player.living_room'
[C][homeassistant.text_sensor:026]:   Attribute: 'source'
[C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'heos'
[C][homeassistant.text_sensor:024]:   Entity ID: 'media_player.marantz_sr7015_2'
[C][homeassistant.text_sensor:026]:   Attribute: 'source'
[W][component:204]: Component st7789v.display took a long time for an operation (0.27 s).
[W][component:205]: Components should block for at most 20-30ms.
`

**Comment by RC-Thoughts** [comment]
Unfortunately still broken in 2023.9.2, only "interface: software" works, slow as watching paint dry.

**Comment by clydebarrow** [comment]
Just saw this issue - will check it tomorrow. I have an st7789v display to test on.

**Comment by clydebarrow** [comment]
Tested with my st7789v display - no problem. There are a few possibilities, I think it's less likely to be an SPI problem, more likely to be related to changes to the st7789v driver. These changes were tested on several boards, but one possibility is that the data rate was changed from 10MHz to 20MHz. The chip is specified at the higher rate, but may fail depending on the electrical characteristics of the connection.

Currently the data rate is not configurable for the st7789v so I have raised a PR to test this. Add this to your yaml:

```
external_components:
  source: github://pr#5466
  components: [ spi, st7789v ]
```

And add `data_rate` to your display config:

```
display:
  - platform: st7789v
    data_rate: 10MHz
```

Test and report back.

**Comment by RC-Thoughts** [comment]
Using the "external_components" gives no issues, using "data_rate: 10MHz" is not allowed.

**Comment by clydebarrow** [comment]
That's strange. What was the exact error message? Also check you have the right PR number. - I originally posted the wrong one and later edited it. You could try this instead:

```
external_components:
  source: github://clydebarrow/esphome@st7789v
  components: [ spi, st7789v ]
```

**Comment by RC-Thoughts** [comment]
This is getting interesting. I thought that maybe the "data_rate" is not accepted since driver is not loaded correctly. So I did a clean build and then the "data_rate" was accepted. However, unless I do "interface: software" the display stays black.

Current yaml:
`# Display
external_components:
  source: github://clydebarrow/esphome@st7789v
  components: [ spi, st7789v ]

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  #interface: software

display:
  - platform: st7789v
    data_rate: 10MHz
    model: Custom
    height: 240
    width: 240
    offset_height: 0
    offset_width: 0
    rotation: 90
    eightbitcolor : yes
    #update_interval: 200ms
    backlight_pin: GPIO16
    cs_pin: GPIO25
    dc_pin: GPIO26
    reset_pin: GPIO27
    lambda: |-`

**Comment by clydebarrow** [comment]
Is the backlight on? I.e. can you see the LED behind the display? And in the log do you see messages about the display taking a long time? And which display exactly are you using? I assume it's not built into the board.

You could also try a much lower data_rate, like say 1MHz. Will be slow of course but if that still fails it should rule out data rate as an issue. The software SPI runs at around 200kHz.

**Comment by RC-Thoughts** [comment]
Yes, I can clearly see the backlight so there is signs of life. I have no idea what the exact display it is, it has st7789v chip and have been working as such up to 2023.9.0. 

I have tried various speeds from 1MHz and up, nothing with hw-spi.

And yes, these exist:
[14:59:50][W][component:204]: Component st7789v.display took a long time for an operation (1.14 s).
[14:59:50][W][component:205]: Components should block for at most 20-30ms.

**Comment by clydebarrow** [comment]
Ok, so next step is to isolate the st7789v and spi changes. I'll make a couple of branches for you to try, one with the old display driver and new SPI, and one the reverse. Will be tomorrow though, it's late here.

**Comment by RC-Thoughts** [comment]
No worries, your help is highly appreciated!

**Comment by RC-Thoughts** [comment]
Updated to 2023.9.3, no change.

**Comment by clydebarrow** [comment]
Ok, I've updated the PR - you will probably want to do clean _and_ delete the `.esphome/external_components` folder to make sure you get the latest version.

With the change you can now add a line like `spi_mode: MODE3` to the display config. There are four possible modes (0-4) and on my display only MODE0 works. I know there are other boards that work with both MODE0 and MODE3. So I suggest trying the different modes (start with 3) and see if it has any effect.

The ST7789V datasheet clearly shows it as expecting mode 0, but I wonder if there are other "st7789v-like" chips that might behave differently. The mode was changed from 0 to 3 in the recent update.

**Comment by clydebarrow** [comment]
And best add a `refresh` line to the external components config:

```
external_components:
  source: github://clydebarrow/esphome@st7789v
  components: [ spi, st7789v ]
  refresh: always
```

**Comment by RC-Thoughts** [comment]
I did changes one at a time with clean build every time, the adding of "spi_mode: MODE3" is the key, that made spi work with default "interface: hardware" and display speed is now back to normal.

**Comment by clydebarrow** [comment]
Great! I have found mention elsewhere on the net that some st7789v's require mode 3, so it's just going to have to be a user-configured option.

**Comment by DrBando** [comment]
I'm not sure if this is related, but seeing my post above, I'm still not able to change the brightness of the backlight, while it is working with other display types and was working with st7789v before 2023.9.0.
I've tried the possible solution with spi_mode: MODE3, where I can confirm that MODE0 and 3 are showing content in the display, while 1 and 2 are not working, however, display brightness can't be changed in either 0 or 3. Should I open a new issue?

**Comment by kbx81** [comment]
@DrBando the issue with the backlight is fixed by https://github.com/esphome/esphome/pull/5476 and it will either be in the next patch release or next major release. No need to open a new issue at this point.

**Comment by besanur** [comment]
same problem here with the Adafruit Library and the example code it is working. But in esp-home not anymore since the update. I have this display https://de.aliexpress.com/item/1005005039702168.html.  Until recently it worked great in esphome.

```
esp32:
  board: lolin_s2_mini
  variant: ESP32S2
  framework:
    type: arduino

# Enable logging
logger:

time:
  - platform: homeassistant
    id: esptime

### Display
font: 
  - file: "fonts/Roboto-Regular.ttf"
    id: font_clock
    size: 34
    glyphs: ':0123456789'

spi:
  clk_pin: GPIO7 # SCL
  mosi_pin: GPIO11 # SDA

display:
  - platform: st7789v
    id: arbeitstisch_display
    model: Adafruit RR 280x240
    backlight_pin: GPIO39 # BLK
    cs_pin: GPIO10 # CS
    dc_pin: GPIO33 # DC
    update_interval: 30s
    reset_pin: GPIO15 # RES
    lambda: |-
      it.printf(it.get_width()/2, 0, id(font_clock), TextAlign::TOP_CENTER, id(esptime).now().strftime("%H:%M").c_str());
```

**Comment by besanur** [comment]
> And best add a `refresh` line to the external components config:
> 
> ```
> external_components:
>   source: github://clydebarrow/esphome@st7789v
>   components: [ spi, st7789v ]
>   refresh: always
> ```

with this and spi_mode: 'mode3' it works
