### ISSUE TITLE
Black console screen after clicking install, build or validate when using the add-on

### ISSUE THREAD

**Issue by felipecrs** [esphome/issues#4989]
### The problem

Apparently my issue is the same as:

- https://community.home-assistant.io/t/esphome-web-ui-black-screen-for-validate-install-and-log/337578
- https://github.com/esphome/issues/issues/1549

Note that my HA URL looks like:

```
https://something.duckdns.org:8123
```

https://github.com/esphome/issues/assets/29582865/345f5d19-6249-438b-9aee-7fd9599f0ea3

### Which version of ESPHome has the issue?

All

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

All

### What platform are you using?

ESP8266

### Anything in the logs that might be useful for us?

```txt
I found this in my browser console logs, but it is probably unrelated:


ap0DqpJ5GRCNt5egF2uJkiAI07yqu0ukO5IC2BjatnI/:1 The resource https://something.duckdns.org:8123/api/hassio_ingress/ap0DqpJ5GRCNt5egF2uJkiAI07yqu0ukO5IC2BjatnI/static/fonts/material-icons/MaterialIcons-Regular.woff2?hash=570eb838 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

In ESPHome add-on logs I find some 403:

```
2023-10-16 09:44:28,359 INFO 304 GET /devices (0.0.0.0) 0.67ms
2023-10-16 09:44:30,186 INFO 200 GET /devices (0.0.0.0) 0.79ms
2023-10-16 09:44:31,527 INFO 200 GET /static/js/esphome/c.f574a6e6.js (0.0.0.0) 4.14ms
2023-10-16 09:44:31,561 WARNING 403 GET /validate (0.0.0.0) 0.75ms
2023-10-16 09:44:33,365 INFO 304 GET /devices (0.0.0.0) 0.71ms
2023-10-16 09:44:38,377 INFO 304 GET /devices (0.0.0.0) 1.59ms
2023-10-16 09:44:44,022 INFO 304 GET /devices (0.0.0.0) 0.85ms
2023-10-16 09:44:50,016 INFO 304 GET /devices (0.0.0.0) 0.60ms
2023-10-16 09:44:56,017 INFO 304 GET /devices (0.0.0.0) 0.89ms
2023-10-16 09:45:01,018 INFO 304 GET /devices (0.0.0.0) 0.95ms
2023-10-16 09:45:06,020 INFO 304 GET /devices (0.0.0.0) 1.31ms
2023-10-16 09:45:08,283 WARNING 403 GET /validate (0.0.0.0) 0.91ms
2023-10-16 09:45:11,025 INFO 304 GET /devices (0.0.0.0) 0.75ms
2023-10-16 09:45:11,077 INFO 304 GET /info?configuration=botao-do-interfone.yaml (0.0.0.0) 1.22ms
2023-10-16 09:45:12,291 WARNING 403 GET /run (0.0.0.0) 1.11ms
2023-10-16 09:45:16,037 INFO 304 GET /devices (0.0.0.0) 1.11ms
```
```


### Additional information

When I try to apply an update to the device using the update entity, it works just fine.

**Comment by jesserockz** [comment]
I believe this happens when websockets are not correctly set up. 
You should be using a **reverse proxy** doing your SSL termination, not setting up SSL in HA directly and then accessing that on port 8123.

**Comment by felipecrs** [comment]
That's exactly what I have: NGINX (https://github.com/home-assistant/addons/tree/master/nginx_proxy) on port 8123. HA itself is in another port.

**Comment by jesserockz** [comment]
Ah, I just assumed you were not as generally if using a reverse proxy you would be using the standard 443 port for https. 

But anyway. I have heard of other people also having the same issue with that addon although it looks to be configured correctly. 

I personally use HA cloud, or Caddy for direct access to my house and it all works as expected.

If you access HA directly not through the proxy does it work?

**Comment by felipecrs** [comment]
> If you access HA directly not through the proxy does it work?

It works! When accessing HA directly through the http (not https) port, then no problems:

![image](https://github.com/esphome/issues/assets/29582865/1de76ea0-e02a-4900-b55b-a5251c810faa)

**Comment by potens1** [comment]
Same problem for me, but unable to correct it. Everything seems too work but esphome. 
I tried to add the configuration found [here](https://community.home-assistant.io/t/esphome-web-ui-black-screen-for-validate-install-and-log/337578/16?u=potens) 
```
location /api/hassio_ingress {
    proxy_pass http://homeassistant.local.hass.io:8123;
    proxy_set_header Host $http_host;
    proxy_redirect http:// https://;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header X-Forwarded-Host $http_host;
}
```
(header set to $http_host instead of $host), but then it nginx output "400 Bad Request The plain HTTP request was sent to HTTPS port" for all the addons.
Is the clue in the linked thread right ? (ESPHome requiring Origin and Host to match).

**Comment by felipecrs** [comment]
Issue fixed by https://github.com/home-assistant/addons/pull/3356
