### ISSUE TITLE
Hass.io missing Docker aarch64 image

### ISSUE THREAD

**Issue by stefball** [esphome/issues#5]
Trying to install extension from hassio the following error appears:
```
18-07-09 15:22:33 INFO (SyncWorker_19) [hassio.docker.interface] Pull image ottowinter/esphomeyaml-hassio-aarch64 tag 1.7.0.
18-07-09 15:22:35 ERROR (SyncWorker_19) [hassio.docker.interface] Can't install ottowinter/esphomeyaml-hassio-aarch64:1.7.0 -> 404 Client Error: Not Found ("manifest for ottowinter/esphomeyaml-hassio-aarch64:1.7.0 not found").
```
Verifying docker registry I found: 

No tags for this repository. :)

![docker-esp](https://user-images.githubusercontent.com/14624722/42460027-35dfe522-839d-11e8-8a01-0d6ac3c6f8c0.png)

**Comment by apeeters** [comment]
This change in Hass.io might resolve the issue: [Support armv7 and allow support of multible arch types per CPU](https://github.com/home-assistant/hassio/pull/892): raspberrypi3-64 now supports aarch64 and armhf containers.

**Comment by OttoWinter** [comment]
This has been fixed, aarch64 images are now available

**Comment by OvCa77** [comment]
Still error during compilation on aarch64, need to reopen till the platformio team supports this platform
