### ISSUE TITLE
sensor.in_range syntax error with float script parameter

### ISSUE THREAD

**Issue by szupi-ipuzs** [esphome/issues#5010]
### The problem

For my lamp I have defined an (ambient light) sensor on adc platform as such:
```
sensor:
  - platform: adc
    id: ambient
    name: Ambient
    unit_of_measurement: "V"
    state_class: "measurement"
    update_interval: 5s
    pin: P23
```

I also wanted to create a script that checks if the above sensor's value is above a specified threshold. I decided to use "sensor.in_range", as such
```
script:
  - id: onAfterPIR
    parameters:
      ambient_pwm_above: float
    then:
      - if:
          condition:
            - sensor.in_range:
                id: ambient
                above: !lambda return ambient_pwm_above;
            - light.is_off: light_cwww
          then:
            - lambda: !lambda |-
                      id(auto_running_flag)=true;
                      id(light_cwww).turn_on();
```

However, **the above does not compile** and the error is reported in the "above" part, the compilers simply says "**expected float**". The value parameter passed to script.execute is 3.650, so I believe it is a valid float?

I worked around this by changing the "sensor.in_range" part to a lambda that does the same, and **this does compile correctly**:

```
script:
  - id: onAfterPIR
    parameters:
      ambient_pwm_above: float
    then:
      - if:
          condition:
            - lambda: !lambda |-
                      return id(ambient).state > ambient_pwm_above;
            - light.is_off: light_cwww
          then:
            - lambda: !lambda |-
                      id(auto_running_flag)=true;
                      id(light_cwww).turn_on();
```

So, what was the "expected float" error about?

### Which version of ESPHome has the issue?

2023.10.1

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

wb3s

**Comment by ssieb** [comment]
That's the yaml parser complaining.  That value is not templatable, so it's telling you that you need to give it a float constant.
