### ISSUE TITLE
Cannot connect to a wifi network configured with an hidden ssid

### ISSUE THREAD

**Issue by StephRagazzi** [esphome/issues#5022]
### The problem

From an ESPMuse system, I can't connect to a wifi network which uses an hidden ssid 

### Which version of ESPHome has the issue?

2023.10.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

RASPIAUDIO / ESP Muse

**Comment by ssieb** [comment]
Github issues aren't for support requests.  You didn't even include your yaml.  Please come ask on the esphome discord server.
