### ISSUE TITLE
substitutions of the entity_id in the homeassistant text sensor does not work

### ISSUE THREAD

**Issue by ThomasFTL** [esphome/issues#5047]
### The problem

I have a project in ESPhome that should be installed on several ESPs.
The only differences are name, IP and an entity_ip of a text sensor.
And it is exactly this sensor that causes problems. I can't set the entity_id using substitutions.

substitution:
   myEntityID: "timeX"

text_sensor:
   - platform: homeassistant
     id: "timex"
     entity_id: input_text.$(myEntityID)

==> Invalid Character for entity_id

substitution:
   myEntityID: "input_text.timeX"

text_sensor:
   - platform: homeassistant
     id: "timex"
     entity_id: (myEntityID)

==> Entity ID must have exactly one dot in it.

You can make substitutions everywhere using substitutes. Why not here?

### Which version of ESPHome has the issue?

2023.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.5

### What platform are you using?

ESP8266

### Board

ESP8266 12f

### Component causing the issue

homeassistant text sensor

**Comment by ssieb** [comment]
Substitutions are `$myEntityID` or `${myEntityID}`, so both of your cases are invalid.
