### ISSUE TITLE
'Device Type' dropdown list is sticking out of the frame of the wizard.

### ISSUE THREAD

**Issue by W00D00** [esphome/issues#506]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
HASS.IO 167
Raspberry Pi3B + SSD boot + Docker
HA 0.95.4
Host system Raspbian GNU/Linux 9 (stretch)

**ESP (ESP32/ESP8266, Board/Sonoff):**
NodeMCU v2 ESP8266

**Affected component:**
-

**Description of problem:**
When I try to create a new configuration with the wizard, I want to set the 'Device Type' from the dropdown list, the list appairs but the list is sticking out of the frame of the wizard. I can see the top items of the list and I can select item very tricky way.

**Problem-relevant YAML-configuration entries:**
-

**Logs (if applicable):**
-

**Additional information and things you've tried:**
A screenshot is attached about the problem.
![issue](https://user-images.githubusercontent.com/1571719/60684910-94357c80-9ea0-11e9-87bc-cce4cd5ce8ca.png)

**Comment by OttoWinter** [comment]
It's a problem with the CSS framework used (materializecss) and not easy to fix.

Please just use the scroll wheel (works great for me).

**Comment by W00D00** [comment]
Thanks for your reply. However, I am not able to scroll up with the scroll wheel. I want to select the Nodemcu list item, which is not shown. The tricky way is that I select a shown list item and use the up arrow key to move the selection up but, the list is not moving and the selection is not shown and I do it at random.
