### ISSUE TITLE
PlatformIO build_path - unknown option

### ISSUE THREAD

**Issue by special-k-uk** [esphome/issues#5061]
### The problem

Since the removal of the `.esphome` directory in 2023.9.0 https://esphome.io/changelog/2023.9.0.html#home-assistant-add-on I am unable to include a custom board definition.

Trying to use the Platform IO 'build_path' option as documented here https://esphome.io/components/esphome.html results in the following compilation error

```
Warning! Ignore unknown configuration option `build_path` in section [env:test]
```

This option is required to use a non-native supported board - see https://github.com/esphome/feature-requests/issues/1960#issuecomment-1426215068

### Which version of ESPHome has the issue?

2023.10.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.10.1

### What platform are you using?

ESP32

### Board

lilygo-t5-47-plus

### Component causing the issue

PlatformIO

### Example YAML snippet

```yaml
esphome:
  name: test
  friendly_name: test
  platformio_options:
    build_path: addons/esphome_build_data
    board_dir: boards
    #include https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/blob/master/platformio/boards/lilygo-t5-47-plus.json as custom board
    board: lilygo-t5-47-plus
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.10.4
INFO Reading configuration /config/esphome/test.yaml...
WARNING GPIO45 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Detected timezone 'Europe/London'
INFO Detected timezone 'Europe/London'
INFO Generating C++ source...
INFO Compiling app...
Warning! Ignore unknown configuration option `build_path` in section [env:test]
Processing test (board: lilygo-t5-47-plus; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
UnknownBoard: Unknown board ID 'lilygo-t5-47-plus'
```

**Comment by nickolay** [comment]
`build_path` should be under `esphome`, not under `esphome.platformio_options`.  This works for me with esphome 2023.12.5 (CLI)
