### ISSUE TITLE
Deep sleep component not working in bk72xx board. Does anyone know how I can add it?

### ISSUE THREAD

**Issue by yaminahacs** [esphome/issues#5062]
### The problem

Deep sleep component not working in bk72xx board. Does anyone know how I can add it? See my yaml below.

substitutions:
  name: door-sensor-2
  friendly_name: Door Sensor 2
  static_ip: 10.0.0.44

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

          
bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:
  level: VERBOSE

web_server:

captive_portal:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${static_ip}
    gateway: 10.0.0.1
    subnet: 255.255.255.0
    dns1: 209.203.10.208
    dns2: 196.22.218.248

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "${friendly_name}"
    password: "!secret ap_password"

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

mqtt:
  broker: !secret my_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

sun:
  latitude: -29.077101°
  longitude: 26.238661°

time:
  - platform: sntp  
    timezone: SAST-2

binary_sensor:
# hardware button  
  - platform: gpio
    id: on_off_button
    pin:
      number: P24
      inverted: true
      mode: INPUT_PULLUP

  - platform: gpio
    pin:
      number: P8
      mode:
        input: true
        pullup: false
      inverted: false
    name: "${friendly_name}"
    device_class: door
    id: door_1
    on_state:
      then:
        - light.turn_on:  # blink the status LED once when opening/closing the door
            id: led
            flash_length: 500ms
    publish_initial_state: true
    on_press:
      then:
        - mqtt.publish:
            topic: doorsensor1/state
            payload: "Door Open"
            qos: 1
    on_release:
      then:
        - mqtt.publish:
            topic: doorsensor1/state
            payload: "Door Closed"
            qos: 1

sensor:
  - platform: adc
    pin: ADC3
    name: "${friendly_name} battery"
    update_interval: 90s
    raw: true
    unit_of_measurement: "%"
    accuracy_decimals: 2
    filters:
      - multiply: 100

light:
  - platform: status_led  # use the onboard LED as status indicator
    id: led
    pin: P26
    internal: true

switch:
  - platform: restart
    name: "${friendly_name} Restart"  

deep_sleep:
  run_duration: 60s
  sleep_duration: 60min
  id: deep_sleep_1

### Which version of ESPHome has the issue?

2023.10.5

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

BK72XX

**Comment by ssieb** [comment]
This is not a bug.  You can file a feature request at https://github.com/esphome/feature-requests/issues/ if you want.
