### ISSUE TITLE
IR Remote climate fails to compile

### ISSUE THREAD

**Issue by yaminahacs** [esphome/issues#5063]
### The problem

IRremote climate is not compiling. Any assistance will be appreciated. Check log error bellow:

INFO ESPHome 2023.10.5
INFO Reading configuration /config/ir-remote.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing ir-remote (board: generic-bk7231n-qfn32-tuya; framework: arduino; platform: libretiny @ 1.4.1)
--------------------------------------------------------------------------------
Warning! Non-Git installations are NOT SUPPORTED.
HARDWARE: BK7231N 120MHz, 256KB RAM, 1.03MB Flash
 - framework-arduino-api @ 2022.8.24+sha.237b10a 
 - framework-beken-bdk @ 0.0.0+v2021.06.07.sha.6491b8c 
 - library-flashdb @ 1.2.0+sha.d5c892f 
 - library-freertos @ 9.0.0+sha.95cc959 
 - library-freertos-port @ 2023.5.23+sha.a917d93 
 - library-lwip @ 2.1.3-bdk+sha.4ee4d34 
 - library-printf @ 6.1.0+sha.28a79bd 
 - library-uf2ota @ 5.0.0+sha.f955412 
PLATFORM VERSIONS:
 - libretiny @ 1.4.1
 - ltchiptool @ 4.7.0
CUSTOM OPTIONS:
 - fw_name = esphome
 - fw_version = 2023.10.5
Dependency Graph
|-- AsyncTCP-esphome @ 2.0.1
|-- IRremoteESP8266 @ 2.8.6
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 1.1.0
|-- ArduinoJson @ 6.18.5
Archiving .pioenvs/ir-remote/liba5c/libAsyncTCP-esphome.a
Compiling .pioenvs/ir-remote/lib84c/IRremoteESP8266/IRrecv.cpp.o
Compiling .pioenvs/ir-remote/lib84c/IRremoteESP8266/IRsend.cpp.o
Compiling .pioenvs/ir-remote/lib84c/IRremoteESP8266/IRtext.cpp.o
Compiling .pioenvs/ir-remote/lib84c/IRremoteESP8266/IRtimer.cpp.o
/piolibs/IRremoteESP8266/src/IRrecv.cpp:140:7: error: '_IRrecv' has not been declared
  140 | using _IRrecv::timer;
      |       ^~~~~~~
/piolibs/IRremoteESP8266/src/IRrecv.cpp:174:3: error: expected unqualified-id before 'if'
  174 |   if (params.rawlen) params.rcvstate = kStopState;
      |   ^~
/piolibs/IRremoteESP8266/src/IRrecv.cpp:181:1: error: expected declaration before '}' token
  181 | }
      | ^
/piolibs/IRremoteESP8266/src/IRrecv.cpp:184:27: error: expected initializer before 'gpio_intr'
  184 | static void USE_IRAM_ATTR gpio_intr() {
      |                           ^~~~~~~~~
/piolibs/IRremoteESP8266/src/IRrecv.cpp: In member function 'void IRrecv::enableIRIn(bool)':
/piolibs/IRremoteESP8266/src/IRrecv.cpp:389:35: error: 'gpio_intr' was not declared in this scope
  389 |   attachInterrupt(params.recvpin, gpio_intr, CHANGE);
      |                                   ^~~~~~~~~
*** [.pioenvs/ir-remote/lib84c/IRremoteESP8266/IRrecv.cpp.o] Error 1
========================== [FAILED] Took 4.33 seconds ==========================

### Which version of ESPHome has the issue?

2023.10.5

### What type of installation are you using?

Docker

### What platform are you using?

BK72XX

**Comment by ssieb** [comment]
This is not an esphome issue because you're using a custom component and external libraries.
The [discussion](https://github.com/esphome/esphome/discussions/5650) you created was a valid place or you could ask on discord or one of the forums.
