### ISSUE TITLE
https://esphome.io/components/esphome.html is not referenced in the ESP documentation home page

### ISSUE THREAD

**Issue by erapade** [esphome/issues#5074]
### The problem

At https://esphome.io I can't understand how to navigate to the basic documentation for https://esphome.io/components/esphome.html

### Which version of ESPHome has the issue?

NA, this is for the documentation

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

N/A

### Component causing the issue

esphome

**Comment by ssieb** [comment]
This isn't really a question for the github issues.
![image](https://github.com/esphome/issues/assets/649904/523c7514-ef48-4f02-98e4-665bba61e69b)
