### ISSUE TITLE
Error in documentation for Custom Switch

### ISSUE THREAD

**Issue by ProASV** [esphome/issues#51]
In example of using Custom Switch [https://esphome.io/components/output/custom.html](url) there is no constructor in `class MyCustomSwitch`. But now, base class `switch_::Switch` declares only one constructor:
`  explicit Switch(const std::string &name);`, so you have to set switch name to compile without errors.

**Comment by OttoWinter** [comment]
Fixed in https://github.com/esphome/esphome-core/pull/509
