### ISSUE TITLE
RP2040 PIO LED Strip RGBW bits not assembled properly

### ISSUE THREAD

**Issue by kenjikozai** [esphome/issues#5105]
### The problem

When using RP2040 PIO LED Strip with an RGBW (4 channel) strip like SK6812, when the color is set to what should be monochromatic, it has a "rainbow" effect of every 4 pixels. For example, setting all pixels to pure red will show:

1st pixel - red
2nd pixel - blue
3rd pixel - off
4th pixel - green
5th pixel - red
6th pixel - blue
7th pixel - off
8th pixel - green

This is even though `is_rgbw: true` option is set.

I _think_ this is probably caused by this code in led_strip.cpp within `void RP2040PIOLEDStripLightOutput::write_state(light::LightState *state)`

```
  for (int i = 0; i < this->num_leds_; i++) {
    uint8_t c1 = this->buf_[(i * 3) + 0];
    uint8_t c2 = this->buf_[(i * 3) + 1];
    uint8_t c3 = this->buf_[(i * 3) + 2];
    uint8_t w = this->is_rgbw_ ? this->buf_[(i * 4) + 3] : 0;
    uint32_t color = encode_uint32(c1, c2, c3, w);
    pio_sm_put_blocking(this->pio_, this->sm_, color);
  }
```

When color is sent as RGBW instead of RGB, c1, c2, and c3 should be every fourth 8-bit chunk, and probably needs to be indexed by `[i*4+0]`, `[i*4+1]`, `[i*4+2]`. As is, the RGB colors will be written every three 8-bit chunks as R1G1B1R2G2B2R3G3B3..., then the W channels written on top of them, so R1G1B1W1G2B2R3W2B3R4G4W3... etc., which would explain something like the color pattern I'm seeing when set to full red on all pixels, as in 4-channel mode, this will be read as

R1G1B1W1->full red (with R1 set to full, all others off)
G2B2R3W2->full blue (with R3 set to full, all others off)
B3R4G4W3->full green

When setting to the white channel being 100% and all others off, all pixels light up white, so this seems likely to be where the bug is.

I'm on 2023.6.5, but this component hasn't been updated since then, so I'm looking at the current code where this issue exists.

### Which version of ESPHome has the issue?

2023.6.5

### What type of installation are you using?

Docker

### What platform are you using?

RP2040

**Comment by gretel** [comment]
hmm.. i'm getting similar with two leds on a strip: it's one entity but each change shifts the color to the other led instead of setting both.

```yaml
light:
  - platform: rp2040_pio_led_strip
    name: "${upper_devicename} Button Light"
    id: button_led
    chipset: WS2812B
    pio: 1
    pin: GPIO22
    num_leds: 2
    rgb_order: GRB
    is_rgbw: false
```
