### ISSUE TITLE
BME280 module does not collect dewpoint

### ISSUE THREAD

**Issue by BrettDikeman** [esphome/issues#511]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Not applicable

**ESP (ESP32/ESP8266, Board/Sonoff):**

Not applicable

**Affected component:**

BME280 (and BME680)

**Description of problem:**

The BME sensors with temperature and humidity provide dew point values, but these are not available in the corresponding component.

**Problem-relevant YAML-configuration entries:**

N/A

**Logs (if applicable):**

**Additional information and things you've tried:**

N/A

**Comment by brandond** [comment]
I don't believe either device actually provides this as a raw measurement. Other firmwares will derive it for you based on temperature and humidity but I imagine @ottowinter will tell you to do this for yourself with a template sensor lambda.

Example: https://github.com/nodemcu/nodemcu-firmware/blob/master/app/modules/bme280.c#L457

**Comment by BrettDikeman** [comment]
Yep, not a single mention of the word "dew" in the datasheet. Good job, me.

\*_facepalm_\*

I guess if anything this would end up being a feature request for the module to provide. Closing...
