### ISSUE TITLE
Can't collect logs from device

### ISSUE THREAD

**Issue by X4V1** [esphome/issues#5117]
### The problem

I just updated to the version 2023.11.1 and I'm not not able to connect to show logs anymore.
I installed esphome with pip (manual install) on a windows 11 machine.
I was able to flash a running device but can't see logs.
After flashing the device it shows an error message
![image](https://github.com/esphome/issues/assets/15031703/6181c808-177a-45c8-b92d-02f23157381f)
If I go the web interface, everything seems to be running as expected and logs are visible. It's just not possible to get logs with the `esphome logs whatever.yaml` command. Am I missing something ?

I also tried to get logs from another device running an older version of esphome and I'm getting the same error.

### Which version of ESPHome has the issue?

2023.11.1

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2023.11.2

### What platform are you using?

ESP32

### Board

generic esp32

**Comment by marshn** [comment]
I am seeing exactly the same thing when Windows 10, pip and v2023.11.0. Was not happening with v2023.10.6

**Comment by ssieb** [comment]
@bdraco maybe related to the logger changes and windows?

**Comment by bdraco** [comment]
@X4V1 you can work around this by uninstalling `aioesphomeapi` and reinstalling it with `SKIP_CYTHON=1` in the env

**Comment by bdraco** [comment]
@X4V1 
<https://github.com/esphome/aioesphomeapi/releases/tag/v18.5.2> cooking now <https://github.com/esphome/aioesphomeapi/actions/runs/6897892491>

Can you give it a try once its published to pypi?

**Comment by X4V1** [comment]
@bdraco Thank you for your answer. It works fine with the updated version of aioesphomeapi (18.5.2).

**Comment by bdraco** [comment]
Thanks for confirming
