### ISSUE TITLE
Connection Timeout Platformio

### ISSUE THREAD

**Issue by darth-caedus900** [esphome/issues#5160]
### The problem

Receive this error whenever I try to compile anything;

WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2366562710>, 'Connection to api.registry.nm1.platformio.org timed out. (connect timeout=10)')': /v3/packages/platformio/platform/espressif8266

Using the ESPHome Addon in HA. 

### Which version of ESPHome has the issue?

2023.11.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.11.3

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Anything in the logs that might be useful for us?

```txt
WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2366562710>, 'Connection to api.registry.nm1.platformio.org timed out. (connect timeout=10)')': /v3/packages/platformio/platform/espressif8266
```

### Additional information

No blocking that I am aware of, does it with new devices even. Can't even manually download for offline install as it won't compile.

**Comment by ssieb** [comment]
There's nothing esphome can do about this.  Either platformio is having a server issue or more likely it's a network issue.
Come ask on discord and we can try to help you sort it out.
