### ISSUE TITLE
When Compiling: ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by cassio299** [esphome/issues#523]
Hi

Im trying to update a gosund power-plug which I successfully flash back in march with ESPHome 12.2 Now I wanted to update my plug to 13.6 however ESPHome won't let me recompile instead I get a ZeroDivisionError: float division by zero I am able to make the standard file (with wifi ) and upload that but but when I edit the file with my program I get the ZeroDivisionError:

I have installed ESPHome 13.6 in home assistant 95.4

here is the compiling error:

INFO Reading configuration...
INFO Detected timezone 'CET' with UTC offset 1 and daylight savings time from 03/29/20 02:00:00 to 10/25/20 03:00:00
INFO Generating C++ source...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 11, in <module>
    load_entry_point('esphome', 'console_scripts', 'esphome')()
  File "/opt/esphome/esphome/__main__.py", line 483, in main
    return run_esphome(sys.argv)
  File "/opt/esphome/esphome/__main__.py", line 473, in run_esphome
    return POST_CONFIG_ACTIONS[args.command](args, config)
  File "/opt/esphome/esphome/__main__.py", line 272, in command_compile
    exit_code = write_cpp(config)
  File "/opt/esphome/esphome/__main__.py", line 147, in write_cpp
    CORE.flush_tasks()
  File "/opt/esphome/esphome/core.py", line 616, in flush_tasks
    next(task)
  File "/opt/esphome/esphome/core.py", line 421, in _wrapper_generator
    for x in var:
  File "/opt/esphome/esphome/core.py", line 421, in _wrapper_generator
    for x in var:
  File "/opt/esphome/esphome/core.py", line 421, in _wrapper_generator
    for x in var:
  File "/opt/esphome/esphome/core.py", line 421, in _wrapper_generator
    for x in var:
  File "/opt/esphome/esphome/core.py", line 421, in _wrapper_generator
    for x in var:
  File "/opt/esphome/esphome/core.py", line 421, in _wrapper_generator
    for x in var:
  File "/opt/esphome/esphome/core.py", line 421, in _wrapper_generator
    for x in var:
  File "/opt/esphome/esphome/core.py", line 421, in _wrapper_generator
    for x in var:
  File "/opt/esphome/esphome/core.py", line 417, in _wrapper_generator
    var = gen.send(var)
  File "/opt/esphome/esphome/components/sensor/__init__.py", line 193, in calibrate_linear_filter_to_code
    k, b = fit_linear(x, y)
  File "/opt/esphome/esphome/components/sensor/__init__.py", line 300, in fit_linear
    r = _correlation_coeff(x, y)
  File "/opt/esphome/esphome/components/sensor/__init__.py", line 294, in _correlation_coeff
    return s_xy / math.sqrt(s_sq_x * s_sq_y)
ZeroDivisionError: float division by zero

And here is the code Im trying to upload:

substitutions:
  plug_name: XXXXXX

  
  # Model Gosund SP1-4

esphome:
  name: ${plug_name}
  platform: ESP8266
  board: esp8285
  
wifi:
  ssid: XXXXXXX
  password: XXXXX
  power_save_mode: light

logger:

api:
  password: XXXXX
ota:
  password: XXXXX

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      inverted: True
    name: "${plug_name}_button"
    on_press:
      - switch.toggle: "${plug_name}_Relay"
    
switch:
  - platform: gpio
    name: "${plug_name}_Relay"
    id: "${plug_name}_Relay"
    pin: GPIO14
    restore_mode: ALWAYS_ON
    on_turn_on:
      - switch.turn_on: "${plug_name}_LED_Blue"
    on_turn_off:
      - switch.turn_off: "${plug_name}_LED_Blue"
  - platform: gpio
    name: "${plug_name}_LED_Blue"
    id: "${plug_name}_LED_Blue"
    pin: GPIO1
    inverted: True
    restore_mode: ALWAYS_OFF

status_led:
  pin: 
    number: GPIO13
    inverted: True

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    # Higher value gives lower watt readout
    current_resistor: 0.00599
    current:
      name: "${plug_name}_Current"
      unit_of_measurement: A
      filters:
        - calibrate_linear:
            # Map 0.0 (from sensor) to 0.0 (true value)
          - 0.0 -> 0.203
          - 0.0 -> 0.203
          - 0.0 -> 0.201
    voltage:
      name: "${plug_name}_Voltage"
      unit_of_measurement: V
      filters:
        - calibrate_linear:
            # Map 0.0 (from sensor) to 0.0 (true value)
          - 612.4 -> 230.8
          - 609.1 -> 230.7
          - 611.6 -> 231.1
    power:
      name: "${plug_name}_Wattage"
      unit_of_measurement: W
      id: "${plug_name}_Wattage"
    change_mode_every: 8
    update_interval: 10s
    
  - platform: wifi_signal
    name: "${plug_name}_wifi"
    update_interval: 60s
    filters:
    - sliding_window_moving_average:
        window_size: 15
        send_every: 15
  
  - platform: uptime
    name: ${plug_name}_Uptime Sensor 
  
  - platform: total_daily_energy
    name: "${plug_name}_Total Daily Energy"
    power_id: "${plug_name}_Wattage"
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh
      
text_sensor:
  - platform: version
    name: "${plug_name}_version"

**Comment by brandond** [comment]
Issue is closed but this looks invalid:
```yaml
      filters:
        - calibrate_linear:
            # Map 0.0 (from sensor) to 0.0 (true value)
          - 0.0 -> 0.203
          - 0.0 -> 0.203
          - 0.0 -> 0.201
```

Why are you mapping 0 to three different values? There's obviously no check for that but it's probably why it's failing.
