### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by eccmaster** [esphome/issues#529]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by glmnet** [comment]
Wouldn't it be nice if GH would tell you how many people are going to be emailed when you push a button?
