### ISSUE TITLE
SSID is disappear

### ISSUE THREAD

**Issue by wanwisawkk** [esphome/issues#530]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
pip
ESP8266
**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**
MycroPython(SSID) is gone(cannot find) after I did some configuration about WebRepl.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
try restart computer and re-install all of esptool.

**Comment by OttoWinter** [comment]
I think you're using the wrong issue tracker - this is for ESPHome, not micropython
