### ISSUE TITLE
Disallow invalid characters from name: "Error while reading config: Invalid YAML syntax"

### ISSUE THREAD

**Issue by wajeemba** [esphome/issues#5318]
### The problem

I initially tried to put a colon in the friendly name for my device. Not knowing much about YAML I got back a fairly cryptic error message:

"esphome ERROR Error while reading config: Invalid YAML syntax: mapping values are not allowed in this context in "<unicode string>", line 3, column 24"

Would suggest disallowing invalid characters from the New Device fields to prevent this in the future.
Luckily I did realize that the colon was a problem by looking at the actual YAML and seeing colons being used elsewhere.

Looks like # and " are both great candidates for exclusion from names, but that's just my uninformed guess.

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.4

### What platform are you using?

RP2040

### Board

Pi Pico W

### Example YAML snippet

```yaml
esphome:
  name: myname-a
  friendly_name: myname: A
```

### Anything in the logs that might be useful for us?

```txt
esphome ERROR Error while reading config: Invalid YAML syntax: mapping values are not allowed in this context in "<unicode string>", line 3, column 24
```

**Comment by ssieb** [comment]
Those characters are allowed if you quote it.  But any validation happens after the yaml parsing anyway and if you give it bad yaml, it will fail.  There's nothing we can do about this.
