### ISSUE TITLE
Problems with USB_CDC on ESP32-C3 with Arduino

### ISSUE THREAD

**Issue by bearpawmaxim** [esphome/issues#5332]
### The problem

Hello!
Cannot use hardware USB_CDC uart on my ESP32-C3 board with the Arduino framework.
ESP-IDF is ok.

The symptoms:
1. USB_CDC works (outputs some early esphome messages) for some time after the boot and then stops output.
2. Cannot choose USB_CDC as hardware uart for logger: looks like an error in esphome's logger config validation and code generation because it is actually supported by both mcu and Arduino.

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

esp32-c3-devkitm-1

### Component causing the issue

logger

**Comment by bearpawmaxim** [comment]
@kbx81 could you take a look at this?

**Comment by kbx81** [comment]
Yeah, I'll have a look shortly. 😇

**Comment by kbx81** [comment]
Hi -- please test https://github.com/esphome/esphome/pull/6069 and comment back if this fixes the issue for you.

```yaml
external_components:
  - source: github://pr#6069
    components: logger
    refresh: 0s
```

**Comment by bearpawmaxim** [comment]
> Hi -- please test

It is now working even without setting the `hardware_uart: USB_CDC` (with also works), thanks!
