### ISSUE TITLE
ESP32 PWM / 20kHz + 20kHz + 50Hz

### ISSUE THREAD

**Issue by unknown1818** [esphome/issues#5344]
### The problem

Hi,

How i can get 3 different frequencies on different GPIO? When i use only 2x20kHz its okey, two DC motors spins with hbridge but when i use simultaneously 2x 20kHz and one 50Hz for hbridge solenoid, 20kHz motor only make buzzing sound?

Its possible to have high freq and low freq at same time?

My board is ESP32 Wroom 

### Which version of ESPHome has the issue?

latest

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

latest

### What platform are you using?

ESP32

**Comment by ssieb** [comment]
See the explanation of channels in the "Advanced options" section.
