### ISSUE TITLE
Error trying to use CCS811 Sensor: ERROR Unable to find component sensor.ccs811

### ISSUE THREAD

**Issue by dkran** [esphome/issues#537]
Hi, I've been using ESPhome with 1-wire, dht, and I2C sensors successfully.  I recently got CCS811 sensors, and I wired it up.  I2C scan detects the device at the proper address.  When I try to update by running the .yaml file, it gives an error trying to find the files for the sensor it seems.  ESPHome seems up to date, but esphome version doesn't print version, it just says invalid number of arguments.

YAML: 
```
sensor:
  - platform: dht
    model: AM2302
    pin: GPIO27
    temperature:
      name: "Living Room Temperature"
      id: LivingRoom_temperature
    humidity:
      name: "Living Room  Humidity"
      id: LivingRoom_humidity
    update_interval: 30s

  - platform: ccs811
    eco2:
      name: "Living Room eCO2"
      id: LivingRoom_eCO2
    tvoc:
      name: "Living Room tVOC"
      id: LivingRoom_tVOC
    address: 0x5A
    update_interval: 60s
```

upon running, I get:
```
INFO Reading configuration...
ERROR Unable to find component sensor.ccs811
INFO Detected timezone 'EST' with UTC offset -5 and daylight savings time from 03/10/19 02:00:00 to 11/03/19 02:00:00
Failed config

sensor.ccs811: [source lr-sensors.yaml:38]
  
  Platform not found: 'sensor.ccs811'
  platform: ccs811
  eco2: 
    name: Living Room eCO2
    id: LivingRoom_eCO2
  tvoc: 
    name: Living Room tVOC
    id: LivingRoom_tVOC
  address: 90
  update_interval: 60s
```

I realize this may be a simple issue, but I've searched quite a bit and I'm at a loss.  it doesn't seem to be a format error as far as I can see?

**Comment by OttoWinter** [comment]
Please check you're using the latest version
