### ISSUE TITLE
xpt2046 Touchscreen 'on_update' Trigger Issue + Broken Hyperlink in documentation 

### ISSUE THREAD

**Issue by nbartzeliotis** [esphome/issues#5371]
### The problem

I have an ESP32 connected to an xpt2046 touchscreen via SPI. The touchscreen works correctly and I have been using it for almost 6 months now. 

I was playing with the different touchscreen triggers and I noticed the 'on_update' trigger doesn't seem to report the touch coordinates back. 

The documentation states:
_This trigger provides one argument named touches of type [API Reference](https://esphome.io/api/touchscreen_1_1_touch_points__t.html) which has a list of
[TouchPoint Argument Type](https://esphome.io/components/touchscreen/index.html#touchscreen-touchpoint)._

Based on this my code is simply: 
```
on_update:
    - lambda: |-
              ESP_LOGI("Touch points:", "x=%d, y=%d", touches.x, touches.y);
```
**Issues:** 

1. [API Reference](https://esphome.io/api/touchscreen_1_1_touch_points__t.html) link does not work - page cannot be found.
This is mentioned here: https://esphome.io/components/touchscreen/index.html#on-update-trigger
I believe this is trying to point to https://esphome.io/api/structesphome_1_1touchscreen_1_1_touch_point

2. When trying to install the .yaml on my ESP32, I get the following errors: 
```
<unicode string>: In lambda function:
<unicode string>:356:55: error: 'const class std::vector<esphome::touchscreen::TouchPoint>' has no member named 'x'
src/esphome/core/log.h:108:88: note: in definition of macro 'esph_log_i'
   esp_log_printf_(ESPHOME_LOG_LEVEL_INFO, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                        ^~~~~~~~~~~
<unicode string>:356:7: note: in expansion of macro 'ESP_LOGI'
<unicode string>:356:66: error: 'const class std::vector<esphome::touchscreen::TouchPoint>' has no member named 'y'
src/esphome/core/log.h:108:88: note: in definition of macro 'esph_log_i'
   esp_log_printf_(ESPHOME_LOG_LEVEL_INFO, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                        ^~~~~~~~~~~
```

Looking in the esphome::touchscreen::TouchPoint Struct Reference (https://esphome.io/api/structesphome_1_1touchscreen_1_1_touch_point) I can see that all the data fields / members are there, but for some reason I can't access them from the lamda code. 

Am I doing something silly or is this an issue? I think the documentation would benefit from at least one example on how to use this trigger instead of just text instructions.

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1.2

### What platform are you using?

ESP32

### Board

LILYGO® T-Call V1.4

### Component causing the issue

XPT2046 Touch Screen Controller (Updated version)

### Example YAML snippet

```yaml
on_update:
    - lambda: |-
              ESP_LOGI("Touch points:", "x=%d, y=%d", touches.x, touches.y);
```

**Comment by nielsnl68** [comment]
Hi @nbartzeliotis, in compare to `on_touch` the `on_update` event will give you an `std::vector` list of all the the touches that are detected.
For example you could do:

```yaml
on_update:
    - lambda: |-
          for (auto touch: touches)  {
              ESP_LOGI("Touch points:", "id=%d x=%d, y=%d", touch.id, touch.x, touch.y);
          }
```
