### ISSUE TITLE
YAML file name missing from config error messages and main.cpp 'lambda headers'

### ISSUE THREAD

**Issue by marshn** [esphome/issues#5377]
### The problem

In yaml error messages and in 'lambda headers' in main.cpp the yaml file name has been replaced by "\<unicode string\>".

I had been expecting https://github.com/esphome/esphome/pull/6081 to fix this, but it doesn't seem to have done so. I have tried a fresh installation of 2023.12.6 (a pip install on Windows), so I don't think that anything from 2023.12.5 is cached.

If there is an error in the yaml, like this one:
```
binary_sensor:
  - platform: gpio
    asdf: asdf
    pin: 
      number: GPIO0 
```
2023.12.6 (which incorporates https://github.com/esphome/esphome/pull/6081) still outputs an error message like this:
```
INFO ESPHome 2023.12.6
INFO Reading configuration Generic_Controller.yaml...
Failed configFailed config

binary_sensor.gpio: [source <unicode string>:232]
  platform: gpio

  [asdf] is an invalid option for [binary_sensor.gpio]. Please check the indentation.
  pin:
    number: GPIO0
```
2023.11.6 and earlier versions produced an error message like this:
```
Failed config

binary_sensor.gpio: [source <Fused_Spur-ESP32.yaml>:232]
  platform: gpio

  [asdf] is an invalid option for [binary_sensor.gpio]. Please check the indentation.
  asdf: asdf
  pin:
    number: GPIO0
```
Additionally, in the main.cpp file generated by v2023.12.6 the lambda entries look like:
```
lambdaaction_3 = new LambdaAction<std::string>([=](std::string x) -> void {
      #line 54 "<unicode string>"
      snprintf(global_location_text->value(), sizeof(global_location_text->value()), "%s", (const char *)(id_location->state.c_str()));
  });
```

Where v2023.11.6 and earlier they looked like:
```
  lambdaaction_3 = new LambdaAction<std::string>([=](std::string x) -> void {
      #line 54 "common/pkg_location.yaml"
      snprintf(global_location_text->value(), sizeof(global_location_text->value()), "%s", (const char *)(id_location->state.c_str()));
  });
```
This make debugging complex lambdas in nested yaml configuation files more difficult that it used to be.

I did report this in Issue https://github.com/esphome/issues/issues/5354, which was closed as it 'was a duplicate of https://github.com/esphome/issues/issues/5310'.  PR https://github.com/esphome/esphome/pull/6081 has fixed https://github.com/esphome/issues/issues/5310 which is the error message generated when the YAML does not parse, but not Issue #5354. 

For example, this error in yaml produced a broken error message:
```
  - platform: gpio
    pin: 
      asdf: asdf:
      number: GPIO0 
```
But now correctly produces an error message containing the offending file name:
```
INFO ESPHome 2023.12.6
INFO Reading configuration Generic_Controller.yaml...
ERROR Error while reading config: Invalid YAML syntax:

mapping values are not allowed here
  in "Generic_Controller.yaml", line 234, column 17:
          asdf: asdf:
                    ^
```

### Which version of ESPHome has the issue?

2023.12.6

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

pico32

### Example YAML snippet

```yaml
binary_sensor:
  - platform: gpio
    asdf: asdf
    pin: 
      number: GPIO0
```

### Anything in the logs that might be useful for us?

```txt
Failed config

binary_sensor.gpio: [source <unicode string>:484]
  platform: gpio

  [asdf] is an invalid option for [binary_sensor.gpio]. Please check the indentation.
  pin:
    number: GPIO0
```

**Comment by Unfocused** [comment]
CC @bdraco, who has been working on this.

Another related regression:
- https://github.com/esphome/issues/issues/5423
