### ISSUE TITLE
cannot use sensor bmi160

### ISSUE THREAD

**Issue by FlyingFeng2021** [esphome/issues#5413]
### The problem

when i paste the config to the yaml of one of my ESP32,it says "Platform not found: 'sensor.BMI160'"
<img width="423" alt="image" src="https://github.com/esphome/issues/assets/87404327/2a9c7d97-a6af-425b-ba0a-8d24e37ee20c">

### Which version of ESPHome has the issue?

2023.7.1

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

denky32

### Component causing the issue

bmi160

**Comment by GD-Dal** [comment]
What was the solution here?
FAcing the same problem

**Comment by randybb** [comment]
"The [I²C Bus](https://esphome.io/components/i2c#i2c) is required to be set up in your configuration for this sensor to work."

**Comment by ssieb** [comment]
The original problem was that the esphome version was too old.  `2023.7.1` is before this component was added.

**Comment by randybb** [comment]
Ah yes. If i2c is missing then it tells "Component sensor.bmi160 requires component i2c."

**Comment by GD-Dal** [comment]
Thanks for answering. 
It was the same for me; the ESPHome version was too old

But I still cannot connect to the BMI160 sensor though

I get the
[bmi160:192]: Communication with BMI160 failed!
and 
component:082]:   Component bmi160.sensor is marked FAILED

But that's a story for another thread I guess

Thanks

**Comment by ssieb** [comment]
Please come ask on discord about that.
