### ISSUE TITLE
Sen5x Sensor incorrect temperature values

### ISSUE THREAD

**Issue by Smiley098** [esphome/issues#5415]
### The problem

At temperatures below 0 degrees, the value 325.6 degrees is displayed.

### Which version of ESPHome has the issue?

2023.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1.5

### What platform are you using?

ESP32

### Board

Esp32dev

### Component causing the issue

Sensoren Sen55

**Comment by ssieb** [comment]
Duplicate of https://github.com/esphome/issues/issues/5365
fixed in dev by https://github.com/esphome/esphome/pull/6082
