### ISSUE TITLE
Regression: Logger broken for ESP32-C3

### ISSUE THREAD

**Issue by fornellas** [esphome/issues#5416]
### The problem

@kbx81, It looks like that the fixes from:

https://github.com/esphome/issues/issues/5332
https://github.com/esphome/esphome/pull/6069

created some regression. With a [ESP32-C3-DevKitM-1](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/hw-reference/esp32c3/user-guide-devkitm-1.html#esp32-c3-devkitm-1), and logger setup as:

```
logger:
  baud_rate: 115200
  level: debug
```

This works fine:

```
docker run --rm --privileged --net=host --device=/dev/ttyUSB0 -v "esphome-configs":/config -it ghcr.io/esphome/esphome:2023.12.5 run --device /dev/ttyUSB0 foo.yaml
```

and I can immediately see logs on reset, but the next version, containing the fix:

```
docker run --rm --privileged --net=host --device=/dev/ttyUSB0 -v "esphome-configs":/config -it ghcr.io/esphome/esphome:2023.12.6 run --device /dev/ttyUSB0 foo.yaml
```

outputs no logs: only the boot up message on manual reset:

```
[18:29:17]ESP-ROM:esp32c3-api1-20210207
[18:29:17]Build:Feb  7 2021
[18:29:17]rst:0x1 (POWERON),boot:0xc (SPI_FAST_FLASH_BOOT)
[18:29:17]SPIWP:0xee
[18:29:17]mode:DIO, clock div:1
[18:29:17]load:0x3fcd6100,len:0x438
[18:29:17]load:0x403ce000,len:0x918
[18:29:17]load:0x403d0000,len:0x24e4
[18:29:17]entry 0x403ce000
```

Setting the logger like tihs:

```
logger:
  baud_rate: 115200
  hardware_uart: UART0
  level: debug
```

seems to be the fix.

### Which version of ESPHome has the issue?

2023.12.6

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

ESP32-C3-DevKitM-1

### Component causing the issue

logger

**Comment by ssieb** [comment]
Your board uses a uart bridge instead of the native USB.  The default for C3 is the USB, so yes, you will need to override it.
https://esphome.io/components/logger#default-hardware-interfaces
