### ISSUE TITLE
Image component requires the `libmagic` binary to be manually installed on most OSes (& isn't documented)

### ISSUE THREAD

**Issue by Unfocused** [esphome/issues#5427]
### The problem

ESPHome 2023.11.4 added the ability to specify remote URLs for images:

- <https://github.com/esphome/esphome/pull/5214> (CC @landonr, @guillempages, @jesserockz)

It relies on the `python-magic` package to determine the file type of the remote image. That package is installed as a dependency of ESPHome. However, the `python-magic` package depends on the `libmagic` binary - which is **not** included in the package. And no runtime checks were added like how `pillow` and `cairosvg` are handled (both of which will output helpful error messages if the package is missing & instructions on how to fix it).

Unfortunately, most OSes require `libmagic` to be manually installed. And worse, how to install the right binary differs depending on your OS and Python version:
- On Linux it may be installed by default, or you'll typically install `libmagic1` (but it depends on the distro)
- On OSX you'll need to install either `libmagic` if using Brew, or `file` if using MacPorts
- And on Windows there's at least 4 different options that also depend on whether you're using 32bit Python or 64bit Python

(It is included in the Docker image, so the HA add-on isn't affected)

And while the docs were updated for the new functionality (<https://github.com/esphome/esphome-docs/pull/3409>), there was nothing added about needing the `libmagic` binary or how to install it.

Rather than adding it to the documentation and requiring people to manually install an OS-specific binary (that may also depend on the Python version used), here are two possible easy fixes that would require no user intervention:

- `python-magic-bin` is a fork of `python-magic` that includes the necessary binaries for the major platforms (but not all platforms - it's missing any binary for Raspberry Pi, for instance). You can actually install this package instead of `python-magic` and it will just work:

  - <https://pypi.org/project/python-magic-bin/>
  - Unfortunately, it hasn't been updated in 4 years. It hasn't had fixes pulled in from the original `python-magic` package, nor any updates to the included binaries. Given it's used for checking files downloaded from potentially anywhere on the internet, this could be a security risk.
- `puremagic` is a pure Python implementation of the `libmagic` binary:
  - <https://pypi.org/project/puremagic/>
  - This has a slightly different API, so will need some minimal code changes.

Of the two, I think `puremagic` is by far the better and safer option. It's explicitly meant to be cross-platform, it has no dependencies on third-party binaries (it'll work on every platform, instead of just most platforms), it's faster, and it's actively maintained.

### Which version of ESPHome has the issue?

2023.11.4

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

image

**Comment by guillempages** [comment]
https://github.com/esphome/esphome/pull/7365 should fix this issue
