### ISSUE TITLE
Force flash write?

### ISSUE THREAD

**Issue by DLV111** [esphome/issues#5433]
### The problem

Is there the ability to force a flash write? My use case is I like my automations to be usable even when the central controller is off-line.
This particular use case is a light. If the controller is off-line to manage the automation of the light I want to manually be able to turn it on. To do this, i'm thinking toggle power switch twice and use a global var to increment the count. If count is > xx times then turn the light on with some defaults.

Whatever I do, the setting needs to persist on power outage.

Here's my test code - but the issue i'm running into is the toggle time of the switch and the write to flash. To get this semi-working as expected, i need this set to 0s but I don't want to wear out the flash when I really just need a special call to write on boot

```
preferences:
    flash_write_interval: 0s  # Ideally i'd set this at 30s or 1m
```

```
on_boot:
    priority: 600
    then:
      - lambda: |-
          (id(my_global_int) += 1);
          # Force flash write here if possible
          ESP_LOGD("main", "%s: %d", id(my_global_string).c_str(), id(my_global_int));
      - if: 
          condition:
            lambda: return id(my_global_int) > 1;
          then:
            - light.turn_on:
                id: this_light
                brightness: 80%
            - globals.set:
                id: my_global_int
                value: '0'
          else:
            - light.turn_on:
                id: this_light
                brightness: 10%
            - delay: 10s
            - globals.set:
                id: my_global_int
                value: '0'

```

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1.5

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

N/A

**Comment by ssieb** [comment]
Github issues are not for support requests.  Ask on discord or one of the forums.
`global_preferences->sync();`
