### ISSUE TITLE
mDNS config and error Cannot write to closing transport

### ISSUE THREAD

**Issue by Adorem** [esphome/issues#544]
Hello,

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io HassOS 2.12
Home Assistant 0.96.3
ESPHome 1.13.6

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266, Arilux AL-LC11 

**Affected component:**

https://esphome.io/components/wifi.html

**Description of problem:**
I have to use `use_address:` to be able to to upload new files. After that the device is still shown as Offline. I see it online if I change the ESPHome option `status_use_ping` to true.
And even after these changes I get the following error about "ConnectionResetError: Cannot write to closing transport" spam in the log.
FYI My device and HA are on the same subnet. Just the device works with wifi while the HA machine is connected via cable.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: led_sous_sol
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "xx"
  password: "xx"
  use_address: 192.168.1.10
```

**Logs (if applicable):**

```
Tue Jul 23 2019 12:44:26 GMT+0200 (heure d’été d’Europe centrale)
Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 448, in start
    await resp.write_eof()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_response.py", line 444, in write_eof
    await self._payload_writer.write_eof(data)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 138, in write_eof
    self._write(chunk)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport

```

**Additional information and things you've tried:**
Without the `use_address:` the upload failed:
```
========================= [SUCCESS] Took 24.21 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of led_sous_sol.local
ERROR Error resolving IP address of led_sous_sol.local. Is it connected to WiFi?
ERROR (If this error persists, please set a static IP address: https://esphome.io/components/wifi.html#manual-ips)
ERROR Error resolving IP address: Error resolving address with mDNS: Did not respond. Maybe the device is offline., [Errno -2] Name or service not known
```

With previous version of HA/ESPHome it works without adding theses options.

Thanks,
Christophe

**Comment by OttoWinter** [comment]
> ConnectionResetError: Cannot write to closing transport

That doesn't have anything to do with the error you're seeing. That's a bug in Hass.io, see also https://github.com/home-assistant/hassio/issues/1102

As for the other stuff, mDNS can be finicky sometimes with some setups (and by now I've learned that it doesn't make sense to debug it much; some routers just don't like it). I would suggest you to use static IPs in this case.
