### ISSUE TITLE
Dashboard - device sorting issue

### ISSUE THREAD

**Issue by Masterz69** [esphome/issues#5484]
### The problem

It started as soon ESPHome upgraded from 2023.12.5 to 2023.12.7.
Newly added devices in dashobard appears at the end/bottom of list and sorting not happens.

Add-on restart resort existing devices, but then new devices again appears at the end.

### Which version of ESPHome has the issue?

2023.12.7

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

**Comment by ssieb** [comment]
Duplicate of #5483.
