### ISSUE TITLE
Improve documentation for Infrared codes in Hex-Format

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [esphome/issues#5508]
### The problem

Hi,

I'm reading this page https://esphome.io/components/remote_transmitter.html#remote-transmitter-transmit-raw-action and can't figure out the way to make my infrared led make it work with following codes:

> 0000 006D 0000 0024 0000 00AA 0000 0015 0000 003F 0000 0015 0000 0015 0000 0015 0000 0015 0000 0015 0000 003F 0000 0015 0000 003F 0000 0015 0000 0015 0000 003F 0000 003F 0000 003F 0000 0015 0000 0015 0000 0015 0000 003F 0000 003F 0000 0015 0000 0015 0000 0015 0000 003F 0000 003F 0000 003F 0000 0015 0000 0015 0000 003F 0000 003F 0000 003F 0000 0015 0000 0640 0000 0055 0000 1304

https://www.remotecentral.com/cgi-bin/codes/harmon_kardon/avr7000/page-2/

I really dont understand (and chatgpt couldnt help me too) on how to convert these hex codes to the mentioned format of positive and negative alternating integers?

Any suggestions? Would be great to improve the documentation too!

### Which version of ESPHome has the issue?

latest

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

**Comment by ssieb** [comment]
Esphome docs are not the place to explain how to convert codes.  If you read the top of the page you linked, those are supposed to be pronto codes, which esphome can send.  However, I don't understand why there are zeros in it.
