### ISSUE TITLE
Syntax Highlight Broken in v2024.2.0

### ISSUE THREAD

**Issue by samuelolteanu** [esphome/issues#5516]
### The problem

Like the title says, yaml syntax highlight in HA addon is broken. No highlight at all unless saved and open file again where it recognises the previous error/typo, but not new ones. Cleaning build files did not do anything. Compiling finds the error.
Downgrading the addon (with a backup) fixes the issue except I have to go back and forth with the versions because it gives "ERROR Unsupported OTA version 2" when uploafing with the old 2023.12.9.
Update: issue present in v2024.2.1

Missing squigly lines in the picture:
![Capture](https://github.com/esphome/issues/assets/85267083/f0b01b50-a734-4fd4-82c0-fcb6f6337573)

### Which version of ESPHome has the issue?

2024.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.2.2

### What platform are you using?

ESP32

### Board

ESP32C3

### Component causing the issue

Addon syntax highlight, OTA Downgrading

### Anything in the logs that might be useful for us?

```txt
ERROR Unsupported OTA version 2
```

**Comment by x99percent** [comment]
Flash with version 2024.2.0 using...
```
ota:
  version: 1
```
This will allow you to go back to 2023.12.9. You will need to remove the `version: 1` when flashing from the older ESPHome.

**Comment by EOUpSL93Y** [comment]
Looks like fixed here: https://github.com/esphome/esphome/pull/6431

**Comment by samuelolteanu** [comment]
> Looks like fixed here: [esphome/esphome#6431](https://github.com/esphome/esphome/pull/6431)
