### ISSUE TITLE
Platform not found: 'sensor.bme280'

### ISSUE THREAD

**Issue by JerryLutor** [esphome/issues#5518]
### The problem

INFO ESPHome 2024.2.0
INFO Reading configuration /config/esphome/senseair.yaml...
Failed config

sensor.bme280: [source /config/esphome/senseair.yaml:86]
  
  Platform not found: 'sensor.bme280'.
  platform: bme280
  temperature: 
    name: senseair_bme280_temperature
    id: senseair_bme280_temperature
    icon: mdi:thermometer
  pressure: 
    name: senseair_bme280_pressure
    id: senseair_bme280_pressure
    icon: mdi:gauge
  humidity: 
    name: senseair_bme280_humidity
    id: senseair_bme280_humidity
    icon: mdi:gauge
  address: 118

### Which version of ESPHome has the issue?

2024.2.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

esp-wrover-kit

### Component causing the issue

bme280

### Example YAML snippet

```yaml
After updating to version 2024.2.0, a compilation error appeared - Platform not found: 'sensor.bme280'.
```

**Comment by jsuanet** [comment]
Please read the release notes, it is (more or less) mentioned as a breaking change see also https://github.com/esphome/esphome/pull/5538

Solution is: _To update your configuration, simply replace bme280 with bme280_i2c_
