### ISSUE TITLE
bme280 no support 

### ISSUE THREAD

**Issue by CrazyUs3r** [esphome/issues#5521]
### The problem

INFO ESPHome 2024.2.0
INFO Reading configuration /config/esphome/wetterstation.yaml...
INFO Detected timezone 'Europe/Berlin'
Failed config

sensor.bme280: [source /config/esphome/wetterstation.yaml:65]
  
  Platform not found: 'sensor.bme280'.
  platform: bme280
  temperature: 
    name: BME280 Temperature
    id: bme280_temperature
    oversampling: 16x
  pressure: 
    name: BME280 Pressure
    id: bme280_pressure
  humidity: 
    name: BME280 Humidity
    id: bme280_humidity
  address: 118
  update_interval: 60s

### Which version of ESPHome has the issue?

2024.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.2

### What platform are you using?

ESP8266

### Board

proxmox

**Comment by ssieb** [comment]
https://esphome.io/changelog/2024.2.0.html#breaking-changes
The changelog will be updated soon with more details on what that means, but use `bme280_i2c` now.
