### ISSUE TITLE
Editor Code Check not 'Live' anymore [Edit: Being worked on]

### ISSUE THREAD

**Issue by 3ative** [esphome/issues#5533]
### The problem

When editing code, the editor no longer updates live with errors. 
 - You have to save, close and re-open for them to appear.
 

### Which version of ESPHome has the issue?

2024.2.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

**Comment by 3ative** [comment]
Leaving this open of others to find. However, I've been informed there **IS** a fix coming. 💖

**Comment by 3ative** [comment]
Maybe related to:
 -  https://github.com/esphome/issues/issues/5342
 - https://github.com/esphome/esphome/pull/6280

**Comment by BigBobbas** [comment]
I have have the same issue, was hoping that https://github.com/esphome/esphome/pull/6280 would resolve this issue as well as the save speed issue. 
The validation problem was mentioned in https://github.com/esphome/issues/issues/5342 which has been closed as resolved. However the validation issue is still the same after update to 2024.2.1
I Have to save and close editor for validation errors to show.

**Comment by 3ative** [comment]
Indeed... I put "_maybe related to_" as there seemed to be some similarities
