### ISSUE TITLE
Add `esphome --version`

### ISSUE THREAD

**Issue by mondalaci** [esphome/issues#5572]
### The problem

esphome should expose its version number somehow, like via a `--version` parameter.

You may argue that the version number can be retrieved via `pip3 show esphome`, but I seldom use the Python ecosystem, and I usually have to look up the pip command.

### Which version of ESPHome has the issue?

2024.2.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

**Comment by ssieb** [comment]
`esphome version`
`esphome -h` will give you the list of commands.
