### ISSUE TITLE
ESPHome not seeing device though HA does (docker, mDNS or not)

### ISSUE THREAD

**Issue by edasque** [esphome/issues#5607]
### The problem

Forgive me, I've asked this question before on Discord and while the answer were helpful, I haven't been able to fix it.

I have a similar setup in two sites:
* Firewalla router, dumb switches
* Eero Wifi in Bridge Mode
* ESPHome & HA in Docker (on Ubuntu, host network mode, privileged mode)

In Site A, after I flash a device with Web ESPHome and connect it to my Wifi:
* I see it pop up in ESP Home **and** HA
* I can connect to that device's web server

In Site B, after I flash a device with Web ESPHome and connect it to my Wifi,
* I see it pop up in HA
* I can connect to that device
* I **cannot** see it in ESPHome.
* I see on the device's web page it connecting to HA.

I've been told it's a mDNS issue on my network but I can't find a difference from that perspective between the two sites.

I've tried `ESPHOME_DASHBOARD_USE_PING=true` but that doesn't seem to help.

I run HA & ESPHome in Docker (`network_mode: host` and `privileged: true`). I've perused the Github repo issues to try to find some solutions to no avail

Posting here in case someone had a similar problem and fixed it.

People seem to be having similar problems with HA but not ESPHome like me 

### Which version of ESPHome has the issue?

2024.2.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.3.1

### What platform are you using?

ESP8266

### Board

ESP8266 (and others)

**Comment by ssieb** [comment]
github issues are not for support requests.  Discord is the right place.  And it would be the same people answering here, so this doesn't help.
