### ISSUE TITLE
Compilation errors on 4GB RAM device, Host memory consumed during ESPHome compilation

### ISSUE THREAD

**Issue by blackie333** [esphome/issues#5611]
### The problem

Hello, from ESPHome ver. 2024.2 I started to experience compilation errors during compilation of "esp32-s3-box-3.yaml" Voice assistant firmware for ESP32-S3-Box3 device.

Compilation works for a batch of files until stops on some file.o with random error.
After pressing "Retry" compilation works for another batch of files until hits another error.
After about 5-6 compilation batches it reached the linking stage and the firmware was created and uploaded successfully, but the process is very annoying and time-consuming.

The problems seems to be related to Host memory consumption which goes from 50% to 95% during every compilation batch.
![Home Assistant — memory during ESPHome compilation](https://github.com/esphome/issues/assets/22171229/5b681645-17c6-4112-97c9-b4dbd8a11ed1)

It's hard to believe that for compilation of 4MB firmware the compiler really needs more than 1.5GB of memory and crashes.
I would never expect ESPhome compilation being the reason pressing me to another hardware upgrade... (after upgrade RPi3 1GB to ODROID-C4 4GB a year ago).
Please optimize/fine-tune the esphome compiler memory management.

### Which version of ESPHome has the issue?

2024.2 and newer

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.2 - 2024.3

### What platform are you using?

ESP32-IDF

### Board

ESP32-S3-BOX-3

### Component causing the issue

esphome compilator

### Example YAML snippet

```yaml
Host is HassOS installation for Odroid-C4 (4GB ram), 128GB storage.

ESPHome project causing compilation errors:
https://github.com/esphome/firmware/blob/main/wake-word-voice-assistant/esp32-s3-box-3.yaml

Add-ons in use:
Advanced SSH & Web Terminal
ESPHome
File Editor
go2rtc
Mosquitto broker
Network UPS tools
Nginx Proxy Manager
openWakeWord
Piper
Whisper
Samba Share
Zigbee2MQTT
```

### Additional information

Core 2024.3.1
Supervisor 2024.03.0
Operating System 12.1
Frontend 20240307.0

**Comment by ssieb** [comment]
esphome has no control over the compiler memory usage, but there's an option to limit the number of processes that you could use.
https://esphome.io/components/esphome#configuration-variables
