### ISSUE TITLE
HLW8012 change_mode_every set to never returns no values

### ISSUE THREAD

**Issue by sbussinger** [esphome/issues#5619]
### The problem

The HLW8012 device's change_mode_every: never setting doesn't seem to work. I’m trying to set it up to measure current only and if I use the never setting it don’t produce any values. If I set it to a very large number it works OK.
```
    update_interval: 3s
    initial_mode: CURRENT
    change_mode_every: never  # generates no values
```
However, setting change_mode_every to a very large number works fine:
```
    update_interval: 3s
    initial_mode: CURRENT
    change_mode_every: 4294967295  # about 408 years and works

```

### Which version of ESPHome has the issue?

2024.3.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.3.1

### What platform are you using?

ESP8266

### Board

A power monitoring outlet device

### Component causing the issue

hlw8012

**Comment by srnoth** [comment]
Still an issue.
