### ISSUE TITLE
Wake on lan button send discard protocol 

### ISSUE THREAD

**Issue by plplaaa2** [esphome/issues#5623]
### The problem

First, the wol function through my router is working well. 

The wake-on-lan button did not run with error code. 
I search it with wireshark and confirmed that the protocol was sent to discard protocol, not wol protocol.

I'm not a programmer, so I don't know what's wrong, but I want to make sure that the wol button is sent to discard protocol is normal behavior.

esphome wol
![image](https://github.com/esphome/issues/assets/124797654/ebf5ebab-f25b-445f-a430-4e2df3abdc4b)

router's wol
![image](https://github.com/esphome/issues/assets/124797654/16a62c50-3a45-491d-94d7-b8e31bf4a261)

### Which version of ESPHome has the issue?

2024.3.0 Mar 21 2024

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.3.1

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

wake_on_lan

### Example YAML snippet

```yaml
button:
  - platform: wake_on_lan
    name: "Start the PC"
    id: wake_up
    target_mac_address: "XX:XX:XX:XX:XX:XX"
```

### Anything in the logs that might be useful for us?

```txt
[22:37:41][I][wake_on_lan.button:030]: Sending Wake-on-LAN Packet...
[22:37:41][E][wake_on_lan.button:054]: Sending Wake-on-LAN Packet Failed!
```

**Comment by ssieb** [comment]
There isn't a WoL protocol.  The usual port is UDP 9 (discard).  But there's another option with a raw ethernet packet and that's what you're seeing in the second case.
