### ISSUE TITLE
Config 'name_add_mac_suffix' isn't considered when updating OTA

### ISSUE THREAD

**Issue by DanITman** [esphome/issues#5656]
### The problem

If you are using the config 'name_add_mac_suffix: true', the name of you device will not be the same as you declared and OTA updates will fail.

esphome:
  name: esp32_home
  friendly_name: esp32_home
  name_add_mac_suffix: true

If you name is esp32_home and you have 'name_add_mac_suffix: true' then the name will actually be esp32_home-xxxxxx. Where 'xxxxxx' will be the last 6 of the mac address.  

When attempting to do OTA update on ESP Home OSX pip install.  It will fail as it does not take into account the 'name_add_mac_suffix' and will attempt to find the device at esp32_home.local when it should attempt to look for esp32_home-xxxxxx.local

### Which version of ESPHome has the issue?

2024.3.1

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

esp32-poe

### Component causing the issue

none

### Example YAML snippet

```yaml
esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
```

### Anything in the logs that might be useful for us?

```txt
ERROR Error resolving IP address of esp32_home.local. Is it connected to WiFi?
ERROR (If this error persists, please set a static IP address: https://esphome.io/components/wifi.html#manual-ips)
ERROR Error resolving IP address: Error resolving address with mDNS: Did not respond. Maybe the device is offline., [Errno 8] nodename nor servname provided, or not known
```

**Comment by jesserockz** [comment]
This is working as designed. 
This field is for people/companies mass producing devices that need the same firmware. End users should then adopt the device and flash it using the generated yaml which will have the Mac suffix hard coded in the name.
