### ISSUE TITLE
Logger uart type changed in esp-idf 5.2

### ISSUE THREAD

**Issue by luar123** [esphome/issues#5672]
### The problem

Tried using the latest platformio 6.6.0 with esp-idf 5.2.1 and it is mostly working, but the logger won't compile anymore because the definition of uart_port_t changed from typedef int to enum.

### Which version of ESPHome has the issue?

2024.3.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Component causing the issue

logger

### Additional information

Setting `=-1` is not valid anymore
```
#ifdef USE_LOGGER_USB_CDC
      case UART_SELECTION_USB_CDC:
        this->uart_num_ = -1;
        break;
#endif
#ifdef USE_LOGGER_USB_SERIAL_JTAG
      case UART_SELECTION_USB_SERIAL_JTAG:
        this->uart_num_ = -1;
        init_usb_serial_jtag_();
        break;
#endif
    }
    if (this->uart_num_ >= 0) {
      init_uart(this->uart_num_, baud_rate_, tx_buffer_size_);
    }
```

**Comment by ssieb** [comment]
Changing the platform versions is not supported.  We are aware of this change and it will be handled when the project is updated to use a new platform, which is currently ongoing.
