### ISSUE TITLE
BluetoothLERawAdvertisementsResponse Decoder ?

### ISSUE THREAD

**Issue by tamaskan** [esphome/issues#5684]
### The problem

I'm using the esphome-integration in home assistant and i am getting data like "\002\001\032\002\010\000\003\003a\376\020\377\003\000\000\245[\000\000\006\354\316\327}\200\2172" inside the diagnostics file . Is there some kind of decoder for that ?

### Which version of ESPHome has the issue?

2024.2.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Anything in the logs that might be useful for us?

```txt
2024-04-06 18:22:13.729 DEBUG (MainThread) [aioesphomeapi.connection] atom-bluetooth-proxy-a04a5c @ 99.6.0.7: Got message of type BluetoothLERawAdvertisementsResponse: advertisements {
  address: 211280406819128
  rssi: -96
  data: "\002\001\032\002\010\000\003\003a\376\020\377\003\000\000\245[\000\000\006\354\316\327}\200\2172"
}
```

**Comment by clydebarrow** [comment]
This is a question for the Home Assistant Discord support channels, not an ESPHome problem.

There are integrations that decode advertisements for specific devices, e.g. https://www.home-assistant.io/integrations/inkbird/
