### ISSUE TITLE
Support Platformio 4.0 / Python 3

### ISSUE THREAD

**Issue by grzeg8102** [esphome/issues#569]
I think would be good to start working on support for Platformio 4.0, which finally supports Python 3.5+. Python 2.7 will be deprecated in less 5 months now. Seems platformio tema understood the impact and added support for Python 3.5. So the only reason why esphome runs on top of python 2.7 would be gone forever (hopefully).

**Comment by glmnet** [comment]
https://github.com/esphome/feature-requests/issues/320
