### ISSUE TITLE
Lan8720 with ESP32s wire connect

### ISSUE THREAD

**Issue by metalica196** [esphome/issues#571]
I tried connect the ESP32 (https://www.aliexpress.com/item/32967151972.html?spm=a2g0s.9042311.0.0.6df84c4dE7KXuP) to Waveshare Lan8720 (https://www.aliexpress.com/item/33005830292.html?spm=a2g0s.9042311.0.0.6df84c4dE7KXuP)
with default config on esphome as follow:
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 0
and no result for this, anybody can help me how to wire ESP32s and Lan8720?
I found this thread https://sautter.com/blog/ethernet-on-esp32-using-lan8720/ but it seam a a complex way and also use too much pin i/o that I would like to use then, and the sketch use IDE so how to use with esphome? Is there any way to solve this problem?
Thanks in advance.

**Comment by szurr** [comment]
I had the same problem. Could you fill the template to rise this issue again?
