### ISSUE TITLE
GPS time seems wrong

### ISSUE THREAD

**Issue by deltazerorsan** [esphome/issues#576]
Hi Otto,

Thanks a lot for this incredible tool!

Using Hass.io 0.97 ESPHome 1.13.6 over a raspi3.

I'm trying the GPS module and I'm obtaining this:

22:44:39.215 -> [0;36m[D][time:030]: Synchronized time: Tue Jul 20 07:36:28 1965[0m
22:49:39.222 -> [0;36m[D][time:030]: Synchronized time: Tue Jul 20 07:36:28 1965[0m

Every five minutes. If I disconnect the GPS, there is no synchro, and a few seconds after I reconnect the GPS there comes the same synchro time... The GPS and the UART are both at 9600 bauds, and the GPS has fix.

EDIT*******************

With VERY_VERBOSE I can catch up the serial comms and I decode it by hand, here you have the relevan part in terms of time:

$GPRMC,083317.00,A, here comes my correct position and speed and date -->,0.074,,110819,,,A*64
(Simulated to see every position $GPRMC,083317.00,A,0000.0000,N,00000.00000,W,0.072,,110819,,,A*66)

$GPGGA,083317.00, again position and fix -->,1,07,1.1.65*08

next second

$GPRMC,083318.00,A, again position
$GPGGA,083318.00, again position

As you can see there is no static time, it is changing every second...

Where can I go deeply?

Thanks!

rsan

**Comment by rradar** [comment]
Could your share your gps board you use? Some of them have a rtc on it but sometimes without battery...

**Comment by deltazerorsan** [comment]
> Could your share your gps board you use? Some of them have a rtc on it but sometimes without battery...

I'm using ublock 6 and ublock 8 boards and all of then works when connected to a PC or other micros including that one with a different soft. 

And please read the NMEA messages posted, they contains a correct date and time and as I described above are captured from the logs and decoded by hand...

In general in any board, if you have fix you have correct time, despite the battery status. And as you can see I have fix, logically checked and physically viewing the onboard led indicator.

Cheers!
