### ISSUE TITLE
matrix_keypad doesn't always set row pins as outputs properly

### ISSUE THREAD

**Issue by Wolverine-14** [esphome/issues#5776]
### The problem

when setting up a matrix keypad not all row pins are being set up properly. this shows as buttons connected to those rows giving no outputs unless there is also a Output Component set up on the same pins for the row component
[see my config with workaround implemented](https://github.com/esphome/issues/files/15269095/esphome-web-89db8c.txt)

### Which version of ESPHome has the issue?

2024.5.0b3

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

**Comment by ssieb** [comment]
This was fixed with https://github.com/esphome/esphome/pull/7163
