### ISSUE TITLE
Pillow version > 10.2.0 not accepted

### ISSUE THREAD

**Issue by zeirix** [esphome/issues#5797]
### The problem

Hello,

I did an upgrade on my system. Now I'm getting the error
`Please update your pillow installation to 10.2.0. (pip install "pillow==10.2.0").`
when I try to run my ESPHome config.
Currently I have python-pillow 10.3.0-2 installed

My distro is Manjaro Linux 24.0.0.

### Which version of ESPHome has the issue?

2024.5.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Anything in the logs that might be useful for us?

```txt
Please update your pillow installation to 10.2.0. (pip install "pillow==10.2.0").
```

**Comment by ssieb** [comment]
You need to use a venv with the correct pillow version.
