### ISSUE TITLE
Heartbeat filter for binary_sensor

### ISSUE THREAD

**Issue by craigueh** [esphome/issues#582]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**
I’m trying to use heartbeat filter option for binary_sensor on an esp32 but validation is failing. I read this was reported in https://github.com/esphome/ESPHome-Core/issues/140 and support would be added but still not working. 
Has this been removed or can I get it working another way?

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
The filter was added after the linked issue got closed.

But since then, it got removed again because it doesn't make sense anymore. See also https://esphome.io/changelog/v1.11.0.html?highlight=heartbeat
