### ISSUE TITLE
ESPHome devices disappear from the dashboard

### ISSUE THREAD

**Issue by hardl1** [esphome/issues#5873]
### The problem

About 3 weeks ago I installed my first ESPHome device under Homeassistant.
I was able to see the device from the ESPHome dashboard and edit it there. Additional devices have since been added.

Since yesterday there are suddenly no more devices on the dashboard. The Yaml files are visible in the file editor and the devices are also present in HA.
I restarted ESPHome, server and browser, with no change.
Then deleted the ESPHome add-on and reinstalled it, also beta.
The devices were back, but all with an update request.
After the first update the devices are all gone again.

What should I do?

### Which version of ESPHome has the issue?

 2024.5.4 + 2024.5.4 beta

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core 2024.5.5

### What platform are you using?

ESP8266

### Board

D1 mini

**Comment by ssieb** [comment]
Is this the same as https://github.com/esphome/issues/issues/5802?  Can you check your browser console?

**Comment by hardl1** [comment]
Looks like it, but I have no idea what that means.
<img width="718" alt="Bildschirmfoto 2024-06-02 um 10 31 14" src="https://github.com/esphome/issues/assets/38688960/a11202a9-165b-4f30-887c-0afbf6d1d4f9">

**Comment by hardl1** [comment]
Same problem with 3 different browsers.

**Comment by hardl1** [comment]
The highlighted line could be the problem, but I don't know how or what I could change.
<img width="723" alt="Bildschirmfoto 2024-06-02 um 12 20 23" src="https://github.com/esphome/issues/assets/38688960/50905f57-a089-4814-a6f4-ede8b01c7ca2">

**Comment by ssieb** [comment]
That's not the same issue as the other one.
What does that error message say?

**Comment by hardl1** [comment]
I found my mistake. 
I created a "New Device" esp129.yaml.
When copying from frost.yaml I mixed up the names.
In 129.yaml the name was: frost and in frost.yaml the name was esp129.
Your tip about the browser error showed me the way, thank you.
