### ISSUE TITLE
upgrading to 2024.6.1  breaks OTA key

### ISSUE THREAD

**Issue by wesselah** [esphome/issues#5961]
### The problem

after upgrading to 2024.6.1 i was not able to update the devices because ota key was not found even when in place and in the config on all devices. After rolling back to 2024.5.5  every thing is working again 

### Which version of ESPHome has the issue?

2024.6.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.6.4

### What platform are you using?

ESP8266

### Board

all boards have this issue so esp8266 and esp32

### Component causing the issue

ota

### Example YAML snippet

```yaml
ota:
  password:"otakey"

the ota key is underlined and says not found
```

### Anything in the logs that might be useful for us?

```txt
nothing found
```

**Comment by ssieb** [comment]
Read the changelog.
