### ISSUE TITLE
OTA automations do not get triggered

### ISSUE THREAD

**Issue by DeanCording** [esphome/issues#5965]
### The problem

OTA on_begin: and on_end:  automations do not get triggered during an OTA update using the ESPHome platform.

### Which version of ESPHome has the issue?

2024.6.0  onwards

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

### Board

ESP-12

### Component causing the issue

ota

### Example YAML snippet

```yaml
ota:
  - platform: esphome
    on_begin:
        then:
        - lambda: |-
            id(serial).write_str(" \n");
            id(serial).flush();
            id(serial).write_str("{\"reset\":1}\n");
            id(serial).flush();
            id(serial).write_str("Updating...\n");
            id(serial).flush();
    on_end:
        then:
        - lambda: |-
            id(serial).write_str(" \n");
            id(serial).flush();
            id(serial).write_str("{\"reset\":1}\n");
            id(serial).flush();
            id(serial).write_str("Rebooting...\n");
            id(serial).flush();
```

### Anything in the logs that might be useful for us?

[W][component:157]: Component esphome.ota set Warning flag: unspecified
[I][esphome.ota:326]: Update complete
[W][component:170]: Component esphome.ota cleared Warning flag
[I][app:132]: Rebooting safely...
[W][component:170]: Component mqtt cleared Warning flag
[I][mqtt:274]: MQTT Connected!
[W][esphome.ota:059]: Socket unable to bind: errno 112
[E][component:119]: Component esphome.ota was marked as failed.
[E][component:164]: Component esphome.ota set Error flag: unspecified
[I][app:062]: setup() finished successfully!
[I][app:100]: ESPHome version 2024.6.2 compiled on Jun 25 2024, 19:24:58
[E][component:082]:   Component esphome.ota is marked FAILED 

### Additional information

Tested with 2024.5.5 and it works as expected

**Comment by kbx81** [comment]
Based on your logs, this is likely because of #5952, not because of a problem with the automations.

**Comment by DeanCording** [comment]
Yes, that was the issue.
