### ISSUE TITLE
Dallas Temp Probes Reporting Incorrect Temps

### ISSUE THREAD

**Issue by hiltctn** [esphome/issues#5968]
### The problem

Dallas Temp probes potentially reporting incorrect temperature value after updating ESPHome

### Which version of ESPHome has the issue?

2024.6.x

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

Dallas

### Example YAML snippet

```yaml
Examples of YAML detailed in the thread linked below
```

### Additional information

After updating to 2024.6.x from 2024.5.x, the temperature probe appears to be reading around 3 degrees less than it should.  

More detail is highlighted here : https://community.home-assistant.io/t/dallas-temp-ds18b20-shows-lower-temperature-after-update/742739

In support of this potential finding, I compared my own Dallas temp in 2024.5.4 to a regular old school bulb thermometer.  They were near as makes no difference the same.  So on surface value at least, it appears that there is indeed an issue with the way Dallas has been implemented in 2024.6.x

**Comment by hiltctn** [comment]
I ran my own update and the temps are reporting fine.   Please feel free to close the issue if it doesn't warrant further investigation

**Comment by ssieb** [comment]
I've replied there.  It will be fixed in the next point release.  I'll leave this open to link with the PR.

**Comment by hiltctn** [comment]
> I've replied there. It will be fixed in the next point release. I'll leave this open to link with the PR.

Thank you kindly
