### ISSUE TITLE
All devices showing as "offline" but they really aren't

### ISSUE THREAD

**Issue by finity69x2** [esphome/issues#603]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

non-hassio HA in Docker on NUC running ESPHome v0.13.6

**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff, Shelly & NodeMCU

**Affected component:**

dashboard

**Description of problem:**

All devices show as "offline" in the ESPHome dashboard installed in docker.

As far as i can tell everything is working the way it should be - I can upload configs, see the OTA logs, etc.

It just shows that everything is offline all the time.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by caphm** [comment]
Same here. Running the dashboard in a docker container. When I execute ping in the container, the nodes all answer successfully.

**Comment by Anonym-tsk** [comment]
Use `--network host` in your container.
Or set `ESPHOME_DASHBOARD_USE_PING` environment variable to `True` in your container.
Or set `use_address` in your YAML.

**Comment by caphm** [comment]
@Anonym-tsk setting ESPHOME_DASHBOARD_USE_PING solved it. Thanks :)

**Comment by finity69x2** [comment]
@Anonym-tsk 

thanks, I didn't try --net=host but adding the environment variable fixed it. 

Here is the complete variable to add:

```
-e ESPHOME_DASHBOARD_USE_PING="true"
```
