### ISSUE TITLE
 esp32_ble_tracker - mac_address list

### ISSUE THREAD

**Issue by kuchel77** [esphome/issues#6032]
### The problem

In the documentation, for the esp32_ble_tracker it has 

```
esp32_ble_tracker:
  on_ble_advertise:
    - mac_address:
        - 11:11:11:11:11:11
        - 22:22:22:22:22:22
```

But if you copy and paste this, you get 
```
Failed config

esp32_ble_tracker: [source /config/powerpalesp32.yaml:51]
  on_ble_advertise: 
    - mac_address: 
        
        Must be string, got <class 'esphome.helpers.EInt'>. did you forget putting quotes around the value?.
        - 8698576271
        
        Must be string, got <class 'esphome.helpers.EInt'>. did you forget putting quotes around the value?.
        - 17397152542
```

If you put the mac addresses in either " " then it works as expected.

Everything else seems to expect a single item for mac_address options, whereas this one can be a list.

Should the documentation be updated, or is there something that should be fixed in the code. 

### Which version of ESPHome has the issue?

2024.6.6

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Component causing the issue

esp32_ble_tracker

### Example YAML snippet

```yaml
As above
```

### Anything in the logs that might be useful for us?

```txt
As above
```

**Comment by jesserockz** [comment]
This is simply a documentation issue as python recognises the all number mac address as a number and not a string. 
But you shouldn't be copying the example exactly, you should be using your own mac addresses and you would only get this error if there are no letters in your mac addresses.
