### ISSUE TITLE
"Sending state" printed in log for sensor with `internal: true` set

### ISSUE THREAD

**Issue by exetico** [esphome/issues#6037]
### The problem

I noticed that "Sending state" are printed for sensors where `internal: true` are set, which means, it's internal. 

The sensor are not listed in Home Assistant, not is it exposed on the ESP device itself, as expected.

But I don't expect to print `Stand up State Duration': Sending state 712.00000  with 0 decimals of accuracy` as it's not sending anything to anyone about that sensor.

### Which version of ESPHome has the issue?

2024.6.6

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

Not Home Assistant related (But tested with 2024.5.5 and 2024.7.2)

### What platform are you using?

ESP32

### Board

ESP32-C3 (https://www.aliexpress.com/item/1005005968727477.html)

### Component causing the issue

Logging

### Example YAML snippet

```yaml
- platform: template
    name: "${upper_devicename} State Duration"
    id: sit_stand_duration
    internal: true
    accuracy_decimals: 0
    update_interval: 1s
    lambda: |-
      static int last_state_change = 0;
      static int sit_duration = 0;
      static int stand_duration = 0;
      static bool previous_state = true; // Set initial state to sit
      int current_time = id(my_time_1).now().timestamp;
      float current_state = id(sit_stand_state).state;
      ...
```

### Anything in the logs that might be useful for us?

```log
17:01:40 | [D] | [sensor:094] | 'Stand up State Duration': Sending state 711.00000  with 0 decimals of accuracy
-- | -- | -- | --
17:01:40 | [D] | [sensor:094] | 'Stand up State': Sending state 1.00000  with 1 decimals of accuracy
17:01:41 | [D] | [sensor:094] | 'Stand up State Duration': Sending state 712.00000  with 0 decimals of accuracy
17:01:41 | [D] | [sensor:094] | 'Stand up State': Sending state 1.00000  with 1 decimals of accuracy
17:01:42 | [D] | [sensor:094] | 'Stand up State Duration': Sending state 713.00000  with 0 decimals of accuracy
17:01:42 | [D] | [sensor:094] | 'Stand up State': Sending state 1.00000  with 1 decimals of accuracy
17:01:43 | [D] | [vl53l0x:310] | 'Stand up distance' - Got distance 0.182 m
17:01:43 | [D] | [sensor:094] | 'Stand up distance': Sending state 0.18200 m with 2 decimals of accuracy
17
```

### Additional information

I 
<img width="1410" alt="image" src="https://github.com/esphome/issues/assets/3549445/d54c8af5-0142-4ddf-9cd5-8ffef5e643eb">

It's not critical at all. I'm just wondering why it's printing that, no that the "Stand up State Duration" are internal.

**Comment by ssieb** [comment]
It's sending to whatever is listening.  If it's internal, then that won't be the api or mqtt, but it might be the web server if that's enabled.  Or other components if they're linked.  Or the `on_value` trigger.  etc.
