### ISSUE TITLE
M5Atom Echo Ready-Made-Project: Only starts streaming when loud noise is detected

### ISSUE THREAD

**Issue by Neolanco** [esphome/issues#6068]
### The problem

I have the issue that the microphone will only be streamed to home assistant when making a loud sound (taping, blowing on the microphone) before saying the wakeword ("ok nabu" in my case).
This means I cannot just say the wakeword directly, which is quite frustrating.

As far as I understand, vad_threshold is handeling the voice detection, but chaning that value doesnt seem to change anything for me.

I hope I came to the right place with my issue ^^

### Which version of ESPHome has the issue?

M5Atom Echo Ready-Made-Project

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

M5Atom Echo

**Comment by dbensmith** [comment]
Sounds like the same issue as #6059

**Comment by Neolanco** [comment]
Thanks!
