### ISSUE TITLE
esphome and card hardware features ( psram )

### ISSUE THREAD

**Issue by blademckain** [esphome/issues#607]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**Affected component:**

hardware feature

**Description of problem:**

Hello,
for a project in development I would like to put an esp32 in every room of my house.
Connected to esp32 there will be:
-lights
-dimmable lights
-thermostatic valves
-temperature sensor
-motion sensor
-Push-buttons
I have to choose the esp32 card and ask for advice, according to you which is the best esp32 card of all?
What features are most important?

Better a board with 8MB PSRAM like this
http://www.raspberrypiwiki.com/index.php/ESP32_WROVER-i_DevKit 5
(esphome uses psram?)

or better a board with dual core like this
http://www.hiletgo.com/ProductDetail/1906566.html 

**Problem-relevant YAML-configuration entries:**
```yaml
```

**Logs (if applicable):**

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
> I have to choose the esp32 card and ask for advice, according to you which is the best esp32 card of all?

Just use any cheap ESP32 board you can find, there are mostly no big differenes.

PSRAM is not used anywhere (except in esp32_camera, but there you would buy special camera ESP32 modules).
dual core also isn't really effectively used by esphome, as the performance is already good enough.
