### ISSUE TITLE
Creating my first external component - few questions

### ISSUE THREAD

**Issue by WasuMrTomass0** [esphome/issues#6084]
### The problem

Hi experts,

I am not sure if this is the right place to ask about this.

I have an issue with creating my first external component that I would like to share with community. I have problem with understanding how to properly create top level files (__Init__.py, and top class).
From [docs external components](https://esphome.io/components/external_components.html) I know what is the file structure, how to set up testing evnritonmet and that the suggestion was to look at other components and figure things out. 

I struggle with getting a good understanding of what I am going to need for my component just by looking at other more complicated components. 

* How to configure all the pin, name, i2c bus config
* How to expose settings from my component (brightness controll, time delays, modes, etc.)
* How to use them in C++ code

My question to you would be: 
* What are some good entry level examples of components to learn from?
* Is there anything more than mentioned doc about external componets? 
* What would be your suggestion for me to start with components? Right now my plan is to create few basic components to break the issue in smaller problems and then I am going to try create config for my component. (C++ source code is ready. It just needs to be updated for ESPHome usage)
* Could you share what was your experience when you craeted your first component?

Thank you in advance for all your advices

### Which version of ESPHome has the issue?

2024.7.1

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

**Comment by ssieb** [comment]
This is not the right place.  You can look through the existing esphome components, many people have external component repos, and there is a repo with template examples for different types of components.  If you need more help, I suggest that you come ask on the esphome discord server.
