### ISSUE TITLE
How to start ESPHome actions from Home Assistant

### ISSUE THREAD

**Issue by bart1604** [esphome/issues#6098]
### The problem

More a question then an issue, and sorry if this is very clear but im just not seeing it.

I now have 4 Haier ESPHome working and connected to my home assistant, everything is working fine.
But on the page about Haier ESPHome (https://esphome.io/components/climate/haier.html)
You see that there are a lot of actions you can use, but they only discribe it to build in and automation in ESPHome itself.

For example, i want to use the "climate.haier.set_vertical_airflow" action, which can be used to let the airflow blow down.

Is there a way, to just start this action straight from home assistant?

### Which version of ESPHome has the issue?

2024.7.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.7.3

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

**Comment by ssieb** [comment]
github issues are not for questions.
If the climate component doesn't provide an interface for that in HA, then you will have to use a button, switch, service call, or something else to provide an interface on HA.
If you have more questions, then come ask on the esphome discord server or one of the forums.
