### ISSUE TITLE
mics_4514 sensor reading way off 

### ISSUE THREAD

**Issue by erkr** [esphome/issues#6106]
### The problem

I noticed that the sensor readings for the mics_4514 are way off. The current code two issues: Low concentrations are ignored, higher values are calculated wrong. 

Here is the graph for the datasheet for the RED sensor (the OX based sensors have the same issue):

![image](https://github.com/user-attachments/assets/c1409981-50d4-4596-a934-408bebe9201f)

I marked the thresholds used in code for the various sensors with colored dots. Two issues for each sensor:
- only concentrations on the right side of these dot are reported! Especially dangerous with the CO sensor that ignores values below 11ppm (red dot). Please note 6ppm is the max CO concentration for 24h, totally ignored by this implementation
- The value calculations are wrong! The datasheet graph is logarithmic, but the value interpolation is  done linear (only correct for the max concentrations).

### Which version of ESPHome has the issue?

Firmware: 2024.6.6 (Jul 8 2024, 07:53:53)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core 2024.7

### What platform are you using?

mics_4514

### Board

ESP32-C3 (Apollo Air-1 device)

### Component causing the issue

mics_4514

### Example YAML snippet

n/a the issue is in the component code itself. Here a code snippet of the component. 
- Arrow 1 marks the threshold (red CO dot in the graph)
- Arrow 2 the linear interpolation formula (only correct for the lowest red_f value 0.01):

![image](https://github.com/user-attachments/assets/b71edf6e-4f4c-4746-a46c-6021cd76fcbd)
(https://github.com/esphome/esphome/blob/3920029aff9dd85fd5f0775945b8426c03da471c/esphome/components/mics_4514/mics_4514.cpp#L71-L80)

### Anything in the logs that might be useful for us?

```txt
N/A
```

**Comment by erkr** [comment]
Update; I was able to determine the right math for calculating the CO value by mapping points from the datasheet onto a double log graph and find a matching function (see [here](https://www.desmos.com/calculator/u9abxqqxre)).
The calculation for CO should be:
```
if (red_f > 3.4f) {
 CO = 0.0;
}
else if (red_f < 0.01) {
  CO = 1000;
}
else {
  CO = 4.2/ pow(x,1.2);
}
```
I will determine the other sensors as well

**Comment by erkr** [comment]
Ammonia ([here](https://www.desmos.com/calculator/xknqara4nb)): 
if (red_f > 0.98f) {
 Ammonia = 0.0;
}
else if (red_f < 0.2532) {
  Ammonia = 500.0;
}
else {
  Ammonia = 0.9/ pow(x,4.6);
}

**Comment by erkr** [comment]
Methane ([here](https://www.desmos.com/calculator/dxjf1ygh84)):

if (red_f > 0.9f) {
 Methane = 0.0;
}
else if (red_f < 0.54) {
  Methane = 0.0;  // outside the range->unlikely
}
else {
  Methane = 630/ pow(x,4.4);
}

**Comment by erkr** [comment]
Ethanol ([here](https://www.desmos.com/calculator/86yjd1uvt7)):

```
if (red_f > 1.0f) {
  Ethanol = 0.0;
}
else if (red_f < 0.04) {
  Ethanol = 0.0; // outside the range->unlikely
}
else {
  Ethanol = 1.52/ pow(x,1.55);
}
```

**Comment by erkr** [comment]
Last but not least. NO2 on the OX sensor ([here](https://www.desmos.com/calculator/v0w0tsvgdb)):

```
if (ox_f < 0.3f) {
  NO2 = 0.0;
}
else {
  NO2 = 0.4 * pow(x,0.74);
}
```

**Comment by erkr** [comment]
Thanks for working on this🥳

> Working on a PR for this. Are they by chance backwards in some? CO example below

No, I believe I got that right.  Note in the graph the relation sensor readout of RED vs CO is negative. So smaller readouts are higher CO values. 
A readout of 3.4 represents the top left of the CO curve (1ppm), 0.01 represents the bottom right 1000ppm

**Comment by erkr** [comment]
Small remark. This formula:

``` 
CO = 4.2 / pow(red_f,1.2);
``` 

It's mathematically equal to:

``` 
CO = 4.2 * pow(red_f,-1.2);
``` 

Whatever you prefer☺️

**Comment by TrevorSchirmer** [comment]
Created a PR that matches. Mind taking a look @erkr 

https://github.com/esphome/esphome/pull/7173

**Comment by erkr** [comment]
Looks great. How does the process work? Will this be a dev version that we can test before realising it to the public?

**Comment by jesserockz** [comment]
> Looks great. How does the process work? Will this be a dev version that we can test before realising it to the public?

You can test the PR using [External Components](https://esphome.io/components/external_components.html)

Please confirm on the PR itself once tested.

**Comment by mperone** [comment]
Thanks for catching the original issue and finding curves that work better. I'm just coming off a heart attack from seeing all my sensor readings spike in the house before realizing that I had updated ESPHome a few hrs prior and following the thread here.

Anyway, wanted to chip in a thought.... your proposed updates (I'll use CO but same applies to all) use the curve you fitted across the entire sensor reading range, but then you applied piece-wise. This leaves awkward discontinuities, for instance in your CO logic:

> if (red_f > 3.4f) {
>  CO = 0.0;
> }
> else if (red_f < 0.01) {
>   CO = 1000.0;
> }
> else {
>   CO = 4.2/ pow(red_f,1.2);
> }

We get the result that a reading of more than 3.4 gets 0, but something very close to 3.4 jumps up to 4.2. That's actually my new baseline for CO it seems since I guess my sensor is reading something very close to 3.4. In fact, I'm getting the threshold value in your GAS = Threshold/ pow(red_f,EXP) formula for every gas off the MICS sensor now (ie Ethanol is reading 1.5, NO2 is reading .16, etc...)

**Comment by erkr** [comment]
I think there is also an initialisation issue. The math should be correct. When red_f equals 3.4 then pow(red_f,1,2) = 4.34. So the CO=4.3/4.34 = 0.99. For lower ref_f values the CO will become higher

**Comment by mperone** [comment]
Hi erkr - thanks for taking a look.... somehow I got got it backwards in my head and was calculating for red_f = 0 at the break. Will delete the original comment so as not to confuse.

**Comment by Ariosinm** [comment]
Hi everyone, I don't know if your update is the cause o what may have happened but since new update, my MICS4514 reports all the sensors as nan. 
In example:
`
[18:51:46][D][sensor:094]: 'MICS4514 Carbon Monoxide': Sending state nan ppm with 2 decimals of accuracy`

**Comment by TrevorSchirmer** [comment]
@Ariosinm 
Hi ,

Are you still having trouble with nan results? Your config looks very similar to ours. You are using the DFRobot MiCS-4514 sensor or a different style of MiCS-4514?


 - platform: mics_4514
    id: mics4514
    nitrogen_dioxide:
      name: Nitrogen Dioxide
    carbon_monoxide:
      name: Carbon Monoxide
    hydrogen:
      name: Hydrogen
    ethanol:
      name: Ethanol
    methane:
      name: Methane
    ammonia:
      name: Ammonia
    update_interval: 10s
