### ISSUE TITLE
ESPHome wizard is a lizard - installing on desktop venv

### ISSUE THREAD

**Issue by andzejsp** [esphome/issues#6135]
### The problem

In the documentation you can see that you can install the esphome on desktop. 
![image](https://github.com/user-attachments/assets/79fa2540-eb93-4ac0-95cd-7b975181912b)

While the installation page is accessible, its not very visible on the first page. You have to search deep for it, and to even know it exist.
https://esphome.io/guides/installing_esphome.html

Next after creating the venv like a human should, we get to the wizard.

```
 esphome wizard pc2.yaml
```
Greeted gently by the wizard we follow the prompts carefully.
![image](https://github.com/user-attachments/assets/94625d14-308c-4bb1-a99d-f67222f90396)

Until the STEP 2 where we enter host

And get a response that it does not exist.
```
Unfortunately, I can't find an espressif microcontroller called "host". Please try again.

(ESP32/ESP8266/BK72XX/RTL87XX/RP2040):

```

So what am i supposed to do here?

Ok, so if fw is ESP "BASED" then how can i create "Virtual" ESP device that doesnt require WIFI to function?

Because using the ESP32 as the controller in the STEP 2 will ask for a wifi creds.

### Which version of ESPHome has the issue?

Version: 2024.7.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

no home assistant

### What platform are you using?

ESP32

### Board

desktop PC windows 10

**Comment by randybb** [comment]
This option is not available in any wizard as it is only for testing. Anyway, it will not work under windows, only under linux/macosx.
