### ISSUE TITLE
Bluetooth Proxys unavailable since 2024.8

### ISSUE THREAD

**Issue by Lux315** [esphome/issues#6137]
### The problem

All bluetooth proxys and their devices are offline and unavailable since 2024.8
![IMG_8979](https://github.com/user-attachments/assets/4151aa91-d590-4978-bab4-a52f19a9ed96)

### Which version of ESPHome has the issue?

2024.7.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.8

### What platform are you using?

ESP32

**Comment by ssieb** [comment]
How did you install it?
The message tells you what the issue is.

**Comment by fjavimer** [comment]
I have exactly the same problem. Has anyone been able to solve it?

**Comment by Lux315** [comment]
I reinstalled the proxy and now it works fine for me

**Comment by fjavimer** [comment]
working, thank you very much
