### ISSUE TITLE
Pronto IR dump is not conforming to standard

### ISSUE THREAD

**Issue by Miq1** [esphome/issues#6147]
### The problem

When dumping Pronto data from the ``remote_receiver`` component the output is not valid according to the specs. Simplifyingly speaking the Pronto data consists of a header and two optional burst blocks. Each of these must contain an even number of data words, namely an on cycles word and an off cycles word.
While this is maintained in the component, an additional ``off word`` is added unconditionally [here](https://github.com/esphome/esphome/blob/2a70ef05d17c0645fd4e9023d6b1bc5c2ea078ca/esphome/components/remote_base/pronto_protocol.cpp#L222).
This makes the word count odd, causing f.i. IRScrutinizer to bail out with an error.

The addition of that word seems to be intending to add a safety gap between two IR bursts, but will fail doing that.

- as an off cycle always will follow an on cycle which is missing here, it will not be applied
- most IR remotes will add such off interval after their sent sequence anyway
- detecting an IR transmission will require the receiver to wait for some quiet time to detect the end of the signal. This is obviously done in ``remote_receiver``, so the last off cycle dumped usually is much longer already.

### Which version of ESPHome has the issue?

newest

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Component causing the issue

remote_receiver

**Comment by ssieb** [comment]
I've meant to do something about this for quite a while.  I didn't realize it was such a simple fix.   Please try the PR.
