### ISSUE TITLE
Updates kills the device also some alternations of code and upload does the same

### ISSUE THREAD

**Issue by bandric1** [esphome/issues#615]
I was updating nodes from 1.12.2 ➡️1.13.6 latest and node after node died after upgrade. Sonoff basic, SV. NodeMCU etc.

I had also a particular issue with sonoff SV after migration from tasmota to esphome it connected to network and appeared on the list 10 sec later it was unavailable so i removed it from its working enviroment reflashed via 323 it directly and got it to connect again then aletered code defined working paramaters and OTA flashed it and bum its gone again cant revieve it again it wont reconnect back no matter what i try or do.

**Comment by glmnet** [comment]
May be a duplicate of https://github.com/esphome/issues/issues/455
