### ISSUE TITLE
1 wire dallas sensor does does not report any value if logger is in level info

### ISSUE THREAD

**Issue by jrvrcd** [esphome/issues#6162]
### The problem

Dear ESP HOME TEAM

1 wire dallas sensor does does not report any value if logger is in level info whereas temperature is reported if logger is in debug

### Which version of ESPHome has the issue?

2024.7.3 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.08

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

one_wire

**Comment by jesserockz** [comment]
Umm. What?

The logs for both dallas_temp where it says Got Temperature and the Sensor log where it says Sending State are both at `DEBUG` level, so of course you wont see them if you change the level to INFO. This does not affect the actual sensor publishing.
