### ISSUE TITLE
Docs for LVGL tips/cookbook

### ISSUE THREAD

**Issue by nickrout** [esphome/issues#6225]
### The problem

The preview for LVGL docs has this useful page https://deploy-preview-4115--esphome.netlify.app/cookbook/lvgl but it is not in current docs. This is a doc issue so I haven't filled in most of this template, but can't find anywhere else to post it. It may be in the pipeline, but it would be handy to refer people to, 

### Which version of ESPHome has the issue?

2024.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.8

### What platform are you using?

ESP32-IDF

### Board

Guition

### Component causing the issue

Docs

### Example YAML snippet

```yaml
None
```

### Anything in the logs that might be useful for us?

```txt
No
```

**Comment by randybb** [comment]
It is simple - It was not merged as it is not ready yet.

**Comment by nickrout** [comment]
Thanks.
