### ISSUE TITLE
No password for OTA via HTTP web page

### ISSUE THREAD

**Issue by tripplet** [esphome/issues#626]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 (Sonoff S20)
**Affected component:**

http and ota

**Description of problem:**
Enabling the HTTP component allows for an OTA update via the web page, this kind of defeats the purpose of having and OTA password and seems a bit unsecure by default.
A http basic protection for the OTA feature would be nice or the option to disable it for HTTP.
At least the documentation should mention this, for me this was kind of unexpected.
Generally I an option to protect the web page with a password would be nice.

**Problem-relevant YAML-configuration entries:**
```yaml
web_server:
  port: 80
ota:
  password: "supersecret"
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

Not relevant.

**Comment by OttoWinter** [comment]
This is more of a feature request IMO. -> https://github.com/esphome/feature-requests
