### ISSUE TITLE
XL9535 why 0-7 10-17 pins are used instead of 0-15?

### ISSUE THREAD

**Issue by mahnunchik** [esphome/issues#6265]
### The problem

I've faced with the fact that `0-7` and `10-17` pins are used instead of more logical `0-15`?

Python code: https://github.com/esphome/esphome/blob/8e5d7337c8e9490c901cd17f59b72ed300f775b1/esphome/components/xl9535/__init__.py#L38-L43

Cpp code: https://github.com/esphome/esphome/blob/dev/esphome/components/xl9535/xl9535.cpp#L39

It seems it should be:

```cpp
register_data = register_data & (~(1 << (pin - 8)));
```

And there will be no need for hacks and checks to work with a continuous range of pins from `0` to `15`.

### Which version of ESPHome has the issue?

2024.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.9.2

### What platform are you using?

ESP32

### Board

XL9535 relay board

### Component causing the issue

https://github.com/esphome/esphome/blob/dev/esphome/components/xl9535/xl9535.cpp#L39

### Additional information

Related:

* https://github.com/esphome/esphome/discussions/5710
* https://community.home-assistant.io/t/xl9535-integration/637632
* https://github.com/esphome/esphome/pull/5722/files
* https://www.lcsc.com/datasheet/lcsc_datasheet_2211110930_XINLUDA-XL9535_C561273.pdf

**Comment by ssieb** [comment]
If you look at the datasheet that you linked, it's how the manufacturer labels the pins.
And you linked all the reasons that the component was changed to be this way, so I have no idea what your point is.
