### ISSUE TITLE
2024.9.2: Substitution must only consist of upper/lowercase characters, the underscore and numbers. The character '-' cannot be used.

### ISSUE THREAD

**Issue by 532910** [esphome/issues#6303]
### The problem

  
  Substitution must only consist of upper/lowercase characters, the underscore and numbers. The character '-' cannot be used.
  eugene-phone_ibeacon_uuid: UUID

### Which version of ESPHome has the issue?

2024.9.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Additional information

Such breaking changes MUST NOT happen on minor update. 2024.9.1 worked fine

**Comment by ssieb** [comment]
That code hasn't changed in years.

**Comment by 532910** [comment]
hmm, indeed, my fault
