### ISSUE TITLE
slzb06 does not update

### ISSUE THREAD

**Issue by javifly** [esphome/issues#6368]
### The problem

Hi,

I have a SLZB06 from smlight working as bluetooth proxy in home assistant.

Now my home assistant has detected it under the esphome integration and tells me that my firm version is 2024.9.2 and that there is a new one, the 2024.10.1 and from home assistant does not let me update the device indicating that the file for this device is not available via ota.

The manufacturers of the slzb06 tell me that everything is correct on their side. They think it's esphome bug because the firmware has ota component with esphome platform, can check it here https://github.com/smlight-dev/slzb-06-fw-esphome/blob/main/configs/bt.yaml

Kind regards, Taras
<img width="713" alt="Captura de pantalla 2024-10-21 164607 (1)" src="https://github.com/user-attachments/assets/188b1b17-3b61-4860-a61b-f297f9bcdcf9">

### Which version of ESPHome has the issue?

2024.10.1 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.10.3

### What platform are you using?

ESP8266

**Comment by javifly** [comment]
Does no one know about this matter?

**Comment by javifly** [comment]
Does no one know about this matter?

**Comment by randybb** [comment]
It is exactly telling what you have to do. There was a breaking change in [2024.6](https://esphome.io/changelog/2024.6.0#ota-platforms) you need to update your config accordingly. The linked config has it fixed, your local one does not.

**Comment by javifly** [comment]
Where should I make these changes? In which file?
`# Old
ota:

# New
ota:
  platform: esphome`

**Comment by randybb** [comment]
Can you share your full config?
![image](https://github.com/user-attachments/assets/8cc1ee06-26a1-467a-885b-b18d33594848)

**Comment by javifly** [comment]
yes, it is:

substitutions:
  name: slzb-06-bluetooth-f7c714
packages:
  SMLIGHT.SLZB-06(Bluetooth-only): github://smlight-tech/testesphome/bt.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by Tarik2142** [comment]
You are using outdated firmware or outdated config. You can find the current config here https://github.com/smlight-dev/slzb-06-fw-esphome/blob/main/configs/bt.yaml

**Comment by javifly** [comment]
should I change?
__SMLIGHT.SLZB-06(Bluetooth-only): github://smlight-tech/testesphome/bt.yaml

for this other?
__SMLIGHT.SLZB-06(Bluetooth-only): github://smlight-dev/slzb-06-fw-esphome/blob/main/configs/bt.yaml](https://github.com/smlight-dev/slzb-06-fw-esphome/blob/main/configs/bt.yaml

**Comment by Tarik2142** [comment]
__SMLIGHT.SLZB-06(Bluetooth-only): github://smlight-dev/slzb-06-fw-esphome/configs/bt.yaml

**Comment by javifly** [comment]
I have tried to change in the file

/homeassistant/esphome/slzb-06-bluetooth-f7c714.yaml

the line:

SMLIGHT.SLZB-06(Bluetooth-only): github://smlight-tech/testesphome/bt.yaml

By the line:

SMLIGHT.SLZB-06(Bluetooth-only): github://smlight-dev/slzb-06-fw-esphome/configs/bt.yaml

I have restarted the Home Assistant virtual machine. But the updates are not working either. I leave screenshots of the errors obtained:
 
<img width="1144" alt="image" src="https://github.com/user-attachments/assets/52d13aad-89fc-4dbb-acf2-378210b89bf0">

<img width="547" alt="image" src="https://github.com/user-attachments/assets/3337c432-ba73-4cbe-804b-c557d66f4a85">
