### ISSUE TITLE
UART interface is super noisy for gap-delimited protocols.

### ISSUE THREAD

**Issue by fake-name** [esphome/issues#638]
I have a piece of software that uses gap-delimited serial messages. Basically, you read until you don't get any bytes for a period of time, and then parse the received message. 

Right now, every time I try to read from the device, I get

```
[00:36:56][E][uart:090]: Reading from UART timed out at byte 0!
```

Now, if there was a way to turn this off, that'd be fine, but there isn't. You're stuck with it. You can't change the hard-coded timeouts either.

Basically, a timeout should not be assumed to be an error, and it shouldn't be logged as such. 

There's also no way to change the serial mode (I need `8N2`, not the default `8N1`), but that's a separate issue. For the moment, I've fixed it by just hacking on `uart.cpp` in the python directory, but that's pretty damn horrible.

------

Irrelevant issue template cruft:

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
Not relevant

```

**Logs (if applicable):**

```
Not relevant

```

**Additional information and things you've tried:**

**Comment by brandond** [comment]
Call `available()` to see if there's any data in the RX buffer instead of blindly calling `read()`.

**Comment by OttoWinter** [comment]
@brandond Is right, with available you can check how much is in the receive buffer. That is the correct way to read from the bus - the timeout is there to protect the main esphome loop from getting caught up waiting for data that never arrives.
