### ISSUE TITLE
First time user

### ISSUE THREAD

**Issue by berasomnath** [esphome/issues#6424]
### The problem

I have installed "Empty ESPHome Device" on an ESP32 board. It got installed. The first page is opening at 192.168.43.16. The board is connected to my serial port. But I am not able to connect any "new device" as there is no "new device" button in the page. A
<img width="1671" alt="Screenshot 2024-11-12 at 8 37 56 AM" src="https://github.com/user-attachments/assets/f0fada95-8d02-4338-883c-2c261b8677d3">
![screenshot1](https://github.com/user-attachments/assets/bda180f9-93bd-4275-bd90-383de4d177d9)
@lso there is an "OTA update" window for which I do not know. What to do from here now

### Which version of ESPHome has the issue?

ESPHome Web ea07b0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

ESP-Wroom-32

**Comment by berasomnath** [comment]
I have installed "Empty ESPHome Device" on an ESP32 board. It got installed. The first page is opening at 192.168.43.16. The board is connected to my serial port. But I am not able to connect any "new device" as there is no "new device" button in the page. How to proceed from here.

**Comment by ssieb** [comment]
That is not the esphome dashboard, that's the device web page.
This is not the place for support questions.  Come ask for help on the esphome discord server.
