### ISSUE TITLE
LVGL & SSD1351: Blank screen when "update_interval: never"

### ISSUE THREAD

**Issue by zoide** [esphome/issues#6428]
### The problem

I'm starting to use lvgl with esphome and a Waveshare SSD1351 Oled display.

According to the docs for lvgl, I should set "update_interval: never" when configuring the display.

However, when I do that, I get only a blank screen.

As soon as I set the update_interval to something else (i.e.: default 1s) contents are shown.

### Which version of ESPHome has the issue?

2024.10.3

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

ESP32-WROOM-2 (4MB PSRAM)

### Component causing the issue

lvgl

### Anything in the logs that might be useful for us?

```txt
No errors.
```

**Comment by clydebarrow** [comment]
that's actually correct for the OLED displays - the drivers for those have not been updated for LVGL so still require an update interval to copy the buffer to the screen. So it's a documentation issue rather than a code problem.
