### ISSUE TITLE
Change or bug? Font glyphs now require quotes around number

### ISSUE THREAD

**Issue by Cenedd** [esphome/issues#6463]
### The problem

If specifying all the characters required for a font (to add some extra symbols but maintain normal characters), it seems you now have to add quotes around any numerals or they comilation fails because they aren't a string.

The code below works but previously the numbers could just be part of the unquoted list like the alpha's.  Not sure if this is intentional or not but at worst it may help someone trying to work out why it isn't acepted after 2024.11

```
    glyphs: [
      A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,
      a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,
      (,),+,-,_,.,°,/,
      "0","1","2","3","4","5","6","7","8","9",
      "\u0020", #space
      "\u0021", #!
      "\u0022", #"
      "\u0023", ##
      "\u0024", #$
      "\u0025", #%
      "\u0026", #&
      "\u0027", #'
      "\u002c", #,
      "\u003a", #:
      "\u003b", #:
      "\u003d", #=
      "\u003f", #?
      ]
```

### Which version of ESPHome has the issue?

2024.11

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

M5Stack Atom S3

### Component causing the issue

font

### Example YAML snippet

```yaml
font:
  - file: "gfonts://Noto+Sans"
    id: font_clock
    size: 45
  - file: "gfonts://Josefin+Sans"
    id: font_default
    size: 20
    glyphs: [
      A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,
      a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,
      (,),+,-,_,.,°,/,
      "0","1","2","3","4","5","6","7","8","9",
      "\u0020", #space
      "\u0021", #!
      "\u0022", #"
      "\u0023", ##
      "\u0024", #$
      "\u0025", #%
      "\u0026", #&
      "\u0027", #'
      "\u002c", #,
      "\u003a", #:
      "\u003b", #:
      "\u003d", #=
      "\u003f", #?
      ]
```

### Anything in the logs that might be useful for us?

```txt
Must be string, got <class 'esphome.helpers.EInt'>. did you forget putting quotes around the value?.
```

**Comment by clydebarrow** [comment]
The expectation is that the glyphs should be strings, so while this is a breaking change, it does remove ambiguity and closes a probably unintentional loophole in the original code. You can combine multiple chars in a string, e.g. "0123456789".
