### ISSUE TITLE
Error compiling code, which includes "font" component

### ISSUE THREAD

**Issue by Atarinside** [esphome/issues#6467]
### The problem

Please see : https://github.com/esphome/esphome/pull/5985
and 
https://github.com/esphome/issues/issues/5109
We have the exact same problem (again) with ESPHome 2024.11.0

### Which version of ESPHome has the issue?

2024.11.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

All

### What platform are you using?

ESP8266

### Board

ESP32

### Component causing the issue

libtiff.so.6

### Example YAML snippet

```yaml
INFO ESPHome 2024.11.0
INFO Reading configuration /config/esphome/esp32-temp-humid.yaml...
INFO Detected timezone 'Europe/Paris'
INFO Generating C++ source...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/esphome/esphome/__main__.py", line 1036, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1023, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 452, in command_compile
    exit_code = write_cpp(config)
                ^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 212, in write_cpp
    generate_cpp_contents(config)
  File "/esphome/esphome/__main__.py", line 224, in generate_cpp_contents
    CORE.flush_tasks()
  File "/esphome/esphome/core/__init__.py", line 684, in flush_tasks
    self.event_loop.flush_tasks()
  File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
    next(task.iterator)
  File "/esphome/esphome/__main__.py", line 204, in wrapped
    await coro(conf)
  File "/esphome/esphome/components/font/__init__.py", line 557, in to_code
    base_font = EFont(config[CONF_FILE], size, point_set)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/components/font/__init__.py", line 475, in __init__
    self.font = load_ttf_font(path, size)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/components/font/__init__.py", line 519, in load_ttf_font
    from PIL import ImageFont
  File "/usr/local/lib/python3.11/dist-packages/PIL/ImageFont.py", line 39, in <module>
    from . import Image
  File "/usr/local/lib/python3.11/dist-packages/PIL/Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: libtiff.so.6: cannot open shared object file: No such file or directory
```

### Anything in the logs that might be useful for us?

```txt
Can be fixed manually :

Open Terminal within HA, then :

docker exec -it addon_5c53de3b_esphome /bin/bash

apt-get update
apt-get install libopenjp2-7 libtiff6
```

**Comment by bert269** [comment]
Still not working. And it seems the ESPHome entry on the left panel shows now "ESPHome Device Compiler" - not a problem, just saying.

I wish I can get the recompiles to go through

**Comment by clydebarrow** [comment]
I can't reproduce this problem - can you please attach sample yaml, and specify what system you are running HA on.

**Comment by Atarinside** [comment]
Core  2024.11.3
Supervisor  2024.11.4
Operating System 13.2
Interface utilisateur 20241106.2
Hardware : odroid-xu4 (HA OS)

here's a sample yaml ( i replaced secrets with ---)

############ BUREAU ############
esphome:
  ##--------------------------Personnalisation--------------------------##
  name: esp32-temp-humid

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

#### Ajout d'un logger (valeur par défaut)" ####
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "---"

#### Gestion du WIFI ####
ota:
 - platform: ---
   password: "---"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ##--------------------------Personnalisation--------------------------##
    ssid: "---"
    password: "---"
captive_portal:

#### Ajout d'un état binaire "dispo ou pas dispo" ####
binary_sensor:
  - platform: status
  ##--------------------------Personnalisation--------------------------##
    name: "Etat TempBureau"

#### Ajout de la version ####
text_sensor:
  - platform: version
  ##--------------------------Personnalisation--------------------------##
    name: "ESPHome Version TempBureau"

#### Ajout d'un bouton de restart ####
switch:
  - platform: restart
  ##--------------------------Personnalisation--------------------------##
    name: "Restart TempBureau"

#### Ajout des sensors qu'on va remonter à Home Assistant ####
sensor:
  - platform: dht
    pin: GPIO04
    temperature:
      ##--------------------------Personnalisation--------------------------##
      name: "Temperature Bureau"
      id: temp
      filters:
        ##--------------------------Personnalisation--------------------------##
        - lambda: return x-2.1;
    humidity:
      ##--------------------------Personnalisation--------------------------##
      name: "Humidité Bureau"
      id: humid
    update_interval: 5s
  - platform: wifi_signal
  ##--------------------------Personnalisation--------------------------##
    name: "WiFi Signal TempBureau"
    update_interval: 60s

#### Mise à jour de l'heure ####
time:
  - platform: sntp
    id: sntp_time
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

##### Affichage écran #####
i2c:
  sda: GPIO21
  scl: GPIO22
  frequency: 400kHz

font:
  - file: "fonts/comic-sans-ms.ttf"
    id: my_font
    size: 20

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    # reset_pin: D0
    address: 0x3C
    lambda: |-
      it.strftime(0, 00, id(my_font), "   %H:%M:%S", id(sntp_time).now());
      it.printf(0, 18, id(my_font), "Temp:  %.1fc", id(temp).state);
      it.printf(0, 36, id(my_font), "Humid: %.1f%%", id(humid).state);

**Comment by clydebarrow** [comment]
Ah, you're running on armv7l. The other architectures appear to work fine. Will look into it further.

**Comment by TheStork239** [comment]
I’m having exactly the same issue, with code using the font component (in my case for a waveshare e-paper display), on an ESP8266.  Problem started with ESPHome 2024.11.0; updating to 2024.11.1 did not make a difference.

**Comment by clydebarrow** [comment]
> My HomeAssistant is running on a Raspberry Pi 4 (not sure if that is armv7l?)

If you're seeing the problem it must be. The Pi4 will run arm64 but that build does not suffer from this issue.
