### ISSUE TITLE
lvgl widget Line (is it possible to set up points using lambda?)

### ISSUE THREAD

**Issue by LGhost1973** [esphome/issues#6475]
### The problem

Is it possible to set up points using lambda?

### Which version of ESPHome has the issue?

last

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

last

### What platform are you using?

ESP32

**Comment by clydebarrow** [comment]
yes, it should be. you will just need to figure out the correct syntax. I'd suggest you look at the generated code for lines to do that.

**Comment by LGhost1973** [comment]
is it possible to describe this in the documentation for widget Line?

**Comment by LGhost1973** [comment]
and is there a transfer plan for the widget Charts?

**Comment by clydebarrow** [comment]
> is it possible to describe this in the documentation for widget Line?

No, it's not practical to include in the documentation all the implementation details of widgets. The chart widget will be implemented at some point, can't offer a timeline ATM.
