### ISSUE TITLE
Touchscreen FT5X06 interrupt pin is an invalid option

### ISSUE THREAD

**Issue by 5of9** [esphome/issues#6518]
### The problem

With Touchscreen FT5X06 and set interrupt_pin I get [interrupt_pin] is an invalid option for [touchscreen.ft5x06]
As written in the documentation interrupt_pin could be used, so one thing is wrong, manual or implementation?

https://esphome.io/components/touchscreen/ft5x06.html

### Which version of ESPHome has the issue?

2024.4.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

m5dial

### Component causing the issue

ft5x06

**Comment by clydebarrow** [comment]
Update your ESPHome version - the docs refer to the latest released version.
