### ISSUE TITLE
Update from console fails - `ERROR Error resolving IP address: Int or String expected`

### ISSUE THREAD

**Issue by r-xyz** [esphome/issues#6521]
### The problem

The issue seems to affect 2024.11.2, and probably all 2024.11.X.
2024.10.X is not affected.

Trying to flash a device wirelessly results in an error resolving the IP when no static IP is used.
Nonetheless:

- logs also show the IP being correctly resolved from the hostname
- the IP is reachable by esphome and firewall shows ping packets being correctly forwarded.

Downgrading to 2024.10.x, the upgrade works flawlessly.

### Which version of ESPHome has the issue?

2024.11.X

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

any

### YAML Config

```yaml
# Relevant YAML
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .esphome

mdns:
  disabled: true 

api:
  port: 8200
  encryption:
    key: REDACTED

# Enable OTA updates
ota:
  - platform: esphome
    password: REDACTED
    port: 8201
```

### Anything in the logs that might be useful for us?

```txt
Building .pioenvs/test/firmware.bin
esp8266_copy_factory_bin([".pioenvs/test/firmware.bin"], [".pioenvs/test/firmware.elf"])
esp8266_copy_ota_bin([".pioenvs/test/firmware.bin"], [".pioenvs/test/firmware.elf"])
========================= [SUCCESS] Took 78.31 seconds =========================
INFO Successfully compiled program.
ERROR Error resolving IP address of 192.168.1.100. Is it connected to WiFi?
ERROR (If this error persists, please set a static IP address: https://esphome.io/components/wifi.html#manual-ips)
ERROR Error resolving IP address: Int or String expected
```
```


### Additional information

_No response_

**Comment by randybb** [comment]
Already fixed https://github.com/esphome/esphome/pull/7888 - will be in 2024.11.3
