### ISSUE TITLE
As of 2024.11.3 cannot compile anymore

### ISSUE THREAD

**Issue by jelmerkk** [esphome/issues#6526]
### The problem

All compiles give the same error:
`xtensa-esp32-elf-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.`
This happens with own YAML but also with packages such as bluetooth proxy or the voice assistant

### Which version of ESPHome has the issue?

2024.11.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.12.1

### What platform are you using?

ESP8266

### Board

shelly, atom echo, nodemcu

### Anything in the logs that might be useful for us?

Nothing in the ESPHOME logs except the error msg above. 

### Additional information

Host is a Yellow with 4GB ram.

**Comment by ssieb** [comment]
You probably need more RAM.  Otherwise, change the addon settings to reduce the number of compile processes.

**Comment by jelmerkk** [comment]
Hmm. After HAOS reboot a compile went OK without using more than 60% of the 4GB RAM. 
I'll see if the issue resurfaces, thanks for thinking along!

**Comment by ssieb** [comment]
After a reboot, less things are running.  Just make sure you don't end up thrashing the swap.

**Comment by jelmerkk** [comment]
Yeah and it's very tempting to solve it permanently with an 8Gb CM5...
