### ISSUE TITLE
Can't update for ESPHome 2024.11.3

### ISSUE THREAD

**Issue by kuchar91** [esphome/issues#6527]
### The problem

As title says. Can't update ESP Home HA Addon

### Which version of ESPHome has the issue?

2024.11.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.12.1

### What platform are you using?

ESP8266

### Anything in the logs that might be useful for us?

```txt
[supervisor.docker.interface] Can't install ghcr.io/esphome/esphome-hassio:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fesphome%2Fesphome-hassio&platform=linux%2Famd64: Internal Server Error ("Head "https://ghcr.io/v2/esphome/esphome-hassio/manifests/2024.11.3": Get "https://ghcr.io/token?scope=repository%3Aesphome%2Fesphome-hassio%3Apull&service=ghcr.io": dial tcp 140.82.121.33:443: i/o timeout")
```

**Comment by ssieb** [comment]
That's either a problem with your network or internet connection or it's a github server issue.
