### ISSUE TITLE
Thermostat controller does not control heater when switched to HEAT mode.

### ISSUE THREAD

**Issue by dwmw2** [esphome/issues#6557]
### The problem

I use a [Thermostat Climate Controller](https://esphome.io/components/climate/thermostat) to control underfloor heating. ([`ufh.yaml`](https://git.infradead.org/?p=users/dwmw2/esp32-pool.git;a=blob;f=ufh.yaml))

If the heating is manually turned on/off by an actual meat person, then the thermostat is temporarily disabled (set to `OFF` mode) for half an hour, and then is re-engaged by a `back_to_auto` script which was triggered when the manual setting occurred:
```
  - id: back_to_auto
    mode: restart
    then:
      - delay: 30 min
      - climate.control:
          id: ntc_climate
          mode: HEAT
```

The problem is that when the thermostat is turned on again, it doesn't take control of the heating. If the user had manually turned the heating on, and the target temperature has been reached/exceeded, we'd expect the thermostat to turn it off again when re-engaged. But instead, it just leaves the heater on as it keeps getting hotter and hotter and hotter...

Manual switch on (disengages thermostat)
```
Dec 15 12:39:38 kitchen switch ﻿[D][switch:012]: 'Kitchen UFH' Turning ON.
Dec 15 12:39:38 kitchen switch ﻿[D][switch:055]: 'Kitchen UFH': Sending state ON
Dec 15 12:39:38 kitchen climate ﻿[D][climate:011]: 'Kitchen floor' - Setting
Dec 15 12:39:38 kitchen climate ﻿[D][climate:015]:   Mode: OFF
Dec 15 12:39:38 kitchen climate ﻿[D][climate:396]: 'Kitchen floor' - Sending state:
Dec 15 12:39:38 kitchen climate ﻿[D][climate:399]:   Mode: OFF
Dec 15 12:39:38 kitchen climate ﻿[D][climate:401]:   Action: OFF
Dec 15 12:39:38 kitchen climate ﻿[D][climate:419]:   Current Temperature: 25.15°C
Dec 15 12:39:38 kitchen climate ﻿[D][climate:425]:   Target Temperature: 10.00°C
```

Thermostat re-engages after 30 minutes:
```
Dec 15 13:09:38 kitchen climate ﻿[D][climate:011]: 'Kitchen floor' - Setting
Dec 15 13:09:38 kitchen climate ﻿[D][climate:015]:   Mode: HEAT
Dec 15 13:09:38 kitchen climate ﻿[D][climate:396]: 'Kitchen floor' - Sending state:
Dec 15 13:09:38 kitchen climate ﻿[D][climate:399]:   Mode: HEAT
Dec 15 13:09:38 kitchen climate ﻿[D][climate:401]:   Action: IDLE
Dec 15 13:09:38 kitchen climate ﻿[D][climate:419]:   Current Temperature: 28.59°C
Dec 15 13:09:38 kitchen climate ﻿[D][climate:425]:   Target Temperature: 10.00°C
```
But it *didn't* run its `idle_action`. And then it stays like that, with the heating still on, until I realise it's overheating:
```
Dec 15 15:47:43 kitchen climate ﻿[D][climate:396]: 'Kitchen floor' - Sending state:
Dec 15 15:47:43 kitchen climate ﻿[D][climate:399]:   Mode: HEAT
Dec 15 15:47:43 kitchen climate ﻿[D][climate:401]:   Action: IDLE
Dec 15 15:47:43 kitchen climate ﻿[D][climate:419]:   Current Temperature: 32.56°C
Dec 15 15:47:43 kitchen climate ﻿[D][climate:425]:   Target Temperature: 10.00°C
```
It looks like I can trick it into running the `idle_action` or `heat_action` as appropriate, with a `heat_mode` action:
```
    heat_mode:
      - lambda: |-
         // If the heater is already on, let the thermostat know. Otherwise it won't turn it off!
         if (id(ufh_relay).state)
           id(ntc_climate)->action = esphome::climate::CLIMATE_ACTION_HEATING;
         else
           id(ntc_climate)->action = esphome::climate::CLIMATE_ACTION_IDLE;
         ESP_LOGD("ufh", "Start heating, current action %s", LOG_STR_ARG(climate_action_to_string(id(ntc_climate)->action)));
```

But that's very counterintuitive. Shouldn't the thermostat component run the appropriate action when it's re-engaged, to ensure that the system is in the mode it expects? And if not, this should be documented clearly as it could cause real damage.
```

### Which version of ESPHome has the issue?

2024.11.2-dev

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32-IDF

### Board

esp32-gateway

### Component causing the issue

thermostat

### YAML Config

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

**Comment by ssieb** [comment]
The problem is that you're doing things behind its back.  It can only assume that it knows the full state.  Your re-engaging script needs to fix the state first.

**Comment by dwmw2** [comment]
That's what I've made it do, but if that's necessary then it should be clearly documented.

Better still, rrather than *assuming* its idea of the state is correct when it is turned on, it could just *set* the state it expects/needs to ensure it?

**Comment by ssieb** [comment]
Why would that have to be documented?  Are you going to document that for every component?  Don't mess around with a component's state without telling it.  Calling triggers when not needed is bad.  The user has a valid assumption that the trigger is only going to get called when necessary.

**Comment by dwmw2** [comment]
Surely the trigger ought to be idempotent? If the thermostat is off(and Action:OFF) and then I switch it on and then it says Action:HEAT) is it not reasonable to expect it to invoke the heating trigger?

**Comment by dwmw2** [comment]
Is there at least a documented way to tell the thermostat component to manually switch on/off for a set period of time and then resume automatic operation *without* going behind its back?

**Comment by ssieb** [comment]
> If the thermostat is off(and Action:OFF) and then I switch it on and then it says Action:HEAT) is it not reasonable to expect it to invoke the heating trigger?

It would do that, but that's not what your situation was.

> Is there at least a documented way to tell the thermostat component to manually switch on/off for a set period of time and then resume automatic operation _without_ going behind its back?

You are doing that and that's ok.  But then you are going behind its back and turning on the heat.  And then you don't turn it off before resuming automatic operation.  The thermostat still thinks the heat is off, so no, it's not going to turn it off and there's no way to tell it that the heat is actually on.
