### ISSUE TITLE
RPI_DPI_RGB Is this macro fully functional?

### ISSUE THREAD

**Issue by Y1hsiaochunnn** [esphome/issues#6601]
### The problem

RPI_DPI_RGB This macro provides the LCD RGB driver, which is great, but as far as I know, some of the RGB interface LCD screens also need to configure registers to work properly, which is contradictory to the description document, because different LCD display chips such as ST7701, ST7262, ST77916 chip register functions are different. The initialization register configuration is also different. This does not represent all RGB LCD screens. Did the author of the library actually validate multiple RGB LCDS? There is also a case that these register configurations are initialized by the built-in chip between different RGB LCD screens, and no additional register configuration is required for such screens (unless a function needs to be adjusted, such as hardware rotation).

By the way, I have not come into contact with ESPHome, it would be appreciated if you could answer my questions, and I will do a lot of board support in the future.

### Which version of ESPHome has the issue?

lastest

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

lastest

### What platform are you using?

ESP32

### Board

Waveshare ESP32-S3-Touch-LCD-4.3

### Component causing the issue

RPI_DPI_RGB

**Comment by clydebarrow** [comment]
The ESPHome documentation is available at ESPHome.io - check the display hardware section for details on supported display chips. The `rpi_dpi_rgb` _component_ is not intended for displays that need configuration after power on, there are other drivers for those that do.
