### ISSUE TITLE
[hassio.api.ingress] Ingress error: Cannot connect to host 

### ISSUE THREAD

**Issue by Klagio** [esphome/issues#680]
ESPHome HASIIO addon does not start . HASSIO 0.99.2   ssl in config is set to false
```

19-09-22 17:44:57 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:65023 ssl:None [Connection refused]
19-09-22 17:46:00 ERROR (MainThread) [hassio.utils.json] Can't write /data/addons/data/15ef4d2f_esphome/options.json: [Errno 2] No such file or directory: '/data/addons/data/15ef4d2f_esphome/options.json'

```

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
That looks like a bug in Hass.io - as seen in the log the container/addon is not started (so no esphome code executed).
