### ISSUE TITLE
Sun component documentation example

### ISSUE THREAD

**Issue by Dunder-Dan** [esphome/issues#688]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**Affected component:**

https://esphome.io/components/sun.html

**Description of problem:**
The example in the sun component documentation states that the longitude and latitude should end with a "°"
 However when entering this in the configurator it states that it should be a float. Works great without the "°", so documentation should maybe be edited.
Very new to GitHub, I have no idea if i should make a pull request or something instead..

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
You can paste it with or without the degree symbol - in esphome there are many values that accept units (and convert between them) but when given no unit use the default one (`cv.float_with_unit`)

I don't think this is an issue, the reason it says `float` there is to add additional information what range the value can be in (must it be an int, or can it also have decimal places?). Not putting anything there would be worse.
