### ISSUE TITLE
Character-Based LCD Display PCF8574 - Clear command not found

### ISSUE THREAD

**Issue by alegiovannelli** [esphome/issues#712]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

HASSIO
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**Affected component:**

https://esphome.io/components/display/lcd_display.html

**Description of problem:**
For the LCD 1602 component I have not found in the documentation, except for errors, a command that deletes the text from the display (lcd.clear () in Arduino).
Thanks in advance.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
This is a feature request. Please also see https://github.com/esphome/esphome/pull/772
