### ISSUE TITLE
witty cloud LDR

### ISSUE THREAD

**Issue by lpt2007** [esphome/issues#770]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Witty cloud ESP8266 nodemcu
**Affected component:**

**Description of problem:**

I try to use witty cloud LDR

![160422_witty_cloud_01-1-768x595](https://user-images.githubusercontent.com/38924279/67487386-1cb57400-f66e-11e9-91cf-e63f23d70760.jpg)

Somethink is wrong with filters:

```
    filters:
      - lambda: (x * 3.3 / 10000.0) * 2000000.0
```

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```
sensor:
  - platform: adc
    pin: A0
    name: Illuminance
    unit_of_measurement: lux
    filters:
      - lambda: (x * 3.3 / 10000.0) * 2000000.0
```
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
1. Please post the error you get. I can't read minds and I won't try each example someone posts just because they didn't post the log output.

2. Try `lambda: 'return (x * 3.3 / 10000.0) * 2000000.0;'`

**Comment by lpt2007** [comment]
Thanks now is working.
