### ISSUE TITLE
REST API Floating Point Transition Times

### ISSUE THREAD

**Issue by alexyao2015** [esphome/issues#772]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

Feit Bulb
**Affected component:**

Light, REST API

**Description of problem:**
Transition time of 0.4 does not work properly when sent over the REST API. It appears that decimal transition times are ignored and 0 is instead used as the transition. Logs look exactly the same when using a default transition time of 0.4 and when sending 0.4 as the transition time. Only difference is one transition time is actually 0.4 (default) and one just acts like its a 0 transition time (REST API).

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: light2
  platform: ESP8266
  board: esp01_1m

ota:
  password: "redacted"
    
wifi:
  ssid: "redacted"
  password: "redacted"
  
# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: "redacted"
  reboot_timeout: 0s

output: 
  - platform: gpio
    pin: GPIO13
    id: fast_led_pwr
    inverted: True
    
light:
  - platform: fastled_spi
    id: color_led
    chipset: SM16716
    data_pin: GPIO14
    clock_pin: GPIO4
    num_leds: 1
    rgb_order: BGR
    name: "color_led"
    default_transition_length: 0.4s
    gamma_correct: 2.6

web_server:
  port: 80
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
Working fine with 0.4 transition time (default, as expected):
No transition time POST request
curl -H "Content-Type: application/json" -X POST "http://192.168.1.30:80/light/color_led/turn_on?r=242&g=146&b=72"

[23:49:03][D][light:261]: 'color_led' Setting:
[23:49:03][D][light:283]:   Red=100%, Green=60%, Blue=30%
[23:49:03][D][light:300]:   Transition Length: 0.4s

Not working, sending 0.4 transition time:
Sending transition time POST request
curl -H "Content-Type: application/json" -X POST "http://192.168.1.30:80/light/color_led/turn_on?r=242&g=146&b=72&transition=0.4"

[00:11:07][D][light:261]: 'color_led' Setting:
[00:11:07][D][light:283]:   Red=100%, Green=60%, Blue=30%
```

**Additional information and things you've tried:**
It appears ESPHome truncates the transition time from 0.4 to 0 and does not accept floats for transitions.

**Comment by OttoWinter** [comment]
Please explain the logs you see a bit more. Only thing I see is two times the same logs (though that may be what you're meaning). Is it correct that the first one is from a request without transition length and the second one with the transition length parameter?

What happens when you send a value other than 0.4 over the network?

What version of ESPHome is this?

What light platform is this using? rgb + esp8266_pwm?

Please attach the request you're sending so that I can verify it (curl, just the URL or whatever you're using).

**Comment by alexyao2015** [comment]
This is version 1.13.6.

I've added additional information into the original comment including curl examples and corresponding logs. 

It appears that ESPHome truncates transition times and does not accept a float value. For example, if I send 1.9, it shows transition time as 1s instead of 1.9s. Same 0.5 which has no transition. 

The issue here appears to be floating transition values in the url. Potentially if floating points are not allowed, use milliseconds instead of seconds when interpreting transition times?

This is using fastled rgb.
