### ISSUE TITLE
ERROR Error creating directories : [Errno 2] No such file or directory: ''

### ISSUE THREAD

**Issue by maltitco** [esphome/issues#796]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

macOS Catalna, virtualenv python 3.8.0

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 nodemcu

**Description of problem:**
After the fourth step - OTA and entering the password, an error appears:
ERROR Error creating directories : [Errno 2] No such file or directory: ''

**Comment by brandond** [comment]
Can you include your YAML?

**Comment by maltitco** [comment]
The wizard does not create the YAML file.
