### ISSUE TITLE
ESP32 FastLED Clockless Not Working Correctly

### ISSUE THREAD

**Issue by mdgrab** [esphome/issues#84]
running version 1.11.0
compiles correctly uploads fine
controlling it through Home Assistant version 0.87.0

light card appears on default view.
using the slider button to turn on / off leds does not work.
effects work fine , dimmer works when effects are running.
but leds do not come on in a static mode . also no color picker control on color wheel

**Comment by mdgrab** [comment]
thank you

**Comment by OttoWinter** [comment]
1.11.1 is already out with exactly that fixed: https://esphome.io/changelog/v1.11.0.html#release-1-11-1-february-23

Also duplicate of https://github.com/esphome/issues/issues/77
