### ISSUE TITLE
Custom Sensor Component with multiple output values does not create Entities

### ISSUE THREAD

**Issue by manju-rn** [esphome/issues#847]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32s
**Affected component:**

https://esphome.io/components/sensor/custom.html
Bonus: Sensors With Multiple Output Values

**Description of problem:**
I am using a iTag BLE device to trigger custom sensor in ESP32 which integrates in an entity of Home Assistant. The idea is to click the button in the iTag and populate the Entity in Home Assistant via ESP32. Here are the working and the non-working scenario:
1. Working Scenario:  If i just use the Custom Component as described ESPhome's Custom, all is well, a single sensor defined in ESPHome is integrated to entity in HA and shows up in Lovelace. So when iTag button is clicked, the value is updated in the HA. The sensor name and values are constantly updated in the log file
2. Not-Working Scenario: If I use the Bonus feature of Custom Component where multiple sensors (2 in this case) for output are used, then the entities do not show up in the HA
When a Custom Component is created with the multiple output values, the sensors from ESP32 does not integrate in Home Assistant and do not show up in lovelace.  The actual functionality of triggering the value when iTag button is clicked is working as you could see in the log below that Sensor names are showing up with the values in the log.  However, when the button is not clicked, the log shows empty sensor in log (unlike in Working Scenario, where Sensor and value is shown always)

I have provided the Yaml, log and .h files for both the scenarios.  Kindly help as to how to show 2 or more sensors in HA using this Sensors with Multiple Output values feature?

**Problem-relevant YAML-configuration entries:**
 **Working Scenario - Code** The iTagSensor shows up the in Home Assistant UI and updates the values when the button in clicked as written in the .h file
```yaml
sensor:
- platform: custom
  lambda: |-
    iTagSensor *itag_sensor = new iTagSensor();
    App.register_component(itag_sensor);
    return {itag_sensor};
    
  sensors:
  - name: "iTagSensor"
```

**Not working scenario - code:** The iTagSensor and iTagBattery are not shown up in UI. In the logs, only when the iTag button is clicked, the values are shown up in the logs
```yaml
sensor:
- platform: custom
  lambda: |-
    iTagSensor *itag_sensor = new iTagSensor();
    App.register_component(itag_sensor);
    return {itag_sensor->button_sensor, itag_sensor->battery_sensor};
    
  sensors:
  - name: "iTagSensor"
  - name: "iTagBattery"
```

**Logs (if applicable):**

**Working Scenario - Log:**  Note that the iTagSensor shows up the Home Assistant . The value is always 0 unless iTag button is clicked - see 1.00000 value below
```
[15:09:36][D][sensor:092]: 'iTagSensor': Sending state 0.00000  with 0 decimals of accuracy
[15:09:36][D][sensor:092]: 'iTagSensor': Sending state 0.00000  with 0 decimals of accuracy
[15:09:37][D][sensor:092]: 'iTagSensor': Sending state 0.00000  with 0 decimals of accuracy
[15:09:38][D][sensor:092]: 'iTagSensor': Sending state 1.00000  with 0 decimals of accuracy
[15:09:38][D][sensor:092]: 'iTagSensor': Sending state 0.00000  with 0 decimals of accuracy
[15:09:41][D][sensor:092]: 'iTagSensor': Sending state 0.00000  with 0 decimals of accuracy
[15:09:41][D][sensor:092]: 'iTagSensor': Sending state 0.00000  with 0 decimals of accuracy
```
**Not working scenario - Log:** Notice that the iTagSensor and iTagBattery entries are only updated when a button is clicked in iTag (as per the code written in .h file). I was expecting the iTagSensor  & iTagBattery entries to show up in log just like the Working log files above. As expected, these 2 fields also do not show up in the Home Assistant
```
[15:03:10][D][sensor:092]: '': Sending state 0.00000  with 0 decimals of accuracy
[15:03:11][D][sensor:092]: '': Sending state 0.00000  with 0 decimals of accuracy
[15:03:12][D][sensor:092]: '': Sending state 0.00000  with 0 decimals of accuracy
[15:03:13][D][sensor:092]: 'iTagSensor': Sending state 1.00000  with 0 decimals of accuracy
[15:03:13][D][sensor:092]: 'iTagBattery': Sending state 99.00000  with 0 decimals of accuracy
[15:03:13][D][sensor:092]: '': Sending state 0.00000  with 0 decimals of accuracy
[15:03:16][D][sensor:092]: '': Sending state 0.00000  with 0 decimals of accuracy
[15:03:17][D][sensor:092]: '': Sending state 0.00000  with 0 decimals of accuracy

```

**Additional information and things you've tried:**

**Working Scenario:**  .h file
```
#include "BLEDevice.h"

static BLEUUID serviceUUID("0000ffe0-0000-1000-8000-00805f9b34fb");
//static BLEUUID serviceUUID("0000180f-0000-1000-8000-00805f9b34fb");

static BLEUUID charUUID("0000ffe1-0000-1000-8000-00805f9b34fb");
//static BLEUUID charUUID("00002a19-0000-1000-8000-00805f9b34fb");

static BLEAddress *pServerAddress;
static BLERemoteCharacteristic* pRemoteCharacteristic;   

class iTagSensor : public PollingComponent, public Sensor 
{
    public:

    iTagSensor() : PollingComponent(1000) {}
    
    void setup() override 
    {
           BLEDevice::init("");
           delay(500);
         
           pServerAddress = new BLEAddress("xx:xx:xx:xx:xx:xx");
           delay(500);
           BLEClient* pClient = BLEDevice::createClient();
           pClient->connect(*pServerAddress);
           delay(500);
           BLERemoteService* pRemoteService = pClient->getService(serviceUUID);
           pRemoteCharacteristic = pRemoteService->getCharacteristic(charUUID);
    }
    void update() override 
    {
        uint8_t  rxValue = pRemoteCharacteristic->readUInt8();
        
        if (rxValue > 0)
        { 
            publish_state(rxValue);
            delay (50);
            pRemoteCharacteristic->writeValue(0);
        }    
        
        publish_state(0);
    }
};

```

**Not working Scenario:** .h file
```
#include "BLEDevice.h"

static BLEUUID serviceUUID("0000ffe0-0000-1000-8000-00805f9b34fb");
static BLEUUID serviceUUID_1("0000180f-0000-1000-8000-00805f9b34fb");

static BLEUUID charUUID("0000ffe1-0000-1000-8000-00805f9b34fb");
static BLEUUID charUUID_1("00002a19-0000-1000-8000-00805f9b34fb");

static BLEAddress *pServerAddress;
static BLERemoteCharacteristic* pRemoteCharacteristic;   
static BLERemoteCharacteristic* pRemoteCharacteristic1;   

class iTagSensor : public PollingComponent, public Sensor 
{
    public:
    Sensor *button_sensor = new Sensor();
    Sensor *battery_sensor = new Sensor();

    iTagSensor() : PollingComponent(1000) {}
    
    void setup() override 
    {
           BLEDevice::init("");
           delay(500);
         
           pServerAddress = new BLEAddress("xx:xx:xx:xx:xx:xx");
           delay(500);
           BLEClient* pClient = BLEDevice::createClient();
           pClient->connect(*pServerAddress);
           delay(500);
           BLERemoteService* pRemoteService = pClient->getService(serviceUUID);
           BLERemoteService* pRemoteService1 = pClient->getService(serviceUUID_1);
           pRemoteCharacteristic = pRemoteService->getCharacteristic(charUUID);
           pRemoteCharacteristic1 = pRemoteService1->getCharacteristic(charUUID_1);
    }
    void update() override 
    {
        uint8_t  rxValue = pRemoteCharacteristic->readUInt8();
        uint8_t  rxValue1 = pRemoteCharacteristic1->readUInt8();
        
        if (rxValue > 0)
        { 
            button_sensor->publish_state(rxValue);
            battery_sensor->publish_state(rxValue1);
            delay (100);
            pRemoteCharacteristic->writeValue(0);
        }    
        
        publish_state(0);
    }
};
```

**Comment by brandond** [comment]
In the non working examples, your lambda is returning Sensors, not Components. You have to register the component, not the sensors.

**Comment by OttoWinter** [comment]
You need to return the sensor component also, see below:

```cpp
return {itag_sensor, itag_sensor->button_sensor, itag_sensor->battery_sensor};
```

Otherwise ESPHome only knows of the button and battery sensor, not the parent itag_sensor.

**Comment by manju-rn** [comment]
okay thanks.  The docs were incorrect then.  I create a PR #414
