### ISSUE TITLE
ESPHome-Flasher boot loop not fixed on mac version 1.2.0

### ISSUE THREAD

**Issue by HA-TB303** [esphome/issues#853]
This issue: https://github.com/esphome/issues/issues/598

1.20 Fixed it for windows, but the MAC os version 1.20 still has the same issue. Took me a 2 hours to figure that one out. ;)

**Comment by OttoWinter** [comment]
I don't think that can be true.

The code is shared between macOS and Windows version - and the fix for it would certainly not be platform-specific.

Please check you're actually using the correct esphome-flasher version.

**Comment by HA-TB303** [comment]
I have downloaded both today v1.20. On my iMac I can flash, but the esp32 get's in bootloop.
On the same MAC I run the windows 64bit version in parallels and I can flash it and it works.
I can repeat this action multiple times with the same result.

**Comment by OttoWinter** [comment]
You keep saying 1.20 - but there's only 1.2.0, please confirm you mean 1.2.0

**Comment by HA-TB303** [comment]
Sorry, 1.2.0
