### ISSUE TITLE
esphome as hassio addon and /dev/ttyAMA0 dows not turn up-

### ISSUE THREAD

**Issue by blurkis** [esphome/issues#93]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Raspberry pi3 with up2date hass.io and the esphome addon.
.

**ESP (ESP32/ESP8266, Board/Sonoff):**

Its a sonoff pow2 which is connected to the GPIO of the pi3.

**Affected component:**

**Description of problem:**
The AMA0 device does not turn up t in the droplist of the esp hough when I log in with ssh to my Pi3 I can see that its detected.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Traceback (if applicable):**

```
core-ssh:/# dmesg |grep AMA
[    0.816806] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2

```

**Additional information and things you've tried:**

**Comment by blurkis** [comment]
I have used esphome to flash some nodemcu so I know that it works. And those turn up in the droplist of esphome in the esphome addon to hassio. The problem being that AMA0 does not turn up though its recognized (as far as I know, the logs says so) by the underlying system of hassio.

**Comment by OttoWinter** [comment]
What is the problem with using an FTDI adapter? Also, esphome would theoretically support that but I opted to manually exclude it from the dropdown list because 99% of users would be confused by it and would think it's the FTDI adapter they just plugged in. Also don't want to add an option because I want to keep the number of options minimal.

**Comment by blurkis** [comment]
Well, first off its a problem because I don't own a cable like the one you
suggest. I have ordered one but has not yet arrived. So I thought that I
would use the gpio instead since I got the impression that it should work.
Knowing it doesn't is ok. I can wait for cable. Maybe some how the docs
should say this doesn't work. Esptool as such supports it so it's easy to
think it should work.

Thanks for a great product. I use it for nodemcu and those support flashing
from normal USB cable.

Den tis 5 mars 2019 14:10Otto Winter <notifications@github.com> skrev:

**Comment by OttoWinter** [comment]
I looked again and esphome does not suppress ttyAMA0, I only did that while initially building the dashboard.

This means this is an external issue in Hass.io, apparently ttyAMA0 is not passed in with `auto_uart` for addons.

I will therefore close this issue.
