### ISSUE TITLE
error on running esphome compile

### ISSUE THREAD

**Issue by mvturnho** [esphome/issues#932]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Windows with pyhon 3.8. esphome latest dev branch

**ESP (ESP32/ESP8266, Board/Sonoff):**
esp8266

**Affected component:**
Core compile

**Description of problem:**
when compiling i get the following log:

```
$ esphome woonkamer.yaml  compile
INFO Reading configuration woonkamer.yaml...
INFO Detected timezone 'CET' with UTC offset 1 and daylight savings time from 29 March 02:00:00 to 25 October 03:00:00
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d woonkamer
ERROR Running command failed: 'str' object has no attribute 'decode'
ERROR Please try running platformio run -d woonkamer locally.
```

Then when running `platformio run -d woonkamer `from the prompt it compiles fine

**Logs (if applicable):**

**Additional information and things you've tried:**

**Comment by glmnet** [comment]
This should be fixed by https://github.com/esphome/esphome/pull/923
