### ISSUE TITLE
Create new device under latest dev file names are converted to special characters.

### ISSUE THREAD

**Issue by marc-gist** [esphome/issues#945]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip using  ` pip install --upgrade git+https://github.com/esphome/esphome`
Python 3.6.9
`esphome config/ dashboard`

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32

**Affected component:**

Configure/Make new

**Description of problem:**

When I create a new item, the file and name convert to: 

> b&#39;quinled_quad_2&#39; 

edit file shows

> Edit b'quinled_quad_2'.yaml

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by poldim** [comment]
Confirming the same thing happens to me.  

##**Steps to reproduce:**

1. Go to the dashboard
2. Click the plus button to add a new device
3. Name the device "esphome_dining_room_dimmer"
4. Fill out the rest of the form to have the device created
5. UI shows the following: 
<img width="1033" alt="ESPHome Dashboard 2020-01-06 07-37-07" src="https://user-images.githubusercontent.com/16869713/71828557-6865a000-3057-11ea-9177-3abc10391b43.png">
6. The filename as created: `b'esphome_dining_room_dimmer'.yaml`
<img width="566" alt="ssh 2020-01-06 07-39-52" src="https://user-images.githubusercontent.com/16869713/71828723-c2666580-3057-11ea-9240-1dac237a240b.png">

**Comment by timsavage** [comment]
A pull request with the fix is open.

**Comment by brandond** [comment]
Fixed by https://github.com/esphome/esphome/pull/941
