### ISSUE TITLE
cannot migrate to esphome from tasmota 8+

### ISSUE THREAD

**Issue by mrpraline** [esphome/issues#955]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io raspberry pi 3
**ESP (ESP32/ESP8266, Board/Sonoff):**

Sonoff S20
**Affected component:**

https://esphome.io/devices/sonoff_s20.html?highlight=s20

**Description of problem:**
If you have tasmota 8+ installed on the S20 device, migrating to esphome by uploding the binary does not work anymore, you have to use a version 7.x or older. Tasmota now apparently does a check on the binary before installing. You either have to downgrade to rev. 7.2 first (if possible), or flash by hardware UART. I suspect this will be true for any Tasmota device. 
 
This is obviuosly not a problem of esphome, but the documentation should make this clear to potential users that want to migrate.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by bingobob** [comment]
hi, same for me...  trying to convert my sonoff basics from tasmota to ESPHOME OTA, they are running the latest tasmota 8.1.0... i create an esp binary and try to flash it via the tasmota web interface OTA, unfortunately i get "upload failed" "not compatible"... am keen to convert if poss?
this [migrate](https://esphome.io/guides/migrate_sonoff_tasmota.html) makes it look simple but compatibility problem for me. Reflashing by wire will be tricky as they're all installed, some in the roof !

would be great to find a solution?

**Comment by john-arvid** [comment]
Had the same problem. The solution for me was to upgrade (downgrade) to tasmota-minimal v7.2. Then I would upgrade to the esphome firmware that I had compiled and downloaded.

(I had to use the tasmota-minimal since the normal tasmota was to big for OTA to handle)

**Comment by nwesoccer** [comment]
Same issue, glad to see there will be a coded work around.  For now running `Setoption78 1` in the tasmota console disables capability check and allows for the update to esphome.

**Comment by Phontana** [comment]
`Setoption78 1` did not work for me, downgrading to 7.2 did. Thanks!

**Comment by Thunderbiscuits** [comment]
> `Setoption78 1` did not work for me, downgrading to 7.2 did. Thanks!

Type it in the console, press enter, reboot/restart device (no need to power cycle), and it worked for me!

**Comment by Ryan-Hobbies** [comment]
Thanks - Setoption78 worked for me.  Easy fix.

**Comment by Gumboot13** [comment]
Cheers, just downgraded to 7.2 and it worked.

**Comment by iondulgheru** [comment]
```Setoption78 1 ``` worked for me

**Comment by shafr** [comment]
For me no restart was necessary. 
Just SetOption78 1 and then upload new firmware

**Comment by poldim** [comment]
My process:
- Restart didn't work
- `SetOption78 1` then flash didn't work
- `SetOption78 1` then restart then flash didn't work
- Downgrade to [7.2 minimal](https://github.com/arendst/Tasmota/releases/download/v7.2.0/tasmota-minimal.bin) then flash finally worked!

**Comment by myfingerhurt** [comment]
Here is what I did.
Sonoff pow R1

- 8.4.1 Full
    -  8.5.1 minimal(OK) 
       -  9.1    minimal(OK) 
            - 9.3.1 Full first try( not compatible)
            - go 9.1 minimal console run `Setoption78 1` even without rebooting.
            - 9.3.1 Full  second try     ( OK)

**Comment by feutl** [comment]
I know this is an old issue, but I ran into this today.
Having 9.4 and 9.5 version of tasmota and I am unable to flash the esp binary to it, even with `setoption78 1` being set.
I do not get an error, the upload starts and runs into a connection timeout. After that, tasmota is back.

Any ideas why this happens and how to fix ?

**Comment by shafr** [comment]
whats the os you are flashing from? windows / linux / mac? 
are you using browser / mqtt upload?

**Comment by feutl** [comment]
Sorry
Windows 10
Firefox
All updated to the latest version.

**Comment by Gumboot13** [comment]
> Sorry
> Windows 10
> Firefox / Chrome
> All updated to the latest version.
> 
> Error: ERR_CONNECTION_RESET

Downgrade to 7.2 minimal and try to flash esphome

**Comment by feutl** [comment]
@Gumboot13 this is an option, butvmore a workaround instead of a solution.

I would like to help figuring out, why it does notvqork the way it is intendend and documented.
If more people should use esphome, such things should work if stated this way.

**Comment by shafr** [comment]
probably minimal flashing first is good solution. i would also recommend
doing 'Reset 6' from console and trying again.

**Comment by feutl** [comment]
Ok I found a much easier solution, which worked on all my devices (Shelly 1) running Tasmota 9.x
After I have downloaded the binary, I gzipped it and was able to upload it to different devices without any issues, not extra configuration needed, no reset, not what so ever.
Just upload the gzipped binary via the web interface and *bumm* done.

Perhaps this should be tested by others and documentation updated
https://esphome.io/guides/migrate_sonoff_tasmota.html

**Comment by shafr** [comment]
that's from Tasmota 8.2 or 8.4

**Comment by feutl** [comment]
the ticket as well as the article reference 8+ which implies 8 or 9 or 10 ....
otherwise it would be referenced as 8.x

therefor I assume that perhaps even with 8.x compressing the bin to a gz could have solved the problem.
For 9 it does, anyhow what is the process to get this tested and the documentation updated if this is a feasable solution?

**Comment by Didel** [comment]
I can confirm @feutl 's solution seems to work fine!

I was trying to flash a Sonoff SV that already had Tasmota 9.5 flashed to it. Using the firmware upload from the Tasmota Web interface didn't work, not even after applying `setoption78 1` and restarting the device.

However, running a simple `gzip [esphome-firmware-filename].bin` (from the MacOS command line) and uploading the gzipped ESPHome firmware file in the Tasmota web interface did the trick (although the `setoption78` was still enabled). The file flashed successfully and ESPHome was running as expected!

**Comment by feutl** [comment]
@Didel this sounds great, I opened another ticket to adjust documentation at
https://github.com/esphome/issues/issues/2201
backing this could help updating the documentation.

**Comment by Didel** [comment]
Just to provide a bit more information: I was able to upgrade 2 other Sonoff Basic devices from Tasmota 9.5.0 to ESPHome using the GZip method. This time, however, I was able to confirm that `setOption78` was actually *turned off*before uploading the gzipped .bin file. That means that for the gzip method, you don’t have to enable `setOption78` first!
