### ISSUE TITLE
Set warm-cold white component with automation (button)

### ISSUE THREAD

**Issue by Keeze** [esphome/issues#997]
Hello,

I have a Shelly RGBW2 and succesfully put esphome on it. I can drive 2 outputs as warm-white and 2 as cold white. I can set the right temperature from home-assistant.

Now, I want to use the AC-switch input to not only toggle the wwcw-outputs, but also to set (with a longer press) the ww/cw values (both to 100%)

I could not find how to set the ww and cw %-values (like RGB values) in the automation section.

Can this be done?

Thanks,
Kees

**Comment by OttoWinter** [comment]
Those values can not be set in automations. This is more a feature request
