### ISSUE TITLE
The link in the docs for core config board options doesn't list valid boards

### ISSUE THREAD

**Issue by brettp** [esphome/issues#998]
The [core config vars section of the docs](https://esphome.io/components/esphome.html#configuration-variables) says to use a board name from the list at platformio's site, but the linked pages do not contain board name values that are accepted by esphome.

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by brandond** [comment]
Platformio updated their docs, but if you click on one of the board names in the list, the details page will give you the actual board value.
